= Applications with Bonita UI Builder
:description: In this page you will learn more about Bonita UI Builder and Applications.

{description}


== Bonita UI Builder

Bonita UI Builder is a development environment made for designing all kind of interfaces, pages, forms, for your applications. 
It brings a host of advanced features and improved usability, designed to help you create even more compelling and user-friendly interfaces: 

* A set of more than 45 widgets
* Code completion
* Custom JavaScript code
* Native debugging options
* A restriction-free drag & drop interface
* Import and export JSON options
* React interfaces
* ...and many more

Bonita UI Builder is an application-centric development environment that allows for designing forms and application pages, without distinction. You can now design fully-fledged applications, embedding dashboards and complex interfaces. Or, you can just design single-page applications. The choice is up to you. 

With Bonita UI Builder, you can still manage your workflows, continuous integration, etc., the way you’re managing them now. 


== Applications

Applications are created and operated within Bonita Platform, created with Bonita Studio and Bonita UI Builder, run by Bonita Runtime. 

They are not standalone elements (such as pages and forms) in a process anymore, which is a paradigm change compared to Bonita UI Designer.

Bonita also comes with four xref:runtime:bonita-applications-interface-overview.adoc[Bonita Applications].

“Applications” are very similar to “Living Applications”, which are created with Bonita UI Designer and will be phased out. Once pushed to production, Applications cannot be live edited.


== Subscription

Bonita UI Builder is available by default and for no additional cost in all https://www.bonitasoft.com/pricing[Scale subscriptions]. It is also available as a payable add-on in https://www.bonitasoft.com/pricing[Access subscriptions]. 

If you haven’t subscribed to a Scale of Access plan yet, please https://www.bonitasoft.com/contact-us[get in touch] with our sales team to start your journey today!

If you have already subscribed to a Scale plan or purchased the UI Builder add-on, then start your journey by following our documentation.


[.card-section]
== Start your journey

[.card.card-index]
--
xref:applications:initiation-manual.adoc[[.card-title]#Initiation manual# [.card-body.card-content-overflow]#pass:q[Steps to download and use Bonita UI Builder]#]
--

[.card.card-index]
--
xref:applications:how-tos-builder.adoc[[.card-title]#Guides# [.card-body.card-content-overflow]#pass:q[Guides to make the most of Bonita UI Builder]#]
--

[.card.card-index]
--
xref:applications:resources.adoc[[.card-title]#Resources# [.card-body.card-content-overflow]#pass:q[Find all the resources you need]#]
--

[.card.card-index]
--
xref:applications:faq.adoc[[.card-title]#FAQ# [.card-body.card-content-overflow]#pass:q[Find answers to your questions]#]
--

[.card-section]


== Legal notice

Bonita UI Builder is commercially licensed and has Copyright (c) 2024 Bonitasoft S.A.
[NOTE]
====
For Subscription editions only.
====

*Bonita UI Builder* has been developed based on Appsmith and modifies some portions of it to integrate with the Bonita Platform.

*Appsmith* is an open-source project. It can be obtained in its original version at https://github.com/appsmithorg/appsmith[its Github home page] or through the https://www.appsmith.com/[official website]. +
It is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
