= FAQ
:description:


== Bonita UI Builder

=== What is Bonita UI Builder? 
Bonita UI Builder (sometimes abbreviated UIB) is a development environment used for creating all kind on interfaces, whether they are pages or forms or else, that make up an Application. It is a web-based tool that is launched from a Bonitasoft custom docker image. It is the new and only standard used in the Bonita ecosystem for designing interfaces.

 
=== What does it mean for my workflows? 
There should be no changed in your logic, continuous integration, and workflows. You can still manage them the way you’re managing them today. Just download the docker image and follow the xref:applications:initiation-manual.adoc[initiation manual]. 

 
=== How to subscribe? 
Bonita UI Builder is available by default and for no additional cost in all https://www.bonitasoft.com/pricing[Scale subscriptions]. It is also available as a payable add-on in https://www.bonitasoft.com/pricing[Access subscriptions].

 

=== How to use? 
Please refer to the xref:applications:initiation-manual.adoc[initiation manual]. If you have any other additional questions, reach out to our https://csc.bonitacloud.bonitasoft.com[Support team].

 

=== Can I expect any support from Bonitasoft?
Yes you can!

* Support and resources: We offer extensive documentation, tutorials, and support to help you make the most of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder].
* Facilitated transition: We are dedicated to facilitate the transition, with detailed guides on how to use Bonita UI Builder, as well as https://www.bonitasoft.com/professional-services/on-demand-services[professional services support].

 

=== I am using the Open source edition of Bonita, can I use Bonita UI Builder? 
Unfortunately no. You’ll need to either use Bonita UI Designer or design your interfaces with the language or tool of your choice and integrate them to Bonita. Upgrade to an Access or Scale edition if you want to use Bonita UI Builder.

 

=== Is Bonita UI Builder compatible with all supported versions of Bonita?
Bonita UI Builder is compatible with all Bonita versions starting from 2024.3.

 

=== What is an advancedApplication?
It is a tag used to describe an Application made with Bonita UI Builder in the Studio’s Application descriptor.

 

=== Can I use other datasources than Bonita’s? 
Theoretically you can, yes. However, we’re not supporting them yet.


=== How do Bonita UI Builder and Bonita UI Designer compare?
[cols="1,1,1"]
|===
|Feature |Bonita UI Designer |Bonita UI Builder

|Widgets
|~25
|~45

|Custom widgets
|Yes
|Yes

|Downloadable array data
|Yes (custom code)
|Yes (native)

|Form's auto-generation from a contract
|Yes
|Yes in a future release

|Templates
|No
|Yes

|Themes
|Yes (using CSS bootstrap 3)
|Yes (native feature)

|Custom code
|Yes (HTML, CSS, JS)
|Yes (HTML, JS, custom JS libraries)

|Code completion
|No
|Yes

|Native debugging options
|No
|Yes

|Application import/export
|Yes
|Yes (JSON)

|Page components' hierarchy
|No
|Yes

|Page preview
|Yes
|Yes

|Undo/redo, copy/paste
|No
|Yes

|Stack
|AngularJS
|React

|Works best for...
|Quick development tests, simple use cases
|Fully-fledged applications, complex use cases


|===



=== What does it mean for my existing forms and pages? 
You existing forms and pages will always be compatible with Bonita. Eventually, Bonita UI Designer will be phased out as we fully transition to Bonita UI Builder. We cannot guarantee you will be able to edit your existing interfaces made with Bonita UI Designer in the future versions of Bonita.

Our goal is to make this transition as smooth as possible, minimizing any disruption to your workflow:

* Continued access: Bonita UI Designer will remain fully operational for an extended period, allowing ample time for adaptation.
* Support and resources: We offer extensive documentation, tutorials, and support to help you make the most of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder] 
* Facilitated transition: We are dedicated to facilitate the transition, with detailed guides on how to use Bonita UI Builder, as well as https://www.bonitasoft.com/professional-services/on-demand-services[professional services support]

 
=== Are the interfaces made with Bonita UI Builder compatible with platform mode and self-contained applications ? 
Yes they are. 


=== Is Bonita UI Builder Bonita Cloud compatible? 
Yes it is. Reach out to your customer service representative to explore how you can migrate to Bonita Cloud.
