= Interact with your Bonita process
:description: Interact with a Bonita runtime in multiple ways using API requests.

{description}

== Create a Bonita datasource
From a page in edit mode, click the `Data` icon from the left panel.
Then, you get the list of the provided datasources.

From the `APIs` section, click on the `Bonita API`. By default, it will connect to the Bonita runtime running on the local machine. No need to provide any credential information,
since they are already provided at the xref:download-and-launch.adoc[Download and launch] step.

Then, click on the `Save` button to save the datasource.

GIF

== Create Bonita API requests
Once the datasource is saved, you can create API requests and interact with the Bonita runtime with the xref:api:rest-api-overview.adoc[REST APIs].
We will describe below how you can for example retrieve a list of Bonita processes, and instantiate one of them.

=== Get a list of processes
To get the list of the processeses deployed on the Bonita runtime (first 10): click the `Editor` icon from the left panel, click the `Queries` tab, then click the `new query / API` button and select the Bonita datasource created previously. 
Enter the following configuration:

* `Name`: getProcess
* `Method`: GET
* `URL`: /bonita/API/bpm/process
* `Params`:
    - `Key`: p
    - `Value`: 0
    - `Key`: c
    - `Value`: 10

Then, click on `Run` to test the API and see the result in the `Response` tab.

GIF

[NOTE]
====
The authentication to the Bonita runtime is automatically handled by the Bonita datasource.
====


=== Instantiate a process
Now, we will instantiate one of the processes with what the user typed in the form we created xref:create-an-interface.adoc[previously]. 

Click the `Editor` icon from the left panel, click the `Queries` tab, then click the `new query / API` button and select the Bonita datasource created previously. 
Enter the following configuration:

* `Name`: instantiateProcess
* `Method`: POST
* `URL`: API/bpm/process/{{getProcess.data[0].id}}/instantiation
* `Params`:
    - `Key`: p
    - `Value`: 0
    - `Key`: c
    - `Value`: 10
* `Body`:
`
{{
	{
		claimInput: {
			description: Input1.text,
		}
	}
}}
`
CHANGE SO THAT IT IS A CODE BLOCK

This API will instantiate the first process returned by `getProcess` with the `body` 's content. 

[NOTE]
====
To instantiate a process, you need to refer to your Bonita contract. 
Here, we used to Getting Started tutorial as an example: `description` is a mandatory input for the `claimInput` xref:declare-contracts.adoc[contract], and `description` will take as value what is typed in the `Input1` widget of the form.
====

Now, we need to tell the form to execute this API request after clicking the `submit` button.
Go to the `UI` tab and click the form's `submit` button. On the right panel, click the `onclick` button...


GIF
