= Develop a layout
:description: This page explains how to handle layouts in Bonita Applications, and how to use it in an application.

{description}

Layouts are xref:ROOT:resource-management.adoc[added, exported, edited, and deleted] as resources in Bonita Applications.

== Use in applications

It is linked to an application thanks to the application descriptor in Bonita Studio. +
A layout can only be use as the main container of an application. It cannot be used as a simple application page.

In a Non-Production or Production environment, a layout is imported as a .zip archive containing a page.properties file and a resources folder.

== Live update

xref:runtime:live-update.adoc[Live update] allows the Administrator to update one element of the application in a situation of emergency.

=== Edit the layout

You can xref:ROOT:resource-management.adoc#modify[edit the content of a layout] by installing a new version.

=== Modify the pages in an application

You can xref:runtime:applications.adoc#define-navigation[link another layout to an application] in the application descriptor.

== Create a layout

=== From the provided Bonita layout
==== If you have not installed any Bonita application in your project in Bonita Studio

. From Bonita Studio, click on the *_Applications_* icon and select either the Administrator or Super Administrator application
. Go to the *_Resources_* menu option
. If needed, filter the type by _Layout_, and select *_Bonita Layout_*
. Click on the *_Export_* button
. From Bonita Studio, click on the *_UI Designer_* icon to open the UI Designer
. Click on the *_Import_* button
. Find the Bonita layout you have exported and load it
. Edit it and save it with another name

==== If you have installed a Bonita application

. In Bonita Studio, go to the _Project Explorer_
. Open the project, and the _Pages/Forms/Layouts_ section
. Double click on _Bonita layout_. This automatically opens the UI Designer with the layout ready to edit.
. Edit it and save it with another name

=== From scratch

Use the same sequence of steps than to create a page from scratch.

== Deployment

A layout is deployed in a Bonita Runtime as a .zip archive containing a page.properties file and a resources folder.

* The `page.properties` file contains the metadata for the layout (the name used in the URL, the display name, and a description). For example:
+
----
name=custompage_layout
displayName=Application layout page
description=This is a layout page dedicated to new born living applications. It is created and editable using the UI designer. It allows to display an horizontal menu, and an iframe. The menu allows to target some pages and the iframe define the area to display those targeted pages.
resources=[GET|living/application,GET|living/application-page,GET|living/application-menu]
contentType=layout
----

* The resources folder must contain an `Index.groovy` class or an `index.html` file and optionally can contain some additional resources.

In case of layout edition using Bonita UI Designer, the contentType is kept unchanged.
xref:ROOT:resource-management.adoc[Export the examples] to see how to structure your layout.

== Constraints

A layout can only be used as the main container of an application. It cannot be used as a simple application page.

== Layout resources management

=== Layout resources

If you are not using Groovy, you can directly access a resource by adding a link in `index.html`.

For example: `<link href="css/file.css" rel="stylesheet" />`

=== API acces

If your page is viewed in an application, you will have access facilities for xref:ROOT:rest-api-overview.adoc[the APIs].

You will be able to access the APIs using the following path: "../API/{API name}/{resource name}"

=== Theme access

If your page is viewed in an application, you will have access facilities for xref:runtime:applications.adoc[the application theme].

The `Theme.css` is directly accessible by adding the following link in `index.html`: `<link href="../theme/theme.css" rel="stylesheet" />`
