= Package and deploy your application
:description: Step-by-step guide to transition from development to production using Bonita UI Builder

[NOTE]
====
For Subscription editions only.
====

== Prerequisites

Before starting, ensure you have **Docker** the following tools installed on your system:

== Steps to Move from Development to Production

=== 1. Design Your Application

Begin by designing your application using xref:download-and-launch.adoc[Bonita UI Builder].

=== 2. Export Your Application

Once the design is complete, export the application(s) from Bonita UI Builder. This export will be used for building the production binary.

=== 3. Store Your Application in a Workspace Folder

Place the exported application(s) in a designated `workspace` folder. This folder will be referenced during the build process.
You can store these applications in a Git repository too.

=== 4. Build the Production Binary

To create the production-ready binary, you need to build a Docker image. This image will contain the application(s) and the Bonita UI Builder runtime.

The xref:applications:production-packaging.adoc#dockerfile[Dockerfile] and more details and information on how to build the Docker image can be found in this xref:applications:production-packaging.adoc[dedicated page].

=== 5. Run the Docker Image

After building the Docker image, run it using the following command:

[source,shell]
----
docker run --name bonita-ui bonita-ui:1.0.0
----

=== 6. Access to your Application

Once Bonita UI Builder is ready, all applications contained in the dedicated folder will be:
- Imported
- Published
- Made available for users

Then, these applications can be accessed from the bonita application directory

===
