= Bonita platform overview

Bonita is an open-source and extensible platform for business process automation and optimization. The Bonita platform accelerates development and production with clear separation between capabilities for visual programming and for coding.  BPMN graphical notation, full extensibility, and reusable components allow smooth collaboration among the different profiles on the IT team, and with the business teams. Bonita integrates with existing information systems, orchestrates heterogeneous systems, and provides deep visibility into processes across the organization.

The Bonita Platform has two components: the development environment, Bonita Studio, and the runtime environment, Bonita Runtime.

== Bonita Studio

Bonita Studio contains all the elements needed to develop and compile a Bonita application. It is a graphical environment for creating processes, applications, data models, and users views (pages and forms). It contains three major design tools:

* the whiteboard, for drawing a process flow diagram and defining the detail of steps, transitions, decision points and other process elements
* the Development menu, to extend the Studio capabilities and create your data models
* the UI Designer, which is used to create application pages and process forms

Bonita Studio is the development tool for the Business Analyst and Application Developer. Back-end java developers work in Bonita Studio and collaborate with front-end developers working in the UI Designer.

You can xref:bonita-bpm-installation-overview.adoc[install Bonita Studio] on your computer, then create and test processes, create data models, applications and application views (pages and forms).

Bonita Studio contains a *Bonita Runtime* (Tomcat, UI Designer, Bonita Portal, Bonita Engine, and an h2 database), suitable for testing an application that is in development. When you run a process, it is automatically deployed onto the development platform.

Process forms, used to complete the human tasks, are created in the UI Designer, and use the data models created in the Studio.

Users can use Bonita Portal (_User_ profile) to view and complete the process tasks for all processes. You can also build personalized process-based applications. To do so, use the UI Designer to create application pages that display business data from the data models, link the pages to processes thanks to action buttons, then use the Bonita Portal application builder to construct the application piece by piece.

+++<a id="platform">++++++</a>+++

== Bonita Runtime

Bonita Runtime is composed of one or more Bonita Server nodes installed on some hosts (physical machine, virtual machine, a cloud instance, a container like Docker, ...). A Bonita Runtime composed of multiple nodes constitutes a cluster.

xref:engine-architecture-overview.adoc[Bonita Engine] is the execution engine of Bonita.

As mentioned before, xref:bonita-bpm-portal-interface-overview.adoc[Bonita Portal] is the part of Bonita that is visible to process users, who use it to view tasks and take actions thanks to a generic task list for all processes they are involved in.

But Bonita Portal is also the tool used by the tenant administrator to xref:processes.adoc[install, deploy and manage processes] and to xref:applications.adoc[build applications]. We use the word "tenant" here, in case the platform would be made of xref:multi-tenancy-and-tenant-configuration.adoc[several tenants].

To install Bonita Engine and Bonita Portal in a qualification or production environment, link:bonita-bpm-installation-overview.md#platform[install Bonita Platform].

In Bonita Studio, once a process is ready, you can xref:build-a-process-for-deployment.adoc[build] it and deploy it on your Bonita qualification or production platform.

== Editions

Until 2019 Bonita was provided in four different editions: Community, Teamwork, Efficiency and Performance. Since 2019 Bonita is only provided in two editions : Community and Enterprise.

== Getting started

*I'm currently using Bonita 6.x. Will 7.x be a big change?*

Bonita 7.x provides new and improved features, including the xref:ui-designer-overview.adoc[UI Designer] for creating application pages and forms, as well as xref:contracts-and-contexts.adoc[contracts and context] to create a clear split between the process logic, the data, and the user views.

WARNING: Attention: Starting with Bonita 7.8, 6.x forms and case overview pages are not available for modeling or execution. Before migrating to Bonita 7.8, you need to create all forms with Bonita UI Designer to benefit from technologies like html/AngularJS and use contracts in tasks and process instantiation. For more information, read the xref:migrate-a-form-from-6-x.adoc[migrate a form from 6.x] page. 

You will also find lots of familiar features, which continue to work as they did in 6.x.

*Tell me about the documentation.*

We're continually updating the documentation. +
There are four main information categories: Application and process design, Installation, Portal administration, and Development.

*Tell me about using Bonita.*

See xref:lifecycle-and-profiles.adoc[Lifecycle and profiles].

*Can I migrate an existing process into Bonita 7.x?*

You can xref:import-and-export-a-process.adoc[import a process] from any earlier Bonita release if  they don't contain Legacy v6 forms or case overview pages. If they do, you need to rework your process and xref:migrate-a-form-from-6-x.adoc[migrate those froms or pages].

*Tell me about creating an application.*

An application is a collection of related processes, user interfaces, and shared data. See xref:design-methodology.adoc[design methodology].

*Tell me about creating a process.*

A process can be included in an application or can be accessed through Bonita Portal. See xref:design-methodology.adoc[design methodology].

*Tell me about creating a diagram.*

See xref:diagram-overview.adoc[diagrams].

*How can I get started?*

Download and install Bonita 7.x: see the xref:bonita-bpm-installation-overview.adoc[installation instructions].
