= Bonita's purpose
:description: Bonita is an open-source and extensible platform for business process automation and optimization. Bonita Platform accelerates the development and production of business applications, with clear separation between capabilities for visual programming and for coding. +

{description}

BPMN (Business Process Modeling Notation), full extensibility, and reusable components allow smooth collaboration among the different profiles on the IT team, and with the business teams. +
Bonita integrates with existing information systems, orchestrates heterogeneous systems, and provides deep visibility into processes across the organization.

Bonita Platform has two components: the development environment, Bonita Studio, and the runtime environment, Bonita Runtime.

== What can I do with Bonita?

Bonita is a Digital Process Automation (DPA) platform that allows you to create applications based on processes. Processes can be partially automated (if involving users) or fully automated.

DPA, available with all Bonita editions, is applicable to a wide range of use cases: applications can go from loan request management, to student application processes, to analytical processes in drug discovery - and more! You can find the various industries where Bonita is used as well as use cases from our https://www.bonitasoft.com/industries[website dedicated page].

Starting with Bonita 7.10, you can also handle Adaptive Case Management (ACM) with Bonita.
ACM is like DPA in the sense that it allows to handle cases with some automation. But it also relies on strong principles that make it different from DPA:

* Empower the actors:
Actors in charge of the case have some autonomy to lead the case to its closure: not all process paths are pre-determined. Some tasks are optional, some are discretionnary.
Actors' specific knowledge make them fully able to choose the right next action for a case.
* Expect the unexpected:
A case can be stopped, resumed and can even change its state at any time without a path being predefined. New tasks may need to be created on the fly to reflect the specificity of a case while still benefiting from traceability.
* Adapt to the context: case type and state define the availability of tasks following a set of business rules. Those rules must be editable on the fly.
* Center on data: Case execution is not centered around a strict process, but around case data to create and update.

To learn more about how to use ACM capabilities in Bonita, check the dedicated xref:use-bonita-acm.adoc[documentation].

== Overview of the Bonita solution architecture

