= Bonita Applications overview
:page-aliases: bonita-bpm-portal-interface-overview.adoc
:description: This page describes the Bonita Applications. +

{description} 

They rely on the analysis that four types of personas use process-based applications in a company:

* the *User* is responsible of performing the tasks for which they are a candidate and also for starting new instances of the processes to which they have access.
* the *Administrator* is responsible for the administration of Bonita at tenant level, and particularly for the management of the processes, the organization, the reports, the custom profiles and the Look & Feel.
* the *Process Manager* shares process management responsibilities with the Administrator for the processes he has been declared as the Process Manager.
* the *Technical User* is responsible for granting permissions to use Bonita in non-production or production environments by creating users. S·he is also the only person with permissions to start and stop the BPM services for maintenance operations or BDM update. 

== Bonita Applications details

Bonita Runtime embeds two types of applications:

* _*Core applications*_: they are critical to the good operation of Bonita in a Production environment. Only their look & feel can be customized:
  ** _Super Administrator application_, the Technical User's tool to bootstrap Bonita Runtime, pause and resume BPM services, and update the BDM
  ** _Application Directory_, that displays the catalog of available applications to the logged user
* _*Generic applications*_: they are fully functional, can be fully customized, but can be deleted if not useful in a Production environment:
  ** _User_ , based on a standard BPM usage, centered on a generic tasklist
  ** _Administrator_, allowing the management (monitoring and troubleshooting) of an automation project in production (BDM excepted)

These applications are installed by default for a fresh installation of the platform. +
In addition to that, the generic Bonita Applications can be downloaded from the Welcome Page of the Studio, in the "Resources" tile. +
You may want to do so to create your applications from an example. +

Applications are flexible in two ways:

* The navigation can be customized: remove the pages that are not needed, add custom pages that are needed.
* Some pages of those applications have been recreated with Bonita UI Designer (find xref:design-methodology.adoc[the list here]). This means that you can open and customize the page to make it fit the precise needs of the users. Starting with an existing page accounts for a big gain of time.

== Custom Applications

You can also create views that fit users' needs better than the Bonita Applications. +
With Bonita 7.0, Living applications have given the possibility to create applications _made of custom pages_, with their own look & feel. The pages can be created with Bonita UI Designer or with another technology. +
To know more about how to create an application, or create an application from a Bonita Application, go to the xref:custom-applications-index.adoc[custom applications] page.
