= Bonita installation overview

Description of the different options for Bonita installation.

Bonita exists in several http://www.bonitasoft.com/bonita-editions[editions]: Enterprise, Performance, Efficiency, Teamwork, and Community.

For the Bonita Subscription editions: Enterprise, Performance, Efficiency, and Teamwork, you need to xref:licenses.adoc[install a license] during the installation procedure. This license depends on the edition, the deployment environment, the number of cases purchased or the number of cores.

For the Bonita Community edition, no license is needed.

Bonita Studio
// {.h2}

Bonita Studio contains an embedded test platform that includes an Apache Tomcat application server, an h2 database and the Bonita web application (that itself includes Bonita Engine).

To install Bonita Studio you can either use:

* The installer for your operating system (Windows, Mac OS, Linux).
Used to install Bonita Studio (using a wizard) on your computer. No configuration necessary.
* The OS independent package. Used to manually set up Bonita Studio.
The package contains the individual launchers in one .zip file, and creates the same installation environment as the installers.

To know more, go to xref:bonita-bpm-studio-installation.adoc[Bonita Studio installation].

+++<a id="platform">++++++</a>+++

Bonita Platform
// {.h2}

Bonita Platform can be installed in several ways:

* If you want to migrate an existing installation to the latest version follow the xref:migrate-from-an-earlier-version-of-bonita-bpm.adoc[migration guide].
* If you want to do a fresh install, get one of our prepackaged bundles that include an Application Server
 ** xref:tomcat-bundle.adoc[Tomcat + Bonita]
 ** xref:wildfly-bundle.adoc[WildFly + Bonita]
* If you want to do a custom installation, use the xref:deploy-bundle.adoc[Deploy bundle].

For all options, you will need to xref:database-configuration.adoc[configure] Bonita Engine to work with the database of your choice (e.g. PostgreSQL or Oracle).

WARNING:
Starting from Bonita 7.3.0, there is no more bonita home to store the configuration, all the configuration is in the database. For more information, take a look at xref:BonitaBPM_platform_setup.adoc[Bonita Platform configuration]


For detailed information on the Supported Environment Matrix, see the https://customer.bonitasoft.com/support-policies[Support Guide] or http://www.bonitasoft.com/contact-us[ask to be contacted by our commercial team].
