= Bonita BPM overview

Bonita BPM 7 is a powerful BPM-based application platform for building highly engaging, personalized, process-based business applications to get things done, take full advantage of BPM, and adapt to business changes in real time.

Bonita BPM has two parts: the development environment, Bonita BPM Studio, and the runtime environment, Bonita BPM Platform.

== Bonita BPM Studio

Bonita BPM Studio is a graphical environment for creating processes, applications, data models, and users views (pages and forms). It contains three major design tools:

* the whiteboard, for drawing a process flow diagram and defining the detail of steps, transitions, decision points and other process elements
* the Development menu, to extend the Studio capabilities and create your data models
* the UI Designer, which is used to create application pages and process forms

Bonita BPM Studio is the development tool for the Business Analyst and Application Developer. Back-end java developers work in Bonita BPM Studio and collaborate with front-end developers working in the UI Designer.

You can xref:bonita-bpm-installation-overview.adoc[install Bonita BPM Studio] on your computer, then create and test processes, create data models, applications and application views (pages and forms).

Bonita BPM Studio contains a *Bonita BPM Platform* (Tomcat, UI Designer, Bonita BPM Portal, Bonita BPM Engine, and an h2 database), suitable for testing an application that is in development. When you run a process, it is automatically deployed onto the development platform.

Process forms, used to complete the human tasks, are created in the UI Designer, and use the data models created in the Studio.

Users can use Bonita BPM Portal (_User_ profile) to view and complete the process tasks for all processes. You can also build personalized process-based applications. To do so, use the UI Designer to create application pages that display business data from the data models, link the pages to processes thanks to action buttons, then use the Bonita BPM Portal application builder to construct the application piece by piece.

+++<a id="platform">++++++</a>+++

== Bonita BPM Platform

xref:engine-architecture-overview.adoc[Bonita BPM Engine] is the execution engine of Bonita BPM.

As mentioned before, xref:bonita-bpm-portal-interface-overview.adoc[Bonita BPM Portal] is the part of Bonita BPM that is visible to process users, who use it to view tasks and take actions thanks to a generic task list for all processes they are involved in.

But Bonita BPM Portal is also the tool used by the tenant administrator to xref:processes.adoc[install, deploy and manage processes] and to xref:applications.adoc[build applications]. We use the word "tenant" here, in case the platform would be made of xref:multi-tenancy-and-tenant-configuration.adoc[several tenants].

To install Bonita BPM Engine and Bonita BPM Portal in a qualification or production environment, link:bonita-bpm-installation-overview.md#platform[install Bonita BPM Platform].

In Bonita BPM Studio, once a process is ready, you can xref:build-a-process-for-deployment.adoc[build] it and deploy it on your Bonita BPM qualification or production platform.

== Editions

Bonita BPM is provided in four different editions: Community, Teamwork, Efficiency, Performance.

== Getting started

*I'm currently using Bonita BPM 6.x. Will 7.x be a big change?*

Bonita BPM 7.x provides new and improved features, including the xref:ui-designer-overview.adoc[UI Designer] for creating application pages and forms, as well as xref:contracts-and-contexts.adoc[contracts and context] to create a clear split between the process logic, the data, and the user views. +
You will also find lots of familiar features, which continue to work as they did in 6.x.

*Tell me about the documentation.*

We're continually updating the documentation. +
There are four main information categories: Application and process design, Installation, Portal administration, and Development.

*Tell me about using Bonita BPM.*

See xref:lifecycle-and-profiles.adoc[Lifecycle and profiles].

*Can I migrate an existing process into Bonita BPM 7.x?*

You can xref:import-and-export-a-process.adoc[import a process] from any earlier Bonita BPM release. You can also xref:migrate-a-process-from-bonita-open-solution-5-x.adoc[migrate a process from Bonita Open Solution 5.9 or 5.10] to this release. A 6.x process will continue to run unchanged in 7.x, but to take advantage of the new features, you will need to update the process and xref:migrate-a-form-from-6-x.adoc[migrate the forms].

*Tell me about creating an application.*

An application is a collection of related processes, user interfaces, and shared data. See xref:design-methodology.adoc[design methodology].

*Tell me about creating a process.*

A process can be included in an application or can be accessed through Bonita BPM Portal. See xref:design-methodology.adoc[design methodology].

*Tell me about creating a diagram.*

See xref:diagram-overview.adoc[diagrams].

*How can I get started?*

Download and install Bonita BPM 7.x: see the xref:bonita-bpm-installation-overview.adoc[installation instructions].
