= Bonita's purpose
:description: This page gives an overview of the business use-cases Bonita helps solve.

{description}

Digital Process Automation (DPA), the core of Bonita Platform, is applicable to a wide range of use cases: applications can go from loan request management, to student application processes, to analytical processes in drug discovery - and more! You can find the various industries where Bonita is used as well as use cases from our https://www.bonitasoft.com/industries[website dedicated page].

== Processes that need automation

Some business processes do not need to be automated. Their execution stays in the scope of one team, the data they handle does not need to be retrieved nor sent from/to many places, nor undergo transformations from one step to the other, the execution of each instance does not need traceability nor reminders, and there is no need of reporting about their execution. +
In two words, such processes are not critical to the company's business: it is good when their execution is flawless, but it is ok if there is a little delay sometimes too.

For all other processes, automation is more than welcome.

== The automation types

Some processes need a chain of technical systems actions to take place in specific amount of time, with no errors. Although humans will supervise that the execution goes well, specific user interfaces might not be needed: error monitoring and a few database queries can do the supervising job.

For all other processes, user interfaces are more than welcome, in the form of business applications, running processes in the background.

== The business applications types 

This is where business analysts need to take one step aside and look at the overall way the end-users work. +

* Their job may require to be process-centric and do tasks from different processes as they appear in their todo list, with some filtering options. The task-list application is what you need. As an option, team coordinators can pre-sort and assign tasks as they become available, let the team organize themselves, or have the assignment criteria implemented in the process xref:actors.adoc[actor mapping]. Bonita provides such a task list in the xref:user-application-overview.adoc[User application].
* Their job may require to be data-centric, with very standardized processes creating, modifying and sharing data in a consisteny way. In this case, a BPM approach with a Living application displaying lists of cases (requests, claims, invoices, tickets,...) to handle is the right way to go.
* Their job may require to be data-centric and manage each case in a specific way due to some conditions. They may need to skip some tasks, add others, so the process can be partially structured and partially open to changes decided by the knowledge workers. In this case, an xref:use-bonita-acm.adoc[Adaptive Case Management] (ACM) approach, with specific process design and user interfaces, is right for them.


