= Bonita Layout
:description: [NOTE]

[NOTE]
====

For Enterprise, Performance, Efficiency, and Teamwork editions only.
====

This layout has different desktop and mobile versions.

For the desktop version, the layout contains two rows. +
The first row has the logo, the name of the application on the left, as well as the user name, which, when clicked,
opens the information about the current session. The last button of the first row opens a window that will let you
switch between living applications. +
The second row contains the menu of the application pages.

For the mobile version there is only one row that has the name of the application, as well as a button that opens a
dropdown. The dropdown will contain the menu of the application pages, the user name which, when clicked, opens the
information about the current session, as well as the button that opens the navigation between applications.

== Customizing this layout

You can customize this layout by following the xref:customize-layouts.adoc[customize-layouts] steps.

== Dependencies

=== Adding a logo to the layout

The first option is changing the theme that is used by the application by adding a``logo.png`` file in the
`resources/images/` folder. If the folder does not exist, create it manually. +
The second option is adding an image asset to the layout in UI Designer, and using this asset directly in the URL
property of the image widget.

=== Font awesome

This layout requires a theme containing the font-awesome library.
If you are using a custom theme, make sure xref:themes.adoc#font-awesome[font-awesome is available in your theme].
