= Bonita Studio hints and tips

Discover how to add items to a diagram in Bonita Studio, use the tree view, and search/edit diagrams.

== Adding items to a diagram

There are several ways to add an item to the diagram:

* Click-and-hold on a icon in the *BPMN elements* menu and drag it to where you want the item in the whiteboard.
* Click-and-release on an icon in the *BPMN elements* then click where you want it to appear in the whiteboard.
* Select the previous item in the flow, and drag the item from the context menu to where you want it in the whiteboard.
* Copy and paste an item from another pool.

The advantage of selecting items from the *BPMN elements* menu is that you can choose precisely the item you want. +
The advantage of using the content menu is that the transition is automatically created.

If you add an icon to the diagram over a transition, the transition will be broken into two parts and the new item inserted between them. This is called _break-and-insert_, and can be used with any BPMN flow element except text annotations. You can also use _break-and-insert_ when moving an item to a different place in a pool, if the transitions can be resolved.

== Using the tree view and search

The tree view shows all the information that is in a diagram, arranged in a hierarchical structure. It can be a useful way to see all the information related to a particular step or form, or to find where a specific item is configured. For example, you can see the step where a variable is defined without having to check all the steps.

To find a term in your diagram, go to the Tree View panel (by default, at the bottom-left of the screen), enter the term in the filter field and press return. +
The tree view is updated to show only the items that match the term.

== Changing the diagram name and version

Click on the background (outside of a pool) and go to the *Diagram tab* in the *Details panel*. Click on *_Edit..._* then specify the new name and version number.

You can use the same dialog to change the name and version of any pools in the diagram.

== Changing the diagram appearance

You can modify the appearance of an item in the diagram by selecting it and going to the *Appearance tab* in the *Details panel*.

In addition to changing the appearance of individual items in the diagram, there are some tools that you can use to make the layout clearer, by selecting a group of items and making the vertical or horizontal alignment regular. If a diagram is being developed or maintained by more than one person, it is important to keep the layout clear, to prevent misunderstanding.

The alignment tools, and others, are accessed from the icons at the bottom-left of the whiteboard.

== Open a recently modified diagram

To see a list of recently modified diagrams without having to go to the Welcome page, go to the *Diagram* menu and choose *Recently modified*. +
A submenu of the last ten diagrams you have modified is displayed. Click the _*name*_ of a diagram to open it.
