= REST API BPM API
:description: Easily retrieve human or service tasks, call activities, and subprocesses with BPM APIs. Perform maintenance tasks.

Easily retrieve human or service tasks, call activities, and subprocesses with BPM APIs. Perform maintenance tasks.

Documentation split : 

* xref:activities-tasks-flow-nodes-API.adoc[Activities, Tasks and Flow nodes]
* Data and CaseDocument 
* Actors, Process and Connectors 
* Cases (Process Instances) 


// first cut VBO 170322

== Cases (Process Instances)

[#case]

=== Case

==== Description

Case is an instance of a process. When you start a process, it creates a case.

==== Identifier

ID of the Object: a long value

==== Representation

[source,json]
----
{
  "id":"the identifier of the case",
  "end_date":"the date set when the case is closed",
  "failedFlowNodes":"count of failed flow nodes if parameter n=failedFlowNodes is given",
  "startedBySubstitute":"the identifier of the substitute user (as Process manager or Administrator) who started the process. It can be also the substitute user if d=startedBySubstitute is given.",
  "start":"the starting date of the case",
  "activeFlowNodes":"count of active flow nodes if parameter n=activeFlowNodes is given",
  "state":"state: an enum that represent the state of the case, it can be INITIALIZING, STARTED, SUSPENDED, CANCELLED, ABORTED, COMPLETING, COMPLETED, ERROR, ABORTING",
  "rootCaseId":"the identifier of the container of the case",
  "started_by":"the identifier of the user who started the case",
  "processDefinitionId":"the identifier of the process related of the case",
  "last_update_date":"the date of the last update done on the case",
  "searchIndex1Label":"the 1st search index label (from 6.5, in Subscription editions only)",
  "searchIndex2Label":"the 2nd search index label (from 6.5, in Subscription editions only)",
  "searchIndex3Label":"the 3rd search index label (from 6.5, in Subscription editions only)",
  "searchIndex4Label":"the 4th search index label (from 6.5, in Subscription editions only)",
  "searchIndex5Label":"the 5th search index label (from 6.5, in Subscription editions only)",
  "searchIndex1Value":"the 1st search index value (from 6.5, in Subscription editions only)",
  "searchIndex2Value":"the 2nd search index value (from 6.5, in Subscription editions only)",
  "searchIndex3Value":"the 3rd search index value (from 6.5, in Subscription editions only)",
  "searchIndex4Value":"the 4th search index value (from 6.5, in Subscription editions only)",
  "searchIndex5Value":"the 5th search index value (from 6.5, in Subscription editions only)"
}
----

==== Methods

* POST - Create a case
* GET - Read a case or search for a case
* DELETE - Remove a case

[#case-deploy]

==== Response object extension (deploy query parameter)

The `d` (deploy) used to xref:rest-api-overview.adoc#extend-resource[extend response object] can be used with :

* `started_by`
* `startedBySubstitute`
* `processDefinitionId`

==== Read a case

You can get a case by using its identifier. Request url

* *URL* +
`/API/bpm/case/:id`
* *Method* +
`GET`
* *Data Params*
 ** d: extend resource response parameters of <<case-deploy,this resource>> are available.
Available values: started_by, startedBySubstitute, processDefinitionId.
 ** n: count of related resources. Available values: activeFlowNodes, failedFlowNodes.
* *Success Response* +
A JSON representation of the case
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "id": "1",
  "end_date": "",
  "failedFlowNodes": "9",
  "startedBySubstitute": {
    "last_connection": "2014-12-01 10:46:03.750",
    "created_by_user_id": "-1",
    "creation_date": "2014-11-27 17:53:46.516",
    "id": "4",
    "icon": "/default/icon_user.png",
    "enabled": "true",
    "title": "Mr",
    "manager_id": "3",
    "job_title": "Human resources benefits",
    "userName": "walter.bates",
    "lastname": "Bates",
    "firstname": "Walter",
    "password": "",
    "last_update_date": "2014-11-27 17:53:46.516"
  },
  "start": "2014-11-27 17:55:00.906",
  "activeFlowNodes": "9",
  "state": "started",
  "rootCaseId": "1",
  "started_by":{
    "last_connection": "",
    "created_by_user_id": "-1",
    "creation_date": "2014-11-27 17:53:46.509",
    "id": "3",
    "icon": "/default/icon_user.png",
    "enabled": "true",
    "title": "Mrs",
    "manager_id": "1",
    "job_title": "Human resource manager",
    "userName": "helen.kelly",
    "lastname": "Kelly",
    "firstname": "Helen",
    "password": "",
    "last_update_date": "2014-11-27 17:53:46.509"
  },
  "processDefinitionId": {
    "id": "5777042023671752656",
    "icon": "",
    "displayDescription": "",
    "deploymentDate": "2014-11-27 17:54:37.774",
    "description": "",
    "activationState": "ENABLED",
    "name": "Pool2",
    "deployedBy": "4",
    "displayName": "Pool 2",
    "actorinitiatorid": "1",
    "last_update_date": "2014-11-27 17:54:43.621",
    "configurationState": "RESOLVED",
    "version": "2.0"
  },
  "last_update_date": "2014-11-27 17:55:00.906",
  "searchIndex1Label":"mySearchIndex1Label",
  "searchIndex2Label":"mySearchIndex2Label",
  "searchIndex3Label":"mySearchIndex3Label",
  "searchIndex4Label":"mySearchIndex4Label",
  "searchIndex5Label":"mySearchIndex5Label",
  "searchIndex1Value":"mySearchIndex1Value",
  "searchIndex2Value":"mySearchIndex2Value",
  "searchIndex3Value":"mySearchIndex3Value",
  "searchIndex4Value":"mySearchIndex4Value",
  "searchIndex5Value":"mySearchIndex5Value"
}
----

==== Search for a case

* *URL* +
`/API/bpm/case` +
_Example_:  list active cases for process definition with ID 1234 `/API/bpm/case?p=0&c=10&f=processDefinitionId=1234`
* *Method* +
`GET`
* *Data Params* +
xref:rest-api-overview.adoc#resource_search[Standard search parameters] are available.
 ** f: filter of the search. Available filters are :
  *** `processDefinitionId`: The process derfinition ID
  *** `name`: the process name
  *** `started_by`: the ID of the user who started the process
  *** `team_manager_id`: allow to retrieve the cases in which all users with this manager ID ar involved)
  *** `supervisor_id`: allow the retrived the cases of all processes the user with this ID is supervisor of)
beware you cannot use team_manager_id and supervisor_id at the same time
 ** n: count of related resource. Available values: `activeFlowNodes`, `failedFlowNodes`
 ** d: extend resource response parameters of <<case-deploy,this resource>> are available.
* *Success Response* +
JSON representations of matching cases
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
[
  {
    "id": "1",
    "end_date": "",
    "failedFlowNodes": "9",
    "startedBySubstitute":{
      "last_connection": "2014-12-01 10:46:03.750",
      "created_by_user_id": "-1",
      "creation_date": "2014-11-27 17:53:46.516",
      "id": "4",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mr",
      "manager_id": "3",
      "job_title": "Human resources benefits",
      " userName": "walter.bates",
      "lastname": "Bates",
      "firstname": "Walter",
      "password": "",
      "last_update_date": "2014-11-27 17:53:46.516"
    },
    "start": "2014-11-27 17:55:00.906",
    "activeFlowNodes": "9",
    "state": "started",
    "rootCaseId": "1",
    "started_by":{
      "last_connection": "",
      "created_by_user_id": "-1",
      "creation_date": "2014-11-27 17:53:46.509",
      "id": "3",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mrs",
      "manager_id": "1",
      "job_title": "Human resource manager",
      "userName": "helen.kelly",
      "lastname": "Kelly",
      "firstname": "Helen",
      "password": "",
      "last_update_date": "2014-11-27 17:53:46.509"
    },
    "processDefinitionId":{
      "id": "5777042023671752656",
      "icon": "",
      "displayDescription": "",
      "deploymentDate": "2014-11-27 17:54:37.774",
      "description": "",
      "activationState": "ENABLED",
      "name": "Pool2",
      "deployedBy": "4",
      "displayName": "Pool 2",
      "actorinitiatorid": "1",
      "last_update_date": "2014-11-27 17:54:43.621",
      "configurationState": "RESOLVED",
      "version": "2.0"
    },
    "last_update_date": "2014-11-27 17:55:00.906",
    "searchIndex1Label":"case1SearchIndex1Label",
    "searchIndex2Label":"case1SearchIndex2Label",
    "searchIndex3Label":"case1SearchIndex3Label",
    "searchIndex4Label":"case1SearchIndex4Label",
    "searchIndex5Label":"case1SearchIndex5Label",
    "searchIndex1Value":"case1SearchIndex1Value",
    "searchIndex2Value":"case1SearchIndex2Value",
    "searchIndex3Value":"case1SearchIndex3Value",
    "searchIndex4Value":"case1SearchIndex4Value",
    "searchIndex5Value":"case1SearchIndex5Value"
  },
  {
    "id": "2",
    "end_date": "",
    "failedFlowNodes": "0",
    "startedBySubstitute":{
      "last_connection": "2014-12-01 10:46:03.750",
      "created_by_user_id": "-1",
      "creation_date": "2014-11-27 17:53:46.516",
      "id": "4",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mr",
      "manager_id": "3",
      "job_title": "Human resources benefits",
      "userName": "walter.bates",
      "lastname": "Bates",
      "firstname": "Walter",
      "password": "",
      "last_update_date": "2014-11-27 17:53:46.516"
    },
    "start": "2014-11-27 17:56:28.596",
    "activeFlowNodes": "1",
    "state": "started",
    "rootCaseId": "2",
    "started_by":{
      "last_connection": "",
      "created_by_user_id": "-1",
      "creation_date": "2014-11-27 17:53:46.509",
      "id": "3",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mrs",
      "manager_id": "1",
      "job_title": "Human resource manager",
      "userName": "helen.kelly",
      "lastname": "Kelly",
      "firstname": "Helen",
      "password": "",
      "last_update_date": "2014-11-27 17:53:46.509"
    },
    "processDefinitionId":{
      "id": "4948193168427526005",
      "icon": "",
      "displayDescription": "",
      "deploymentDate": "2014-11-27 17:56:10.920",
      "description": "",
      "activationState": "ENABLED",
      "name": "ConnectorFailed",
      "deployedBy": "4",
      "displayName": "ConnectorFailed",
      "actorinitiatorid": "2",
      "last_update_date": "2014-11-27 17:56:12.470",
      "configurationState": "RESOLVED",
      "version": "1.0"
    },
    "last_update_date": "2014-11-27 17:56:28.596",
    "searchIndex1Label":"case2SearchIndex1Label",
    "searchIndex2Label":"case2SearchIndex2Label",
    "searchIndex3Label":"case2SearchIndex3Label",
    "searchIndex4Label":"case2SearchIndex4Label",
    "searchIndex5Label":"case2SearchIndex5Label",
    "searchIndex1Value":"case2SearchIndex1Value",
    "searchIndex2Value":"case2SearchIndex2Value",
    "searchIndex3Value":"case2SearchIndex3Value",
    "searchIndex4Value":"case2SearchIndex4Value",
    "searchIndex5Value":"case2SearchIndex5Value"
  }
]
----

==== Create a case

This way of creating a case using this method will only work for processes in which no contract is defined. To instantiate a process with a contract, check the <<instantiate_process,process instantiation resource documentation>>.

* *URL* +
`/API/bpm/case`
* *Method* +
`POST`
* *Request Payload* +
The process definition id, in JSON

===== Create a case without variables

[source,json]
----
{
  "processDefinitionId":"5777042023671752656"
}
----

===== Create a case with variables

[IMPORTANT]
====
The attribute "variables" on the request payload is used to initialize the process variables (not BDM variables).
If you want to initialize BDM variables at process instantiation, add a contract on the process and map BDM variables to the contract data.
See <<start-a-process-using-an-instantiation-contract,Start a process using an instantiation contract>> for usage.
====

[source,json]
----
{
  "processDefinitionId":"5777042023671752656",
  "variables":[
    {
      "name":"stringVariable",
      "value":"aValue"
    },
    {
      "name":"dateVariable",
      "value":349246800000
    },
    {
      "name":"numericVariable",
      "value":5
    }
  ]
}
----

* *Success Response* +
The JSON representation of a case resource
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "id": "1001",
  "end_date": "",
  "startedBySubstitute": "4",
  "start": "2014-12-01 14:36:23.732",
  "state": "started",
  "rootCaseId": "1001",
  "started_by": "4",
  "processDefinitionId": "5777042023671752656",
  "last_update_date": "2014-12-01 14:36:23.732"
}
----

==== Delete a case

* *URL* +
`/API/bpm/case/:caseId`
* *Method* +
`DELETE`
* *Success Response*
 ** *Code*: 200

==== Delete cases in bulk

* *URL* +
`/API/bpm/case/`
* *Method* +
`DELETE`
* *Request Payload*
List of case ids to delete
+
[source,json]
----
["1", "2" , ...]
----

* *Success Response*
 ** *Code*: 200

[#retrieve-the-case-context]

==== Retrieve the case context

* *URL* +
`/API/bpm/case/:caseId/context`
* *Method* +
`GET`
* *Success Response* +
A context object
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "myBusinessData_ref":{
    "name":"myBusinessData",
    "type":"com.company.model.BusinessObject1",
    "link":"API/bdm/businessData/com.company.model.BusinessObject1/2",
    "storageId":2,
    "storageId_string":"2"
  },
  "myDocument_ref":{
    "id":1,
    "processInstanceId":3,
    "name":"myDocument",
    "author":104,
    "creationDate":1434723950847,
    "fileName":"TestCommunity-1.0.bos",
    "contentMimeType":null,
    "contentStorageId":"1",
    "url":"documentDownload?fileName=TestCommunity-1.0.bos&contentStorageId=1",
    "description":"",
    "version":"1",
    "index":-1,
    "contentFileName":"TestCommunity-1.0.bos"
  }
}
----

=== ArchivedCase

==== Description

A completed instance of a process.

==== Identifier

The ID of the archived case (a long value).

==== Representation

[source,json]
----
{
  "id":"the identifier of the archived case",
  "end_date":"the date set when the case was archived",
  "startedBySubstitute":"the id of the user",

  "sourceObjectId":"the id of the case before it was archived"
  "start":"the stard date of the initial case",
  "state":"the state of the archived case",
  "rootCaseId":"the id of the case before it was archived",
  "started_by":"id of the user who start the case",
  "archivedDate":"the date set when the case was archived",
  "processDefinitionId":"the id of the process related to this archived case",
  "last_update_date":"the date of the last update done on the case",
  "searchIndex1Label":"the 1st search index label (from 6.5, in Subscription editions only)",
  "searchIndex2Label":"the 2nd search index label (from 6.5, in Subscription editions only)",
  "searchIndex3Label":"the 3rd search index label (from 6.5, in Subscription editions only)",
  "searchIndex4Label":"the 4th search index label (from 6.5, in Subscription editions only)",
  "searchIndex5Label":"the 5th search index label (from 6.5, in Subscription editions only)",
  "searchIndex1Value":"the 1st search index value (from 6.5, in Subscription editions only)",
  "searchIndex2Value":"the 2nd search index value (from 6.5, in Subscription editions only)",
  "searchIndex3Value":"the 3rd search index value (from 6.5, in Subscription editions only)",
  "searchIndex4Value":"the 4th search index value (from 6.5, in Subscription editions only)",
  "searchIndex5Value":"the 5th search index value (from 6.5, in Subscription editions only)"
}
----

==== Methods

The methods used for this resource are:

* GET - Read a resource or search for a resource
* DELETE - Remove a resource

[#archived-case-deploy]

==== Response object extension (deploy query parameter)

The `d` (deploy) used to xref:rest-api-overview.adoc#extend-resource[extend response object] can be used with :

* `started_by`
* `startedBySubstitute`
* `processDefinitionId`

==== Read an archived case

You can get an archived case by using its identifier. An archive case is linked to a case with the key.

* *URL* +
`/API/bpm/archivedCase/:archivedCaseId`
* *Method* +
`GET`
* *Success Response* +
A JSON representation of the archived case resource
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "id": "9",
  "end_date": "2014-10-22 10:57:00.299",
  "startedBySubstitute": "4",
  "sourceObjectId": "3",
  "start": "2014-10-22 10:56:53.415",
  "state": "completed",
  "rootCaseId": "3",
  "started_by": "4",
  "archivedDate": "2014-10-22 10:57:00.299",
  "processDefinitionId": "6054482369194211518",
  "last_update_date": "2014-10-22 10:57:00.299"
  "searchIndex1Label":"case9SearchIndex1Label",
  "searchIndex2Label":"case9SearchIndex2Label",
  "searchIndex3Label":"case9SearchIndex3Label",
  "searchIndex4Label":"case9SearchIndex4Label",
  "searchIndex5Label":"case9SearchIndex5Label",
  "searchIndex1Value":"case9SearchIndex1Value",
  "searchIndex2Value":"case9SearchIndex2Value",
  "searchIndex3Value":"case9SearchIndex3Value",
  "searchIndex4Value":"case9SearchIndex4Value",
  "searchIndex5Value":"case9SearchIndex5Value"
}
----

==== Search archived cases

You can search cases.

* *URL* +
`/API/bpm/archivedCase`
* *Method* +
`GET`
* *Data Params* +
xref:rest-api-overview.adoc#resource_search[Standard search parameters] are available.
 ** o (order): available values are `id`, `processDefinitionId`, `startedBy`, `startedBySubstitute`, `startDate`,
`endDate`, `lastUpdate`, `archivedDate`, `sourceObjectId`
 ** f: filter of the search. Available filters are :
  *** `sourceObjectId`: The original case ID before the case was archived
  *** `processDefinitionId`: The process derfinition ID
  *** `name`: the process name
  *** `started\_by`: the ID of the user who started the process
  *** `team\_manager\_id`: allow to retrieve the cases in which all users with this manager ID ar involved)
  *** `supervisor\_id`: allow the retrived the cases of all processes the user with this ID is supervisor of)
beware you cannot use team_manager_id and supervisor_id at the same time
 ** d: extend resource response parameters of <<archived-case-deploy,this resource>> are available.
* *Success Response* +
A JSON representation of an array of archived case resources
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
[
  {
    "id": "3002",
    "end_date": "2014-10-22 15:21:10.129",
    "startedBySubstitute": "4",
    "sourceObjectId": "6",
    "start": "2014-10-22 11:47:28.859",
    "state": "completed",
    "rootCaseId": "6",
    "started_by": "4",
    "archivedDate": "2014-10-22 15:21:10.129",
    "processDefinitionId": {
      "id": "5652578116304089592",
      "icon": "",
      "displayDescription": "",
      "deploymentDate": "2014-10-22 11:42:26.644",
      "description": "",
      "activationState": "ENABLED",
      "name": "données",
      "deployedBy": "4",
      "displayName": "données",
      "actorinitiatorid": "4",
      "last_update_date": "2014-10-22 11:42:45.672",
      "configurationState": "RESOLVED",
      "version": "2.0"
    },
    "last_update_date": "2014-10-22 15:21:10.129",
    "searchIndex1Label":"case6SearchIndex1Label",
    "searchIndex2Label":"case6SearchIndex2Label",
    "searchIndex3Label":"case6SearchIndex3Label",
    "searchIndex4Label":"case6SearchIndex4Label",
    "searchIndex5Label":"case6SearchIndex5Label",
    "searchIndex1Value":"case6SearchIndex1Value",
    "searchIndex2Value":"case6SearchIndex2Value",
    "searchIndex3Value":"case6SearchIndex3Value",
    "searchIndex4Value":"case6SearchIndex4Value",
    "searchIndex5Value":"case6SearchIndex5Value"
  }, {
    "id": "9",
    "end_date": "2014-10-22 10:57:00.299",
    "startedBySubstitute": "4",
    "sourceObjectId": "3",
    "start": "2014-10-22 10:56:53.415",
    "state": "completed",
    "rootCaseId": "3",
    "started_by": "4",
    "archivedDate": "2014-10-22 10:57:00.299",
    "processDefinitionId": {
      "id": "6054482369194211518",
      "icon": "",
      "displayDescription": "",
      "deploymentDate": "2014-10-22 10:55:24.219",
      "description": "",
      "activationState": "ENABLED",
      "name": "PoolTestEntry",
      "deployedBy": "4",
      "displayName": "PoolTestEntry",
      "actorinitiatorid": "1",
      "last_update_date": "2014-10-22 10:55:31.178",
      "configurationState": "RESOLVED",
      "version": "1.0"
    },
    "last_update_date": "2014-10-22 10:57:00.299",
    "searchIndex1Label":"case9SearchIndex1Label",
    "searchIndex2Label":"case9SearchIndex2Label",
    "searchIndex3Label":"case9SearchIndex3Label",
    "searchIndex4Label":"case9SearchIndex4Label",
    "searchIndex5Label":"case9SearchIndex5Label",
    "searchIndex1Value":"case9SearchIndex1Value",
    "searchIndex2Value":"case9SearchIndex2Value",
    "searchIndex3Value":"case9SearchIndex3Value",
    "searchIndex4Value":"case9SearchIndex4Value",
    "searchIndex5Value":"case9SearchIndex5Value"
  }
]
----

==== Retrieve an archived case context

* *URL* +
`/API/bpm/archivedCase/:archivedCaseId/context`
* *Method* +
`GET`
* *Success Response* +
A context object
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "myBusinessData_ref":{
    "name":"myBusinessData",
    "type":"com.company.model.BusinessObject1",
    "link":"API/bdm/businessData/com.company.model.BusinessObject1/2",
    "storageId":2,
    "storageId_string":"2"
  },
  "myDocument_ref":{
    "id":1,
    "processInstanceId":3,
    "name":"myDocument",
    "author":104,
    "creationDate":1434723950847,
    "fileName":"TestCommunity-1.0.bos",
    "contentMimeType":null,
    "contentStorageId":"1",
    "url":"documentDownload?fileName=TestCommunity-1.0.bos&contentStorageId=1",
    "description":"",
    "version":"1",
    "index":-1,
    "contentFileName":"TestCommunity-1.0.bos"
  }
}
----

==== Remove an archived case

You can delete an archived case by using its identifier. An archived case is linked to a case with the key.

* *URL* +
`/API/bpm/archivedCase/:archivedCaseId`
* *Method* +
`DELETE`
* *Success Response*
 ** *Code*: 200

=== CaseInfo

==== Description

Retrieves information about a case. It returns counters for each flow node in the case, showing the number of flow node instances that are in completed, ready, or failed state. If there are no flow node instances in a given state, no counter is returned for that state for the flow node.

==== Identifier

The ID of the case (a long value).

==== Representation

[source,json]
----
{
  "id": "case identifier",
  "flowNodeStatesCounters": {
    "Flow Node name from Studio": {
      "completed": "number of instance of the given Flow Node in completed state",
      "ready": "number of instance of the given Flow Node in ready state",
      "failed": "number of instance of the given Flow Node in failed state",
    }
  }
}
----

==== Methods

The method used for this resource is:

* GET - Read a resource

==== Retrieve counters for case flow nodes

Retrieve information about the flow nodes of the case identified by the given ID.

* *URL* +
`/API/bpm/caseInfo/:id`
* *Method* +
`GET`
* *Success Response* +
The JSON representation of the case information
 ** *Code*: 200
 ** *Payload*: +
In this example, counters are returned for two flow nodes in the case, Step1 and Step3. For Step3, there are no flow nodes in ready state, so no counter is returned for this.
+
[source,json]
----
{
  "id": "123",
  "flowNodeStatesCounters": {
    "Step1": {
      "completed": "2",
      "ready": "1",
      "executing": "5"
    },
    "Step3": {
      "completed": "10",
      "failed": "2"
    }
  }
}
----

=== CaseComment

==== Description

Retrieves information about a case comment.

==== Representation

[source,json]
----
{
  "id": "1",
  "content": "the comment content",
  "tenantId": "the id of the tenant the comment is associated to",
  "processInstanceId": "the process instance(case) the comment is associated to",
  "postDate": "the comment creation date",
  "userId": "the user that created the comment"
}
----

==== Methods

The method used for this resource is:

* GET - Search for comments
* POST - Add a comment

==== Response object extension (deploy query parameter)

The `d` (deploy) used to xref:rest-api-overview.adoc#extend-resource[extend response object] can be used with :

* `userId`

[NOTE]
====

Note: if the `userId` is not provided as a deploy parameter, the `userId` property of a comment is filled with the system user :

[source,json]
----
{
  "icon": "/default/icon_user.png",
  "userName": "System"
}
----

====

==== Create a comment

* *URL* +
`/API/bpm/comment`
* *Method* +
`POST`
* *Request Payload* +
The process instance (case) id and the comment content, in JSON
+
[source,json]
----
{
  "processInstanceId":"5777042023671752656",
  "content": "The case has been started"
}
----

* *Success Response* +
The JSON representation of a case comment
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
{
  "content": "test",
  "tenantId": "1",
  "id": "20005",
  "processInstanceId": "1",
  "postDate": "2016-06-16 14:51:33.053",
  "userId": "30"
}
----

==== Search for comments

* *URL* +
`/API/bpm/comment` +
_Example_: `/API/bpm/comment?p=0&c=10&o=postDate%20DESC&f=processInstanceId%3d1&d=userId`
* *Method* +
`GET`
* *Data Params* +
xref:rest-api-overview.adoc#resource_search[Standard search parameters] are available.
 ** o: you can sort on the `postDate`
 ** f: filter of the search. Available filters are :
  *** `supervisor_id`
  *** `user_id`
  *** `processInstanceId`
You cannot use `supervisor_id` and `user_id` filter at the same time.
* *Success Response* +
JSON representations of matching comments
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
[
  {
    "content": "Need to review the last inputs of this case",
    "tenantId": "1",
    "id": "20005",
    "processInstanceId": "1",
    "postDate": "2016-06-16 14:51:33.053",
    "userId": {
      "last_connection": "2016-06-16 14:49:37.067",
      "created_by_user_id": "-1",
      "creation_date": "2016-06-15 11:37:22.709",
      "id": "30",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mr",
      "manager_id": "0",
      "job_title": "Chief Executive Officer",
      "userName": "william.jobs",
      "lastname": "Jobs",
      "firstname": "William",
      "password": "",
      "last_update_date": "2016-06-15 11:37:22.709"
    }
  }, {
    "content": "The task \"Etape1\" is now assigned to walter.bates",
    "tenantId": "1",
    "id": "20003",
    "processInstanceId": "1",
    "postDate": "2016-06-15 12:36:18.541",
    "userId": {
      "icon": "/default/icon_user.png",
      "userName": "System"
    }
  }
]
----

=== ArchivedCaseComment

==== Description

Retrieves information about the comment of an archived case.

==== Representation

[source,json]
----
{
  "id": "1",
  "content": "the comment content",
  "processInstanceId": "the process instance(case) the comment is associated to",
  "postDate": "the comment creation date",
  "archivedDate": "the date set when the case was archived"
  "userId": "the user that created the comment"
}
----

==== Methods

The method used for this resource is:

* GET - Search for archived comments

==== Response object extension (deploy query parameter)

The `d` (deploy) used to xref:rest-api-overview.adoc#extend-resource[extend response object] can be used with :

* `userId`

[NOTE]
====

Note: if the `userId` is not provided as a deploy parameter, the `userId` property of a comment is filled with the system user :

[source,json]
----
{
  "icon": "/default/icon_user.png",
  "userName": "System"
}
----

====

==== Search for archived comments

* *URL* +
`/API/bpm/archivedComment` +
_Example_: `/API/bpm/archivedComment?p=0&c=10&o=postDate%20DESC&f=processInstanceId%3d1&d=userId`
* *Method* +
`GET`
* *Data Params* +
xref:rest-api-overview.adoc#resource_search[Standard search parameters] are available.
 ** o: you can sort on the `postDate` and `archivedDate`
 ** f: filter of the search. Available filters are :
  *** `supervisor_id`
  *** `user_id`
  *** `processInstanceId`
You cannot use `supervisor_id` and `user_id` filter at the same time.
* *Success Response* +
JSON representations of matching comments
 ** *Code*: 200
 ** *Payload*:
+
[source,json]
----
[
  {
    "content": "Need to review the last inputs of this case",
    "id": "20005",
    "processInstanceId": "1",
    "postDate": "2016-06-16 14:51:33.053",
    "archivedDate": "2016-06-17 10:18:24.723",
    "userId": {
      "last_connection": "2016-06-16 14:49:37.067",
      "created_by_user_id": "-1",
      "creation_date": "2016-06-15 11:37:22.709",
      "id": "30",
      "icon": "/default/icon_user.png",
      "enabled": "true",
      "title": "Mr",
      "manager_id": "0",
      "job_title": "Chief Executive Officer",
      "userName": "william.jobs",
      "lastname": "Jobs",
      "firstname": "William",
      "password": "",
      "last_update_date": "2016-06-15 11:37:22.709"
    }
  }, {
    "content": "The task \"Etape1\" is now assigned to walter.bates",
    "id": "20003",
    "processInstanceId": "1",
    "postDate": "2016-06-15 12:36:18.541",
    "archivedDate": "2016-06-17 10:18:24.723",
    "userId": {
      "icon": "/default/icon_user.png",
      "userName": "System"
    }
  }
]
----
