= Build a process for deployment
:description: Build deployment artifacts that will allow you to install your process onto a server.

Build deployment artifacts that will allow you to install your process onto a server.

== How to

When a process is ready for deployment, build an archive file in Bonita Studio that can be installed in Bonita Applications.
You also need to initialize the organization information needed in Bonita Applications.

A process is deployed by installing a business archive (.bar) file in Bonita Administrator Application.
To create the business archive you can :

. Choose *Build...* from the *Server* menu.
. Select the process to be exported.
. Specify whether you want to export a configuration with the process.
Exporting a configuration will export all the information and other items that you configured, including connectors and dependencies.
. Specify the location where the .bar file will be created. The filename is determined by the process name and cannot be changed at this stage.
. Click *Finish*. The business archive is created.

or

. Right click on a diagram on the project explorer
. Select a process on the menu Build
. Specify the location where the .bar file will be created. The filename is determined by the process name and cannot be changed at this stage.
. Click *Finish*. The business archive is created.

When you build a process from the project explorer, the configuration used is the configuration saved as default. You can edit it from the xref:configuring-a-process.adoc[configure menu]

You can now xref:processes.adoc[install the process in Bonita Administrator Application].

== Initialize the organization in Bonita Administrator Application

To prepare your production system (unless you are using a Subscription editions and the LDAP synchronizer),
you must create the organization that you need for all the processes that will be deployed, export it from Bonita Studio,
and import it into Bonita Administrator Application.

To export the organization, go to the *Organization* menu and choose *Export...*. You
can then xref:import-export-an-organization.adoc[import the organization into Bonita Administrator Application]. After the organization is imported,
you can xref:group.adoc[manage the groups], xref:role.adoc[roles], and xref:manage-a-user.adoc[users] in the organization.
