= Configure a process

Process contains Actor mapping, Connectors, Actor filter, Parameters, Java dependencies. Configuration can be done per Environment.

NOTE:
*Note:* Multiple environments can be created with the Subscription.


To configure a process in Bonita Studio, open the process diagram, select the pool, and click *_Configure_* in the Cool bar.

If you are using a Enterprise, Performance, Efficiency, or Teamwork edition of Bonita, you can configure a process for an xref:environments.adoc[environment]:
with the process diagram open and the pool selected, choose an environment from
the Configuration menu in the Cool bar.

The configuration wizard indicates the items that need to be configured, with a reminder in the wizard title bar for each category. Check the _Display advanced configuration_ box to
see all the items that need to be configured. Follow the instructions in the configuration wizard to complete the configuration.

The following items can be configured:

* Actor mapping
* Connectors
* Parameters
* Actor filters
* Process dependencies
* Application dependencies
* Run user

After deployment, depending on the Bonita edition that you are using, you can xref:live-update.adoc[update the process configuration in production] for some aspects of the process.
