= Connector's development and testing toolkit
:description: A set of best of breed tools to develop and test custom connectors independently of the Bonita Studio.

A set of best of breed tools to develop and test custom connectors independently of the Bonita Studio.

[NOTE]
====

For Performance, Efficiency, and Teamwork editions only.
====

== Overview

The Connector Development Toolkit is a set of tools for implementing and testing Bonita connectors independently of the Bonita Studio. +
A connector implemented with the toolkit can be used in Bonita Studio or in Bonita Portal just like any Bonita connector.

This toolkit uses industry-standard tools such as Java IDEs, dependency management tools (Maven), and unit testing frameworks (JUnit, Mockito and AssertJ).
It has the following benefits for connector developers:

* You can use any Java IDE for implementation, so you have access to all configuration options and can make use of convenient features such as refactoring.
* You can unit test connectors, perform integration tests, and automate builds with a CI platforms.
* It simplifies refactoring of connector wizards, by enabling them to be regenerated them at any time.
* It simplifies dependency management and connector artifact version management, by leveraging Maven capabilities.

== Installation

=== Prerequisites

To develop and test a Bonita connector with the toolkit, you need the following software installed:

* Java 8 or later
* Maven 3.2.x or later

=== Installation procedure

. Download the toolkit from the Customer Portal.
. Unzip the toolkit file into a temporary installation folder.
. Run either `install.bat` for Windows users or `install.sh` for Mac or Linux users.
. When the installer has finished, delete the temporary installation folder because you no longer not need.

== Creating a new connector definition

. Open a command window and navigate to the folder that will hold your connector definition.
. Prepare to run the following command (Windows users: remove the trailing slashes and edit the content to have everything on a single line):

[source,bash]
----
mvn archetype:generate \
    -DinteractiveMode=false \
    -DarchetypeGroupId=com.bonitasoft.connector.definition \
    -DarchetypeArtifactId=bonita-connector-definition-archetype \
    -DarchetypeVersion=1.0 \
    -DgroupId=com.mycompany.connectors \
    -DartifactId=myFirstConnector \
    -Dversion=1.0.0
----

Before running the command, update the following parameter values:

|===
| Parameter | Description

| archetypeVersion
| This must match the version of the toolkit.

| groupId
| Maven project group id.

| artifactId
| Maven project artifact id and Bonita connector definition id.

| version
| Maven project version and Bonita connector definition version.
|===

. Run the command. This generates a new folder named `artifactId` containing the connector definition project files.
