= Custom User Information in Bonita Studio

Learn how you can add custom (business) information on users, that will then be available for filtering.
For instance:

Custom User Information are (key, value) pairs that can be added on users. +
You define the attributes that you want to store, and then add the values for the users. +
You can use custom user information to assign tasks to users based on information that is specific to your organization
and not included in the standard Bonita organization definition.

== Purpose

For example, you may want to create a security badge with an individual value (number) for each user, or an office skill
for a user, a special professional activity, or geographical details.
All these types of information are not displayed in standard information tabs but you may want to filter candidates to a human task thanks to those attributes.

== Define custom user information

In the Organization menu > Manage organizations > Organization users, the second tab *User information management* offers a summary of the default information and allows to create custom user information. Use "Add" to create your own, with a name and an optional description.

. In Bonita Studio, go to *Organization* in the cool bar
. Click on _*Manage*_ in the dropdown menu
. Click on _*Next*_ 3 times to get to the *Organization users* window
. Click on the *User information management* tab
. In the *Custom information* pane on the right hand side of the window, click on _*Add*_
. This will put a default name *Information1* in the *Name column*
. Add a description (if needed). This will only appear in Bonita Studio.
. Double click on the default name *Information1*, to modify it to your needs
. Click on *Finish*
. A message is displayed: _The Organization has been modified. It is recommended to re-publish it. Do you want to do it now?_
. Click on *Yes*
. A confirmation message is displayed showing the organization was successfully re-published
. Click on *Ok*
. A new custom tab is applied to all users.

If the value is changed in Bonita Portal by the admin, and the filter value does not exist in the organization

== Add custom user information values for each user

In the Organization menu > Manage organizations > Organization users, the first tab *List of users* shows detail information for each user on the right hand-side panel, spread over five tabs:

* General (Title, First and last name, Job title)
* Membership (Group/role)
* Personal (Email, phone, website, address etc.)
* Business card (Email, phone, website, address etc.)
* Custom

To add custom user information values for a user, select a user in the *List of users*, click on the *_Custom_* tab, and enter the value for each relevant information. You also see a link *Manage custom information*, to go back and manage the list of custom user information. +
Note: this value can be changed by a user with the Admin profile in the Bonita Portal. See xref:custom-user-information-in-bonita-bpm-portal.adoc[How to edit Custom information for a single user]

== Set an actor filter on custom user information

A task or a lane is linked to an actor. An actor is mapped to a list of users. An actor filter applies to the set of users mapped to the actor. The actor filter configuration can be added to an actor at lane or human task level.

When all relevant users have their Custom User Information set, you can add an actor filter:

. In a process diagram, select a lane or a task
. In the *Details* panel, Go to *General* > *Actors* and select an actor to apply the filter (actors are defined at pool level)
. At *Actor filter* level, click _*Set*_
. In the Actor filters window > Categories, click on _*Organization*_ and choose  _*Users with Custom information*_
. Click on _*Next*_
. Enter a name and a description for the filter configuration
. Click on _*Next*_
. Enter a custom user information *Name* or click on the drop down list to select the one you need
. Enter a value for the information
. To filter on several values using the same string, click _**Partial match **_
. If you expect the filter to return only one user, then it's good that the task is assigned to her automatically. In this case, click the _*Assign tasks automatically*_ checkbox.
. Click on _*Finish*_

The filter is set for the actor and is displayed in the actor filter field. Users from the actor and with the relevant value for the custom information chosen will become candidates to perform the task, or all the tasks in the lane if you set it at lane level.

Note that the filter will not work if you change values in the organization but do not re-publish the organization. This will throw a synchronization error.
