= Bonita portal Custom profiles

Bonita Studio profile editor allows you to create custom profiles that feet better with your needs regarding the Bonita portal.

In a development environment, custom profiles definition and testing is done in xref:profileCreation.adoc[Bonita Studio profile editor].

In a production environment, you can administrate custom profiles in Bonita Portal. To be able to do so, you must be using the *Administrator* profile or a custom profile with access to the profile management page.

NOTE:
*Note:* For Enterprise, Performance and Efficiency editions only.


What customization can I do?

== Create a custom profile

. In the Bonita Portal, in the navigation bar, click the *Organization* menu.
. Click *Profiles*.
. Click _*Add*_.
. In the popup, select *Create a profile*.
. Enter the Name.
. Enter the Description (optional).
. Click *_Create_*.
. Refresh the portal webpage.
. The new profile will appear in the Profiles menu.

For deployment, it is also possible to xref:deploying-profiles-with-export-and-import.adoc[import a profile] by importing an XML file containing the profile definition and mapping to organization and pages.

== Delete custom profile

NOTE: You will need to check the box to make the delete button available.

Select the profile to delete, and click the *delete button*.

== Edit a custom profile

. In the Bonita Portal, in the navigation bar, click the *Organization* menu.
. Click *Profiles*.
. Click _*More*_.
. Click _*Edit*_.
. Change the name or the description of the custom profile
. Click _*Save*_.

== Map a profile to users or groups, membership or role

. In the Bonita Portal, in the navigation bar, click the *Organization* menu.
. Click *Profiles*.
. Choose a profile. This will display the users mapped to the selected profile.
. Click _*More*_.
. Click _*Add a user*_.
. Select a user by ticking the checkbox next to the user name.
. Click _*Add*_.

Do the same steps to map a group, role or membership.

== Create a custom navigation bar

A custom navigation bar can be created for each custom profile created.

NOTE: The navigation bar will not be used by applications as they have their own navigation menu.

. Select profile to add the new menu to
. Click on _*More*_
. This will display the *Navigation bar editor*
. Click _Create menu_.

Here, you will see 3 columns: a check box, a display name and a description.

. Check the boxes to select the pages to include in the new menu.

You can select from the Default pages that are provided with the standard portal and from xref:pages.adoc[Custom pages].

. Click _*Create*_ to confirm your choice of pages and create the menu.

When you select the custom profile, the navigation bar will be applied to it.

NOTE: Click _*Reset*_ to erase the navigation bar if required.

NOTE: The navigation bar is designed to be displayed as a single line. If your menu is too long, use menus with several menu entries in them.

When a user logs in with a profile, the page displayed is the first option in the first menu from the left.
