= Database configuration for engine data
:description: == Database usage

== Database usage

[discrete]
==== Introduction

The Bonita BPM Engine uses an RDBMS (Relational DataBase Management System) to store information about deployed process definitions, process configurations, history of process execution, users, etc. +
One database schema is required by Bonita BPM Engine to store all information.

Bonita BPM Engine connection to the database is done through the Hibernate library (version 4.2). +
This provides a level of abstraction between the engine and the RDBMS. +
Bonita BPM comes with a set of optimized initialization scripts for the https://customer.bonitasoft.com/support-policies[supported RDBMSs].

[NOTE]
====

Some configuration file detailed below are located under `setup` folder. See xref:BonitaBPM_platform_setup.adoc[Bonita BPM platform setup tool] for more information about platform configuration.
====

[NOTE]
====

This page explains database configuration for Bonita BPM Engine data. If you are also using xref:define-and-deploy-the-bdm.adoc[business data objects], these can be stored in a separate database. By default, Bonita BPM comes with an h2 database. For production purposes, we recommend that you xref:database-configuration-for-business-data.adoc[configure a different database for business data].
====

[discrete]
==== Default h2 database

Bonita BPM Studio, the JBoss bundle, the Tomcat bundle, and the deploy bundle come by default with an h2 RDBMS included in the package. The database is automatically created at first startup.

h2 is only suitable for testing purposes.
For production purposes, you must modify the configuration to use another RDBMS.

[discrete]
==== Steps to switch to another RDBMS

[WARNING]
====

Please note this procedure cannot be performed using the Bonita Studio. The Bonita Studio can run only on the H2 Database.
To use Bonita BPM on another RDBMS, please use a xref:_basic-bonita-bpm-platform-installation.adoc[bundle] or set up a xref:deploy-bundle.adoc[standalone server].
====

In order to configure Bonita BPM to work with your RDBMS, you need to perform the following steps:

. Create the database
. Specify the database vendor
. Add the JDBC driver
. Configure data source
. Remove h2
. Configure RDBMS-specific settings

[WARNING]
====

There is a known issue between Bitronix (the Transaction Manager shipped by Bonitasoft for the Tomcat bundle & inside Deploy bundle for Tomcat) and Microsoft SQL Server driver (refer to: https://msdn.microsoft.com/en-us/library/aa342335.aspx[MSDN note], http://bitronix-transaction-manager.10986.n7.nabble.com/Failed-to-recover-SQL-Server-Restart-td148.html[Bitronix note]).
Therefore, using Bitronix as a Transaction Manager with SQL Server is not recommended. Our recommendation is to use the JBoss bundle provided by Bonitasoft.
====

[WARNING]
====

Some RDBMSs require a specific configuration, which must be done before you complete your installation. +
If you do not complete the specific configuration for your RDBMS, your installation may fail.
====

[#database_creation]

== Database creation

The first step in configuring Bonita with your RDBMS is to create a new database (i.e. a new schema).

To do so, you need a RDBMS user account that has sufficient privileges (i.e. privileges to create new schema).

Also, note that the owner of the new schema must have following privileges:

* CREATE TABLE
* CREATE INDEX
* SELECT, INSERT, UPDATE, DELETE on created TABLE

[NOTE]
====

CREATE TABLE and CREATE INDEX are not required after first start in normal use. If the same SQL user is used with xref:migrate-from-an-earlier-version-of-bonita-bpm.adoc[migration tool], then this user needs this grants.
====

To create the database, we recommend you refer to your RDBMS documentation:

* http://www.postgresql.org/docs/9.3/static/app-createdb.html[PostgreSQL]
* https://docs.oracle.com/cd/E11882_01/server.112/e25494/create.htm#ADMIN002[Oracle database]
* https://technet.microsoft.com/en-us/library/dd207005(v=sql.110).aspx[SQL Server]
* http://dev.mysql.com/doc/refman/5.5/en/database-use.html[MySQL]

Your database must be configured to use the UTF-8 character set. You are recommended to configure the database to be case-insensitive so that searches in Bonita BPM Portal are case-insensitive.

== Specify the database vendor

Bonita BPM Engine needs to know which type of RDBMS you use. +
This is defined by setting the `sysprop.bonita.db.vendor` JVM system property value.

The possible values for `sysprop.bonita.db.vendor` / `db.vendor` are:+++<div class="row">+++| Database vendor | Property value | | :- | :- | | PostgreSQL | postgres | | Oracle database | oracle | | SQL Server | sqlserver | | MySQL | mysql | | h2 (default for testing, not for production) | h2 |+++</div>+++

As example, if you want to use postgres, the line will be:
`db.vendor= postgres`

The way to define JVM system properties depends on your application server type:

* JBoss: edit `<JBOSS_HOME>/standalone/configuration/standalone.xml` and set the value of `sysprop.bonita.db.vendor` (look for `<system-properties>` tag).
* Tomcat: edit `setenv.sh` (for Linux) or `setenv.bat` (for Windows) and change the value of `sysprop.bonita.db.vendor` on the line starting by `DB_OPTS`.
* For other application servers, refer to your application server documentation.

An alternative to setting the JVM system property (`sysprop.bonita.db.vendor`) is to set `db.vendor` property value in the
xref:BonitaBPM_platform_setup.adoc[`bonita-platform-community-custom.properties`] file.
The default value of `db.vendor` indicates that the value of the JVM system property value must be used.
If the property is not defined, the fallback value is h2: `db.vendor=${sysprop.bonita.db.vendor:h2}`

== Add the JDBC driver

[discrete]
==== Download JDBC driver

First, you need to download the JDBC driver for your database system. Use the links below to download the driver.

|===
| Database vendor | Download link

| PostgreSQL (use "Current Version")
| https://jdbc.postgresql.org/download.html#current[download]

| Oracle Database
| http://www.oracle.com/technetwork/database/features/jdbc/index-091264.html[download]

| Microsoft SQL Server
| http://go.microsoft.com/fwlink/?LinkId=245496[download]

| MySQL
| http://dev.mysql.com/downloads/connector/j/[download]
|===

NOTE: If you run on Linux, the JDBC driver might also be available in the distribution packages repository. On Ubuntu and Debian, you can, for example, install the `libpostgresql-jdbc-java` package to get the PostgreSQL JDBC Driver (install in `/usr/share/java`).

[#jdbc_driver]

[discrete]
==== Add JDBC driver to application server

The way to install the JDBC driver depends on the application server:

[discrete]
===== JBoss 7

JBoss 7 manages JDBC drivers as modules, so to add a new JDBC driver, complete these steps:
(see https://developer.jboss.org/wiki/DataSourceConfigurationInAS7#jive_content_id_Installing_a_JDBC_driver_as_a_module[JBoss documentation] for full reference):

* Create a folder structure under `<JBOSS_HOME>/modules` folder.
Refer to the table below to identify the folders to create. +
The last folder is named `main` for all JDBC drivers.
* Add the JDBC driver jar file to the `main` folder.
* Create a module description file `module.xml` in `main` folder.

|===
| Database vendor | Module folders | Module description file

| PostgreSQL
| modules/org/postgresql/main
| link:images/special_code/postgresql/module.xml[module.xml]

| Oracle
| modules/com/oracle/main
| link:images/special_code/oracle/module.xml[module.xml]

| SQL Server
| modules/com/sqlserver/main
| link:images/special_code/sqlserver/module.xml[module.xml]

| MySQL
| modules/com/mysql/main
| link:images/special_code/mysql/module.xml[module.xml]
|===

Put the driver jar file in the relevant `main` folder.

In the same folder as the driver, add the module description file, `module.xml`.
This file describes the dependencies the module has and the content it exports.
It must describe the driver jar and the JVM packages that JBoss 7 does not provide automatically.
The exact details of what must be included depend of the driver jar.
*Warning:* You might need to edit the `module.xml` in order to match exactly the JDBC driver jar file name.

[NOTE]
====
 +
By default, when JBoss starts, it removes any comments from `standalone/configuration/standalone.xml` and formats the file.
If you need to retrieve the previous version of this file, go to `standalone/configuration/standalone_xml_history`.
====

[discrete]
==== Tomcat 7

For Tomcat, simply add the JDBC driver jar file in the appropriate folder:

* Bonita BPM Tomcat bundle: in the bundle folder add the driver to the `lib/bonita` folder.
* Bonita BPM deploy bundle: in the Tomcat folder add the driver to the `lib` folder.
* Ubuntu/Debian package: add the driver to `/usr/share/tomcat7/lib`.
* Windows as a service: add the driver to `C:\Program Files\Apache Software Foundation\Tomcat 7.0\lib`

== Configure the data source

Bonita BPM Engine requires the configuration of two data sources. The data source declaration defines how to connect to the RDBMS. The following information is required to configure the data sources:

* Address of the RDBMS server
* Port number of the RDBMS server
* Database (schema) name
* User name to connect to the database
* Password to connect to the database
* JDBC Driver fully qualified class name (see table below)
* XADataSource fully qualified class name (see table below)

|===
| Database vendor | Driver class name | XADataSource class name

| PostgreSQL
| org.postgresql.Driver
| org.postgresql.xa.PGXADataSource

| Oracle Database
| oracle.jdbc.driver.OracleDriver
| oracle.jdbc.xa.client.OracleXADataSource

| Microsoft SQL Server
| com.microsoft.sqlserver.jdbc.SQLServerDriver
| com.microsoft.sqlserver.jdbc.SQLServerXADataSource

| MySQL
| com.mysql.jdbc.Driver
| com.mysql.jdbc.jdbc2.optional.MysqlXADataSource

| h2 (not for production)
| org.h2.Driver
| org.h2.jdbcx.JdbcDataSource
|===

The following sections show how to configure the datasources for JBoss and Tomcat.
There is also an xref:red-hat-oracle-jvm-weblogic-oracle.adoc[example of how to configure datasources for Weblogic].

[discrete]
==== JBoss

This section explains how to configure the data sources if you are using JBoss:

. Open the file `<JBOSS_HOME>/standalone/configuration/standalone.xml`.
. Comment out the default definition for h2.
. Uncomment the settings matching your RDBMS vendor.
. Modify the values for following settings to your configuration: server address, server port, database name, user name and password.

NOTE: For a first test, you might want to keep the h2 section related to Business Data Management (BDM) feature (driver and data sources configuration).
You can update the xref:database-configuration-for-business-data.adoc[configuration related to BDM] later.

[discrete]
==== Tomcat

Configuration of data source for Tomcat is in two parts: because Tomcat doesn't support JTA natively, one data source will be configured in the Bitronix configuration file and the other data source will be configured in the standard Tomcat context configuration file.

[discrete]
===== JTA data source (managed by Bitronix)

. Open `<TOMCAT_HOME>/conf/bitronix-resources.properties` file.
. Remove or comment out the lines regarding the h2 database.
. Uncomment the line matching your RDBMS.
. Update the value for each of the following settings:
 ** For `resource.ds1.driverProperties.user`, put your RDBMS user name.
 ** For `resource.ds1.driverProperties.password`, put your RDBMS password.
 ** For `resource.ds1.driverProperties.serverName`, put the address (IP or hostname) of your RDBMS server.
 ** For `resource.ds1.driverProperties.portNumber`, put the port of your RDBMS server.
 ** For `resource.ds1.driverProperties.databaseName`, put the database name.
. Save and close the file.

[discrete]
===== Non-transactional data source

The second data source run SQL queries outside any transaction. To configure it:

. Open `<TOMCAT_HOME>/conf/Catalina/localhost/bonita.xml` file.
. Remove or comment out the lines regarding h2 database.
. Uncomment the line matching your RDBMS.
. Update following attributes value:
 ** `username`: your RDBMS user name.
 ** `password`: your RDBMS password.
 ** `url`: the URL, including the RDBMS server address, RDBMS server port and database (schema) name.

== Remove h2

WARNING: If you use the default configuration for business data (BDM), do not remove h2 yet.
First make sure that you have xref:database-configuration-for-business-data.adoc[configured Business Data] to use your own RDBMS.

Now that you are almost done with the switch from h2 to your chosen RDBMS, you can remove h2:

* For JBoss
 ** Delete the `$JBOSS_HOME/standalone/deployments/h2.sar` folder.
 ** Remove the configuration for h2 from `<JBOSS_HOME>/standalone/configuration/standalone.xml`.
 ** Make sure that `sysprop.bonita.db.vendor` property in `<JBOSS_HOME>/standalone/configuration/standalone.xml` is not set to h2.
* For Tomcat
 ** Remove h2 jar files (`bonita-jboss-h2-mbean-1.0.0.jar`, `bonita-tomcat-h2-listener-1.0.1.jar`, `h2-1.3.170.jar`). Files are located in: `<TOMCAT_HOME>/lib` or in `<TOMCAT_HOME>/lib/bonita`.
 ** Remove the h2 listener, so that h2 is not started automatically: comment out the h2 listener in the `/conf/server.xml` file.
* Check that h2 is no longer set in JVM system property value. Also, for extra security, you can remove it from `bonita-platform.properties` file and replace it with the value for your chosen RDBMS.

[#specific_database_configuration]

== Specific database configuration

=== PostgreSQL

Configure the database to use UTF-8.

Edit `postgresql.conf` and set a non-zero value for `max_prepared_transactions`. The default value, 0, disables prepared transactions, which is not recommended for Bonita BPM Engine. The value should be at least as large as the value set for `max_connections` (default is typically 100). See the https://www.postgresql.org/docs/9.3/static/runtime-config-resource.html#GUC-MAX-PREPARED-TRANSACTIONS[PostgreSQL documentation] for details.

=== Oracle Database

Make sure your database is configured to use the AL32UTF8 character set.
If your database already exists, see the Oracle documentation for details of how to http://docs.oracle.com/cd/E11882_01/server.112/e10729/ch11charsetmig.htm#NLSPG011[migrate the character set].

Bonita BPM Engine uses datasources that handle global transactions that span resources (XADataSource), so the Oracle user used by Bonita BPM Engine, requires some specific privileges, and there are also specific settings for XA activation.

==== *Important information for a successful connection*

The procedure below is used to create the settings to enable the Bonita BPM Engine to connect to the Oracle database.

It is assumed in the procedure that:

* Oracle product is already installed and running
* An 'Oracle' OS user is already created
* A database already exists
* The environment is already set:
+
----
ORACLE_HOME=/u01/app/oracle/product/11.2.0/dbhome_1
ORACLE_SID=...
----

. Connect to the database as the System Administrator.
+
SQL query >
+
[source,sql]
----
oracle@ubuntu:~$ sqlplus / as sysdba
----

. Check that the following components exist and are valid: +
SQL query >
+
[source,sql]
----
select comp_name, version, status from dba_registry;
----

|===
| Comp_name | Version | Status

| Oracle Database Catalog Views
| 11.2.0.1.0
| VALID

| Oracle Database Packages and Types
| 11.2.0.1.0
| VALID

| JServer JAVA Virtual Machine
| 11.2.0.1.0
| VALID

| Oracle XDK
| 11.2.0.1.0
| VALID

| Oracle Database Java Packages
| 11.2.0.1.0
| VALID
|===

. Add XA elements:
+
SQL query >
+
[source,sql]
----
@/u01/app/oracle/product/11.2.0/dbhome_1/javavm/install/initxa.sql
----
+
This only needs to be done once, after the installation of Oracle.

. Create the database user to be used by the Bonita BPM Engine and grant the required rights:
+
SQL query >
+
[source,sql]
----
@/u01/app/oracle/product/11.2.0/dbhome_1/rdbms/admin/xaview.sql
----
+
The following queries must be done for each new user: i.e. one user = one database schema.
+
SQL query >
+
[source,sql]
----
CREATE USER bonita IDENTIFIED BY bonita;
GRANT connect, resource TO bonita IDENTIFIED BY bonita;
GRANT select ON sys.dba_pending_transactions TO bonita;
GRANT select ON sys.pending_trans$ TO bonita;
GRANT select ON sys.dba_2pc_pending TO bonita;
GRANT execute ON sys.dbms_system TO bonita;
GRANT select ON sys.v$xatrans$ TO bonita;
GRANT execute ON sys.dbms_xa TO bonita;
GRANT FORCE ANY TRANSACTION TO bonita;
----

=== SQL Server

[WARNING]
====

There is a known issue between Bitronix (the Transaction Manager shipped by Bonitasoft in the Tomcat bundle and in the Tomcat directories of the Deploy bundle) and the Microsoft SQL Server driver
(refer to: https://msdn.microsoft.com/en-us/library/aa342335.aspx[MSDN note], http://bitronix-transaction-manager.10986.n7.nabble.com/Failed-to-recover-SQL-Server-Restart-td148.html[Bitronix note]).
Therefore, using Bitronix as a Transaction Manager with SQL Server is not recommended. Our recommendation is to use the JBoss bundle provided by Bonitasoft.
====

==== XA Transactions

To support XA transactions, SQL Server requires a specific configuration.

You can refer to https://msdn.microsoft.com/en-us/library/aa342335(v=sql.110).aspx[MSDN] for more information.

Here is the list of steps to perform (as an example, the database name BONITA_BPM is used):

. Make sure you have already downloaded and installed the https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774[Microsoft SQL Server JDBC Driver 4.0].
. Copy the `sqljdbc_xa.dll` from `%JDBC_DRIVER_INSTALL_ROOT%\sqljdbc_4.0\enu\xa\x64\` (x64 for 64 bit version of Windows, x86 for 32 bit version of Windows) to `%SQLSERVER_INSTALL_ROOT%\Instance_root\MSSQL11.MSSQLSERVER\MSSQL\Binn\.`
. Copy/paste the content of xa_install.sql file (located in %JDBC_DRIVER_INSTALL_ROOT%\sqljdbc_4.0\enu\xa) to SQL Server Management Studio's Query Editor.
. Execute the query in the Query Editor.
. To confirm successful execution of the script, open the "Object Explorer" and go to: *Master* > *Programmability* > *Extended Stored Procedures*. +
You should have 12 new procedures, each with a name starting with `dbo.xp.sqljdbc_xa_`.
. Assign the new role 'SqlJDBCXAUser' to the user who owns the Bonita BPM Engine database (`bonitadev` in our example). To do this, execute the following commands in SQL editor:
+
[source,sql]
----
USE master;
GO
CREATE LOGIN bonitadev WITH PASSWORD = 'secret_password';
GO
CREATE USER bonitadev FOR LOGIN bonitadev;
GO
EXEC sp_addrolemember [SqlJDBCXAUser], 'bonitadev';
GO
----

. In the Windows "Start" menu, select *Administrative Tools*\-> *Services*.
. In the "Services" window, make sure that the *Distributed Transaction Coordinator* service is set to start automatically. If it's not yet started, start it.
. Make sure that the other services it depends on, namely "Remote Procedure Call" and "Security Accounts Manager", are also set to start automatically.
. Run the `dcomcnfg` command, or go to the "Start" menu, then Administrative Tools > Component Services.
. In the left navigation pane, navigate to *Component Services* > *Computers* > *My Computer* > *Distributed Transaction Coordinator*.
. Select and right-click on _*Local DTC*_ and then _*Properties*_.
. Click on _*Security*_ tab. Ensure that the checkbox for *Enable XA Transactions* is checked.
. Click _*Apply*_, then click _*OK*_
. Then stop and restart SQLServer.
. Create the BONITA_BPM database: `CREATE DATABASE BONITA_BPM GO`.
. Set `bonitadev` as owner of BONITA_BPM database (use, for example, 'Microsoft SQL Management Studio')

==== Recommended configuration for lock management

Run the script below to avoid deadlocks:

[source,sql]
----
ALTER DATABASE BONITA_BPM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE BONITA_BPM SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE BONITA_BPM SET READ_COMMITTED_SNAPSHOT ON
ALTER DATABASE BONITA_BPM SET MULTI_USER
----

See https://msdn.microsoft.com/en-us/library/ms175095(v=sql.110).aspx[MSDN].

==== Recommended configuration for in-doubt xact resolution

Run the script below to avoid that the SQL Server changes the status of databases to SUSPECT during database server startup when in-doubt XA transactions are found. +
The value 2 in the block below means _presume abort_. +
To minimize the possibility of extended down time, an administrator might choose to configure this option to presume abort, as shown in the following example

[source,sql]
----
sp_configure 'show advanced options', 1
GO
RECONFIGURE
GO
sp_configure 'in-doubt xact resolution', 2
GO
RECONFIGURE
GO
sp_configure 'show advanced options', 0
GO
RECONFIGURE
GO
----

See https://msdn.microsoft.com/en-us/library/ms179586%28v%3Dsql.110%29.aspx[in-doubt xact resolution Server Configuration Option].

=== MySQL

==== Maximum packet size

MySQL defines a maximum packet size on the server side. The default value for this settings are appropriate for most standard use cases.
However, you need to increase the packet size if you see the following error:
`Error: 1153 SQLSTATE: 08S01 (ER_NET_PACKET_TOO_LARGE) Message: Got a packet bigger than 'max_allowed_packet' bytes`

You need to update the file `my.ini` (for Windows) or `my.cnf` (for Linux) to avoid the `ER_NET_PACKET_TOO_LARGE` problem.
Look for `max_allowed_packet` settings and increase the value.

For more information, see the http://dev.mysql.com/doc/refman/5.5/en/packet-too-large.html[MySQL website].

==== Surrogate characters not supported

MySQL does not support https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates[surrogate characters].
If you want to use surrogate characters in your processes, you need to use another type of database.
