= Deactivate a user

NOTE: If a user is deactivated, the user cannot log in to Bonita BPM Portal. The Administrator cannot add a membership to a deactivated user.
In consequence, the **Add membership button ** is not displayed for a deactivated user.

== How to deactivate a user

. Go to the *Organization* menu and choose *Users*.
. Select a user in the *Active* list.
. Click _*Deactivate*_.
. A warning message is displayed:

WARNING: You risk interrupting one or more processes.
Deactivating the only user able to perform a task will cause the interruption of a process.
Before proceeding, you may want to go to the 'More' page of the process and check the actor mapping.
Are you sure you want to deactivate this user now?

. The user is moved from the *Active* list to the *Inactive* list.

== How to activate a deactivated user

. Go to the *Organization* menu and choose *Users*.
. Go to the *Inactive* list.
. Select user from list.
. Click _*activate*_.
. The user is moved from the *Inactive* list to the *Active* list.
