= Bonita Deploy bundle
:description: Description on how to install Bonita Runtime on an existing and already installed Java EE Application Server like Tomcat or WildFly.

Description on how to install Bonita Runtime on an existing and already installed Java EE Application Server like Tomcat or WildFly.

== What is the purpose of the Bonita Deploy bundle?

* The Bonita Deploy bundle is used if you have *already installed a Java EE Application Server*.
* The Bonita Deploy bundle is a way of setting up a Bonita Platform. You'll be able to get a setup quite similar to WildFly or Tomcat bundle.
* It's also used to package other tools such as the LDAP synchronizer.

[WARNING]
====

This installation procedure only specifically targets the Java EE application Servers that have been installed under a single root folder (typically, from a .zip file).
Thus, for installations using native distribution packages (that more often than not split the binaries and the configuration files into separate folder hierarchies),
it would be up to you to adapt the documented steps to your very own folder layout.
====

== Deploy bundle content

* `Tomcat-`_`version`_: a folder/file structure to be merged with an existing setup of Apache Tomcat, in order to install Bonita Portal and Bonita Engine.
* `Wildfly-`_`version`_: a folder/file structure to be merged with an existing setup of WildFly in order to install Bonita Portal and Bonita Engine.
[#platform_setup_tool]
* `setup`: a command-line tool that creates the Bonita Platform before it can be run. It creates the Bonita Platform internal database, and stores the runtime configuration.
It is useful to update the configuration, locally or from a remote computer.
* `Request_key_utils-`_`key_utils.version`_: include script files to generate license request keys.
* `BonitaSubscription`-_``LDAPSync.version``_-`LDAP-Synchronizer` : LDAP synchronizer to synchronize your organization in Bonita with your LDAP
* `cas-`_`cas.version`_`-module`: Module files and description to enable CAS dependency to bonita EAR.
* `License`: license files that apply to Bonita components.
* `README.TXT`: See this file for more details about the `deploy.zip` contents and structure.

== Installation

. Download the deploy.zip file from the http://www.bonitasoft.com/downloads-v2[Bonitasoft download page] for the Community edition
or from the https://customer.bonitasoft.com/download/request[Customer Portal] for Subscription editions.
. Unzip the `deploy.zip` into a temporary folder (DEPLOY_ZIP_HOME).
. Follow the <<tomcat-installation,Tomcat bundle steps>> or <<wildfly-installation,WildFly bundle steps>>

[#tomcat-installation]

== Tomcat installation

=== Install Bonita Platform in Tomcat

Copy all files and directories from DEPLOY_ZIP_HOME/Tomcat-8.5.23/server to your Tomcat root directory (TOMCAT_HOME).
[WARNING]
====

Some configuration files from the deploy zip will overwrite some default tomcat configuration files. Proceed
with care in a tomcat where other applications are already installed.
====
[WARNING]
====

There is an https://bz.apache.org/bugzilla/show_bug.cgi?id=58999[issue on tomcat 8.0.32] preventing the portal Look & feel to be compiled. If you deploy bonita on an existing tomcat installation, make sure it is a different version of tomcat (preferably 8.5.x with x>=23).
====

=== Configure data sources

Configuration of data source for Tomcat is split in two parts: because Tomcat doesn't support JTA natively,
one data source will be configured in the Bitronix configuration file and the other data source will be configured
in the standard Tomcat context configuration file.

Non-transactional data source

. Open the file TOMCAT_HOME/conf/Catalina/localhost/bonita.xml
. For Bonita Standard data source, remove or comment out the lines regarding the h2 database.
. Uncomment the lines matching your RDBMS.
. Update following attributes value:
 ** username: your RDBMS user name.
 ** password: your RDBMS password.
 ** url: the URL, including the RDBMS server address, RDBMS server port and database (schema) name.
. Repeat operations 2. to 4. for Business Data data source

JTA data source (managed by Bitronix)

. Open the file TOMCAT_HOME/conf/bitronix-resources.properties
. For Bonita Standard data source, remove or comment out the lines regarding the h2 database.
. Uncomment the lines matching your RDBMS and edit values for each settings (resource.ds1.*) according to your database installation.
. Repeat operations 2. and 3. for Business Data data source (resources.ds2.*)

=== Configure RDBMS vendor

. {blank}
+
[cols=2*]
|===
| Open the file TOMCAT_HOME/bin/setenv.(bat
| sh)
|===

. Change the value of sysprop.bonita.db.vendor according to your RDBMS vendor
. Change the value of sysprop.bonita.bdm.db.vendor according to your RDBMS vendor

=== Add Jdbc driver

You need to add your jdbc driver in TOMCAT_HOME/lib.
MySQL and PostgreSQL drivers can be found in deploy bundle under DEPLOY_ZIP_HOME/setup/lib directory. For other RDBMS,
use the xref:database-configuration.adoc#proprietary_jdbc_drivers[jdbc driver] provided by your RDBMS vendor

[#wildfly-installation]

== Wildfly installation

=== Install Bonita Platform in Wildfly

Copy all files and directories from DEPLOY_ZIP_HOME/wildfly-10.1.0.Final/server to your Wildfly root directory (WILDFLY_HOME).

=== Configure data sources

. Open the file WILDFLY_HOME/standalone/configuration/standalone.xml
. For Bonita Standard data source, remove or comment out the default definition for h2.
. Uncomment the settings matching your RDBMS vendor.
. Modify the values of the following settings to your configuration: server address, server port, database name, user name and password.
. Repeat operations 2. to 4. for Business Data data source

=== Configure RDBMS vendor

. Open WILDFLY_HOME/standalone/configuration/standalone.xml and look for `system-properties` tag
. Set the value for sysprop.bonita.db.vendor (Bonita Platform database vendor)
. Set the value for sysprop.bonita.bdm.db.vendor (Business Data database vendor)

=== Add Jdbc driver

. Create a folder structure under WILDFLY_HOME/modules folder. Refer to the table below to identify the folders to create.
The last folder is named `main` for all JDBC drivers.

|===
| Database vendor | Module folders | Module description file

| PostgreSQL
| modules/org/postgresql/main
| link:images/special_code/postgresql/module.xml[module.xml]

| Oracle
| modules/com/oracle/main
| link:images/special_code/oracle/module.xml[module.xml]

| SQL Server
| modules/com/sqlserver/main
| link:images/special_code/sqlserver/module.xml[module.xml]

| MySQL
| modules/com/mysql/main
| link:images/special_code/mysql/module.xml[module.xml]
|===

. Put the driver jar file in the relevant main folder.
. In the same folder as the driver, add the module description file, `module.xml`. This file describes the dependencies
the module has and the content it exports. It must describe the driver jar and the JVM packages that Wildfly does not
provide automatically. The exact details of what must be included depend on the driver jar.
*Caution*: you might need to edit the module.xml in order to match exactly the JDBC driver jar file name.

== License installation

If you are installing a Subscription edition, you need to xref:licenses.adoc[request a license].

When you receive your license, copy the file to the `DEPLOY_ZIP_HOME/setup/platform_conf/licenses` folder of your application server.

== Database initialization

We assume here that the database has already been xref:database-configuration.adoc#database_creation[created and configured for Bonita].
Once created and configured you need to initialize it using the setup tool provided in the deploy bundle archive.
This will create database schema and initial values.

. In DEPLOY_ZIP_HOME/setup folder, edit the file database.properties with properties matching your rdbms. Beware of xref:BonitaBPM_platform_setup.adoc#backslash_support[backslash characters].
. In DEPLOY_ZIP_HOME/setup/lib add your jdbc driver if needed (only for Microsoft SQL Server or Oracle, see xref:database-configuration.adoc#proprietary_jdbc_drivers[proprietary jdbc drivers])
. In DEPLOY_ZIP_HOME/setup folder, run `setup.(sh|bat) init`

== Next steps

You're done with Bonita installation. You can now start your application server as usual.
When you have finished installing the deploy bundle, xref:first-steps-after-setup.adoc[complete the setup] of your system by validating the installation, setting passwords, and creating the Administrator user.
