= Process Diagram overview
:description: A process diagram is the representation in the Bonita studio of a group of processes (BPMN pools). A process diagram saved, deployed all pools in one action

A process diagram is the representation in the Bonita studio of a group of processes (BPMN pools). A diagram saved, deployed all pools in one action

A process diagram has a name and a version number. You can xref:bonita-bpm-studio-hints-and-tips.adoc[change the process diagram name] and you can xref:bonita-bpm-studio-hints-and-tips.adoc[update the version number] whenever you want to indicate a major change in the process diagram. A pool also has a version number that can be updated manually. +
There is no link between the process diagram version and the pool version.

[discrete]
== How to create a new process diagram

To create a new process diagram in Bonita Studio, choose *New* from the Cool bar, or click on the *_Create_* button on the Process Diagram card of the project overview. Give your process diagram a name, and optionally set the version number and add a description. +
You can also turn on or off validation of your process diagram. If validation is on, any errors in your diagram structure are flagged with a red x icon. This helps you correct errors as you build your process diagram, instead of correcting them all at the end.

To open an existing diagram, expand the *Process diagrams* node in the project explorer and double click on the corresponding process diagram. You can also use the project overview. Click on the *Process diagram* card title to see all the process diagrams of your project. Click on the *Open* button to open the corresponding process diagram.

You can access the process diagram context menu by right clicking on the corresponding process diagram in the project explorer. 
From this context menu you can perform several actions on your process diagram:
* Duplicate
* Rename
* Deploy
* Build
* Run
* Export

== Adding items to a process diagram

There are several ways to add an item to a process diagram:

* Click-and-hold on a icon in the *BPMN elements* menu and drag it to where you want the item in the whiteboard.
* Click-and-release on an icon in the *BPMN elements* then click where you want it to appear in the whiteboard.
* Select the previous item in the flow, and drag the item from the context menu to where you want it in the whiteboard.
* Copy and paste an item from another pool.

The advantage of selecting items from the *BPMN elements* menu is that you can choose precisely the item you want. +
The advantage of using the content menu is that the transition is automatically created.

If you add an icon to the process diagram over a transition, the transition will be broken into two parts and the new item inserted between them. This is called _break-and-insert_, and can be used with any BPMN flow element except text annotations. You can also use _break-and-insert_ when moving an item to a different place in a pool, if the transitions can be resolved.

== Using the tree view and search

The tree view shows all the information that is in a process diagram, arranged in a hierarchical structure. It can be a useful way to see all the information related to a particular step or form, or to find where a specific item is configured. For example, you can see the step where a variable is defined without having to check all the steps.

To find a term in your process diagram, go to the Tree View panel (by default, at the bottom-left of the screen), enter the term in the filter field and press return. +
The tree view is updated to show only the items that match the term.

== Changing the process diagram name and version

Click on the background (outside of a pool) and go to the *Diagram tab* in the *Details panel*. Click on *_Edit..._* then specify the new name and version number. +
You can use the same dialog to change the name and version of any pools in the process diagram.

== Changing the process diagram appearance

You can modify the appearance of an item in the process diagram by selecting it and going to the *Appearance tab* in the *Details panel*. +

In addition to changing the appearance of individual items in the process diagram, there are some tools that you can use to make the layout clearer, by selecting a group of items and making the vertical or horizontal alignment regular. If a process diagram is being developed or maintained by more than one person, it is important to keep the layout clear, to prevent misunderstanding. +

The alignment tools, and others, are accessed from the icons at the bottom-left of the whiteboard.
