= Diagram overview

A diagram is the representation in the Bonita studio of a group of processes (BPMN pools). A diagram saved, deployed all pools in one action

A diagram has a name and a version number. You can xref:bonita-bpm-studio-hints-and-tips.adoc[change the diagram name] and you can xref:bonita-bpm-studio-hints-and-tips.adoc[update the version number] whenever you want to indicate a major change in the diagram. A pool also has a version number that can be updated manually. +
There is no link between the diagram version and the pool version.

[discrete]
=== How to create a new diagram

To create a new diagram in Bonita Studio, choose *New* from the *Diagram* menu or the Cool bar, or click *_New Diagram_* on the Welcome page. Give your diagram a name, and optionally set the version number and add a description. +
You can also turn on or off validation of your diagram. If validation is on, any errors in your diagram structure are flagged with a red x icon. This helps you correct errors as you build your diagram, instead of correcting them all at the end.

To open an existing diagram, choose *Open* from the *Diagram* menu or the Cool bar, click *_Open a Diagram_* on the Welcome page,
or double-click the diagram name in the *Recently Modified* list on the Welcome page.

The Diagram menu contains options for saving a diagram. You can also duplicate a diagram, which is a useful way of making a backup copy of a diagram before you make major changes.
