= Deploy LDAP Synchronizer with Docker

:description: How to install and use the LDAP Synchronizer docker  distribution.

How to install and use the LDAP Synchronizer docker distribution.

This guide assumes you have a working docker environment.

== Configuration

=== Environment Variables

All general connection settings( `bonita.properties`, `ldap.properties`
and `log.properties`) are configurable with environment properties.

Specific configuration available on `mapper.properties` and `sync.properties` could configurable with a copy of files in directory link by volume `/opt/conf/user-config`.

Those files could be copied directly from ldap-syncrhonizer docker image with command to directory link to volume `/opt/conf/user-config` with  :

[source,bash,subs="verbatim,quotes"]
----
docker cp $(docker create --rm quay.io/bonitasoft/bonita-ldap-synchronizer:*version*):/conf/default/mapper.properties *directory_link_to_volume*
docker cp $(docker create --rm quay.io/bonitasoft/bonita-ldap-synchronizer:*version*):/conf/default/sync.properties *directory_link_to_volume*
----

xref:ldap-synchronizer.adoc#ldap-configuration-files[here] more details about configuration files.

*WARN:* `bonita.properties`, `ldap.properties` and `log.properties` properties files located on volume will overwrite all configuration specified with environment variables.

==== Bonita connection settings

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Default |Description
|`BONITA_URL` |http://localhost:8080 |Url to connect to the server
|`BONITA_APP_NAME` |bonita |Application name
|`BONITA_LOGIN` |install |Username of the Bonita account used for
synchronization.
|`BONITA_PASSWORD` |install |Password of the Bonita account used for
synchronization.
|`BONITA_PLATFORM_LOGIN` |platformAdmin |This is the username of the
platform adminstrator.
|`BONITA_PLATFORM_PASSWORD` |platform |This is the password of the
platform adminstrator.
|===

==== Ldap connection settings

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Default |Description
|`LDAP_HOST_URL` |ldap://localhost:389/ |Host name and port of the LDAP
server.
|`LDAP_AUTH_TYPE` |simple |LDAP authentication type (supported values:
none, simple or strong)
|`LDAP_PRINCIPAL_DN` |cn=Directory Manager |distinguished name (DN) of
the user account used for browsing through the LDAP users
|`LDAP_PRINCIPAL_PASSWORD` |root |password of the LDAP browser account
|`LDAP_ENFORCE_SSL` |false |force the connection between ldap client and
server to use ssl
|`LDAP_DIRECTORY_USER_TYPE` |person |type of the user object (``user''
for an Active Directory, ``person'' for an LDAP)
|`LDAP_USE_PAGE_SEARCH` |false |*Not supported by all LDAP servers* :
Paged search to true to activate page pagination
|`LDAP_PAGE_SIZE` |1000 |Number page result by search query
|===

==== LOGGER CONFIGURATION

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Default |Description
|`LOG_DATE_PREFIX` |yyyy-MM-dd |date format used for prefixing the log
file name ( see
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/SimpleDateFormat.html[SimpleDateFormat]
|`LOG_LEVEL` |INFO |level of reporting of the logger (relevant values
are INFO for production use, FINE for debug use)
|===

== Run
[source,bash,subs="verbatim,quotes"]
----
docker run -v *CONF-DIR-PATH*:/opt/conf/user-config quay.io/bonitasoft/bonita-ldap-synchronizer
----

* *CONF-DIR-PATH* could contain all properties

*eg :*
[source,bash]
----
docker run  -e BONITA_URL=http://192.168.0.10:8080 -v $(pwd)/bonita-ldap-synchronizer/conf:/opt/conf/user-config  quay.io/bonitasoft/bonita-ldap-synchronizer
----

== LOG

All logs are produce on console output.