== Glossary


=== A
*Application*: Application is a set of artifacts (processes, pages, BDM...) based on Bonita Platform. It can cover one or more use cases.

== B
*Bonita Engine*: Bonita Engine is at the core, responsible of process execution

*Bonita Platform*: Bonita Platform is composed of two components : Bonita Studio and Bonita Runtime.
Its purpose is to create, build and run projects.

*Bonita Runtime*:
Bonita Runtime is dedicated to operate automation projects.
Bonita Runtime is composed of one or more nodes. A Bonita Runtime composed of multiple nodes constitutes a cluster to ensure High Availability and or High Performance, See Messaging - Bonita Runtime scalability for all the details.

*Bonita Studio*
Studio contains all the elements needed to develop and build an automation project.  Bonita Studio is a desktop application based on Eclipse IDE.

*Bonita UI Designer*:

*Build*:

=== P
*Project*:

*Project elements*:

== R
*Run*:

== S
*Storage & persistence*
Bonita Runtime requires a storage to operate. The storage is composed of two databases: one for core services and one dedicated to Business Data.