= Hardware and software requirements
:description: == Hardware

== Hardware

[NOTE]
====

The hardware recommended for Bonita BPM Platform is strongly dependent on your environment and
processes (number of processes instances, number of current users, operations and complexity...).
====

Hardware required for Bonita BPM Platform (Bonita BPM Engine and Bonita BPM Portal)

[width="30%"]
|===
| Type | Minimum | Recommended

| Processors
| 4 CPU cores
| 4 CPU cores or more

| Memory (RAM)
| 4 GB
| 8 GB or more

| Disk space
| 10 GB
| 30 GB or more, depending on usage
|===

== Software

Software required for Bonita BPM Platform (Bonita BPM Engine and Bonita BPM Portal).

[width="30%"]
|===
|  | Version

| *Operating system*
|

| Microsoft Windows Server
| 2012 R2 64 bits and higher

| Red Hat Enterprise Linux
| 6.5 64 bits and higher

| Ubuntu
| 14.04 LTS 64 bits and higher

| *Java Virtual Machine*
|

| Oracle Java SE Runtime Environment
| 8 (see note 1)

| OpenJDK
| 8 (see note 1)

| *Application Server*
|

| Apache Tomcat
| 7.0.x (x > 67)

| Red Hat WildFly
| 10.1.x

| *Database*
| (see note 2)

| MySQL
| 5.5.27 and higher in the 5.5.x line (see note 3)

| PostgreSQL
| 9.3 and higher in the postgres 9 line

| SQL Server
| 2012 (see note 4)

| Oracle
| 11gR2 (11.2.0.x) and 12c (12.1.0.x.y) (see note 5)

| *Browser*
|

| Mozilla Firefox
| latest version

| Google Chrome
| latest version (see note 6)

| Microsoft Edge
| latest version

| Internet Explorer
| 11.0.x
|===

NOTE:
. Bonita BPM can be executed on Java 8. All development artifacts (connectors, REST API extensions, etc) must be compiled with Java 8 byte code (target version).
. Your database must be configured to use the UTF-8 character set.
. MySQL must be configured with innoDB storage engine. Even if the 5.5.x line is recommended, tests have shown that Bonita BPM  can run with MySQL 5.6.x and 5.7.x (please make tests prior to using these versions, especially when using exotic encoding/charset). Note that Bonita BPM does not work with MySQL 8.x
. There is a known issue between Bitronix (the transaction manager shipped by Bonitasoft for the Tomcat bundle and inside the Deploy bundle for Tomcat) and Microsoft SQL Server JDBC driver
(refer to: https://msdn.microsoft.com/en-us/library/aa342335.aspx[MSDN note], http://bitronix-transaction-manager.10986.n7.nabble.com/Failed-to-recover-SQL-Server-Restart-td148.html[Bitronix note]).
Therefore, using Bitronix as a transaction manager with SQL Server does not work and is not supported. To use SQL Server database requires that you use the WildFly bundle provided by Bonitasoft.

NOTE: This limitation disappears in the 7.9 release.
. Oracle must be configured using AL32UTF8 character set to store properly all _Char_ data
. Chrome version 60.0.3112 introduced an incompatibility impacting the functionality of Bonita BPM Portal. So from that Chrome version onwards, once Bonita BPM Platform is installed, apply the following procedure to resolve this issue:

=== Fixing procedure

==== Subscription users

[NOTE]
====

In order to apply this procedure, you MUST use a Chrome browser version that doesn't suffer from the incompatibility, or you can use Firefox, Internet Explorer/Edge or Safari, for example.
====

. Log in to Bonita BPM Portal as Administrator.
. In the menu, click on 'Portal'.
. Click on 'Export the current Look&Feel'.
. Make a back-up copy of the exported file.
. Unzip the exported file 'portal-theme.zip'.
. Edit 'BonitaConsole.html' file:
 .. In the `<head>` section, add the code below:
+
[source,javascript]
----
<script>
// Monkey Patch xhr
// Due to a specification change in the xhr.getAllResponseHeaders method Bonita BPM Portal does not behave as expected
// in browsers that implement this new specification (currently only Chrome >60).
// This patch fixes xhr.getAllResponseHeaders unwanted behavior within Bonita Portal context
//    See https://bugs.chromium.org/p/chromium/issues/detail?id=749086
//    See https://github.com/whatwg/xhr/issues/146
(function (xhr) {
    var caseSensitiveHeaders = ['Content-Range', 'X-Bonita-API-Token'];

    var getAllResponseHeaders = xhr.getAllResponseHeaders;

    xhr.getAllResponseHeaders = function () {
        var headers = getAllResponseHeaders.apply(this);
        for (var i = 0; i < caseSensitiveHeaders.length; i++) {
            headers = headers.replace(new RegExp('^' + caseSensitiveHeaders[i].toLowerCase(), 'm'), caseSensitiveHeaders[i]);
        }
        return headers;
    }
})(XMLHttpRequest.prototype)
 </script>
----
. Zip all the files and folders again into 'portal-theme.zip'.
(BEWARE: make sure not to zip the 'portal-theme' folder, but its contents. If the 'portal-theme.zip' contains a 'portal-theme' folder at the base, Bonita BPM Portal will not recognize it as a valid zip structure.)
. In the portal, click on 'Import and apply a new Look&Feel' and choose the updated 'portal-theme.zip' file.
. Back to the Chrome update 60 browser, empty the cache.

==== Community users

. In an installed Bonita BPM bundle, edit file 'server/webapps/bonita/portal/scripts/includes/common.js':
 .. Add the code below before or after the existing code:
+
[source,javascript]
----
`  // Monkey Patch xhr
// Due to a specification change in the xhr.getAllResponseHeaders method Bonita BPM Portal does not behave as expected
// in browsers that implement this new specification (currently only Chrome >60).
// This patch fixes xhr.getAllResponseHeaders unwanted behavior within Bonita Portal context
//    See https://bugs.chromium.org/p/chromium/issues/detail?id=749086
//    See https://github.com/whatwg/xhr/issues/146
(function (xhr) {
    var caseSensitiveHeaders = ['Content-Range', 'X-Bonita-API-Token'];

    var getAllResponseHeaders = xhr.getAllResponseHeaders;

    xhr.getAllResponseHeaders = function () {
        var headers = getAllResponseHeaders.apply(this);
        for (var i = 0; i < caseSensitiveHeaders.length; i++) {
            headers = headers.replace(new RegExp('^' + caseSensitiveHeaders[i].toLowerCase(), 'm'), caseSensitiveHeaders[i]);
        }
        return headers;
    }
})(XMLHttpRequest.prototype)`
----
. Back to the Chrome update 60 browser, empty the cache.
