= Import and export a process

How to import and export processes in Bonita Studio.

== Import a process diagram into Bonita Studio

To import a diagram:

* From a .bos archive (a diagram from another Bonita studio)
 .. Choose *_Import_* \-> *_BOS archive_* from the *_Diagram_* menu or click *_Import_* in the Cool bar.
 .. Specify the archive to be imported.
 .. Manage eventual conflicts
 .. Click *_Import_*, the .bos archive is imported, a new diagram is created.
* From an other format
 .. Choose *_Import_* \-> *_other_* from the *_Diagram_* menu.
 .. Select the input format.
 .. Specify the file to be imported.
 .. Click *_Import_*. A new diagram is created.

You can import diagrams that were exported from the following tools:

* Bonita
* BPMN 2.0
* Microsoft Visio 2010
* ARIS BPM 7.x
* XPDL 1.0
* jBPM 3.2

=== What is supported or compatible?

A diagram that was exported from the same edition of Bonita, or a lower edition, can be imported successfully.
You cannot import a diagram from a higher edition.
For example, you can import a diagram created with the Community edition into an Enterprise edition Bonita Studio,
but you cannot import a diagram that was created with the Enterprise edition into a Community edition Bonita Studio.

If the format to be imported is BPMN 2.0 compatible, any of the BPMN 2.0 elements displayed in the Bonita Studio *BPMN elements* menu, can be imported successfully. However, if the element to be
imported is *not displayed **in the **BPMN elements* menu, it is not supported by Bonita, so Bonita Studio will _interpret_ the element and create the _closest BPMN element_
that is supported. The following specific changes are made for all import formats:

* If a task in an imported process is *not recognised*, Bonita Studio will create an abstract task for it by default.
* A task format can be *redimensioned* (Height/width) when it is imported.
* If a multiple event is *not recognised*, Bonita Studio takes the first element in order that it can interpret.
* If a gateway is *not supported*, it will be interpreted by default as an AND gateway.
* If there are **multiple pools **in a *.bar file, they will all be imported into a single process diagram.

The following sections list restrictions for specific import formats.

==== BPMN 2.0 (*.bpmn)

Most BPM applications export in the BPMN 2.0 file format. This format is the most compatible with Bonita Studio. See http://www.bpmn.org/#tabs-implementers[here] for a list of applications
which export in the .bpmn format.

==== Microsoft Visio 2010 (*.vdx)

This feature is available in the Enterprise, Performance, Efficiency, and Teamwork editions.

* The Visio import format must be .vdx. The .vsd format is not supported in Bonita Studio.
* Only horizontal display is supported.
* The vertical display will be converted and interpreted as a _mirror image_ of the process.
* Visio supports all shapes defined in the BPMN 1.2 standard. See https://blogs.msdn.microsoft.com/visio/2009/12/03/bpmn-support-in-visio-2010/[here for more info about Visio compatibility].

==== Aris BPM 7.x (*.xml)

* This feature is available in the Enterprise, Performance, Efficiency, and Teamwork editions.

See the http://www.softwareag.com/corporate/products/az/aris/default.asp[Aris website] for
more information about exporting in the BPMN 2.0 format ready for importing into Bonita Studio.

==== XPDL from Bonita 4 (*.xpdl)

The .xpdl format will only be compatible if it was created in Bonita 4.x. If the .xpdl file was created by an application other than Bonita 4.x, it cannot be imported into Bonita Studio.

==== jBPM 3.2 (processdefinition.xml)

jBPM uses the http://www.jboss.org/[BPMN 2.0 standard].

== Export a process diagram as a BPMN 2.0 archive

If you export a process diagram as a BPMN 2.0 archive you can import it into any BPM application that supports this format, including Bonita Studio.

To export a diagram in BPMN 2.0 format from Bonita Studio:

. Open the diagram.
. Choose *_Export as..._* from the *_Diagram_* menu and select *_BPMN2..._* from the drop-down list.
. Specify the location and filename for the exported diagram, and click *_OK_*.

== Export process elements

You can export files related to elements of the processes in the Bonita Studio project. The files are exported into a .bos archive that can be imported into another Bonita Studio.

You can export the following:

* Application resources
* Business Data Model
* Configurations
* Dependencies
* Diagrams
* Environments
* Organizations
* XSD files

To create a .bos archive:

. Choose *_Export_* from the *_Diagram_* menu or click *_Export_* in the Cool bar.
. Select the items to be exported.
. Specify the filename and location or use the default suggested.
. Click *_Finish_*.

The resulting .bos file can be imported into Bonita Studio.

== Build a process for deployment

When a process is ready for deployment, you must create an executable business archive (.bar file) for deployment.

To create the business archive:

. Choose *_Build..._* from the *_Server_* menu.
. Select the process to be exported.
. Specify whether you want to export a configuration with the process. Exporting a configuration will export all the information and other items that you
configured, including connectors and dependencies.
. Specify the location where the .bar file will be created. The filename is determined by the process name and cannot be changed at this stage.
. Click *_Finish_*. The business archive is created.

== Export a process diagram as an image

This section explains how to export a diagram as an image.

To export a diagram from Bonita Studio:

. Open the diagram.
. Choose *_Export as..._* from the *_Diagram_* menu and select *_Image..._* from the drop-down list.
. Specify the image format and quality.
. Specify the location and filename for the exported diagram, and click *_OK_*.
