= JBoss bundle
:description: You will find here steps needed to install and configure a JBoss bundle.

You will find here steps needed to install and configure a JBoss bundle.

The JBoss bundle is a zip archive that contains the Red Hat JBoss JEE application server packaged with Bonita BPM Portal and xref:BonitaBPM_platform_setup.adoc]#platform_setup_tool[Bonita configuration folder]. +
The JBoss bundle is a regular zip archive based on the JBoss zip distribution.

== Installation of the JBoss bundle

=== Download and unzip the JBoss bundle

[#download]

==== Download

For the Community edition:

* Go to the http://www.bonitasoft.com/downloads-v2[Bonitasoft website] and get the Bonita BPM Community edition JBoss bundle.

For a Subscription edition:

* Go to the https://customer.bonitasoft.com/download/request[Customer Portal] and download the Bonita BPM Subscription edition JBoss bundle.

==== Unzip

The folder where you unzip the Jboss bundle is known as _`<JBOSS_HOME>`_. We recommend the following locations:

* Windows: `C:\BonitaBPM`. If you want to unzip the bundle to another folder, do not use spaces in the folder name.
* Linux: in `/opt/BonitaBPM`. Make sure that Linux user account used to execute JBoss is the owner of the folders and files.

==== Content of the JBoss bundle

The JBoss bundle is based on a standard JBoss installation with the following additions:

* `bin/standalone.conf`: script to configure JVM system properties.
* `bonita-start.bat`: script to start the bundle on Windows.
* `bonita-start.sh`: script to start the bundle on Linux.
* `standalone/configuration/standalone.xml`: JBoss context configuration for Bonita BPM Portal. It defines data sources used by Bonita BPM Engine.
* `request_key_utils`: script to generate license request keys (Subscription editions only).
* `standalone/deployments/h2.sar`: application that runs the h2 server. (h2 is the default embedded database, not for production)
* `standalone/deployments/bonita-all-in-one-[version].ear`: Bonita BPM Portal (web application) and EJB3 API.

[NOTE]
====

Starting from Bonita BPM 7.3.0, Bonita BPM Platform configuration, including the license file, is stored in the same database as the Bonita BPM Engine data, namely in the `CONFIGURATION` table. +
To initialize and update this configuration, a xref:BonitaBPM_platform_setup.adoc[_Platform setup tool_] is provided and embedded in Bonita BPM bundles.
It will be launched automatically when you start the JBoss bundle to initialize the database. +
====

So your bundle also contains: +
`setup`: database management for Bonita BPM Platform configuration and Bonita BPM Engine data, and a tool to update the configuration.

[#configuration]

=== Configure the JBoss bundle

[NOTE]
====

If you just want to try Bonita BPM Platform with the embedded h2 database (only for development phase of your project), you can skip the next two paragraphs. +
For production, you are recommended to use one of the supported databases, with the following steps.
====

==== Configure Bonita BPM Platform datasource

Make sure your database is created before you start the configuration and make sure you do this before you start the JBoss server.

The first step is to configure the database used by the xref:BonitaBPM_platform_setup.adoc[_Platform setup tool_] to initialize the configuration.

To do so, go to `<JBOSS_HOME>/` and update the `setup/database.properties` files with the connection information of the  database.

[#database]

==== Configure the JBoss server datasources

After configuring the datasource to let the Platform setup tool intialize the configuration, you need to configure this datasource on the server. Follow those steps:

. Update the datasource configuration in `standalone/configuration/standalone.xml` by uncommenting and commenting relevant parts
. Update the `<property name="sysprop.bonita.db.vendor" value="h2" />` in `standalone/configuration/standalone.xml` with your database vendor
. Remove the `standalone/deployments/h2.sar` file
. Add the JDBC driver as decribed in the xref:database-configuration.adoc]#jdbc_driver[database configuration] page

=== Get and install a license

[NOTE]
====

This is not necessary if you are installing the Community edition.
====

If you are installing a Subscription edition, you need to xref:licenses.adoc[request a license].

[#license]

When you receive your license:
If this is your first installation, copy the file to the `<JBOSS_HOME>/setup/platform_conf/licenses` folder before starting the bundle.
If this is a license update, use xref:BonitaBPM_platform_setup.adoc]#update_platform_conf[the _Platform setup tool_].

=== Edition specification

If you are installing the Performance Subscription edition, you need to edit xref:BonitaBPM_platform_setup.adoc[`setup/platform_conf/initial/platform_init_engine/bonita-platform-init-community-custom.properties`] and change the value of the `activeProfiles` key to `'community,performance'`.
No change is needed for the Community, Teamwork, or Efficiency editions.

[#start]

=== Start and shut down JBoss

==== JBoss start script

JBoss can be started by executing the following script:

* Windows `<JBOSS_HOME>\bonita-start.bat`
* Linux `<JBOSS_HOME>/bonita-start.sh`

==== Shutdown

JBoss can be shut down by running the following script:

* Windows `<JBOSS_HOME>\bin\jboss-cli.bat --connect --command=:shutdown`
* Linux `<JBOSS_HOME>/bin/jboss-cli.sh --connect --command=:shutdown`

You can also press Ctrl + C.

== First steps after installation

Once you have your JBoss bundle up and running, complete these xref:first-steps-after-setup.adoc[first steps] to get Bonita BPM Platform fully operational.

=== How to update the configuration

To update the configuration after the first run please take a look at the xref:BonitaBPM_platform_setup.adoc]#update_platform_conf[_Platform setup tool_]

[NOTE]
====

*Keep in mind* that xref:BonitaBPM_platform_setup.adoc]#configure_tool[platform setup tool] is independent from Jboss Bundle and thus needs to be configured by itself to point to the right database.
This is done by editing file `database.properties`
====

=== How to update the license

To update the licenses after the first run please take a look at the xref:BonitaBPM_platform_setup.adoc]#update_platform_conf[platform setup tool]
