= Layouts
:description: This page explains how to handle layouts in Bonita Applications, and how to use it in an application.

{description}

A layout is a page used to define the main frame of an application.

It defines menu positioning, a footer, or any common content that could be displayed on every page of the application.
Each application can have its own layout.

There is an example of layout in Bonita Applications, the "Bonita Layout".

Layouts are xref:ROOT:resource-management.adoc[added, exported, edited, and deleted] as resources in Bonita Applications.

== Use in applications

It is linked to an application thanks to the application descriptor in Bonita Studio. +
A layout can only be use as the main container of an application. It cannot be used as a simple application page.

In a Non-Production or Production environment, a layout is imported as a .zip archive containing a page.properties file and a resources folder.

== Live update

xref:ROOT:live-update.adoc[Live update] allows the Administrator to update one element of the application in a situation of emergency.

=== Edit the layout

You can xref:ROOT:resource-management.adoc#modify[edit the content of a layout] by installing a new version.

=== Modify the pages in an application

You can xref:runtime:applications.adoc#define-navigation[link another layout to an application] in the application descriptor.
