= Managing Extensions in the Studio

:description: The Bonita platform is highly extensible so we created a dedicated view to manage the extensions of your project

The Bonita platform is highly extensible so we created a dedicated view to manage the extensions of your project

== Opening the extensions view
The extensions view is opened from the Studio cool bar.

== Adding Extensions
From the extension view you can add the following extension to your project:

* Connectors
* Actor Filters
* REST API Extensions
* Themes
* Any Java library required for your project

Such extensions can be added through different channels described in the below chapters.

=== Bonita Marketplace
The Bonita Marketplace contains all the extensions provided and supported by Bonitasoft.

=== From a Maven repository
If the extension you are looking for is available in a public or private Maven repository, you can use the maven coordinates (group ID, artifact ID & Version) to add them to your project.

Note that you can configure private repositories in the xref:configure-maven.adoc[Studio settings]

=== From a local file
For extensions that aren't published in a Maven repository, you can add them from a local file on your computer. Imported extensions are added in the project internal store, an hidden folder in a Bonita project. The internal store is exported with the project (in the .bos archive), and is added to the Git repository of the project. 

[CAUTION]
====
It is not recommended to add too many dependencies in the internal store, it makes your project heavier. This mechanism should be used to test artifacts under development, and for the artifacts that cannot be deployed on a Maven repository.
====

== Removing an extension
Extensions can be removed from the extension view.

[WARNING]
====
Removing an artifact might lead to errors if the artifact is used in the project. The Studio tries to detect such impacts and to alert the user before the deletion, but some specific cases cannot be detected, especially for REST API Extension usages.
====

== Updating an extension
Extensions coming from the Bonita Market place can automatically be upgraded to their latest version. All you need to do is click on "Update to latest version". This button is displayed only if an update is available.

Other extensions can be updated manually with the "Update" button. This button is always displayed and can also be used to downgrade an extension. Depending on the change, you may have to manually update your project consequently.

== Detailed extension view
Details are available for extensions of type _Connector_, _Actor filter_ and _REST API Extensions_. They contain details on the content and the usages of the extension, and can be accessed by clicking on the extension title. 
