= Multi-tenant configuration for a Bonita platform
:description: (Deprecated). One single platform to admininstrate with multiple logical engines. Described what a Tenant is and how to setup Bonita with Multi-tenancy.

[WARNING]
====
This feature was deprecated in Bonita 2021.1. This means that Multi-tenant architecture will continue to work in Bonita for existing Bonita subscription customers,
but it will not be offered to new customers, nor offered as a modification for existing Bonita subscription customers who are not already using multi-tenancy.
====

[NOTE]
====
As mentioned in the release note, Bonita Enterprise customers need a contractual agreement to create additional tenants. For any new tenant creation, any general or contractual question related to Multi-tenancy, please contact your customer success representative.
====

For customers already in a multi-tenant architecture:

* *Support is provided*, and it will be provided as long as the feature is not removed from Bonita.

For customers considering a multi-tenant architecture:

 * Multi Tenancy being deprecated, current Bonitasoft's official recommendation is to use multiple instances of Bonita Runtime for every separate entity, or to subscribe to *Bonita Cloud* with as many Runtimes as there are required entities. By entities, we mean either different end-customers, or different internal departments/subsidiaries. Such a multi-runtime approach allows:
 
** a specific configuration, independent software versions, infrastructure resources (CPU, memory, disk) and platform lifecycle for each platform (increased flexibility, customization capacities)
** the physical segregation of resources and data (increased security)
** the possibility to split public/private Cloud instances
