= Portal removal in 2021.2
:description: With the 2021.2 release, the Bonita Portal has been replaced by Bonita Applications.
:page-aliases: analytics.adoc, comparison-of-7-x-and-6-x.adoc, group.adoc, managing-look-feel.adoc, manage-a-user.adoc, living-application-layout.adoc, mobile-portal.adoc, portal-user-case-list.adoc, processes.adoc, profile-list-portal.adoc, role.adoc, tasks.adoc, restore-default-look-feel.adoc, create-a-report.adoc, reporting-overview.adoc

{description} +
The removal of this part of the product implied removal, deprecation or conversion to a new technology of a list of related things.

Some that can be mentioned are: +

- Custom profiles are converted into Living Applications, using Bonita Layout and Bonita Theme
- Process Manager profile, which has been removed and will be re-done in a future release
- Removal of Analytics page, which will be remade in a newer technology
- The Living Application Layout, which has been replaced by the Bonita Layout
- The Look & Feel files, which were used to define how the Portal will be displayed, are removed from the database. The default Look & Feel is re-packaged directly in the `server/webapps/bonita/portal-theme` folder in the Bundle
- The Mobile User Portal has been removed. The users will now be redirected to the Bonita User Application

The changes done for these features implied a removal of some pages that referenced them. The list of links to previous versions of the pages that have been removed is : +

- Analytics
- Living Application Layout
- Manage the Portal Look & Feel
- Restore the default Look & Feel
- Administrator Group list in Bonita Portal
- Administrator User list in Bonita Portal
- Administrator Process list in Bonita Portal
- Administrator Role list in Bonita Portal
- Administrator Task list in Bonita Portal
- Profiles management in Bonita Portal
- User Case list in Bonita Portal
- Mobile User Portal
- Comparison of 7.x and 6.x version
- Create a report
- Reporting overview

[NOTE]
====
To get the documentation related to the features that have been removed, you can refer to the 2021.1 documentation, which is available as xref:0@bonita:archives:bonita.adoc[a zip archive].
====
