= Profiles overview in Bonita User Interfaces
:description: This page explains what a profile is for a user with the profile _Administrator_ in Bonita Portal.

This page explains what a profile is for a user with the profile _Administrator_ in Bonita Portal.

== Definition

A profile is an indirection to some entities of the organization: users, groups, roles, and/or memberships.
Profiles work as permissions to give access to:

* xref:applications.adoc[Living Applications]
* Defined objects and attributes of the BDM (through xref:access-control-api.adoc[BDM Access Control])
* xref:rest-api-authorization.adoc[REST API extension permissions]
* Navigation (menus) of Bonita Portal

One organization entity can be mapped to several profiles. In Bonita Portal, a logged in user can switch between his/her profiles in the navigation bar.

In development, the creation and edition of profiles is done through the xref:profileCreation.adoc[profile editor] in Bonita Studio. +
In non-production and production, an Administrator can use the _Organization_>__Profiles__ menu of Bonita Portal.

[NOTE]
====

Changing the mapping of a profile on a non-production or production Runtime may lead to inconsistencies when updating the project or deploying it on another server. +
It should only be done to recover from an error temporarily. We strongly encourage you to report all changes in the sources profiles files of the project.
====

== Default profiles

=== User

By default, it gives access to the User navigation of Bonita Portal. It includes:

* a xref:user-process-list.adoc[Process list]
* a xref:portal-user-case-list.adoc[Case list]
* a xref:user-task-list.adoc[Task list].
This profile is also the only one mapped with Bonita Mobile Portal. +
This profile is also mapped to the xref:user-application-overview.adoc[Bonita User Application], bringing the same value but with more customization options.

=== Administrator

By default, its gives access to the Administrator navigation of Bonita Portal. It includes:

* xref:_process-maintenance.adoc[Process Management] and xref:analytics.adoc[Analytics]
* xref:organization-in-bonita-bpm-applications-overview.adoc[Organization Management]
* xref:bdm-management-in-bonita-bpm-applications.adoc[Business Data Model Management]
* xref:applications.adoc[Applications Management]
* xref:managing-look-feel.adoc[Portal Look & Feel Management]
* xref:license-info.adoc[License Information] (Enterprise, Performance, Efficiency, and Teamwork editions only)
  This profile is also mapped to the xref:admin-application-overview.adoc[Bonita Administrator Application], bringing about the same value but with more customization options.

=== Process manager

This profile is available for Subscription editions only.
Someone mapped to the _Process manager_ profile has limited administration rights for activities related to the processes they manage. It includes:

* xref:monitoring.adoc[Process monitoring]
* xref:processes.adoc[Process list], but they cannot install a process
* xref:cases.adoc[Case list]
* xref:tasks.adoc[Task list]

[NOTE]
====

In Bonita ACME organization, all users have the role *Member*, and the role *Member* is mapped to all default profiles. +
This simplifies process testing (log in as any user to see any Portal content).
====

== Custom profiles

In addition to the default profiles, users of Enterprise, Performance and Efficiency editions can create xref:custom-profiles.adoc[custom profiles]. +
To create a custom profile, use the xref:profileCreation.adoc[profile editor] in Bonita Studio, and map it to entities of the organization. +
If a custom profile is created to give access to custom content in Bonita Portal, its Portal menu (navigation structure and pages) must also be defined in the profile.
We highly recommend to create the profiles in Bonita Studio so the custom profiles are versioned with the whole project and maintained consistently. +
In a production environment, if updating a profile is needed to recover from an issue temporarily, the Administrator can use the _Organization_>_Profiles menu.
