= Project deployment in a Studio

This page presents an overview of the _Deploy wizard_ capabilities in Bonita Development Suite.

== Artifact selection

After importing or cloning a project in the studio, you will have the possibility to directly deploy your project in the embedded studio runtime. +
You can open the _Deploy wizard_ using the contextual menu of the project in the Project Explorer view or find the action directly in the toolbar. +
In the wizard, you have the possibility to select or deselect an artifact. An artifact can be a process, a page or any deployable element of your project. +
Processes are categorized by versions and you can opt to only select the latest version (https://semver.org/[SemVer]). The artifact selection is persisted between two deployments. You may also use the search text to quickly find an artifact in a large project.

== Deploy options

* Select Process configuration environment (SP Only): You can choose the environment to be used for the deployment. All the parameters values, actors, connector and actors filters implementations mappings and custom scripts belong to the configuration environment.
* Default user name: The user that will be used to login in the Portal or your applications after the deployment
* Clean BDM database before deployment: Erase all existing data in the BDM and recreate the database schema from scratch.
* Validate before deploy: Perform a validation of selected artifacts before the deployment.

== Quick access after deploy

Once the deployment successful, you are able to choose the application to open, either the Portal or one of the deployed living application. +
Only application that can opened by the user choose in the deploy options will be displayed.

== Error management

In case of errors or warnings, only a status dialog is displayed at the end of the deploy.
Common errors and warnings:

* Process validation errors and warnings: you will be redirected to the diagram with the validation issues.
* Process enablement failed: Use a valid environment or configure your processes before the deploy.
* REST API Extension build errors
* API resources required by web pages but not found: Check that Rest API Extensions providing those resources are also deployed.
* Custom permissions not mapped but needed by a form: Use the `Edit permissions mapping` action on Rest API Extension before deploy.

WARNING:
API resources detection in pages and forms is a best effort detection. If API urls are forged using Javascript expression variables in you pages and forms, it will not be detected properly. In this case no error or warning will be thrown at deployment but you may have forbidden access error at runtime if permission mapping is invalid or if the Rest API Extension is missing.

