= Release notes
:description: Bonita release note

[NOTE]
====
The 2022.2 is in Beta.
====

== New added values

=== Bonita process monitoring now with embeded bpmn-visualization library

Bonitasoft launched the open source project https://process-analytics.dev/[Process Analytics] two years ago in response to the market need to perform BPMN process monitoring using BPMN standards.
The deliverable of this project is called the _bpmn-visualization library_. You can find a nice array of examples of what it can do in its https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.25.2/examples/index.html[demo web site], and you can even contribute to this initiative in its https://github.com/process-analytics/bpmn-visualization-js[Github repository]. +
Till Bonita 2022.2, another library has been used to display process execution data for administrators at both process and case levels. This library had some limitations and was not easy to improve with new features. +
Hence, integrating the bpmn-visualization library to Bonita, was a very natural choice. +

The new values are available for Bonita Subscription Editions starting with the Efficiency edition.
  
  * Bonita Administration application users will get a faster and more robust view on the process execution data (thanks to the library and new REST APIs)
  * As the bpmn-visualization library evolves, more interactivity and information for a better monitoring capacity will be provided
  * Since the pages have been created by using Bonita UI Designer, developers can:
        
        ** Use the custom widget embedded in the new pages in their own application pages. The widget has been wrapped into a fragment that makes it very easy to use.
        ** Modify the process or case visualization page, and use it in any Bonita application

For more details, check xref:pages-and-forms:customize-display-process-monitoring.adoc[How to page to customize the display of process execution monitoring]

=== Bonita Reporting Application 

Here it comes, Bonita Reporting Application is now available for download on Bonita’s Customer Service Center/Customer Portal and is compatible starting with Bonita 2021.2. 

A subscription account is required for downloading the .jar , that contains “Process Historical Data” and “Human tasks historical data” reports, designed for process performance and human tasks execution analysis. More details are available in the dedicated documentation page xref:runtime:reporting-app.adoc[Bonita application for analytics and reporting].

=== A new widget to deal with Currencies

A new widget is now available in UI Designer to manage financial data at ease in pages or forms with any currency.

== Improvements

=== Development suite changes

==== A new first-start flow for the Studio

When launched for the first time after an install, the Studio will no longer start with a default project. The goal is to make this first start less cumbersome.
Also, to increase user guidance, the Welcome page has been improved with clear call-to-action buttons.

==== Bonita Marketplace - Display installed extension

A new filter was added to display the already installed extensions in order to help users know the extensions installed in their project while browsing the Bonita Marketplace

==== Detecting  extension's related issues at import 

With the previous version, you could import malformed extensions in your project without any warnings. This leading to errors downstream and confused users.
From now, when importing or updating an extension, errors will be detected and users will be informed in Studio.

==== Improved guidance when the actor mapping is not defined

With the previous version, if the actor mapping of a process was not defined, an unclear error message was displayed to the user. To help our users move forward with the deployment of their processes, we have improved the error detection by providing a clear message when this issue occurs.

==== New Menus for Bonita Studio

The menus have been reviewed for an easier user journey.

==== Added Environment duplication feature

With the previous versions, creating a new environment required to set up the whole project configuration entirely, including configuration of each process, what could be time consuming and error prone with big projects. From now on, users can create environments starting from duplicating an existing one. 

== Functional changes

=== Case info REST API resource- *Subscription editions*

Case info `bpm/caseInfo` REST API resource which is used for process and case user tasks visualization is now available.

For Community users who update to 2022.2, if you need this API resource, you can create a REST API extension that leverages Bonita Engine java API to get the same functionality as in 2022.1.

== Technical updates

UI Designer frontend has been migrated to AngularJS 1.8.

[Note]
====
Only the UID application has been upgraded to AngularJS 1.8. Your applications will still generated with AngularJS 1.3. Stay tuned for further updates.
====

== Feature deprecations and removals

=== SVN

SVN integration in Bonita Studio Subscription has been removed. You may migrate an existing SVN repository to a Git repository following this xref:migrate-a-svn-repository-to-github.adoc[guide].

== Bug fixes


== Known issues


