= Release notes
:description: == New values added

== New values added

[#git]

=== Collaborative development with Git (starting with Teamwork edition)

Working as a team on a Bonita project, securing resources on a shared server, and keeping track of the resources revisions is now possible with the integration of Eclipse http://wiki.eclipse.org/EGit/User_Guide[EGit plug-in] in Bonita Studio, as well as the creation of a dedicated gitignore file.
Managing branches, viewing the differences between two revisions of a file, or between the local and remote repositories, as well as managing conflicts for a given file can be performed. Find more in the dedicated xref:workspaces-and-repositories.adoc]#git[documentation page section] and in the howto: xref:share-a-repository-on-github.adoc[Share a repository on GitHub].
Combining Git capabilities with https://documentation.bonitasoft.com/bcd/2.0/[Bonita Continuous Delivery add-on] offers best of breed technologies for multi-disciplinary teams to sustain a DevOps approach.

[#bdm-access-control]

=== Business data access control (BDM AC) (starting with Efficiency edition)

It is now possible to protect the access to BDM data through REST API calls.
This feature, xref:bdm-access-control.adoc[*BDM access control*], is available in Bonita Studio and works as a *white list* mechanism: through access rules, access is granted to entire business objects or to some attributes only, so that only users mapped with the selected *profiles* can access the data.
Help is provided on consistency checking between BDM, profiles, and BDM access control when changes are made on the BDM or the profiles.
A "profile access" tooling is also provided, to validate BDM access by profile.
This new resource can be installed and updated on a Bonita platform while BPM services are running, via the Administrator Portal.

[#save-form]

=== Save a Form temporarily (starting with Teamwork edition)

When a form contains lots of fields, or when the user misses some information required to fill out the form at once, saving the form to complete it later is a need. This is now possible with the new "Save Button" widget, that can be added to any form.
JavaScript information entered by the user is temporarily saved in the web browser local storage while the task is still in "pending" status. When the user comes back to the task, the values entered are displayed on the form, missing data can be added, so the user efficiently submits the form to either start a process instance or execute a task.

[#new-case-overview]

=== New case overview

Although the default case overview page has always been customizable, it was an AngularJS page, not editable in Bonita UI Designer. Moreover, its history section reported actions that occurred in the past. +
The new default case overview page is now designed in the UI Designer and it displays the current available task(s) and, if available, the current assignee(s). You can export if from the Administrator Portal > Resources menu, as the "Autogenerated Case Overview" and import it in the UI Designer to make it suit your needs. As a Portal Administrator, in processes details pages, update the "Mapping" of "Overview" to replace it with your custom overview, and there you go.

== Improvements

[#ldap-synchronizer]

=== LDAP synchronizer to synchronize Custom User Information too (starting with Teamwork edition)

More information than groups can now be synchronized from a Company's LDAP into a Bonita organization: the xref:ldap-synchronizer.adoc]#cui[LDAP synchronizer] can input those additional fields into xref:custom-user-information-in-bonita-bpm-studio.adoc[Custom User Information]. Such information is defined in Bonita Studio, and viewed or edited in Bonita Administrator Portal, and is used in actor filters for better task allocation.

[#readable-names]

=== xref:ui-designer-overview.adoc]#readable-page-name[Readable UI Designer artifact names] in Bonita repositories

New pages, forms, layouts, and fragments created with Bonita UI Designer now use the name given by the developer as IDs in the repository.
Easier to find when they need to be updated.
For existing artifacts, nothing has changed: their IDs is a UUID. You can switch them to the new mechanism by renaming them.

=== UI Designer artifacts last update date

Last update date of all UI Designer artifacts is not updated with the use of the preview any more. Only when changes are made.

=== UI Designer logs separate from Engine logs

In Bonita Studio *Help* menu, you can now find UI Designer logs, distinct from Engine logs, to better monitor UI Designer activities.

=== A responsive login page

The login page, used in Bonita Portal as well as in the Living Applications, is now responsive, so as to look at its best on a desktop, tablet or mobile environment.

=== BDM meta-information for Portal Administrator

Since installing or updating BDM requires BPM Services to be paused, such rights are only granted to the Technical User.
However, since the Portal Administrator can now install and update the BDM Access Control file from the Administrator Portal, he can now get information on BDM status and last update date.

=== New layout for the Administrator Portal "User details" page

All details of a user in the organization are now diplayed on an AngularJS page of the Administrator Portal, bringing still more consistency to the Administrator Portal.

=== Bonita Studio status bar and coolbar

To allow you to work in Bonita Studio while some back-end activities are taking place, especially in case of operations on remote repositories, the Eclipse status bar is now displayed at the bottom right hand corner of the studio window.
To keep the same working space in the studio, we have set the default size of the coolbar at "small". If you prefer big icons, with labels, go to "Edit > Preferences > Appearance" and set the "Coolbar default size" to "Normal". You can also click on the little down arrow at the very right end of the coolbar to expand it.

=== Business objects relationships

The default relationship type between business objects is now "agreggation". It was "composition" before, which led to some validation errors: a single object cannot be linked to several parents with a composition relationship, but it can with an aggregation relationship.

=== Application descriptor "deploy"

Just like for profiles or BDM access control, there is now a "Deploy" option in the Application descriptor menu of Bonita Studio, on top of the toolbar button already available in the editor.

=== Application descriptor refactoring upon a change on a profile

When a change is made on a profile in Bonita Studio, the application descriptors that reference the profile are now refactored in Bonita Studio to take the change into account.

=== French repository is now "dépôt"

For local or shared repositories, Bonita Studio in French is now tuned to the official translation: "dépôt".

=== Official signatures on Windows

Bonita binaries as well as Studio installer are now officially signed on Windows OS, to prevent useless security alerts.

=== Form mapping API error messages

Improvements of messages in case of error on form mapping API calls have been done to explain the cause of error and give options for easier error recoveries.

=== Performance (applies to Bonita 7.7.5+)

The following improvements have been made to Bonita performance:

* There is less I/O requests to temp folders
* Work execution consumes less database resources
* The login REST APIs mechanism consumes less resources
* At engine startup and BPM services resume, the process dependencies loading consumes less memory

A special attention has also been carried out to an improved deletion mechanism of archived cases. Deleting archived cases is now way more efficient.

[WARNING]
====
As a result, some xref:event-handlers.adoc[Events] are not triggered anymore (among others: ARCHIVED_FLOWNODE_INSTANCE_DELETED, only concerns deletion of *archived* elements).
If you used these events and still need them, there is a way to switch back to the previous deletion mechanism.
In such cases, please contact Customer Support to activate this legacy deletion mechanism.
Be aware that this legacy deletion mechanism is deprecated and will be deleted in a future version. There will be not support in the long-term.
====

[#technology-updates]

== Technology updates

=== Supported Tomcat version

* The supported Tomcat version for this new release is Tomcat 8.5.31, in the Bonita Studio as well as in the Tomcat bundle.

=== Hazelcast on AWS

* (Enterprise and Performance editions) Bonita 7.7 now supports the usage of Hazelcast on AWS out-of-the box. Previous versions required
modifying the Bonita installation.

[#feature-removals]

== Feature removals

=== Jasper 5 connector

Jasper connector has been removed from provided connectors in Bonita Studio. If you have a process that depends on this connector and want to migrate in 7.7+, you have two options:

* Export the Jasper connector from a previous Studio version
* Download the connector from the https://community.bonitasoft.com/project/bonita-connector-jasper[community website]
Then just import the connector using the `+Development > Connectors > Import connector...+` menu.

== API behavior change

=== UI Designer URL change

The UI Designer webapp embedded in Bonita Studio is now deployed with the name "bonita" (instead of "designer") in its own container (different from the one of Bonita Engine and Portal). As a result, it is now accessible through the URL `http://localhost:<designer_port>/bonita` instead of `http://localhost:<tomcat_port>/designer`. This name update was a requirement in order for the UI Designer preview to continue working with bonita portal resources URLs starting with "/bonita".

=== Add comment with a Groovy script in an open case

https://documentation.bonitasoft.com/javadoc/api/7.7/org/bonitasoft/engine/api/ProcessRuntimeAPI.html#addProcessComment-long-java.lang.String-[addProcessComment()] method in ProcessRuntimeAPI has had a behavior change that went unnoticed in 7.4.0:
when called from a groovy script, it will systematically write the process comment as having been made by the "System" user, while previously it was using the user executing the task. It is caused by the fix to the bug https://bonitasoft.atlassian.net/browse/BS-14276[BS-14276]. Operations on human tasks are now asynchronous (as it should have been from 7.0.0). Hence all methods relying on the Session to get the userID, as addProcessComment() does, will find -1 as a value.
All scripts that want to perform an action on behalf of the user executing the task, should rely on the task assignee to do so, as there is no user logged during the script execution hence the -1 value in the sessions; as the execution is asynchronous.

This behavior will not be reverted to pre 7.4.0 state for the addProcessComment() method, or any other method that might suffer from a similar problem.
A new method has been introduced : https://documentation.bonitasoft.com/javadoc/api/7.7/org/bonitasoft/engine/api/ProcessRuntimeAPI.html#addProcessCommentOnBehalfOfUser-long-java.lang.String-long-[addProcessCommentOnBehalfOfUser()], that will allow to replicate the previous behavior of the https://documentation.bonitasoft.com/javadoc/api/7.7/org/bonitasoft/engine/api/ProcessRuntimeAPI.html#addProcessComment-long-java.lang.String-[addProcessComment()] method.
This new API method is designed so that a script can leave  a comment on behalf of the user.
*Note:* This use case has never been considered before. As a comment was thought to be left by the user himself / herself.

In practice, it means that if your process has been designed prior to Bonita 7.3 :

* If you are calling the method outside of groovy scripts, you can use the method you like ( addProcessComment() being probably more practical), and your process will not require any additional modifications
* If you are calling the method from a groovy script, in a process designed prior to 7.3 and migrated to 7.7, and want to maintain the previous behavior, you will have to modify your groovy scripts to use the new API method.
* If your process has been designed in Bonita 7.4, 7.5 or 7.6, the behavior of your process will not change. You will however have now access to a new API method upon migration, which will open new possibilities.

=== Deprecated Workspace API

The Workspace API tooling (headless studio build) has been deprecated. You are recommended to use the _bcd build_ command which is part of the tooling suite of https://documentation.bonitasoft.com/bcd/latest/[Bonita Continuous Delivery add-on].

=== Business Archive (*.bar) content updated

In order to build business archives without having a constraint on a GUI, the process _png_ file is not embedded in the archive resources anymore.

== Limitations and known issues

* The EGit plug-in, on which relies the Bonita Studio Git feature, integrates many features, and only a few have been translated to French and English so far. In order to contribute the best translation to the Eclipse community, we need more time. Therefore, translations in French and Spanish will all come in 7.7.1. Stay tuned.
* MacOS environment: starting from MacOS El Capitan 10.11.4 (March 2016), new security rules block the launch of Bonita Studio. You must temporarily remove security on App launching in *System Preferences*>**Security & Confidentiality**.
* Process display name is now used everywhere in Bonita Portal (when it has been set in the process design) except in the default provided Jasper reports.
* Since 7.6.0, the default living application layout does not re-encode the URL passed to the living application iframe anymore.

== Bug fixes

[discrete]
==== Fixes in Documentation

* BS-16862 Cannot fully deploy a REST API extension with Engine APIs
* BS-17598 Documentation steps about "Create your own password validator" lead to maven error: Could not find artifact
* BS-17613 Instructions to use gzip compression no longer apply
* BS-17659 "BDM Management in Bonita Portal" section leads customer to believe updating the BDM in production is supported
* BS-17699 Broken link to 7.6 Engine Javadoc
* BS-17770 Studio preferences Documentation still speaks about Studio profiles
* BS-17795 Single sign-on with SAML not described with Wildfly
* BS-17930 Documentation about 'Changing technical user' needs more detailed explanations
* BS-17994 REST API filter names includes erroneous \ character
* BS-18134 Workaround or guidance missing for time-zoned Java 8 Date types usage in REST API extensions
* BS-18167 Live update of script fails if a new "provided variable" is added to the script
* BS-18441 7.7 Javadocs have missing packages and classes
* BS-18497 Migration: HTTP status code 403 REST API extensions
* BS-18701 Make sure we discourage write operation in groovy scripts on the right operands of Operation

=== Fixes in Bonita 7.7.5 (2018-11-21)

==== Fixes in Engine component

* BS-8505  ProcessAPI.deleteArchivedProcessInstances returns incorrect number of deleted instances
* BS-16972 Engine classloader refresh should use less Heap memory on Engine startup and BPM services resume
* BS-18131 Performance issue when retrieving process.bpmn from bar resources
* BS-18563 Engine arbitrarily fails with License Error 51,27 at server start-up on Windows
* BS-18847 Parallel archive cases deletion via REST API does not delete all rows
* BS-18866 Deletion of archived case times out because it takes too long to execute
* BS-19057 a Business Data with field referencing itself fails to be queried with StackOverflowError
* BS-19062 Lazy referenced BO field to itself fails to serialize with StackOverflowError
* BS-19073 Archived contract data are never deleted

=== Fixes in Bonita 7.7.4 (2018-09-06)

==== Fixes in Engine component

* BS-15941 ExecuteMessageCouple work does not reset messages and should not in certain cases
* BS-18579 Irrecoverable error when message content does not match waiting event
* BS-18615 Missing Hibernate query searchSProcessInstancewithSProcessSupervisor
* BS-18657 Data truncation error when migrating from v7.6.3 to v7.7.0

==== Fixes in Studio component

* BS-18660 The bonita la builder doesn't build connectors jar correctly
* BS-18673 Saving changes in BDM will install an empty Access Control and block permissions if bdm_access_control.xml has no rules

==== Fixes in Web component

* BS-18427 The task stays in pending state for a while before it fails and no error is visible in the Portal
* BS-18437 ASSIGN button: popup displays NOT IMPLEMENTED when a PROCESS MANAGER is not ADMINISTRATOR
* BS-18585 'Location' header not allowed by RESTlet in REST API extension

=== Fixes in Bonita 7.7.3 (2018-08-02)

==== Fixes in Engine component

* BS-18441 7.7 Javadocs have missing packages and classes
* BS-18312 A named Hibernate query to search Activities with type CALL_ACTIVITY is missing.
* BS-18557 Missing Hibernate queries for running and archived process instances can lead to runtime errors when using the Engine API
* BS-18575 "-Djava.security.egd=file:/dev/./urandom" option missing from setup/tomcat-templates/setenv.sh

==== Fixes in Studio component

* BS-18576 Can not import .bos file in 7.7.x Teamwork edition Studio
* BS-18589 LA-Builder groovy script compilation fails due to classpath issues

==== Fixes in Web component

* BS-16976	FileNotFoundException/IOException issues when accessing/deploying custom pages/REST API extensions
* BS-18570	Cannot retrive theme.css from a custom page into a portal profile

=== Fixes in Bonita 7.7.2 (2018-07-09)

==== Fixes in Engine component

* BS-17227 Bundle tomcat does not work if installation path contain special character (like "é")
* BS-18402 BDM Composition and aggregation child update creates a new Child BO instance instead of updating the right one
* BS-18428 Missing Hibernate queries for activity instances can lead to runtime errors when calling ProcessAPI.searchActivities()
* BS-18439 BDM: extra lines generated with null values in table, with aggregation relation
* BS-18445 Webservice connector fails in buildResponseDocumentBody with error: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted

==== Fixes in Studio component

* BS-18445 Webservice connector fails in buildResponseDocumentBody with error: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.
* BS-18467 Database connector wizard does not filter unaccessible connector outputs in scripting mode

==== Fixes in UI Designer component

* BS-18431 The LA-Builder hang for ever on UID page generation error
* BS-18472 Rename fragment does not rename frament into Forms

==== Fixes in Web component

* BS-17975 As Sam, I want the Tomcat bundle to start in less than 7 minutes on my Docker env
* BS-17880 Importing organization with expired session fails with misleading error message
* BS-18366 Started by System displayed in the cases list page if user have an empty Lastname or empty firstname
* BS-18417 User profile - "Done tasks" list cannot be sorted on 'Case' column whereas "To do" and "My tasks" lists can
* BS-18449 Organization can be export by a non admin user from Bonita Portal

=== Fixes in Bonita 7.7.1

==== Fixes in Engine component

* BS-17536 Quartz elements associated with boundary event from a sub process are not deleted when parent process instance is deleted
* BS-17553 Exception, or a stack trace, or an incident are generated when an interruptive boundary timer is triggering during connector execution at ON_ENTER
* BS-18448 Engine failed to start with a ClassNotFoundException after migration when a BDM 's BO defines fields with date or datetime types

==== Fixes in UI Designer component
* BS-18442 Cannot import form in UID in Windows when it contains chinese characters

==== Fixes in Web component
* BS-18374 User membership cannot be removed because memberships have no pagination

=== Fixes in Bonita 7.7.0

==== Fixes in Engine component

* BS-15900 EventTriggers are not always deleted from the EVENT_TRIGGER_INSTANCE table
* BS-16750 FILE contract input type generates a big usage of the heap memory with big documents
* BS-17009 Hazelcast jar is no more available for AWS Discovery
* BS-17267 engine-server temp folder keeps growing in size on windows environment
* BS-17464 CMIS list documents connector and probably the others CMIS connectors generate a ClassNotFoundException on WildFly only
* BS-17514 Setup tool should release files after a pull operation
* BS-17624 7.3.3 and prior java client failed to deserialize an object when communicating with java Engine API 7.4.0 or higher
* BS-17679 Prevent unsupported use case when defining BDM
* BS-17716 Setup tool does not prevent the removal of critical configuration files
* BS-17725 add() to an empty multiple BO (List) is failing
* BS-17726 Case counter for Unlimited instances license is not incremented
* BS-18196 BoundaryEvent stays behind in 'waiting' state if task is skipped
* BS-18201 ProcessAPI.searchConnectorInstances fails with SearchOptions using .filter(ConnectorInstancesSearchDescriptor.STATE, ConnectorState.FAILED)
* BS-18208 logged user / task assignee : Task Operation behavior has changed
* BS-18228 Terminate and End event is not terminating the process after a failed task with a boundary event had been skipped
* BS-18336 HazelcastSerializationException: Failed to serialize 'org.bonitasoft.engine.work.WorkDescriptor'
* BS-18350 Fix Aws discovery sample hostHeader in bonita-platform-sp-cluster.properties
* BS-18389 Tomcat outputs TechnicalLoggerSLF4JImpl for all logs in subscription editions

==== Fixes in Studio component

* BS-17267 engine-server temp folder keeps growing in size on windows environment
* BS-17749 : surounded with space chars in task name generates an error when user clicks on the task in the portal's tasklist
* BS-17939 Content Assist doesn't work without keyboard shortcut in Groovy expression editor
* BS-18101 Process contract inputs missing from process-design.xml when building with BonitaStudioBuilder
* BS-18154 Catch message - Correlation mapping value doesn't display expression editor properly
* BS-18178 Studio splash screen doesn't work on windows
* BS-18191 Automatic dependency resolution can fails in Groovy Expression Editor
* BS-18197 Studio deploys too many sub process versions and the wrong one is used at run-time.
* BS-18269 "Create a parameter..." wizard is not popping-up
* BS-18270 Parameter type is lost on version when re entering process to call section
* BS-18301 Welcome page displays outdated RSS flux content in welcome page
* BS-18343 Using loop "for" in Input Constraints fails with a validation error and a warning in the Editor
* BS-18344 CPU spike and GC overhead limit exceeded when using groovy editor for Inputs constraints
* BS-18381 Installer fails to launch BonitaStudio at end, if path contains space characters

==== Fixes in UI Designer component

* BS-16696 Autocomplete widget issue with asynchronous data (Rest API call)
* BS-16997 File viewer preview display cut and not scrollable with pdf file in Mobile portal
* BS-17809 HTML is not interpreted anymore after page import in studio 7.7.0 from 7.6.x and lower
* BS-18062 UI Designer Devices size Preview doesn't reflect the one selected in the main UI Designer
* BS-18179 Form import in UI Designer displays a non-translated artifact type
* BS-18222 Bonita API resource not exported in page.properties when single resource call with id
* BS-18256 Infinite loop creating css file after migration error
* BS-18385 URL parameters are not decoded in UI Designer

==== Fixes in Web component

* BS-16440 Instance counter starts one day before subscription start date
* BS-17924 CSRF cookie needs to be handled when implementing authentication manager
* BS-18137 Changing filter does not refresh the case list properly
* BS-18149 REST API Not compliant with the If-Modified-Since HTTP header
* BS-18223 Licensing admin page does not handle unlimited case number correctly
* BS-18231 Select widget fails to pre select Value
* BS-18335 Process visu is not display when process contains an intermediate catch event signal
* BS-18341 Error message not explicit in Portal when change password policy enforced
* BS-18367 Click inside a Living application raises a warning in the logs and a 404 on an undefined URL path
* BS-18375 User profile - Done Task list cannot be ordered on 'performed date' column or any other date column; it used to be possible in 7.2.2

== Acknowledgments

Thank you https://github.com/jventrib[Jerome Ventribout] (Engine) for your contribution.
