= Release notes
:description: Bonita release note

[NOTE]
====
The 2023.1 is in development.
====

== Improvements

=== Development suite changes

==== Bonita project layout

Bonita projects layout has been changed to take advantage of Maven multi-module project perks.

First project component that will benefit from Maven multi-module project is the Business Data Model. We decided to align the way the Business Data Model is handled in Bonita with the standard dependency handling practices by using Maven submodules. Submodules, or subprojects, are regular Maven projects that inherit from the parent POM.

With the chosen solution, the users will have the possibility to publish and consume the Business Data Model java dependencies independently. The project will pull the required dependencies from a specified repository - Maven Central or Bonita Artifact Repository - to generate the BDM java sources.

Business Data Model content check at build or deploy will still be developer’s responsibility along with handling data-deletion risks at build or deploy.
For this Bonita version, reusing the generated artifacts in another Bonita project is not supported with refactoring capabilities. All changes will have to be handled manually by developers.

== Feature deprecations and removals

=== Custom Rest API Extension and BDM dependencies

When updating a Bonita project in Bonota Studio 2023.1 version, BDM dependencies will be directed to use the new the `*-bdm-model` artifact introduced with the Bonita project layout changes. Meaning that `bdm-client` and `bdm-dao` dependencies will automatically be replaced with project's `bdm-model` dependency.

Additionnally, the dependency containing the client DAO implementation will be removed from the dependencies list. It can affect the code directly referencing the `*DAOImpl` classes. To avoid this situation, change the code to use the DAO interfaces present in the `bdm-model` dependency. The changes can be done before or after updating to the 2023.1 version without breaking the project.

*Reminder* : in case `*DAOImpl` class was instantiated in the code, `APIClient#getDAO` factory method has to be used instead.

.For example, for a given BusinessObject `Customer`
[source, java]
----
// Direct instantiation
CustomerDAOImpl dao = new CustomerDAOImpl(context.getApiSession());

// Replace it with APIClient factory
CustomerDAO dao = context.getApiClient().getDAO(CustomerDAO.class);
----

=== Accessibility improvements

The following improvements have been made so that digitally accessible applications could be developed natively with Bonita UI Designer with less custom code:

* An attribute lang is now available and based on the BOS_locale cookies at page initialization will automatically get filled without developer’s or end-user’s action.

* Table and data-table widget have a new caption property available for adding a title

* The default widgets in the palette that contain a html input tag have now an associated label, which will facilitate the use of computer tools (screen readers for example)

* To be more accessible for speech synthesizers, screen readers or some other tools, the internal html template of checklist and radio buttons widget has been updated.

[WARNING]
====
The changes will automatically be available when changing a page in Bonita UI Designer <2023.1> developed with a previous Bonita UI Designer version. xref:pages-and-forms:widgets.adoc#widgets-templating-troubleshooting[Custom styling] could be impacted so take this fact into account in your development estimates.
====

=== Multi-tenancy removal

[NOTE]
====
For Subscription editions only.
====


Deprecated xref:2022.2@ROOT:multi-tenancy-and-tenant-configuration.adoc[multi-tenancy] has been removed.

To cover the multi-tenancy use cases in the best technical way, Bonitasoft is proposing a new architecture solution. For customers running a Bonita multi-tenancy platform, the technical path from multi-tenancy proposed by Bonitasoft is multi-runtime. This choice will require to split the current multi-tenant platform into several runtimes, each one with their own Bonita engine database.

As this path can be challenging for customers using multi-tenancy, Bonitasoft developed a conversion tool, available for download https://customer.bonitasoft.com/download/request[on Bonitasoft Customer Portal]. We strongly suggest our customers to take the time and use the tool in a pre-production environment before using it on a production environment.

xref:version-update:mtmr-tool.adoc[Multi-tenancy to multi-runtime conversion tool] can be executed on Bonita Runtimes starting with Bonita 7.11 and up to Bonita 7.15.

[WARNING]
====
In case you are using a non-supported version, perform the update of the platform before converting it to multi-runtime.

Reminder : For commercial and support questions, please refer to your Customer Success referent.
====
