= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
The {bonitaVersion} version is in development.
====

== New available values

=== Enhanced Log Tracing and Filtering

Log tracing and filtering in Bonita have been enhanced using MDC (Mapped Diagnostic Context) to add contextual information across all scopes.
This improvement ensures higher-quality, more readable logs and simplifies integration with third-party monitoring tools, helping customers troubleshoot issues and monitor performance more effectively.

[WARNING]
====
This extra information also means more volume for logs. +
If you have limited space for logs and do not wish this information, you may deactivate this feature by removing `{ - %X}` from the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration].
====

You can see the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration] for more details.


== Deprecations and removals

=== API removals

==== Command API

Up to 2024.3, you could implement custom commands by inheriting either from the `org.bonitasoft.engine.api.TenantCommand` interface or from the `org.bonitasoft.engine.command.PlatformCommand` interface. With multitenancy removal, those two commands have been merged into `org.bonitasoft.engine.command.RuntimeCommand` +
If you have not done it yet, recompile your custom commands by changing parent class to `RuntimeCommand`, https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#unregister(long)[unregister] the previous one and https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#register(java.lang.String,java.lang.String,java.lang.String)[register] the new one.

==== Platform API

Deprecated method PlatformAPI.updateTenant() has been removed.


=== EntityMember (aka. External Identity Mapping)

This concept has been completely removed. It was used to map arbitrary external IDs to Bonita identity (user, group, role, membership).
This feature was not used internally and was not documented. +
Event keys EXTERNAL_IDENTITY_MAPPING_CREATED and EXTERNAL_IDENTITY_MAPPING_DELETED have been removed from the event API and cannot be listened to anymore.

== Bug fixes

=== Fixes in Bonita 2025.1 (! DATE TO ADD HERE !)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-28 - The deletion of a running process instance leaves lines in the DOCUMENT table. +
Before this fix, when a process instance was deleted, the documents associated with it were not deleted. As a consequence, this behavior creates orphan documents that are unused and not linked to any other object. Note that it was not the case for archived process instances where documents were correctly deleted. +
If you have a lot of orphan documents in your database, you can use the latest version of the xref:ROOT:purge-tool.adoc#delete-orphan-document-content[Purge Tool] to remove them.

==== Fixes in Bonita Studio (including Bonita UI Designer)
