= Release notes
:description: Bonita release note

[NOTE]
====
The {bonitaVersion} version is in development.
====

[NOTE]
====
The required Java version is now **Java 17**.
====

== New available values

=== Bonita Runtime

==== Java 17 update

Following the Java 17 update, it is now required to specify the following jvm arguments when using the `bonita-client` library in a standalone application:

[source, shell]
----
--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
----

==== Docker image parent update

The `bonita` and `bonitasoft.jfrog.io/docker/bonita-subscription` images now inherit from the official https://hub.docker.com/_/eclipse-temurin[eclipse-temurin] image in its alpine flavor. As a consequence, if you need to add additional Certificate Authority in the Java TrustStore you may proceed like xref:runtime:bonita-docker-installation.adoc#adding-ca-certificates[described here]. It also applies to to Self Contained Application images.


==== Second-Level Cache available in a Bonita clustered environment

[NOTE]
====
For Subscription editions only.
====

Bonita {bonitaVersion} now handles second-level caching data (also known as L2 Cache) when running Bonita within a xref:overview-of-bonita-bpm-in-a-cluster.adoc[cluster environment].

It is available by default with a preset configuration. It can be disabled by setting the property `bonita.platform.persistence.use_second_level_cache=false` or the environment variable `BONITA_PLATFORM_PERSISTENCE_USE_SECOND_LEVEL_CACHE=false`.

This L2 Cache mechanism is implemented with https://docs.hazelcast.com/hazelcast/latest/cache/overview[Hazelcast]. At the same time, it replaces the Ehcache implementation that was previously used to support L2 caching data within a non-cluster environment.

For more information on how to tune the L2 Cache with Bonita, please refer to the xref:runtime:performance-tuning.adoc#persistence-cache[dedicated documentation].

==== Like-based search

Bonita Runtime search capabilities in APIs and application pages have been improved by changing the algorythm to support "like-based" search. +
With the "like-based" algorithm you can find all the matching records for which the search string occurs anywhere in a phrase or a word. +
This is now the default search behavior for all search APIs and pages of Bonita Runtime.

=== Development suite


=== Bonita UI Designer


== Functional changes


== Feature deprecations and removals

=== Word-based search

The optional "word-based" and default "start-with" search algorithms cannot be used anymore as they have been replaced by a "like-based" search algorithm that is used in all search APIs and pages of Bonita Runtime.

== Configuration changes

=== Word-based search

Since "Word-based" search can no longer be used, its configuration has been removed. +
The properties `bonita.platform.persistence.platform.enableWordSearch` and `bonita.platform.persistence.tenant.enableWordSearch` are removed from the configuration file `platform_engine/bonita-platform-community-custom.properties` when using the update tool, and they no longer have any effect. +
If you used them to configure Bonita Runtime for "word-based" search and specified some objects to exclude using the bean `wordSearchExclusionMappings` in `platform_engine/bonita-platform-custom.xml`, you should remove this bean after updating since it is no longer used. The new "like-based" search is active on all objects that have API search methods.
