= Release notes
:description: Bonita release note

[NOTE]
====
The 2022.2 is in development.
====


== New values added

=== Bonita now embeds the bpmn-visualization library to improve process monitoring for administrators and users 

Bonitasoft has launched the Process Analytics initiative two years ago, to create a new, Open Source means to monitor process execution using the bpmn diagram generated by Bonita Studio. +
The deliverable of this project is called the _bpmn-visualization library_ . You can find a nice array of examples of what it can do in its https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.25.0/examples/index.html[demo web site], and you can even contribute to this initiative in its https://github.com/process-analytics/bpmn-visualization-js[Github repository]. +
On the other hand, Bonita has been using another library to display process execution data for administrators at both process and case levels. This library had some limitations and was not easy to improve with new features. +
So it was a very natural choice to eventually integrate the bpmn-visualization library to Bonita, and team up with the Process Analytics team. +

Some new values are available, starting with the Efficiency Edition of Bonita:
  
  * The users of the Bonita Administration application will see a faster and more robust view of the process execution data (thanks to the library and new REST APIs)
  * As the bpmn-visualization library improves, we will add more interactivity and more information to provide a better monitoring capacity
  * Since the pages have been recreated with the UI Designer, developers can:
        
        ** Use the custom widget embedded in the new pages in their own application pages. The widget has been wrapped into a fragment that makes it very easy to use.
        ** Offer process execution data visualization to users of their applications, by adjusting the permissions accordingly

To know more, visit the xref:pages-and-forms:customize-display-process-monitoring.adoc[How to page to customize the display of process execution monitoring]

== Improvements

=== Development suite changes

==== A new first-start flow for the Studio

When launched for the first time, the Studio will no longer start a default project. The goal is to make this first start less cumbersome.
To increase user guidance, the Welcome page has been improved to have clear call-to-action buttons.

==== Bonita Marketplace - Display installed extension

To help users' awareness on the extensions installed in their project while browsing the Bonita Marketplace, a new filter was added to display the already installed extensions.

==== Detecting issue with extension when importing them

With the previous version, you could import malformed extensions in your project without any warnings. This would lead to errors downstream and confusion for users.
From now, when importing or updating an extension the Studio will detect the issues and inform the user.

==== Improved guidance when the actor mapping is not defined

With the previous version, if the actor mapping of a process was not defined, an unclear error message would be displayed to the user. To help our users move forward with the deployment of their processes, we have improved the error detection to provide a clear message when this issue occurs.

==== New Menus for Bonita Studio

To simplify the usage of Bonita Studio, the menus have been reviewed.

== Functional changes

=== Case info REST API resource- *Subscription editions*

Case info `bpm/caseInfo` REST API resource which is used for process and case visualization (Subscription edtions features) is now only available in subscription editions.

For Community users who update to 2022.2, if you need this API resource, you can create a REST API extension that leverages Bonita Engine java API to get the same functionality as in 2022.1.

== Technical updates

UI Designer frontend has been migrated to AngularJS 1.8.

[WARNING]
====
Only the UID application has been upgraded to AngularJS 1.8. Your applications are still generated with AngularJS 1.3. Stay tuned for later upgrades of this part.
====


== Feature deprecations and removals

=== SVN

SVN integration in Bonita Studio Subscription has been removed. You may migrate an existing SVN repository to a Git repository following this xref:migrate-a-svn-repository-to-github.adoc[guide].


== Bug fixes


== Known issues

