= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
**Welcome to Our Latest Update!**

We are pleased to bring several exciting advancements in this release, including enhancements to our platform and a brand new entry-level offer designed to help new users seamlessly integrate with our technology.
====

== New available values

* [.underline]#Bonita Process Insights Release scope#

** Export tool: Enhancing our integration capabilities the Bonita data export tool, to enable import into BPI, is now compatible with our clients whose database is Oracle. This update enables easier data import into BPI, facilitating smoother transitions and better data management for our clients using Oracle.

* [.underline]#New User Interface Designer (UID)# Get ready for an exciting preview! We are preparing a demo of our new user interface. A beta version will be available in July, with a general availability (GA) launch planned for August. This update aims to enhance user experience and improve interface interactions.

* [.underline]#2024.2 Bonita Platform# → Introducing “Access” our new offer that make it easier than ever to start leveraging the powerful capabilities of Bonita

** **A New Beginning**: We are excited to introduce “Access”, our new entry-level offer tailored for new customers. This package is designed to help new users get started with our technology through a concentrated set of key features.

** **Eligibility** designed specifically for those new to Bonitasoft, this offer aims to make it easier than ever to start leveraging the powerful capabilities of Bonita

** **Easy start**: Access provides an easy and low-cost way to get started

** **Dedicated Support**: Choosing Access means partnering with us. We provide the support and resources you need, tailored to your specific requirements, ensuring you have the best start possible.

** **Regular Updates**: Stay up-to-date with the latest enhancements. Access ensures you always have the most current versions and features, keeping your operations efficient and cutting-edge.

** **Customization Options**: tailor Access to your needs with options for custom extensions, authentication mechanisms, and more, allowing you to shape our technology to fit your operational needs perfectly

== Bug fixes

=== Fixes in Bonita 2024.1-u3 (2024-07-17)

==== Fixes in Bonita Runtime including Bonita Applications

* RUNTIME-1883 - Add extra java 17 open packages instructions for Bundle packaging
* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +
* RUNTIME-1877 - Session Sharing x sameSiteCookies value systematically set to "lax" when cluster is enabled. xref:runtime:install-a-bonita-bpm-cluster.adoc[New configuration properties] specific to cluster mode and session cookie have been added.
* RUNTIME-1884 - `password` attribute silently removed from `org.bonitasoft.engine.identity.impl.UserImpl` class. Add removal information in the release note. Make the XStream deserialization less strict to avoid deserialization exception when a some fields are unknown.
* RUNTIME-1887 - Regression in ServerProxifier algorithm produce a greater number of SQL requests.

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4536 - Hazecalst discovery is enabled by default for Studio embedded Runtime
* STUDIO-4515 - Improve error management when migrating inconsistent project data
* STUDIO-4517 - Improve error management when migrating inconsistent project data
* STUDIO-4530 - ResourceException when using Switch Workspace from a 9.0.x
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
* STUDIO-4533 - Refreshing a project after a git switch branch now adds/removes submodules as expected.
* STUDIO-4535 - Renaming a project without bdm or extensions fails

=== Fixes in Bonita 2024.1-u2 (2024-06-07)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1844 - Update Tomcat to latest 9.0.x
* RUNTIME-1848 - ArchivedTasks filter on type is generating java.lang.ClassCastException
* RUNTIME-1860 - Access Control panel is displayed on page in all subscription editions even when the feature is not active
* RUNTIME-1864 - SCA cannot be started without BDM_ACCESS_CONTROL license key activated
* CVE-63       - Upgrade Apache Tomcat version (fixing CVE-2024-24549)

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4518 - Bdm Access Control / Profile menu item is not completely disabled if license key is not present
