= Release notes
:description: Bonita release note

[NOTE]
====
The 2022.1 is in development.
====

== New values added

== Improvements

== Functional changes

=== Prometheus monitoring active by default (Subscription editions)

From Bonita 2022.1, xref:runtime-monitoring.adoc#_prometheus_publisher[the Prometheus metrics publisher] is now active by default, and can be disabled if needed. +
Its access is now protected with Basic Auth authentication to protect against DOS attacks. +
Thus, when reaching the prometheus metrics endpoint, typically https://localhost:8080/bonita/metrics, you will have to manually enter the configured username and password information for your access to be granted.

These credentials can be consulted and modified:

* in the <BONITA>/server/conf/tomcat-users.xml file in a *Bonita Tomcat bundle*
* using xref:bonita-docker-installation.adoc#_monitoring_username[specific Environment parameters] when starting a *Bonita Docker image*

== Technical updates

===  Log4j2 Logger

Bonita Runtime now use Log4j2 as logger.
One of the great feature that it brings is the automatic reload of configuration files. There is no more need
to restart the platform only to change a log level
More information on how to use it in the docker image xref:runtime:bonita-docker-installation.adoc#logger_configuration[here] and in the bundle xref:setup-dev-environment:logging.adoc#_logging_configuration[here].


[WARNING]
====
If, in previous version, you customized the `logging.properties` file, you should update `log4j2-loggers.xml` as described in the documentation
xref:runtime:bonita-docker-installation.adoc#logger_configuration[here] and xref:setup-dev-environment:logging.adoc#_logging_configuration[here].

A conversion table between loggers level in JUL and in Log4j2 is available
https://logging.apache.org/log4j/2.x/log4j-jul/index.html[here]

If you want to continue using the previous log format, the previous pattern is present in the `log4j2-appenders.xml` file but commented out.

The Tomcat bundle does not log anymore in the console but only in `bonita.log` file. The previous behavior can be activated by activating the `Console` appender in `log4j2-appenders.xml`
====

=== Docker image

Folder structure inside Bonita Docker images has been simplified: instead of having /opt/bonita/BonitaCommunity-{bonitaVersion} or /opt/bonita/BonitaSubscription-{bonitaVersion}, we now simply have */opt/bonita*. +
If you have scripts using the former folder structure, please update them.

The docker image does not create the database schema and the associated user anymore. The database must be created before the image starts. We provide pre-configured database images with already created existing schema and users https://hub.docker.com/r/bonitasoft/bonita-postgres

As a consequence, the following environment properties were removed:

* `ENSURE_DB_CHECK_AND_CREATION`
* `DB_DROP_EXISTING`
* `BIZ_DB_DROP_EXISTING`
* `DB_ADMIN_USER`
* `DB_ADMIN_PASS`

== Feature deprecations and removals

== Bug fixes

== Known issues