= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
The {bonitaVersion} version is in development.
====

== Bonita UI Builder

We are excited to announce the release of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder], our new and enhanced development environment for creating all kind of interfaces, pages and forms for your applications! It brings along a host of advanced features and improved usability, designed to help you create compelling, responsive, and user-friendly interfaces.

You can continue to use Bonita UI Designer as usual, while also having the opportunity to explore and get familiar with the capabilities of Bonita UI Builder. 

Eventually, Bonita UI Designer will be phased out as we progressively transition to Bonita UI Builder. Rest assured, we are committed to providing comprehensive support and resources throughout this process. Our goal is to make this transition as smooth as possible, minimizing any disruption to your workflow.

Here’s what you can expect during this transition period:

* Continued access: Bonita UI Designer will remain fully operational for an extended period, allowing ample time for adaptation
* Support and resources: We offer extensive documentation, tutorials, and support to help you make the most of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder] 
* Facilitated transition: We are dedicated to facilitate the transition, with detailed guides on how to use Bonita UI Builder, as well as https://www.bonitasoft.com/professional-services/on-demand-services[professional services support]


== New available values

=== Application Links

You can now use application links. See xref:applications:bonita-ui-builder.adoc[Applications with Bonita UI Builder] for more details. Community users can also integrate their own links for applications developed with other tools.
See xref:applications:faq.adoc[FAQ] for common problems and solutions (e.g. if you use a customized or an old layout).

xref:api:engine-api-overview.adoc[Engine APIs] that allowed applications manipulation still work with legacy applications and have been deprecated in favor of new APIs that manipulate both application links and legacy applications.

xref:api:rest-api-overview.adoc[REST APIs] (see _Application_ section) now also return application links in addition of legacy applications.

== Bug fixes

=== Fixes in Bonita 2024.3-b3 (2024/08/29)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-48 - SFlowNodeNotFoundException: Quartz's Trigger associated to a Boundary timer does not get deleted when the process instance terminates
* RUNTIME-1895 - [SAML & OIDC SSO]: Bonita redirects to IdP if redirected target URL request lands on different node than the one where the original request was received

=== Fixes in Bonita 2024.3-b2 (2024/07/26)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +
* RUNTIME-1877 - Session Sharing x sameSiteCookies value systematically set to "lax" when cluster is enabled. xref:runtime:install-a-bonita-bpm-cluster.adoc[New configuration properties] specific to cluster mode and session cookie have been added.
* RUNTIME-1883 - Add extra java 17 open packages instructions for Bundle packaging
* RUNTIME-1884 - `password` attribute silently removed from `org.bonitasoft.engine.identity.impl.UserImpl` class. Add removal information in the release note. Make the XStream deserialization less strict to avoid deserialization exception when a some fields are unknown.
* RUNTIME-1887 - Regression in ServerProxifier algorithm produce a greater number of SQL requests.
* RUNTIME-1890 - [LDAP Synchronizer] - Add add-opens for packaged scripts

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4517 - Old version Git repository clone fails with DirectoryNotEmptyException if REST API extension does not contain pom.xml file
* STUDIO-4515 	NPE generated during project migration 
* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4530 - ResourceException at Studio 9.0.4 restart after a Switch Workspace to exisitng workspace from a 9.0.3
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
* STUDIO-4533 - Refreshing a project after a git switch branch now adds/removes submodules as expected.
* STUDIO-4535 - Renaming a project without bdm or extensions fails
* STUDIO-4536 - Hazecalst discovery is enabled by default for Studio embedded Runtime

=== Fixes in Bonita 2024.3-b1 (2024/07/04)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4517 - Old version Git repository clone fails with DirectoryNotEmptyException if REST API extension does not contain pom.xml file
* STUDIO-4515 	NPE generated during project migration 
* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4530 - ResourceException at Studio 9.0.4 restart after a Switch Workspace to exisitng workspace from a 9.0.3
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
