= Release notes
:description: [NOTE]

[NOTE]
====

The 2021.2 is currently work in progress (WIP).
====

== New values added

=== SSO with OpenID Connect

As of Bonita 2021.2 it is possible to xref:single-sign-on-with-oidc.adoc[configure Bonita to use OpenID Connect (OIDC)] as an authentication mechanism to access your Bonita applications and achieve Single Sign-on with an external OIDC provider. +
The Authorization Code Flow of OpenID Connect is supported to authenticate when accessing Bonita applications as well as the Resource Owner Credentials Grant and Authorization Code Grant of OAuth 2.0 to authenticate when requesting Bonita REST API.

== Bonita Studio Project Composition

Bonita projects will use the power Maven projects. Meaning that you will be able to easily compose your project of extensions (connectors, Rest API extensions, themes, and actor filters).

All these extensions, which are technical components, have to be built outside the Studio with our SDK. This will allow the developer to use their preferred tooling. It will also help the industrialization of your project as you will be able to implement tests for each extension making your project more robust.

As the extensions are developed outside the Studio, they are no longer bound to a specific Bonita project. They can be easily reused in a different project - thus improving your efficiency. xref:project-structure.adoc[More information on how Bonita project are structured].

The Studio is stripped of its major coding editor (except for the REST API Extensions) but has now a xref:managing-extension-studio.adoc[dedicated view for extensions]. This view is used to get extensions from different sources: 
* From the Bonita marketplace, which contains all the actor filters and connectors made and maintain by Bonitasoft
* From maven repository (private or public)
* From files (jar or zip)

The Studio is more accessible to citizen developers. Any technical development should be made outside the Studio.

As connectors are now extensions of a project, their version is now bound to the Studio version, therefore you don’t need to upgrade your Studio to upgrade a connector or to upgrade your connector when upgrading your Studio. This will simplify version upgrades.

Finally, your sources will be lighter as the dependencies will be pulled by the project.

== Organization Editor

The Organization wizard has been reworked into an editor, to improve your experience and your efficiency.

== Project Overview

Understanding all the elements of a Bonita project has never been easier thanks to the Project Overview. Accessible from the cool, this new page displays all the elements that can be used in a state-of-the-art Bonita project. From this view, you can create, consult or edit the different elements. You can also find documentation on the different components.

== Improvements

=== Exception reporting

When something goes wrong while executing processes, we now log only the important informations. In addition, the root cause of the issue is the first one shown.

Here is a sample of what will now be logged

----
2021-01-11 17:55:25.551 +0100 WARNING (Bonita-Worker-1-01) org.bonitasoft.engine.work.RetryingWorkExecutorService THREAD_ID=115 | HOSTNAME=Baptistes-MBP | TENANT_ID=1 | Work ExecuteFlowNodeWork: flowNodeInstanceId: 60001 (37, false, false, false) failed. The element will be marked as failed. Exception is: java.lang.ArithmeticException: Division by zero
	wrapped by org.bonitasoft.engine.expression.exception.SExpressionEvaluationException: Groovy script throws an exception of type class java.lang.ArithmeticException with message = Division by zero
Expression : SExpressionImpl [name=aScript, content=1/0, returnType=java.lang.String, dependencies=[], expressionKind=ExpressionKind [interpreter=GROOVY, type=TYPE_READ_ONLY_SCRIPT]]
	wrapped by org.bonitasoft.engine.core.process.instance.api.exceptions.SActivityStateExecutionException: error while updating display name and description
 exception was generated here:	at java.math.BigDecimal.divide(BigDecimal.java:1745)
	at org.codehaus.groovy.runtime.typehandling.BigDecimalMath.divideImpl(BigDecimalMath.java:68)
	at org.codehaus.groovy.runtime.typehandling.IntegerMath.divideImpl(IntegerMath.java:49)
----

A new property `bonita.tenant.work.exceptionsNumberOfFrameToLog` of `bonita-tenant-community-custom.properties` allows the change the number of frame displayed when an exception happens.

=== Development suite changes

==== Expression type simplification
2021.1 introduced a new expression editor. This new expression editor covered most of the existing editor expression type use cases.

Therefore to simplify the expression flow in the Studio we are removing the following expression types:

* Constant
* Comparison
* Constant
* Parameter
* Variable
* Contract
* Connector Output

If your project are using these expression types, they will be migrated to the new expression editor when you import your project in the 2021.2 Studio.

=== Runtime changes

==== Groovy script results casting

Bonita runtime will automatically try to cast the result of groovy scripts when it differs from the declared return type if it can be converted.

For example, when a script returns a long and you have declared `java.lang.Integer` as the return type of your expression,
it was throwing an Invalid return type exception. Now it will cast that result to an integer.

That will make the expression more permissive.
[NOTE]
====

Groovy is able to cast any object in boolean so scripts that declare a return type `java.lang.Boolean` that failed because of the wrong return type will now always
work and return either `true` or `false`. See https://groovy-lang.org/semantics.html#Groovy-Truth[Official Groovy documentation] for truthy/falsy values.
====

==== Logging

default log level for `com.bonitasoft` and `org.bonitasoft` change from `WARNING` to `INFO`

==== Easy upgrade from Community to Subscription

From this release, xref:upgrade-from-community-to-a-subscription-edition.adoc#bonita-platform-upgrade[upgrade from Community to Subscription] is made a lot easier:
all the tricky configuration part is handled automatically by Bonita Runtime at server startup. +
See xref:#_configuration_file_changes[the related changes] done to specific configuration files.

==== JAAS authentication is now Enterprise

From version 2021.2, JAAS Authentication is only available in the Enterprise edition. +
If you are updating from a 2021.1 or earlier version, in the Community edition, you will need to xref:BonitaBPM_platform_setup.adoc[change your configuration] file `authenticationManager-config.properties`
and remove the JAAS configuration to use another Authentication Manager (an implementation of your own, for instance).

== Technical updates

=== Java 11 Compliance

Bonita 2021.2 is now only compatible with Java 11. Support with Java 8 has now been removed.


=== Libraries

=== Support Matrix

=== Configuration file changes

* Unused configuration file `forms-config.properties` has been removed.
* Optional configuration file `jaas-standard.cfg` has been removed from Tomcat Community bundle (because xref:_jaas_authentication_is_now_enterprise[JAAS is now Enterprise])
* CAS and Kerberos configuration files have been moved to `tools/SSO/` folder (Bonita Enterprise only)


== Feature deprecations and removals

=== Deprecations

=== Removals

==== BonitaStudioBuilder

The deprecated `BonitaStudioBuilder` command line interface has been removed. To benefit from an efficient Bonita project building and deploying solution, please refer to https://documentation.bonitasoft.com/bcd[BCD add-on].

== Bug fixes

=== Fixes in Bonita 2021.2

==== Fixes in Bonita Development Suite (Studio and UI Designer)

==== Fixes in Bonita Runtime (including Portal)
