= Release notes
:description: Bonita release note

[NOTE]
====
The 2022.2 is in development.
====


== New values added


== Improvements

=== Development suite changes

====

== Functional changes

=== Case info REST API resource- *Subscription editions*

Case info `bpm/caseInfo` REST API resource which is used for process and case visualization (Subscription edtions features) is now only available in subscription editions.

For Community users who update to 2022.2, if you need this API resource, you can create a REST API extension that leverage the engine java API to get the same functionality as in 2022.1.

== Technical updates

UI Designer has been migrated to AngularJS 1.8, to enable AngularJS extended support.

[WARNING]
====
Your UI Designer applications must be extensively tested to verify if any updates are required on your side to support this new version.
====

See xref:angularjs-1-8-migration.adoc[Migration to AngularJS 1.8] for details.

== Feature deprecations and removals

=== SVN

SVN integration in Bonita Studio Subscription has been removed. You may migrate an existing SVN repository to a Git repository following this xref:migrate-a-svn-repository-to-github.adoc[guide].


== Bug fixes


== Known issues

