= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
The {bonitaVersion} version is in development.
====

== New available values

=== Enhanced Log Tracing and Filtering

Log tracing and filtering in Bonita have been enhanced using MDC (Mapped Diagnostic Context) to add contextual information across all scopes.
This improvement ensures higher-quality, more readable logs and simplifies integration with third-party monitoring tools, helping customers troubleshoot issues and monitor performance more effectively.

[WARNING]
====
This extra information also means more volume for logs. +
If you have limited space for logs and do not wish this information, you may deactivate this feature by removing `{ - %X}` from the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration].
====

You can see the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration] for more details.

=== Improved Admin application

The Admin application has been improved to provide a better user experience and a better way to identify and recover from errors +
The task and case details pages have been redesigned to provide clearer information and new error sections when there are some failures at task or case level (For Access, Performance and Enterprise editions only). +
It is now possible to see child cases (started by call activities) and not just root cases from the case details and the case list page. This improves the consistency of the whole application and allows an administrator to understand more easily what is happening in a case by navigating to the child cases details and diagram visualisation or list of tasks+

=== New BPM Failures recording and API

[NOTE]
====
For Access, Performance and Enterprise editions only.
====

All failures happening in a task or a case are now recorded in the database (and archived when the task/case is archived). The records include a scope (e.g.: Data initialization, Connector, etc), a detailed context (e.g.: data name, connector name, script name etc..) and the exception and its stacktrace. +
Those failures with detailed information are visible in the Admin application in the case details and task details pages. +
New {openApiUrl}/{openApiLatestVersion}#tag/Failure[BPM/failure] and {openApiUrl}/{openApiLatestVersion}#tag/ArchivedFailure[BPM/archivedFailure] REST API resources have been added to retrieve the failures of a task, a case or a root case (including all the child cases). +
Java API also includes new methods to retrieve those failures (see getProcessInstanceFailures or getFlowNodeInstanceFailures in ProcessRuntimeAPI). +

== Notable changes

=== Update tool script has been renamed

To simplify and rationalize the naming of the scripts, the update tool script has been renamed.

The formerly named `bonita-update-tool(.bat)` script has been renamed to `bonita-update(.bat)`.

Moreover, the Subscription version of the script is also named `bonita-update(.bat)`. (there is no `-sp` suffix anymore)



== Deprecations and removals

=== API removals

==== Command API

Up to 2024.3, you could implement custom commands by inheriting either from the `org.bonitasoft.engine.api.TenantCommand` interface or from the `org.bonitasoft.engine.command.PlatformCommand` interface. With multitenancy removal, those two commands have been merged into `org.bonitasoft.engine.command.RuntimeCommand` +
If you have not done it yet, recompile your custom commands by changing parent class to `RuntimeCommand`, https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#unregister(long)[unregister] the previous one and https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#register(java.lang.String,java.lang.String,java.lang.String)[register] the new one.

==== Platform API

Deprecated method PlatformAPI.updateTenant() has been removed.


=== EntityMember (aka. External Identity Mapping)

This concept has been completely removed because the associated feature was not used internally and was not documented.
It was used to map arbitrary external IDs to Bonita identity (user, group, role, membership). +
Event keys EXTERNAL_IDENTITY_MAPPING_CREATED and EXTERNAL_IDENTITY_MAPPING_DELETED have been removed from the event API and cannot be listened to anymore.


=== Configuration changes

==== JAAS / CAS SSO configuration

With the removal of the multi-tenancy feature, the configuration of the xref:identity:active-directory-or-ldap-authentication.adoc[JAAS] / xref:identity:single-sign-on-with-cas.adoc[CAS] SSO has been simplified. +
The notable change is that the configuration module is now named `BonitaAuthentication` (without `-<TENANT_ID>` suffix). +


== Bug fixes

=== Fixes in Bonita 2025.1 (! DATE TO ADD HERE !)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-28 - The deletion of a running process instance leaves lines in the DOCUMENT table. +
Before this fix, when a process instance was deleted, the documents associated with it were not deleted. As a consequence, this behavior creates orphan documents that are unused and not linked to any other object. Note that it was not the case for archived process instances where documents were correctly deleted. +
If you have a lot of orphan documents in your database, you can use the latest version of the xref:ROOT:purge-tool.adoc#delete-orphan-document-content[Purge Tool] to remove them.

==== Fixes in Bonita Studio (including Bonita UI Designer)
