= Release notes
:description: Bonita release note

[NOTE]
====
Bonita 2022.2 is available for download.
====

== New available values

=== Bonita process monitoring now with embeded bpmn-visualization library

Bonitasoft launched the open source project https://process-analytics.dev/[Process Analytics] two years ago in response to the market need to perform BPMN process monitoring using BPMN standards.
The deliverable of this project is called the _bpmn-visualization library_. You can find a nice array of examples of what it can do in its https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.25.2/examples/index.html[demo web site], and you can even contribute to this initiative in its https://github.com/process-analytics/bpmn-visualization-js[Github repository]. +
Till Bonita 2022.2, another library has been used to display process execution data for administrators at both process and case levels. This library had some limitations and was not easy to improve with new features. +
Hence, integrating the bpmn-visualization library to Bonita, was a very natural choice. +

The new values are available for Bonita Subscription Editions starting with the Efficiency edition.

  * Bonita Administration application users will get a faster and more robust view on the process execution data (thanks to the library and new REST APIs)
  * As the bpmn-visualization library evolves, more interactivity and information for a better monitoring capacity will be provided
  * Since the pages have been created by using Bonita UI Designer, developers can:

        ** Use the custom widget embedded in the new pages in their own application pages. The widget has been wrapped into a fragment that makes it very easy to use.
        ** Modify the process or case visualization page, and use it in any Bonita application

For more details, check xref:pages-and-forms:customize-display-process-monitoring.adoc[How to page to customize the display of process execution monitoring]

=== Bonita Reporting Application

Here it comes, Bonita Reporting Application is now available for download on Bonita’s Customer Service Center/Customer Portal and is compatible starting with Bonita 2021.2.

A subscription account is required for downloading the .jar , that contains “Process Historical Data” and “Human tasks historical data” reports, designed for process performance and human tasks execution analysis. More details are available in the dedicated documentation page xref:runtime:reporting-app.adoc[Bonita application for analytics and reporting].

=== A new widget to deal with Currencies

A new xref:pages-and-forms:widgets-inputs.adoc#currency-input-widget[input widget] is now available in UI Designer to manage financial data using currencies at ease in pages or forms.

=== Bonita Artifact Repository 

In Bonita 2022.1, we delivered xref:1.0@test-toolkit::process-testing-overview.adoc[Bonita Test Toolkit] through an additional Maven archive. With Bonita 2022.2 we are delivered our subscription only Bonita Artifact Repository, and Bonita Test Toolkit is the first available for download artifact. Step by step, all our supported products will become available for download through Bonita Artifact Repository. 

== Improvements

=== Development suite changes

==== A new first-start flow for the Studio

When launched for the first time after an install, the Studio will no longer start with a default project. The goal is to make this first start less cumbersome.
Also, to increase user guidance, the Welcome page has been improved with clear call-to-action buttons.

==== Bonita Marketplace - Display installed extension

A new filter was added to display the already installed extensions in order to help users know the extensions installed in their project while browsing the Bonita Marketplace

==== Detecting  extension's related issues at import

With the previous version, you could import malformed extensions in your project without any warnings. This leading to errors downstream and confused users.
From now, when importing or updating an extension, errors will be detected and users will be informed in Studio.

==== Improved guidance when the actor mapping is not defined

With the previous version, if the actor mapping of a process was not defined, an unclear error message was displayed to the user. To help our users move forward with the deployment of their processes, we have improved the error detection by providing a clear message when this issue occurs.

==== New Menus for Bonita Studio

The menus have been reviewed for an easier user journey.

==== Added Environment duplication feature

With the previous versions, creating a new environment required to set up the whole project configuration entirely, including configuration of each process, what could be time consuming and error prone with big projects. From now on, users can create environments starting from duplicating an existing one.

== Functional changes

=== Process and case info REST API resources - *Subscription editions*

It is now possible to retrieve the tasks execution data of all open cases of a process by using the process info xref:api:actors-process-connectors-api.adoc#_processinfo_subscription_editions_only[`bpm/processInfo` REST API resource]. It returns counters for each flow node in the process, showing the number of flow node instances that are in executing, ready, or failed state.

The REST API resource xref:api:cases-process-instance-api#_caseinfo_subscription_editions_only[Case info `bpm/caseInfo`] which is used for case visualization is now available in subscription editions only.
For Community users who update to 2022.2, if you have this business need, you can create a REST API extension that leverages Bonita Engine java API to get the same functionality as in Bonita 2022.2 - Subscription version.

== Technical updates

UI Designer frontend has been migrated to AngularJS 1.8.

[NOTE]
====
Only the UID application has been upgraded to AngularJS 1.8. Your applications will still generated with AngularJS 1.3. Stay tuned for further updates.
====

== Feature deprecations and removals

=== SVN

SVN integration in Bonita Studio Subscription has been removed. You may migrate an existing SVN repository to a Git repository following this xref:migrate-a-svn-repository-to-github.adoc[guide].

=== Multi-tenancy deprecation

xref:ROOT:multi-tenancy-and-tenant-configuration.adoc[Multi-tenancy has been deprecated commercially] by Bonitasoft starting from Bonita 2021.1. 

To cover the multi-tenancy use cases in the best technical way, Bonitasoft is proposing a new architecture solution. For customers running a Bonita multi-tenancy platform, the technical path from multi-tenancy proposed by Bonitasoft is multi-runtime. This choice will require to split the current multi-tenant platform into several runtimes, each one with their own Bonita engine database.

As this path can be challenging for customers using multi-tenancy, Bonitasoft developed a conversion tool. We strongly suggest our customers to take the time and use the tool in a pre-production environment before the production. 

xref:version-update:mtmr-tool.adoc[Multi-tenancy to multi-runtime conversion tool] can be executed on Bonita Platforms starting from Bonita 7.11. In case you are in version not supported (<7.11) perform first an update of the platform.

[WARNING]
====
Reminder : For commercial and support questions, please refer to your Customer Success referent. 
====

== Bug fixes
For the users of Bonita Community edition, Bonita 2022.2 also comes with all the bug fixes released in the Maintenance versions of Bonita 2022.1 (up until version 2022.1-u6).
The detailed list is available in the "What’s new in Bonita 2022.1" page, in the "Bug fixes" section.


==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4399 - Fix synchronize project open/close action 
* STUDIO-4400 - Fix [Organization] Password resolution 
* STUDIO-4419 - Fix failed to Load EMF ressource when trying to open an imported .bpmn file 

==== Fixes in Bonita Runtime (including Bonita native Applications)

* RUNTIME-211  - Fix access to a non existing token in an app raise a 403 instead of a 404
* RUNTIME-334  - Fix REST API ../API/identity/user/-1?d=professionalData as it returns the list of users
* RUNTIME-335  - Fix REST API ../API/identity/user/-1 as it returns a APIMissingIdException
* RUNTIME-864  - [Security] Several dependencies updates for 2022.2 (7.15.0)
* RUNTIME-869  - Fix [Admin App]: BPM process: The 2 Popups to Disable and Enable installed process do not close
* RUNTIME-978  - Fix organisation import does not update 'lastUpdate' field in user entries
* RUNTIME-1011 - Fix processId in URL not taken into account in admin case list
* RUNTIME-1147 - Fix office to PDF connector is not working on a 2022.1-u0 docker enterprise image
* RUNTIME-1248 - Fix [Admin App]: Case list should not display the "view diagram" icon if the feature is not available
* RUNTIME-1273 - Fix [Admin App]: BPM pages should be editable in subscription editions
* RUNTIME-1275 - Fix bonita-sp- maven-repository 7.13.x contains extra files
* RUNTIME-1408 - Fix slow REST API extension requests due to a java sycnhronized block

== Known issues


