= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions


== New available values

=== Enhanced Log Tracing and Filtering

Log tracing and filtering in Bonita have been enhanced using MDC (Mapped Diagnostic Context) to add contextual information across all scopes.
This improvement ensures higher-quality, more readable logs and simplifies integration with third-party monitoring tools, helping customers troubleshoot issues and monitor performance more effectively.

[WARNING]
====
This extra information also means more volume for logs. +
If you have limited space for logs and do not wish this information, you may deactivate this feature by removing `{ - %X}` from the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration].
====

You can see the xref:setup-dev-environment:logging.adoc#logging-configuration[logging configuration] for more details.

=== Improved Admin application

The Admin application has been improved to provide a better user experience and a better way to identify and recover from errors +
The task and case details pages have been redesigned to provide clearer information and new error sections when there are some failures at task or case level (For Access, Performance, Enterprise and Scale editions only). +
It is now possible to see child cases (started by call activities) and not just root cases from the case details and the case list page. This improves the consistency of the whole application and allows an administrator to understand more easily what is happening in a case by navigating to the child cases details and diagram visualisation or list of tasks +

=== New BPM Failures recording and API

[NOTE]
====
For Access, Performance, Enterprise and Scale editions only.
====

All failures happening in a task or a case are now recorded in the database (and archived when the task/case is archived). The records include a scope (e.g.: Data initialization, Connector, etc), a detailed context (e.g.: data name, connector name, script name etc..) and the exception and its stacktrace. +
Those failures with detailed information are visible in the Admin application in the case details and task details pages. +
New {openApiUrl}/{openApiLatestVersion}#tag/Failure[bpm/failure] and {openApiUrl}/{openApiLatestVersion}#tag/ArchivedFailure[bpm/archivedFailure] REST API resources have been added to retrieve the failures of a task, a case or a root case (including all the child cases). +
Java API also includes new methods to retrieve those failures (see getProcessInstanceFailures or getFlowNodeInstanceFailures in ProcessRuntimeAPI). +

=== Support for multiple OpenID Connect providers

[NOTE]
====
For Teamwork, Efficiency, Performance, Enterprise and Scale editions only.
====

When Bonita is configured for xref:identity:single-sign-on-with-oidc.adoc[Single Sign-On (SSO) with OpenID Connect], it is now possible to configure xref:identity:single-sign-on-with-oidc.adoc#multi-providers[several OIDC providers] and allow end-users to choose the provider they want to use to log in. +

=== Custom login page

You can now create xref:identity:user-authentication-overview.adoc#_custom_login_page[a custom external login form] using the technology of your choice and set an environment variable to have Bonita Runtime redirect to this page instead of the default one (login.jsp).


=== New REST APIs to create / update / delete referential Business Data

Bonita now provides a native and secure way to update Business Data Model (BDM) entries at runtime.

Until now, updating reference data or other BDM content required either direct SQL queries, posing risks to data integrity and auditability, or the deployment of dedicated Bonita processes, adding unnecessary complexity for simple operations.

By simplifying updates while ensuring control and traceability, this API reduces operational friction and eases maintainability in production environments.

New REST APIs have been added to create, update and delete business data.

These APIs are recommended for referential business data only, and are limited to Business Data that do not have references to other business data. +

The new APIs are:

* {openApiUrl}/{openApiLatestVersion}#tag/Business-Data-Operations[POST bdm/businessData/+{businessDataType}+] to create a new business data object
* {openApiUrl}/{openApiLatestVersion}#tag/Business-Data-Operations[PUT bdm/businessData/+{businessDataType}+/+{ID}+] to update an existing business data object
* {openApiUrl}/{openApiLatestVersion}#tag/Business-Data-Operations[DELETE bdm/businessData/+{businessDataType}+/+{ID}+] to delete an existing business data object
* {openApiUrl}/{openApiLatestVersion}#tag/Business-Data-Operations[POST bdm/businessData/+{businessDataType}+/import] to import a CSV-formatted file for bulk import of new business data objects

To support these new APIs, https://github.com/bonitasoft/bonita-java-client[Bonita REST client] has been updated accordingly.

Along with these APIs, the xref:integration:event-handlers.adoc#_event_list[following events are triggered], so that you can listen to them and react accordingly, if needed:

* BUSINESS_DATA_CREATED
* BUSINESS_DATA_UPDATED
* BUSINESS_DATA_DELETED

Note that these three events are always triggered, whether through these new APIs or through operations on tasks.

=== New REST API to cancel a case (process instance)

Bonita now provides a way to cancel a process instance (case) using the REST API.

Until now this was only supported in the Java API.

The new API is:

* {openApiUrl}/{openApiLatestVersion}#tag/ProcessInstance[PUT bpm/case/+{id}+] to update a case to the cancelled state

== Notable changes

=== Improving user experience in Studio

The automatic migration of a Bonita project in Studio has been improved when using Git (on a check out or branch switch). +
This migration now happens in a wizard which lets you examine and execute the migration steps one by one, or cancel the whole operation any time you wish. You can also execute them all in batch if you do not want the details. +
All migration step executions are detailed in the log.

When building your process, process dependencies are now handled with maven and the configuration has been simplified to reduce the risk of error while selecting Java libraries.
You can also visualize process dependencies xref:process:managing-dependencies.adoc[with a right click in the explorer view]. +
In an SCA build, these dependencies are not added to the Business Archive, but directly to the webapp classpath.

Bonita Studio allows you to create an extension modules directly in your Bonita Project. See xref:software-extensibility:extensions-sdk.adoc#servers[more details here]. The xref:process:connector-migration.adoc[migration for connectors and actor filters for Bonita projects created with Bonita 2021.1 or lower] has also been facilitated.

=== Update tool script has been renamed

To simplify and rationalize the naming of the scripts, the update tool script has been renamed.

The formerly named `bonita-update-tool(.bat)` script has been renamed to `bonita-update(.bat)`.

Moreover, the Subscription version of the script is also named `bonita-update(.bat)`. (there is no `-sp` suffix anymore)


=== Purge tool script has been renamed

[NOTE]
====
For Subscription editions only.
====

To simplify and rationalize the naming of the scripts, the purge tool script has been renamed.

The formerly named `bonita-purge-tool(.bat)` script has been renamed to `bonita-purge(.bat)`.


=== Setup Tool (aka Platform Setup) file structure has been simplified

The setup tool file structure has been simplified to better fit the multitenancy removal.
For those who were used to fetch their configuration files under `platform_conf/current/tenants/<TENANT_ID>/tenant_engine`, for instance, the path is now `platform_conf/current/tenant_engine`. All the documentation has been updated accordingly. +
For the curious ones, here is the full comparison:

.Up to 2024.3 (10.2)
[%collapsible]
====
Content of the `setup/` folder:

[source,shell]
----
platform_conf
├── current
│  ├── platform_engine
│  │  ├── bonita-platform-community-custom.properties
│  │  ├── bonita-platform-custom.xml
│  │  ├── bonita-platform-sp-cluster-custom.properties
│  │  ├── bonita-platform-sp-custom.properties
│  │  ├── bonita-platform-sp-custom.xml
│  │  └── hazelcast.xml
│  ├── platform_portal
│  │  ├── cache-config.xml
│  │  ├── platform-tenant-config.properties
│  │  └── security-config.properties
│  ├── tenants
│  │  └── 1
│  │      ├── tenant_engine
│  │      │  ├── bonita-tenant-community-custom.properties
│  │      │  ├── bonita-tenants-custom.xml
│  │      │  ├── bonita-tenant-sp-cluster-custom.properties
│  │      │  ├── bonita-tenant-sp-custom.properties
│  │      │  └── bonita-tenant-sp-custom.xml
│  │      ├── tenant_portal
│  │      │  ├── authenticationManager-config.properties
│  │      │  ├── compound-permissions-mapping-custom.properties
│  │      │  ├── compound-permissions-mapping-internal.properties
│  │      │  ├── compound-permissions-mapping.properties
│  │      │  ├── console-config.properties
│  │      │  ├── custom-permissions-mapping.properties
│  │      │  ├── dynamic-permissions-checks-custom.properties
│  │      │  ├── dynamic-permissions-checks.properties
│  │      │  ├── keycloak-oidc.json
│  │      │  ├── keycloak-saml.xml
│  │      │  ├── resources-permissions-mapping-custom.properties
│  │      │  ├── resources-permissions-mapping-internal.properties
│  │      │  ├── resources-permissions-mapping.properties
│  │      │  ├── security-config.properties
│  │      │  ├── spnego-config.properties
│  │      │  ├── user-creation-attribute-mapping-custom.properties
│  │      │  ├── user-creation-attribute-mapping.properties
│  │      │  ├── user-creation-group-mapping.properties
│  │      │  └── user-creation-group-profile-mapping.properties
│  │      └── tenant_security_scripts
│  │          └── SamplePermissionRule.groovy.sample
│  ├── tenant_template_engine
│  │  ├── bonita-tenant-community-custom.properties
│  │  ├── bonita-tenants-custom.xml
│  │  ├── bonita-tenant-sp-cluster-custom.properties
│  │  ├── bonita-tenant-sp-custom.properties
│  │  └── bonita-tenant-sp-custom.xml
│  ├── tenant_template_portal
│  │  ├── authenticationManager-config.properties
│  │  ├── compound-permissions-mapping-custom.properties
│  │  ├── compound-permissions-mapping-internal.properties
│  │  ├── compound-permissions-mapping.properties
│  │  ├── console-config.properties
│  │  ├── custom-permissions-mapping.properties
│  │  ├── dynamic-permissions-checks-custom.properties
│  │  ├── dynamic-permissions-checks.properties
│  │  ├── keycloak-oidc.json
│  │  ├── keycloak-saml.xml
│  │  ├── resources-permissions-mapping-custom.properties
│  │  ├── resources-permissions-mapping-internal.properties
│  │  ├── resources-permissions-mapping.properties
│  │  ├── security-config.properties
│  │  ├── spnego-config.properties
│  │  ├── user-creation-attribute-mapping-custom.properties
│  │  ├── user-creation-attribute-mapping.properties
│  │  ├── user-creation-group-mapping.properties
│  │  └── user-creation-group-profile-mapping.properties
│  └── tenant_template_security_scripts
│      └── SamplePermissionRule.groovy.sample
├── initial
│  ├── platform_engine
│  │  ├── bonita-platform-community-custom.properties
│  │  ├── bonita-platform-custom.xml
│  │  ├── bonita-platform-sp-cluster-custom.properties
│  │  ├── bonita-platform-sp-custom.properties
│  │  ├── bonita-platform-sp-custom.xml
│  │  └── hazelcast.xml
│  ├── PLATFORM_ENGINE_VERSION
│  ├── platform_portal
│  │  ├── cache-config.xml
│  │  ├── platform-tenant-config.properties
│  │  └── security-config.properties
│  ├── tenant_template_engine
│  │  ├── bonita-tenant-community-custom.properties
│  │  ├── bonita-tenants-custom.xml
│  │  ├── bonita-tenant-sp-cluster-custom.properties
│  │  ├── bonita-tenant-sp-custom.properties
│  │  └── bonita-tenant-sp-custom.xml
│  ├── tenant_template_portal
│  │  ├── authenticationManager-config.properties
│  │  ├── compound-permissions-mapping-custom.properties
│  │  ├── compound-permissions-mapping-internal.properties
│  │  ├── compound-permissions-mapping.properties
│  │  ├── console-config.properties
│  │  ├── custom-permissions-mapping.properties
│  │  ├── dynamic-permissions-checks-custom.properties
│  │  ├── dynamic-permissions-checks.properties
│  │  ├── keycloak-oidc.json
│  │  ├── keycloak-saml.xml
│  │  ├── resources-permissions-mapping-custom.properties
│  │  ├── resources-permissions-mapping-internal.properties
│  │  ├── resources-permissions-mapping.properties
│  │  ├── security-config.properties
│  │  ├── spnego-config.properties
│  │  ├── user-creation-attribute-mapping-custom.properties
│  │  ├── user-creation-attribute-mapping.properties
│  │  ├── user-creation-group-mapping.properties
│  │  └── user-creation-group-profile-mapping.properties
│  └── tenant_template_security_scripts
│      └── SamplePermissionRule.groovy.sample
├── licenses
│  └── team-license-21230624-10.2-003-enterprise.lic
└── sql
    ├── h2
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  ├── postCreateStructure.sql
    │  └── preDropStructure.sql
    ├── mysql
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  ├── postCreateStructure.sql
    │  └── preDropStructure.sql
    ├── oracle
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  ├── postCreateStructure.sql
    │  └── preDropStructure.sql
    ├── postgres
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  ├── postCreateStructure.sql
    │  └── preDropStructure.sql
    └── sqlserver
        ├── cleanTables.sql
        ├── createQuartzTables.sql
        ├── createTables.sql
        ├── dropQuartzTables.sql
        ├── dropTables.sql
        ├── initTables.sql
        ├── postCreateStructure.sql
        └── preDropStructure.sql
----
====

.From 2025.1 (10.3) and above
[%collapsible]
====
Content of the `setup/` folder:

[source,shell]
----
platform_conf
├── current
│  ├── platform_engine
│  │  ├── bonita-platform-community-custom.properties
│  │  ├── bonita-platform-custom.xml
│  │  ├── bonita-platform-sp-cluster-custom.properties
│  │  ├── bonita-platform-sp-custom.properties
│  │  ├── bonita-platform-sp-custom.xml
│  │  └── hazelcast.xml
│  ├── platform_portal
│  │  ├── cache-config.xml
│  │  └── security-config.properties
│  ├── tenant_engine
│  │  ├── bonita-tenant-community-custom.properties
│  │  ├── bonita-tenants-custom.xml
│  │  ├── bonita-tenant-sp-cluster-custom.properties
│  │  ├── bonita-tenant-sp-custom.properties
│  │  └── bonita-tenant-sp-custom.xml
│  ├── tenant_portal
│  │  ├── authenticationManager-config.properties
│  │  ├── compound-permissions-mapping-custom.properties
│  │  ├── compound-permissions-mapping-internal.properties
│  │  ├── compound-permissions-mapping.properties
│  │  ├── console-config.properties
│  │  ├── custom-permissions-mapping.properties
│  │  ├── dynamic-permissions-checks-custom.properties
│  │  ├── dynamic-permissions-checks.properties
│  │  ├── keycloak-oidc.json
│  │  ├── keycloak-saml.xml
│  │  ├── resources-permissions-mapping-custom.properties
│  │  ├── resources-permissions-mapping-internal.properties
│  │  ├── resources-permissions-mapping.properties
│  │  ├── security-config.properties
│  │  ├── spnego-config.properties
│  │  ├── user-creation-attribute-mapping-custom.properties
│  │  ├── user-creation-attribute-mapping.properties
│  │  ├── user-creation-group-mapping.properties
│  │  └── user-creation-group-profile-mapping.properties
│  └── tenant_security_scripts
│      └── SamplePermissionRule.groovy.sample
├── initial
│  ├── platform_engine
│  │  ├── bonita-platform-community-custom.properties
│  │  ├── bonita-platform-custom.xml
│  │  ├── bonita-platform-sp-cluster-custom.properties
│  │  ├── bonita-platform-sp-custom.properties
│  │  ├── bonita-platform-sp-custom.xml
│  │  └── hazelcast.xml
│  ├── PLATFORM_ENGINE_VERSION
│  ├── platform_portal
│  │  ├── cache-config.xml
│  │  └── security-config.properties
│  ├── tenant_engine
│  │  ├── bonita-tenant-community-custom.properties
│  │  ├── bonita-tenants-custom.xml
│  │  ├── bonita-tenant-sp-cluster-custom.properties
│  │  ├── bonita-tenant-sp-custom.properties
│  │  └── bonita-tenant-sp-custom.xml
│  ├── tenant_portal
│  │  ├── authenticationManager-config.properties
│  │  ├── compound-permissions-mapping-custom.properties
│  │  ├── compound-permissions-mapping-internal.properties
│  │  ├── compound-permissions-mapping.properties
│  │  ├── console-config.properties
│  │  ├── custom-permissions-mapping.properties
│  │  ├── dynamic-permissions-checks-custom.properties
│  │  ├── dynamic-permissions-checks.properties
│  │  ├── keycloak-oidc.json
│  │  ├── keycloak-saml.xml
│  │  ├── resources-permissions-mapping-custom.properties
│  │  ├── resources-permissions-mapping-internal.properties
│  │  ├── resources-permissions-mapping.properties
│  │  ├── security-config.properties
│  │  ├── spnego-config.properties
│  │  ├── user-creation-attribute-mapping-custom.properties
│  │  ├── user-creation-attribute-mapping.properties
│  │  ├── user-creation-group-mapping.properties
│  │  └── user-creation-group-profile-mapping.properties
│  └── tenant_security_scripts
│      └── SamplePermissionRule.groovy.sample
├── licenses
│  └── team-license-21230624-10.2-003-enterprise.lic
└── sql
    ├── h2
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  └── preDropStructure.sql
    ├── mysql
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  └── preDropStructure.sql
    ├── oracle
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  └── preDropStructure.sql
    ├── postgres
    │  ├── cleanTables.sql
    │  ├── createQuartzTables.sql
    │  ├── createTables.sql
    │  ├── dropQuartzTables.sql
    │  ├── dropTables.sql
    │  ├── initTables.sql
    │  └── preDropStructure.sql
    └── sqlserver
        ├── cleanTables.sql
        ├── createQuartzTables.sql
        ├── createTables.sql
        ├── dropQuartzTables.sql
        ├── dropTables.sql
        ├── initTables.sql
        └── preDropStructure.sql
----
====

[WARNING]
====
If you're starting Bonita with the Docker image and using custom scripts, please check the scripts to make sure they use the new file structure. +
Otherwise, script execution may fail, preventing Bonita from starting.

The changes mainly involve removing `_template` from the Bonita paths used in scripts.
====


== Support matrix changes

=== Ubuntu update

Support for Ubuntu has been updated to version **24.04**. See xref:runtime:hardware-and-software-requirements.adoc[hardware and software requirements] for the full matrix support.


== Deprecations and removals

=== API deprecations

As part of the multi-tenancy remove, some APIs have been deprecated and will be removed in the future:

* com.bonitasoft.engine.api.APIClient
** getLoginAPI
** 2 login methods using a tenantId parameter
* com.bonitasoft.engine.api.TenantAPIAccessor#getLoginAPI

=== API removals

==== Command API

Up to 2024.3, you could implement custom commands by inheriting either from the `org.bonitasoft.engine.api.TenantCommand` interface or from the `org.bonitasoft.engine.command.PlatformCommand` interface. With multitenancy removal, those two commands have been merged into `org.bonitasoft.engine.command.RuntimeCommand` +
If you have not done it yet, recompile your custom commands by changing parent class to `RuntimeCommand`, https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#unregister(long)[unregister] the previous one and https://javadoc.bonitasoft.com/api/{javadocVersion}/org/bonitasoft/engine/api/CommandAPI.html#register(java.lang.String,java.lang.String,java.lang.String)[register] the new one.

==== Platform API

The following deprecated methods have been removed:

* com.bonitasoft.engine.api.PlatformAPI#updateTenant()
* com.bonitasoft.engine.api.PlatformAPI#getDefaultTenantId()

Deprecated method org.bonitasoft.engine.platform.Platform#getPreviousVersion() has been removed.

==== REST API

* Deprecated resource `system/tenant` has been removed. You can use API {openApiUrl}/{openApiLatestVersion}#tag/Maintenance[system/maintenance] instead to enable/disable maintenance mode.
* Deprecated attribute isHidden has been removed from the resource `portal/page`
* Deprecated attribute iconPath has been removed from the resource `living/application`

=== EntityMember (aka. External Identity Mapping)

This concept has been completely removed because the associated feature was not used internally and was not documented.
It was used to map arbitrary external IDs to Bonita identity (user, group, role, membership). +
Event keys EXTERNAL_IDENTITY_MAPPING_CREATED and EXTERNAL_IDENTITY_MAPPING_DELETED have been removed from the event API and cannot be listened to anymore.


=== Custom component changes

If you used custom Spring beans, to customize Bonita event handlers, authentication, authorization rules, etc., you may need to update your code and your bean configuration to adapt to the removal of the tenant notion. +
Check the following configuration files:

* bonita-tenants-custom.xml
* bonita-tenant-sp-custom.xml
* bonita-platform-custom.xml
* bonita-platform-sp-custom.xml

for customizations you may have done there. In particular, if you have inherited from Bonita Spring beans with specialized behaviour, make sure the `tenantId` constructor parameter is removed from the bean definition. If relevant, redeploy a fixed version of your custom component and change its declaration.


=== Configuration changes

==== JAAS / CAS SSO configuration

With the removal of the multi-tenancy feature, the configuration of the xref:identity:active-directory-or-ldap-authentication.adoc[JAAS] / xref:identity:single-sign-on-with-cas.adoc[CAS] SSO has been simplified. +
The notable change is that the configuration module is now named `BonitaAuthentication` (without `-<TENANT_ID>` suffix). +

==== Ldap Synchronizer configuration

With the removal of the multi-tenancy feature, the configuration of the xref:identity:ldap-synchronizer.adoc[LDAP Synchronizer] has been simplified. +
The notable changes are:

- in the `bonita.properties` configuration file, the `technicalPassword`, `technicalUser` and `tenantId` properties are no longer used
- when using the Docker image, the `BONITA_PLATFORM_LOGIN`, `BONITA_PLATFORM_PASSWORD` and `BONITA_TENANT_ID` environment variables are no longer used



== Bug fixes

=== Fixes in Bonita 2025.1-u4 (2026-02-24)

* BPA-206 - LASTUPDATEDATE of rows in the flownode_instance table is not updated
* BPA-278 - Bonita Administrator Application - License page is broken
* BPA-294 - Docker: Slow reverse DNS lookups with ProGrade security manager cause delays on HTTP requests
* Several dependencies updated

=== Fixes in Bonita 2025.1-u3 (2026-01-12)

* xref:security:java-security-policy.adoc[Java Security Policy] is now enabled by default in Docker image (Subscription editions only). This security feature protects against malicious Groovy script execution, including command execution and access to sensitive files. +
*Note:* The xref:process:script.adoc[System script connector] will not work when this policy is active. Set `PRO_GRADE=false` to disable if needed (not recommended).
* BPA-141 - Process diagram (Case visu) shows whitespace on top when the process is not first in the diagram.
* BPA-178 - UiPath connector fails with java.lang.NoSuchFieldError
* BPA-189 - Studio Extra long build duration compare to previous version
* BPA-204 - Classloader initialisation fails because of a hardcoded 5-minutes timeout
* BPA-215 - [OIDC][Cluster] Parallel token refresh race condition and failure to save new tokens
* BPA-220 - session_user missing from access logs when cluster mode is enabled
* BPA-244 - [OIDC][CORS] Allowed origins verification fails with opaque tokens (it assumes access token is a JWT)
* BPA-256 - Bonita Usage Metrics Plugin: Duplicate Requests
* BPA-266 - Incorrect counting of active sessions in tomcat.sessions.active.current
* BPA-271 - UiPath connector does not support OAuth2 authentication to connect to UiPath Cloud
* CVE-120 - SQL Server JDBC driver - Improper input validation (fixing CVE-2025-59250)
* CVE-123 - Apache Tomcat - Console manipulation via escape sequences in log messages (fixing CVE-2025-55754)
* CVE-124 - RCE through admin resources upload or admin process script update
* CVE-125 - OWASP Java HTML sanitizer - XSS via noscript tag and improper sanitization in style tags (fixing CVE-2025-66021)
* CVE-126 - postgresql JDBC Driver - Channel binding option in pgJDBC may allow local network attackers to perform man-in-the-middle (fixing CVE-2025-49146)
* CVE-128 - Bouncy Castle for Java - bcpkix, bcprov, bcpkix-fips on All (API modules) allows Excessive Allocation (fixing CVE-2025-8916)
* Several dependencies updated

=== Fixes in Bonita 2025.1-u1 (2025-11-03)

* BPA-144 - [SSO] OIDC access tokens refresh is failing when the token is opaque (non JWT)
* BPA-187 - Engine fails to start with Access edition license or with invalid license
* BPA-200 - Ongoing case's visualisation doesn't display any status regarding the flownode execution when start event is a Timer
* BPA-209 - Generate Request Key fails in the Docker image with the error "Invalid Java version 21"

=== Fixes in Bonita 2025.1-u0 (2025-09-30)

==== Fixes in Bonita Runtime (including Bonita Applications)

* CVE-104 - Apache Tomcat - DoS via excessive HTTP/2 streams (fixing CVE-2025-53506)
* CVE-105 - Apache Tomcat - APR/Native Connector crash leading to DoS (fixing CVE-2025-52434)
* BPA-135 - [SSO] Refreshing a UIB app page when the session is expired triggers a redirect to login.jsp
* BPA-144 - [SSO] OIDC access tokens refresh is failing when the token is opaque (non JWT)
* RUNTIME-28 - The deletion of a running process instance leaves lines in the DOCUMENT table. +
Before this fix, when a process instance was deleted, the documents associated with it were not deleted. As a consequence, this behavior creates orphan documents that are unused and not linked to any other object. Note that it was not the case for archived process instances where documents were correctly deleted. +
If you have a lot of orphan documents in your database, you can use the latest version of the xref:ROOT:purge-tool.adoc#delete-orphan-document-content[Purge Tool] to remove them.
* RUNTIME-44 - NPE when iterating on multiple BDM objects in event subprocess
* RUNTIME-1786 - When updating an SCA application with profiles mapping, the log is incorrect
* RUNTIME-1870 - REST API: JSON in the HTTP GET response cannot be parsed `/API/bpm/caseInfo/+{id}+`
* RUNTIME-1885 - Unnecessary queries on application_* tables each time we navigate to a page
* RUNTIME-1889 - Super Admin App page is refreshed for each page switch
* RUNTIME-1911 - Using tenantid column in index causing query performance degradation
* RUNTIME-1919 - Email connector fails if it includes an attachment
* RUNTIME-1923 - REST API extension Fails on Second Call on `context.apiClient.getDAO`
* RUNTIME-1932 - Cancelled and Aborted process instances are not returned when using the REST API (bpm/archivedCase)
* RUNTIME-1940 - Process instance connectors may be displayed in task details page
* RUNTIME-1947 - Oracle/MS SQL Server Deadlock Occurring During Mass Task Completion/Cancellation

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4477 - Some reserved keywords (limit) are missing during validation on Business Data Attributes
* STUDIO-4516 - Errors at .bos file import and migration
* STUDIO-4520 - Old version Git repository clone fails with NullPointerException during the execution of bonita-project-maven-plugin:create-bdm-module if local .m2/repository/ is empty
* STUDIO-4543 - Rest API Extension validation fails with NPE when project folder and artifactId does not match
* STUDIO-4547 - Git repository clone fails when migrating a project which has already been cloned in the workspace.
* STUDIO-4548 - After migration RestApi Extension fails with "org.bonitasoft.engine.bdm.BusinessObjectDaoCreationException: java.lang.ClassNotFoundException: com.md.model.WOMSOrderDAOImpl"
* STUDIO-4551 - Bonita Project Analyze Plugin Market Type error
* UID-732 - $form.$invalid x Tabs container : the Submit button is enabled when the widgets' Required of the current tab have a value, and even if there are empty Required widgets in other tabs
* UID-737 - Japan first day of the week is sunday (0 zero) -> FIRSTDAYOFWEEK has a wrong value in the localization.json file
