= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
The {bonitaVersion} version is in development.
====

== Bonita UI Builder

Available in all Scale subscription and as a payable add-on in Convert subscriptions only. Connect with our dedicated sales team to start your upgrade journey today!

== New available values

=== Application Links

You can now use application links. See xref:applications:bonita-ui-builder.adoc[Applications with Bonita UI Builder] for more details. Community users can also integrate their own links for applications developed with other tools.
See xref:applications:faq.adoc[FAQ] for common problems and solutions (e.g. if you use a customized or an old layout).

xref:api:engine-api-overview.adoc[Engine APIs] that allowed applications manipulation still work with legacy applications and have been deprecated in favor of new APIs that manipulate both application links and legacy applications.

xref:api:rest-api-overview.adoc[REST APIs] (see _Application_ section) now also return application links in addition of legacy applications.

== Bug fixes

=== Fixes in Bonita 2024.3 (! DATE TO ADD HERE !)

==== Fixes in Bonita Runtime (including Bonita Applications)

==== Fixes in Bonita Studio (including Bonita UI Designer)
