= Release notes
:description: Bonita release note

[NOTE]
====
The 2022.1 is in development.
====

== New values added

== Improvements

== Functional changes

=== Prometheus monitoring active by default (Subscription editions)

From Bonita 2022.1, xref:runtime-monitoring.adoc#_prometheus_publisher[the Prometheus metrics publisher] is now active by default, and can be disabled if needed. +
Its access is now protected with Basic Auth authentication to protect against DOS attacks. +
Thus, when reaching the prometheus metrics endpoint, typically https://localhost:8080/bonita/metrics, you will have to manually enter the configured username and password information for your access to be granted.

These credentials can be consulted and modified:

* in the <BONITA>/server/conf/tomcat-users.xml file in a *Bonita Tomcat bundle*
* using xref:bonita-docker-installation.adoc#_monitoring_username[specific Environment parameters] when starting a *Bonita Docker image*

== Technical updates

=== Docker image

Folder structure inside Bonita Docker images has been simplified: instead of having /opt/bonita/BonitaCommunity-{bonitaVersion} or /opt/bonita/BonitaSubscription-{bonitaVersion}, we now simply have */opt/bonita*. +
If you have scripts using the former folder structure, please update them.

The docker image does not create the database schema and the associated user anymore. The database must be created before the image starts. We provide pre-configured database images with already created existing schema and users https://hub.docker.com/r/bonitasoft/bonita-postgres

As a consequence, the following environment properties were removed:

* `ENSURE_DB_CHECK_AND_CREATION`
* `DB_DROP_EXISTING`
* `BIZ_DB_DROP_EXISTING`
* `DB_ADMIN_USER`
* `DB_ADMIN_PASS`

To rationalize the Bonita configuration variables, some properties have been renamed:

* [.line-through]#`REST_API_DYN_AUTH_CHECKS`# flag is replaced by `COM_BONITASOFT_ENGINE_AUTHORIZATION_REST_DYNAMIC_CHECK_ENABLE`. See xref:runtime:bonita-docker-installation.adoc#dynamic-check-enable[dedicated section] for details.

== Feature deprecations and removals

== Bug fixes

== Known issues