= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

== Bonita UI Builder

We are excited to announce the release of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder], our new and enhanced development environment for creating all kind of interfaces, pages and forms for your applications! It brings along a host of advanced features and improved usability, designed to help you create compelling, responsive, and user-friendly interfaces.

Key benefits:

* Rapidly create and deploy UIs to reduce time to market
* Connect UIs with Bonitasoft for end-to-end alignment
* Tailor UIs to specific needs with advanced options
* A drag-and-drop interface empowers all users, regardless of technical skill
* Built with React for dynamic, responsive design

Features include:

* Drag & drop tools, 45+ widgets, React interfaces
* Code completion, custom JavaScript, native debugging
* Full Bonita Runtime compatibility

You can continue to use Bonita UI Designer as usual, while also having the opportunity to explore and get familiar with the capabilities of Bonita UI Builder.

Eventually, Bonita UI Designer will be phased out as we progressively transition to Bonita UI Builder. Rest assured, we are committed to providing comprehensive support and resources throughout this process. Our goal is to make this transition as smooth as possible, minimizing any disruption to your workflow.

Here’s what you can expect during this transition period:

* Continued access: Bonita UI Designer will remain fully operational for an extended period, allowing ample time for adaptation
* Support and resources: We offer extensive documentation, tutorials, and support to help you make the most of xref:applications:bonita-ui-builder.adoc[Bonita UI Builder]
* Facilitated transition: We are dedicated to facilitate the transition, with detailed guides on how to use Bonita UI Builder, as well as https://www.bonitasoft.com/professional-services/on-demand-services[professional services support]


== New available values

=== Application Links

You can now use application links. See xref:applications:bonita-ui-builder.adoc[Applications with Bonita UI Builder] for more details. Community users can also integrate their own links for applications developed with other tools.
See xref:applications:faq.adoc[FAQ] for common problems and solutions (e.g. if you use a customized or an old layout).

xref:api:engine-api-overview.adoc[Engine APIs] that allowed applications manipulation still work with legacy applications and have been deprecated in favor of new APIs that manipulate both application links and legacy applications.

xref:api:rest-api-overview.adoc[REST APIs] (see _Application_ section) now also return application links in addition of legacy applications.


== Support matrix changes

=== PostgreSQL update

Support for PostgreSQL has been updated to version **16.4**. See xref:runtime:hardware-and-software-requirements.adoc[hardware and software requirements] for the full matrix support.

=== Ubuntu update

Support for Ubuntu has been updated to version **22.04**. See xref:runtime:hardware-and-software-requirements.adoc[hardware and software requirements] for the full matrix support.

== Feature deprecations and removals

=== Database support

Due to the cost of maintenance of multiple DBMS, we are removing support for the following databases in the Community edition:

* MySQL
* Microsoft SQL Server
* Oracle

These databases will still be supported in Enterprise editions.

=== Deprecated APIs

==== License API

The Rest API `GET /API/platform/license` is now replaced by `GET /API/system/information`. This latter requires to be logged in as a user with the "Admin" profile. See {openApiUrl}/latest/#tag/Information/operation/getSystemInformation[dedicated Rest API documentation] for more details.

The corresponding Java API `com.bonitasoft.engine.api.PlatformAPI#getInformation()` is also deprecated and will be removed in a future release.

Note that this new API is now also available in the Community edition and provides information about the case counters limit and current consumption.


== Bug fixes

=== Fixes in Bonita 2024.3-u5 (2026-01-06)

* BPA-141 - Process diagram (Case visu) shows whitespace on top when the process is not first in the diagram
* BPA-144 - [SSO] OIDC access tokens refresh is failing when the token is opaque (non JWT)
* BPA-158 - UiPath connector does not support OAuth2 authentication to connect to UiPath Cloud
* BPA-200 - On-going case's visualisation doesn't display any status regarding the flownode execution when start event is a Timer
* BPA-204 - Classloader initialisation fails because of a hardcoded 5-minutes timeout
* BPA-215 - [OIDC][Cluster] Parallel token refresh race condition and failure to save new tokens
* BPA-220 - [Cluster] session_user missing from access logs when cluster mode is enabled
* BPA-244 - [OIDC][CORS] Allowed origins verification fails with opaque tokens (it assumes access token is a JWT)
* BPA-256 - [Cluster] Bonita Usage Metrics Plugin: Duplicate Requests
* BPA-266 - [Cluster] Incorrect counting of active sessions in tomcat.sessions.active.current

=== Fixes in Bonita 2024.3-u4 (2025-08-08)

* CVE-104 - Apache Tomcat - DoS via excessive HTTP/2 streams (fixing CVE-2025-53506)
* CVE-105 - Apache Tomcat - APR/Native Connector crash leading to DoS (fixing CVE-2025-52434)
* BPA-135 - [SSO] Refreshing a UIB app page when the session is expired triggers a redirect to login.jsp
* Several dependencies updates

=== Fixes in Bonita 2024.3-u3 (2025-06-25)

* CVE-81 - Apache Tomcat - DoS in multipart upload (fixing CVE-2025-48988)
* CVE-82 - Apache Tomcat - Security constraint bypass for pre/post-resources (fixing CVE-2025-49125)
* CVE-83 - Apache Commons FileUpload - Allocation of resources for multipart headers with insufficient limits enabled a DoS (fixing CVE-2025-48976)
* CVE-84 - Apache Commons BeanUtils - Insufficient input validation may lead to remote code execution (fixing CVE-2025-48734)

=== Fixes in Bonita 2024.3-u2 (2025-05-06)

==== Fixes in Bonita Runtime including Bonita Applications

* CVE-77 - Keycloak SAML adapter - Improper verification of SAML responses leading to impersonation attacks (fixing CVE-2024-8698)
* CVE-78 - Apache Tomcat - Potential RCE and/or information disclosure and/or information corruption with partial PUT (fixing CVE-2025-24813)
* RUNTIME-44 - NPE when iterating on multiple BDM object in event subprocess
* RUNTIME-1865 - When level 2 cache is enabled and Cluster disabled, two or more nodes connect via Hazelcast
* RUNTIME-1932 - Cancelled and Aborted process instances are not returns when using the REST API (bpm/archivedCase)
* RUNTIME-1947 - Oracle/MS SQL Server Deadlock Occurring During Mass Task Completion/Cancellation

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4520 - Old version Git repository clone fails with NullPointerException during the execution of bonita-project-maven-plugin:create-bdm-module if local .m2/repository/ is empty
* STUDIO-4566 - Studio freeze during check dependencies in Groovy console
* UID-732 - $form.$invalid x Tabs container : the Submit button is enabled when the widgets' Required of the current tab have a value, and even if there are empty Required widgets in other tabs

=== Fixes in Bonita 2024.3-u1 (2024-12-10)

==== Fixes in Bonita Runtime including Bonita Applications

* RUNTIME-1786 - When updating an SCA application with profiles mapping, the log is deceitful
* RUNTIME-1870 - REST API: JSON in the HTTP GET response cannot be parsed /API/bpm/caseInfo/\{id\}
* RUNTIME-1885 - Doubtful queries on application_* tables each time we navigate to a page
* RUNTIME-1889 - Super Admin App page is refreshed for each page switch
* RUNTIME-1911 - Using tenantid column in index causing query performance degradation

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4477  - Some reserved keyword (limit) are missing during validation on Business Data Attributes
* STUDIO-4516  - Errors at .bos file import and migration
* STUDIO-4540  - Cloning a community project into a Subscription studio should migrate the internal build for subscription
* STUDIO-4542  - Due to Maven archetype plugin update, rest api generation generates invalid test class
* STUDIO-4543  - Rest API Extension validation fails with NPE when project folder and artifactId does not match
* STUDIO-4547  - Git repository clone failed when migrating a project which has already been cloned in the workspace.
* STUDIO-4551  - Bonita Project Analyze Plugin Market Type error
* UID-732      - $form.$invalid x Tabs container : the Submit button is enabled when the widgets' Required of the current tab have a value, and even if there are empty Required widgets in other tabs

=== Fixes in Bonita 2024.3-b3 (2024/08/29)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-48 - SFlowNodeNotFoundException: Quartz's Trigger associated to a Boundary timer does not get deleted when the process instance terminates
* RUNTIME-1895 - [SAML & OIDC SSO]: Bonita redirects to IdP if redirected target URL request lands on different node than the one where the original request was received

=== Fixes in Bonita 2024.3-b2 (2024/07/26)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +
* RUNTIME-1877 - Session Sharing x sameSiteCookies value systematically set to "lax" when cluster is enabled. xref:runtime:install-a-bonita-bpm-cluster.adoc[New configuration properties] specific to cluster mode and session cookie have been added.
* RUNTIME-1883 - Add extra java 17 open packages instructions for Bundle packaging
* RUNTIME-1884 - `password` attribute silently removed from `org.bonitasoft.engine.identity.impl.UserImpl` class. Add removal information in the release note. Make the XStream deserialization less strict to avoid deserialization exception when a some fields are unknown.
* RUNTIME-1887 - Regression in ServerProxifier algorithm produce a greater number of SQL requests.
* RUNTIME-1890 - [LDAP Synchronizer] - Add add-opens for packaged scripts

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4517 - Old version Git repository clone fails with DirectoryNotEmptyException if REST API extension does not contain pom.xml file
* STUDIO-4515 	NPE generated during project migration
* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4530 - ResourceException at Studio 9.0.4 restart after a Switch Workspace to exisitng workspace from a 9.0.3
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
* STUDIO-4533 - Refreshing a project after a git switch branch now adds/removes submodules as expected.
* STUDIO-4535 - Renaming a project without bdm or extensions fails
* STUDIO-4536 - Hazecalst discovery is enabled by default for Studio embedded Runtime

=== Fixes in Bonita 2024.3-b1 (2024/07/04)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4517 - Old version Git repository clone fails with DirectoryNotEmptyException if REST API extension does not contain pom.xml file
* STUDIO-4515 	NPE generated during project migration
* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4530 - ResourceException at Studio 9.0.4 restart after a Switch Workspace to exisitng workspace from a 9.0.3
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
