= Release notes
:description: This is the release notes for Bonita {bonitaVersion} versions

[NOTE]
====
**Welcome to Our Latest Update!**

We are pleased to bring several exciting advancements in this release, including enhancements to our platform and a brand new entry-level offer designed to help new users seamlessly integrate with our technology.
====

== New available values

* [.underline]#Bonita Process Insights Release scope#

** Export tool: Enhancing our integration capabilities the Bonita data export tool, to enable import into BPI, is now compatible with our clients whose database is Oracle. This update enables easier data import into BPI, facilitating smoother transitions and better data management for our clients using Oracle.

* [.underline]#New User Interface Designer (UID)# Get ready for an exciting preview! We are preparing a demo of our new user interface. A beta version will be available in July, with a general availability (GA) launch planned for August. This update aims to enhance user experience and improve interface interactions.

* [.underline]#2024.2 Bonita Platform# → Introducing “Access” our new offer that make it easier than ever to start leveraging the powerful capabilities of Bonita

** **A New Beginning**: We are excited to introduce “Access”, our new entry-level offer tailored for new customers. This package is designed to help new users get started with our technology through a concentrated set of key features.

** **Eligibility** designed specifically for those new to Bonitasoft, this offer aims to make it easier than ever to start leveraging the powerful capabilities of Bonita

** **Easy start**: Access provides an easy and low-cost way to get started

** **Dedicated Support**: Choosing Access means partnering with us. We provide the support and resources you need, tailored to your specific requirements, ensuring you have the best start possible.

** **Regular Updates**: Stay up-to-date with the latest enhancements. Access ensures you always have the most current versions and features, keeping your operations efficient and cutting-edge.

** **Customization Options**: tailor Access to your needs with options for custom extensions, authentication mechanisms, and more, allowing you to shape our technology to fit your operational needs perfectly

== Bug fixes

=== Fixes in Bonita 2024.2-u7 (2026-01-07)

* xref:security:java-security-policy.adoc[Java Security Policy] is now enabled by default in Docker image (Subscription editions only). This security feature protects against malicious Groovy script execution, including command execution and access to sensitive files. +
*Note:* The xref:process:script.adoc[System script connector] will not work when this policy is active. Set `PRO_GRADE=false` to disable if needed (not recommended).
* BPA-141 - Process diagram (Case visu) shows whitespace on top when the process is not first in the diagram.
* BPA-144 - [SSO] OIDC access tokens refresh is failing when the token is opaque (non JWT)
* BPA-178 - UiPath connector fails with java.lang.NoSuchFieldError: Companion
* BPA-200 - On-going case's visualisation doesn't display any status regarding the flownode execution when start event is a Timer
* BPA-204 - Classloader initialisation fails because of a hardcoded 5-minutes timeout
* BPA-215 - [OIDC][Cluster] Parallel token refresh race condition and failure to save new tokens
* BPA-220 - session_user missing from access logs when cluster mode is enabled
* BPA-244 - [OIDC][CORS] Allowed origins verification fails with opaque tokens (it assumes access token is a JWT)
* BPA-256 - Bonita Usage Metrics Plugin: Duplicate Requests
* BPA-266 - Incorrect counting of active sessions in tomcat.sessions.active.current
* BPA-271 - UiPath connector does not support OAuth2 authentication to connect to UiPath Cloud
* CVE-120 - SQL Server JDBC driver - Improper input validation (fixing CVE-2025-59250)
* CVE-123 - Apache Tomcat - Console manipulation via escape sequences in log messages (fixing CVE-2025-55754)
* CVE-124 - RCE through admin resources upload or admin process script update
* CVE-125 - OWASP Java HTML sanitizer - XSS via noscript tag and improper sanitization in style tags (fixing CVE-2025-66021)
* CVE-126 - postgresql JDBC Driver - Channel binding option in pgJDBC may allow local network attackers to perform man-in-the-middle (fixing CVE-2025-49146)
* CVE-127 - Apache Commons Lang is vulnerable to Uncontrolled Recursion when processing long inputs (fixing CVE-2025-48924)
* CVE-128 - Bouncy Castle for Java - bcpkix, bcprov, bcpkix-fips on All (API modules) allows Excessive Allocation (fixing CVE-2025-8916)
* Several dependencies updated.

=== Fixes in Bonita 2024.2-u6 (2025-08-05)

* CVE-104 - Apache Tomcat - DoS via excessive HTTP/2 streams (fixing CVE-2025-53506)
* CVE-105 - Apache Tomcat - APR/Native Connector crash leading to DoS (fixing CVE-2025-52434)
* Several dependencies updated.

=== Fixes in Bonita 2024.2-u5 (2025-07-03)

* CVE-81 - Apache Tomcat - DoS in multipart upload (fixing CVE-2025-48988)
* CVE-82 - Apache Tomcat - Security constraint bypass for pre/post-resources (fixing CVE-2025-49125)
* CVE-83 - Apache Commons FileUpload - Allocation of resources for multipart headers with insufficient limits enabled a DoS (fixing CVE-2025-48976)
* CVE-84 - Apache Commons BeanUtils - Insufficient input validation may lead to remote code execution (fixing CVE-2025-48734)

=== Fixes in Bonita 2024.2-u4 (2025-04-30)

==== Fixes in Bonita Runtime including Bonita Applications

* CVE-77 - Keycloak SAML adapter - Improper verification of SAML responses leading to impersonation attacks (fixing CVE-2024-8698)
* RUNTIME-44 - NPE when iterating on multiple BDM object in event subprocess
* RUNTIME-1865 - When level 2 cache is enabled and Cluster disabled, two or more nodes connect via Hazelcast
* RUNTIME-1932 - Cancelled and Aborted process instances are not returns when using the REST API (bpm/archivedCase)
* RUNTIME-1947 - Oracle/MS SQL Server Deadlock Occurring During Mass Task Completion/Cancellation

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4520 - Old version Git repository clone fails with NullPointerException during the execution of bonita-project-maven-plugin:create-bdm-module if local .m2/repository/ is empty
* STUDIO-4566 - Studio freeze during check dependencies in Groovy console
* UID-732 - $form.$invalid x Tabs container : the Submit button is enabled when the widgets' Required of the current tab have a value, and even if there are empty Required widgets in other tabs

=== Fixes in Bonita 2024.2-u3 (2024-12-09)

==== Fixes in Bonita Runtime including Bonita Applications

* RUNTIME-1786 - When updating an SCA application with profiles mapping, the log is deceitful
* RUNTIME-1870 - REST API: JSON in the HTTP GET response cannot be parsed /API/bpm/caseInfo/\{id\}
* RUNTIME-1885 - Doubtful queries on application_* tables each time we navigate to a page
* RUNTIME-1889 - Super Admin App page is refreshed for each page switch
* RUNTIME-1911 - Using tenantid column in index causing query performance degradation

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4477  - Some reserved keyword (limit) are missing during validation on Business Data Attributes
* STUDIO-4516  - Errors at .bos file import and migration
* STUDIO-4540  - Cloning a community project into a Subscription studio should migrate the internal build for subscription
* STUDIO-4542  - Due to Maven archetype plugin update, rest api generation generates invalid test class
* STUDIO-4543  - Rest API Extension validation fails with NPE when project folder and artifactId does not match
* STUDIO-4547  - Git repository clone failed when migrating a project which has already been cloned in the workspace.
* STUDIO-4551  - Bonita Project Analyze Plugin Market Type error
* UID-732      - $form.$invalid x Tabs container : the Submit button is enabled when the widgets' Required of the current tab have a value, and even if there are empty Required widgets in other tabs

=== Fixes in Bonita 2024.2-u2 (2024-09-10)

==== Fixes in Bonita Runtime including Bonita Applications

* RUNTIME-48   - SFlowNodeNotFoundException: Quartz's Trigger associated to a Boundary timer does not get deleted when the process instance terminates
* RUNTIME-1845 - Oracle ORA-00060: deadlock detected when multiple cases are done simultaneously
* RUNTIME-1890 - [LDAP Synchronizer] - InaccessibleObjectException: Unable to make field private accessible
* RUNTIME-1895 - [SAML & OIDC SSO]: Bonita redirects to IdP if redirected target URL request lands on different node than the one where the original request was received

=== Fixes in Bonita 2024.2-u1 (2024-07-17)

==== Fixes in Bonita Runtime including Bonita Applications

* RUNTIME-1883 - Add extra java 17 open packages instructions for Bundle packaging
* RUNTIME-1697 - Avoid reading configuration from database, in favor to caching +
  Bonita Runtime makes heavy usage of *cache* to improve performance. In that context, most configuration changes require *server restart* to be taken into account. In particular, all SSO activations and configuration changes fall into this category (OIDC, SAML, Kerberos, JAAS, ...). +
* RUNTIME-1877 - Session Sharing x sameSiteCookies value systematically set to "lax" when cluster is enabled. xref:runtime:install-a-bonita-bpm-cluster.adoc[New configuration properties] specific to cluster mode and session cookie have been added.
* RUNTIME-1884 - `password` attribute silently removed from `org.bonitasoft.engine.identity.impl.UserImpl` class. Add removal information in the release note. Make the XStream deserialization less strict to avoid deserialization exception when a some fields are unknown.
* RUNTIME-1887 - Regression in ServerProxifier algorithm produce a greater number of SQL requests.

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4526 - Cannot add or edit a database connector
* STUDIO-4536 - Hazecalst discovery is enabled by default for Studio embedded Runtime
* STUDIO-4515 - Improve error management when migrating inconsistent project data
* STUDIO-4517 - Improve error management when migrating inconsistent project data
* STUDIO-4530 - ResourceException when using Switch Workspace from a 9.0.x
* STUDIO-4531 - Getting started tutorial not working out of the box in Subscription editions.
* STUDIO-4533 - Refreshing a project after a git switch branch now adds/removes submodules as expected.
* STUDIO-4535 - Renaming a project without bdm or extensions fails

=== Fixes in Bonita 2024.2 (2024-05-28)

==== Fixes in Bonita Runtime (including Bonita Applications)

* RUNTIME-1844 - Update Tomcat to latest 9.0.x
* RUNTIME-1848 - ArchivedTasks filter on type is generating java.lang.ClassCastException
* RUNTIME-1860 - Access Control panel is displayed on page in all subscription editions even when the feature is not active
* RUNTIME-1864 - SCA cannot be started without BDM_ACCESS_CONTROL license key activated
* CVE-63       - Upgrade Apache Tomcat version (fixing CVE-2024-24549)

==== Fixes in Bonita Studio (including Bonita UI Designer)

* STUDIO-4518 - Bdm Access Control / Profile menu item is not completely disabled if license key is not present
