= Release notes
:description: Bonita release note

[NOTE]
====
The 2023.2 version is in development.
====

== New available values

=== Bonita Runtime 

==== User session sharing between nodes (Cluster)

When configuring a xref:runtime:overview-of-bonita-bpm-in-a-cluster.adoc[Bonita cluster] (Enterprise and Performance editions only), HTTP sessions are now shared between all the nodes of the cluster. As a result, the load balancer no longer needs to be configured to use sticky sessions. If a node becomes unavailable, and a user request to this node fails, the user won't need to log back in as their session will remain active. The load balancer will dispatch the new requests to the other nodes.  


=== Development suite


=== Bonita UI Designer


== Functionnal changes

=== REST API and file upload

When using the end point `portal/fileUpload` to upload a file (in order to then use it in Bonita REST API or a REST API extension), the size of the file that can be uploaded is now limited to 25MB. This can be changed in the configuration file `console-config.properties` using the setup tool, but be aware that this will affect upload limit for all users (upload end points used for administration like process upload etc... are not affected by this limit). +
Using Bonita Runtime upload end points for large files (hundreds of MB) is not recommended as the database is used to store temporarily those files (and there can be a 1 or 2GB per file limit depending on the database vendor). Prefer using an external system if you need to manage very large files in your applications.

== Feature deprecations and removals

