= Run a process in Bonita Studio
:description: You can run a process from Bonita Studio. Bonita Studio includes a test environment with all the components required to execute a process.

{description}

When you run a process from Bonita Studio it runs on the local Bonita server. The server includes an Java application server (Tomcat), two databases (h2), and Bonita Runtime. Running a process from Bonita Studio is intended for testing during process development.

Before you can run a process, you must xref:configuring-a-process.adoc[configure the process]
and xref:organization-management-in-bonita-bpm-studio.adoc[configure the organization].

To run a process, you can :

* Right click on the process diagram on the project explorer, and select the process to run from the *run* menu.
* Open the process diagram and select the pool, then click *_Run_* in the Cool bar. The process in the selected pool runs. Only one pool can be run at a time.

If you are using the Enterprise, Performance, Efficiency, or Teamwork editions, you can select the environment in which to run the process. The
process must be configured for the environment in which it runs.