= Talend TIS Job launcher

NOTE:
*Note:* For Performance, Efficiency, and Teamwork editions only.


The Talend TIS Job launcher connector enables you to launch a Talend Integration Suite (TIS) job.

For example, if you are using Talend Integration Suite (TIS) to provide an integrated view of data from many data sources and a process updates one of those data sources, you could trigger a job to update the view.

The job is defined in TIS and specified by the id that was set when the job is created.

You cannot pass data through the connector to the job, and the connector does not return any output.

To configure the Talend TIS Job launcher connector, follow the steps in the wizard. To configure the job use the information below:

|===
| Input | Description | Type

| WSDL URL
| The URL of the TIS project, specified in webservice description language
| string

| Login
| The login of the job owner
| string

| Password
| The password of the job owner
| string

| Task id
| The id of the task to launch. The id is defined in TIS when the job is created
| string
|===

When the connector runs in a process instance, it triggers the specified job in your TIS system.
