= Themes

This page explains how to handle themes in Bonita Portal, and how to use it in an application.

A theme is an archive of files used to define and share CSS definitions and images for an application.
It enables you to specify the same style for all pages and layout of an application.
Each application can have its own theme, or the same theme can be consistently applied to several applications.

There are some examples of themes in Bonita Portal.

== Use in applications

Themes are linked to applications in application descriptors, in Bonita Studio. +
A theme can only be associated with an application to define the style. It cannot itself be used as a simple application page.

Themes are xref:resource-management.adoc[added, exported, edited, and deleted] as resources in Bonita Portal. +
In Non-Production or Production environements, a theme is imported as a .zip archive containing a `page.properties` file and a `resources` folder.

== Live Update

xref:live-update.adoc[Live update] allows the Administrator to update one element of the application in a situation of emergency.

=== Edit the layout

You can link:resource-management.md#modify[edit the content of a theme] by installing a new version.

=== Modify the pages in an application

You can link:applications.md#define-navigation[link another theme to an application] in the application descriptor.
