= Tomcat bundle installation
:description: You will find here steps needed to install and configure a Tomcat bundle.

You will find here steps needed to install and configure a Tomcat bundle.

The Tomcat bundle is a .zip archive that contains the Apache Tomcat JEE application server prepackaged along with Bonita BPM Portal and xref:BonitaBPM_platform_setup.adoc]#platform_setup_tool[Bonita configuration folder].
The Tomcat bundle is a regular .zip archive based on Tomcat zip distribution.

[WARNING]
====
 +
There is a known issue between Bitronix (the Transaction Manager shipped by Bonitasoft in the Tomcat bundle and in the Tomcat directories of the Deploy bundle) and the Microsoft SQL Server driver
(refer to: https://msdn.microsoft.com/en-us/library/aa342335.aspx[MSDN note], http://bitronix-transaction-manager.10986.n7.nabble.com/Failed-to-recover-SQL-Server-Restart-td148.html[Bitronix note]).
Therefore, using Bitronix as a Transaction Manager with SQL Server is not recommended. Our recommendation is to use the JBoss bundle provided by Bonitasoft.
====

== Installation of the Tomcat bundle

=== Download and unzip the Tomcat bundle

[#download]

==== Download

For the Community edition:

* Go to the http://www.bonitasoft.com/downloads-v2[Bonitasoft website] and get the Bonita BPM Community edition Tomcat bundle.

For a Subscription edition:

* Go to the https://customer.bonitasoft.com/download/request[Customer Portal] and download the Bonita BPM Subscription edition Tomcat bundle.

==== Unzip

The fully qualified folder path (including the BonitaBPM-x.y.z-Tomcat-7.0.67 folder) to the folder where you unzip the Tomcat bundle is referred to as `<TOMCAT_HOME>`. We recommend the following locations:

* Windows: `C:\BonitaBPM`.
* Linux: in `/opt/BonitaBPM`. Make sure that Linux user account used to execute Tomcat is the owner of the folders and files.

[WARNING]
====
 +
Whatever location you choose, do not leave blank spaces in the path to the directory, nor in the folder name.
====

==== Content of the Tomcat bundle

The Tomcat bundle is based on a standard Tomcat installation with the following additions:

* `bin/setenv.bat`: script to configure JVM system properties for Windows.
* `bin/setenv.sh`: script to configure JVM system properties for Linux.
* `bonita-start.bat`: script to start the bundle on Windows.
* `bonita-start.sh`: script to start the bundle on Linux.
* `bonita-stop.bat`: script to stop the bundle on Windows.
* `bonita-stop.sh`: script to stop the bundle on Linux.
* `conf/Catalina/localhost/bonita.xml`: Tomcat context configuration for Bonita web application. Define data sources used by Bonita Engine.
* `conf/bitronix-*.properties`: configuration files for Bitronix
* `catalina.properties`: modified to include lib/bonita folder to Tomcat classpath.
* `context.xml`: modified to add JTA support using Bitronix library.
* `logging.properties`: modified to create a log file dedicated to Bonita.
* `server.xml`: modified to add listener for Bitronix and h2 (see below for modification needed if you want to switch to another RDBMS).
* `lib/bonita`: extra libraries needed by Bonita. The following libraries are included: Bitronix JTA Transaction Manager, h2, SLF4J (required by Bitronix).
* `request_key_utils`: folder containing script to generate license request keys (Subscription editions only).
* `webapps/bonita.war`: the Bonita web application.

[NOTE]
====

Starting from Bonita BPM 7.3.0, Bonita BPM Platform configuration, including the license file, is stored in the same database as the Bonita BPM Engine data, namely in the `CONFIGURATION` table.
To initialize and update this configuration, a xref:BonitaBPM_platform_setup.adoc[_Platform setup tool_] is provided and embedded in Bonita BPM bundles.
====

So your bundle also contains:

* `setup`: database management for Bonita BPM Platform configuration and Bonita BPM Engine data, and a tool to update the configuration.

=== Get and install a license

[NOTE]
====

This is not necessary if you are installing the Community edition.
====

If you are installing a Subscription edition, you need to xref:licenses.adoc[request a license].

[#license]

When you receive your license:
If this is your first installation, copy the file to the `<TOMCAT_HOME>/setup/platform_conf/licenses` folder before starting the bundle.
If this is a license update, use xref:BonitaBPM_platform_setup.adoc]#update_platform_conf[the _Platform setup tool_].

[#edition_specification]

=== Edition specification

If you are installing the Performance Subscription edition, you need to edit xref:BonitaBPM_platform_setup.adoc[`setup/platform_conf/initial/platform_init_engine/bonita-platform-init-community-custom.properties`] by uncommenting the line and changing the value of the `activeProfiles` key to `'community,performance'`. No change is needed for the Community, Teamwork, or Efficiency edition.

[#configuration]

=== Configure the Tomcat bundle

[NOTE]
====

If you just want to try Bonita BPM Platform with the embedded h2 database (only for development phase of your project), you can skip the next paragraph.
For production, you are recommended to use one of the supported databases, with the following steps.
====

[#datasources_configuration]

==== Configure the Tomcat server datasources

Make sure your database is created before you start configuring the Tomcat datasources and make sure you do so before you start the Tomcat server.

If you use the xref:define-and-deploy-the-bdm.adoc[Business Data Model (BDM) feature], we recommend that you configure a dedicated database. +
You can also find more details on database configuration in the xref:database-configuration.adoc[dedicated page].

Follow those steps:

. Edit file `[TOMCAT_HOME]`/conf/ *server.xml* and remove (or comment out) the following line to deactivate embedded h2 database:
  `<Listener className="org.bonitasoft.tomcat.H2Listener" tcpPort="9091" baseDir="${org.bonitasoft.h2.database.dir}" start="true" />`
. Drop your database vendor-specific drivers in `[TOMCAT_HOME]`/lib/bonita (you can copy the provided open-source drivers: PostgreSQL, MySQL) from `[TOMCAT_HOME]/setup/lib`
. Edit file `[TOMCAT_HOME]`/conf/ *bitronix-resources.properties*
 .. Comment the default embedded h2 database configuration (preceding the lines with a #)
 .. Uncomment the configuration for your database vendor (PostgreSQL, Oracle, SQL Server, or MySQL)
 .. Change the default values for your database configuration to point to an existing database instance and valid credentials
  Warning: this must be done for 2 different datasources in the file: *resource.ds1.* (for engine and configuration data) and *resource.ds2.* (for BDM data, optional but handy to configure in case some day you need to use it)
. Edit file `[TOMCAT_HOME]`/conf/Catalina/localhost/ *bonita.xml*
 .. Comment the default embedded H2 database configuration (with `<!--` and `+-->+` around the lines to comment)
 .. Uncomment the configuration for your database vendor (PostgreSQL, Oracle, SQL Server, or MySQL)
 .. Change the default values for your database configuration to point to an existing database instance and valid credentials
  Warning: this must be done for 2 different datasources in the file: *bonitaSequenceManagerDS* (for engine and configuration data, same base as *resource.ds1.*) and *NotManagedBizDataDS* (for BDM data, same base as *resource.ds2.*)
. Edit file sentenv.sh (Unix system) or setenv.bat (Windows system)
 .. For engine and configuration data, change the *DB_OPTS* property and change the default *h2* value for the one corresponding to your database vendor
 .. For BDM data, change the *BDM_DB_OPTS* property and change the default *h2* value for the one corresponding to your database vendor

[#start]

=== Start and shut down Tomcat

==== Tomcat start script

Tomcat can be started by executing the following commands:

* Windows: `<TOMCAT_HOME>\bonita-start.bat`
* Linux: `<TOMCAT_HOME>/bonita-start.sh`

==== Shut down Tomcat

Tomcat can be shut down by executing the following command:

* Windows: `<TOMCAT_HOME>\bonita-stop.bat`
* Linux: `<TOMCAT_HOME>/bonita-stop.sh`

If you see `checkThreadLocalMapForLeaks` errors, the probably indicates that Tomcat is shutting down before all work threads are completed.
You can xref:performance-tuning.adoc[increase the work service termination timeout] to ensure that work is complete before shutdown.

[#post-install]

== After installation

=== First steps after installation

Once you have got your Tomcat bundle up and running a xref:first-steps-after-setup.adoc[few extra steps] are required in order to get a fully operational Bonita BPM platform.

=== How to update the configuration

To update the configuration after the first run please take a look at the xref:BonitaBPM_platform_setup.adoc]#update_platform_conf[platform setup tool]

[NOTE]
====

*Keep in mind* that xref:BonitaBPM_platform_setup.adoc]#configure_tool[platform setup tool] is independent from Tomcat Bundle and thus needs to be configured by itself to point to the right database.
This is done by editing file `database.properties`
====
