# Use for running a bonita-ui-builder during development.
services:
  bonita-ui-builder:
    image: ${IMAGE_NAME:-https://bonitasoft.jfrog.io/docker/bonita-ui-builder:1.0.0-beta.1}
    container_name: bonita-ui-builder
    environment:
      BONITA_API_URL: http://host.docker.internal:${BONITA_RUNTIME_PORT:-8080}/bonita/API
    ports:
      - "8090:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
