= Generate process documentation

::: info
*Note:* For Bonita BPM Performance, Efficiency, and Teamwork editions only.
:::

== Overview

When a process is open in Bonita BPM Studio, it is possible to generate documentation, containing a summary of individual elements in the process. This is like a process report. Choose the settings for the format of the export file, how the report will be presented, choose a logo to display and its size in pixels.

== What will be exported in the documentation?

You will see the elements contained in the process definition. The documentation generated contains:

* a description of BPMN elements
* an image of the process
* a list of activities
* tables showing groups, actors, tasks, sequence flows, connectors, data, data types, deadlines, dependencies, messages, message flows, and KPIs
* template settings

The following are not included in the generated documentation:

* contract definitions
* context information
* form mapping
* form information

The way the different elements in the process are presented on paper can be easily configured in a pop-up window, before exporting.

In the optional settings in the pop-up window, you can choose to:

* export the report in different formats: .pdf, .doc, .html, .rtf, .ppt
* show or hide a description of the BPMN elements
* change the colour of headings
* display your logo

== Generate process documentation

. Go to the Menu bar > Process.
. In the dropdown menu, click on _*Generate documentation*_.

A popup window will be displayed where you can configure a number of parameters for the exported file. +
In the optional settings in the pop-up window, you can choose to:

* export the report in .pdf, .doc, .html, .rtf, or .ppt format
* show or hide a description of the BPMN elements
* show or hide empty properties
* change the colour of the background for H1 and H2
* define the size of the logo in pixels (10-150 pixels)
* set the path where a logo is found on your computer, by browsing straight to it
* display a logo on the first page or on all pages
* Once the parameters have been set, click on the‚ Generate button to export the file

== Result

A report about the process will be generated and exported:

* in the format you chose
* with the presentation you chose
* to the place on your computer you chose
