= Migration to AngularJS 1.8
:page-aliases: ROOT:angularjs-18-migration.adoc
:description: Guidance to migrate your UI Designer pages, forms or custom widgets to AngularJS 1.8.

{description}

== Migration overview

[WARNING]
====
To enable AngularJS extended support, UI Designer has been migrated to the latest AngularJS version (1.8.0).
Your code can be potentially impacted by a breaking change, especially if you created custom widgets.
====

If you defined custom widgets, or added JavaScript assets to your UI elements, they should be migrated from AngularJS 1.3 to AngularJS 1.8.

[NOTE]
====
The https://docs.angularjs.org/guide/migration[Migrating an App to a newer version] AngularJS documentation describes all the migration details.
However, you will find below the most common changes to apply for your migration.
====

== Migrating custom widgets

If you defined custom widgets, you should check that:

* The Controller code, and the potential assets, does not contain deprecated $http callbacks ($http.success and $http.error)
* The Template does not contain ng-messages and ng-messages-include in the same <div> element

If you find such patterns, please change your code as follows:
(extract from https://docs.angularjs.org/guide/migration[Migrating an App to a newer version])

=== $http
Before:
``` javascript
$http(...).
success(function onSuccess(data, status, headers, config) {
  // Handle success
  ...
}).
error(function onError(data, status, headers, config) {
  // Handle error
  ...
});
```

After:
``` javascript
$http(...).
  then(function onSuccess(response) {
    // Handle success
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  }).
  catch(function onError(response) {
    // Handle error
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  });
```

=== ng-messages

Before:
``` html
<div ng-messages="$form[ctrl.name].$dirty && $form[ctrl.name].$error " ng-messages-include="forms-generic-errors.html" role="alert"></div>
```

After:
``` html
<div ng-messages="$form[ctrl.name].$dirty && $form[ctrl.name].$error ">
    <div ng-messages-include="forms-generic-errors.html" role="alert"></div>
</div>
```

== Migrating JavaScript assets

If you added some Javascript assets to one of your Page, Form or Layout, you should check:

* The Javascript code does not contain deprecated  $http callbacks ($http.success and $http.error)

To fix this, please apply the change describe above.
