= Migration to AngularJS 1.8
:page-aliases: ROOT:angularjs-1-8-migration.adoc
:description: Guidance to migrate your UI Designer pages, forms or custom widgets to AngularJS 1.8.

{description}

== Migration overview

[WARNING]
====
To enable AngularJS extended support, UI Designer has been migrated to the latest AngularJS version (1.8.2).
Your code may need to be updated, especially if you created custom widgets.
====

If you defined custom widgets, or added JavaScript assets to your UI elements, they should be migrated from AngularJS 1.3 to AngularJS 1.8.

[NOTE]
====
The https://docs.angularjs.org/guide/migration[Migrating an App to a newer version] AngularJS documentation describes all the migration details.
However, you will find below the most common changes to apply for your migration.
====

== Migrating custom widgets

You will find in this section some very common cases.
This is obviously not an exhaustive list, which can be found in the https://docs.angularjs.org/guide/migration[Migrating an App to a newer version] documentation.

If you defined custom widgets, you should check that:

* The *controller* code, and the potential assets, does not contain deprecated `$http` callbacks (`$http.success` and `$http.error`)
* The *template* does not contain `ng-messages` and `ng-messages-include` in the same `<div>` element

If you find such patterns, please change your code as follows:
(extract from https://docs.angularjs.org/guide/migration[Migrating an App to a newer version])

=== $http
Before:
``` javascript
$http(...).
success(function onSuccess(data, status, headers, config) {
  // Handle success
  ...
}).
error(function onError(data, status, headers, config) {
  // Handle error
  ...
});
```

After:
``` javascript
$http(...).
  then(function onSuccess(response) {
    // Handle success
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  }).
  catch(function onError(response) {
    // Handle error
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  });
```

=== ng-messages

Before:
``` html
<div ng-messages="$form[ctrl.name].$dirty && $form[ctrl.name].$error " ng-messages-include="forms-generic-errors.html" role="alert"></div>
```

After:
``` html
<div ng-messages="$form[ctrl.name].$dirty && $form[ctrl.name].$error ">
    <div ng-messages-include="forms-generic-errors.html" role="alert"></div>
</div>
```

== Migrating a page, form or layout

You will find in this section some very common cases.
This is obviously not an exhaustive list, which can be found in the https://docs.angularjs.org/guide/migration[Migrating an App to a newer version] documentation.

=== JavaScript assets

If you added some Javascript assets to one of your page, form or layout, you should check that:

* The JavaScript code does not contain deprecated `$http` callbacks (`$http.success` and `$http.error`)

To fix this, please apply the change described above.

=== Interpolation

Another possible issue is related to interpolation.
In a page, form or layout, if a property is bound to a variable which returns a json value, and you get the variable name instead of its json value,
you will have to apply a json filter.

Before:
``` html
<span>{{ myObject }}</span>
```

After:
``` html
<span>{{ myObject | json }}</span>
```

See https://docs.angularjs.org/guide/migration#-interpolate-[$interpolate] for details.

== Testing your application

Once the changes are done in all the UI elements impacted, you should deploy your application and fully test it.

In case of issue, you may be impacted by any other migration steps described in the https://docs.angularjs.org/guide/migration[Migrating an App to a newer version] documentation.
Please read it carefully, starting from https://docs.angularjs.org/guide/migration#migrating-from-1-3-to-1-4[Migrating from 1.3 to 1.4].
