= Pages
:page-aliases: ROOT:pages.adoc
:description: Pages are resources intended to be used in applications. A page presents information to a user or can also collect information entered by a user.

{description}
Displayed in a browser, a page is intended for use in applications.
They are xref:ROOT:resource-management.adoc[added, exported, edited, and deleted] as resources in the Bonita Administrator Application.


== Create a page

xref:ROOT:pages.adoc[Pages] are created independently from the processes. They are used to display business information that group several processes and several instances of the processes in an efficient view, a list of requests, for example. +
The controls they embed (buttons, links) can call BPM APIs that will trigger the display of the process instantiation form, or the execution of a task.

=== From scratch
. From Bonita Studio coolbar, click on the *_UI Designer_* icon to open the UI Designer. +
. Click on the *_Create_* button
. In the pop up, choose the element to create
. Give it a name
. Click on the *_Create_* button
. In the page editor, drag and drop the widgets, fragments, or BDM objects to create the right user interface

=== From an existing page
You can easily duplicate an exiting page just by saving it under a different name.

. From Bonita Studio coolbar, click on the *_UI Designer_* icon to open the UI Designer. +
. Open the page you want to duplicate
. Click on the *_Save_* button and select *_Save as_*
. In the pop up, choose the element to create (new page or form)
. Give it a name
. Click on the *_Save_* button

=== From a Bonita provided page

Only Bonita pages created with the UI Designer can be customized in the UI Designer. Indeed, as Bonita applications have evolved in several phases, so did the frameworks in which their pages have been made.

To customize a page provided by Bonita:

. From Bonita Studio coolbar, click on the *_Applications_* icon, and open the *_Administrator Application_*
. Go to the *_Resources_* menu, find the page, and and check its description to make sure it is a page done with Bonita UI Designer
. Export the page
. From Bonita Studio coolbar, click on the *_UI Designer_* icon to open Bonita UI Designer
. Import the page in the UI Designer

Note that by doing so, if the page embed fragments and custom widgets, they are also imported and added to the UI Designer palette.

You can find the list of pages ready for customization in a xref:ROOT:pages.adoc#_List_of_Bonita_Applications_customizable_pages[dedicated documentation page].

For more technical information about the pages, visit xref:ROOT:pages-development.adoc[the dedicated documentation page].







== Provided pages

Bonita Runtime comes with some provided pages to use in applications. They are wrapped pages developed in other technologies than Bonita UI Designer (AngularJS, React). +
Starting with Bonita 2021.1, you can also download Bonita User application and Bonita Administrator applications (from Bonita Studio Welcome page), and get more provided pages, developped with Bonita UI Designer. +
Such UI Designer pages can be customized in the UI Designer, to better fit the needs of the end-users.

=== List of Bonita Applications customizable pages

==== Bonita User Application

In this application, you can customize:

* Bonita User Case List `UserCaseListBonitaV_`
* Bonita User Case Details `UserCaseDetailsBonitaV_`

==== Bonita Administrator Applications

In thess applications, when relevant, you can customize:

* Bonita Admin Process List `adminProcessListBonitaV_`
* Bonita Admin Case Details `adminCaseDetailsBonitaV_`
* Bonita Admin Task List `adminTaskListBonitaV_`
* Bonita Admin Task Details `adminTaskDetailsBonitaV_`
* Bonita Admin User List `adminUserListBonitaV_`
* Bonita Admin Group List `adminGroupListBonitaV_`
* Bonita Admin Role List `adminRoleListBonitaV_`
* Bonita Admin Install Export Organization `adminInstallExportOrganizationBonitaV_`
* Bonita Admin Profile List `adminProfileListBonitaV_`
* Bonita Admin Resources List `adminResourceListBonitaV_`

The "_" in "V_" stands for the latest "version" of the resource.

[NOTE]
====
All the "Details" pages must be used as "orphan" pages in the application descriptor, since they need an id to be passed in order to display the details of the right item. They cannot be used at top-level menu.
====

== Custom pages

To create the perfect user experience for different profiles of applications users, you need to create custom pages. This can be done with Bonita UI Designer, or in your favorite IDE. +
A few examples of custom pages:

* Add a welcome page, with dashboards showing activity in Bonita and related external applications.
* Provide a process owner with a dashboard showing the activity of open cases of the process.
* Provide a busy user with a filtered view of the task list.
* Provide an administrator with a multi-attribute search facility.
* Integrate a page from an external application.

For all information about developping a custom page, visit xref:ROOT:pages-development.adoc[the dedicated documentation page].

== Use in applications

Once the pages are all made available in the Resources tab of Bonita Administrator Application, they can be used to xref:applications:application-creation.adoc[create applications]. +
We highly recommend that the creation of applications is done in Bonita Studio, to be managed with all the other resources of the project in the Version Control System (Git).

== Live update

xref:runtime:live-update.adoc[Live update] allows the Administrator to update one element of the application in a situation of emergency.

=== Edit a page

You can xref:ROOT:resource-management.adoc#modify[edit the content of a page] by installing a new version of a page.

=== Modify the pages in an application

You can modify the pages in an application by xref:runtime:applications.adoc#specify-pages[mapping other pages] in the application descriptor, and/or xref:runtime:applications.adoc#define-navigation[creating, moving, or deleting menus or menu options].

== Provided pages

You do not need to create all your pages from scratch. Bonita already provides some pages. +
Bonita Administrator Application "Resources" tab lists all the non-UI Designer-made pages, that can be reused "as-is" in an application.
By downloading the Bonita User and Administrator applications from Bonita Studio Welcome page, you also download Bonita pages created with Bonita UI Designer. +
Those pages can be customized and added to an application.

== Custom pages

A page resource has the general xref:ROOT:resource-management.adoc[resource definition].
If it contains an `Index.groovy` file, this must implement the PageController interface optionally with libraries.
If you create a custom page with Bonita UI Designer, its structure and content will be congruent by default.

A custom page is displayed inside an iframe to prevent conflicts between resources (for example JS and CSS) and those used in the custom page.
This also reduces the risk of migration issues, for example if a custom page uses a version of JQuery that gets updated.

=== PageController interface

[source,java]
----
public interface PageController {

/**
* Let the custom page parse request for specific attribute handling.
*
* @param request the HTTP servlet request intended to be used as in a servlet
* @param response the HTTP servlet response intended to be used as in a servlet
* @param pageResourceProvider provide access to the resources contained in the custom page zip
* @param pageContext provide access to the data relative to the context in which the custom page is displayed
*/
public void doGet(HttpServletRequest request, HttpServletResponse response, PageResourceProvider pageResourceProvider, PageContext pageContext);
}
----

=== Permissions for custom pages

If your custom page is an HTML page using the Web REST API,
you need to specify the xref:identity:rest-api-authorization.adoc[REST API authorizations] that a user needs to have in order to access the resources in the custom page.
These resource authorizations are defined in the `page.properties` file. If your custom page is written in Groovy and uses the Bonita Engine Java APIs, you do not need to specify any resource authorization.

For each REST resource accessed in the page, specify the authorization needed for each method used. +
You can find examples of the default resources in xref:runtime:bonita-platform-setup.adoc[`resources-permissions-mapping.properties`].

The following example shows the resource authorizations defined for a custom page that enables a user to view but not update organization information:

----
#The name must start with 'custompage_'
name=custompage_orgViewer
displayName=Organization viewer
description=Organization viewer page. You cannot modify the organization from this page.
resources=[GET|identity/user, GET|identity/personalcontactdata, GET|identity/professionalcontactdata, GET|identity/role, GET|identity/group, GET|identity/membership, GET|customuserinfo/user, GET|customuserinfo/definition, GET|customuserinfo/value]
----

When a user is given access to this page because they are in a profile that contains it or that is mapped to an application that contains the page, then this user is granted, upon login, the permissions associated to these resources (see xref:identity:rest-api-authorization.adoc[REST API authorizations] for more details).

=== Debugging a custom page in development

While you are developing a custom page, you can enable custom page debug mode. In debug mode, you can see changes to your custom page without importing a new .zip archive.

To enable custom page debug mode, edit xref:runtime:bonita-platform-setup.adoc[`console-config.properties`] and set `custom.page.debug` to `true`.

To work on a page in debug mode:

[NOTE]
====

On a Tomcat installation, `<java.io.tmpdir>` points to `<BUNDLE_HOME>/temp/`
====

. Import your custom page zip archive into the Bonita Administrator Application. This creates a directory `<java.io.tmpdir>/bonita_portal_*/tenants/tenant_id/pages/custompage_<your custom page>`.
. Publish the page to a profile, then log out and log in as a user having this profile.
. You can now update `Index.groovy` and the contents of the `lib` directory directly in `<java.io.tmpdir>/bonita_portal_*/tenants/tenant_id/pages/custompage_<your custom page>`.
. To view the page after you modify it, refresh the page in the browser.

When you have finished developing the page, recreate the custom page zip archive, and then modify the page to import it. This makes your final version of the page permanently available.

[NOTE]
====

In Bonita Studio, the debug mode is enabled by default. +
If you want to disable it, you need to use the setup tool provided in `workspace/tomcat/setup/` to update `console-config.properties` (Update the file database.properties first so it points to the target database. E.g.: h2.database.dir=../../default/h2_database).
====

=== Constraints

When you update to a newer version of Bonita, your custom page definition should still be valid.
However, this cannot be guaranteed for all future updates.

=== Page resources management

==== Page resources

Custom page resources can be accessed by a `PageResourceProvider`.

The `bonita.css` can be retrieved using `pageResourceProvider.getBonitaThemeCSSURL()`

Other `css/js` resources can be retrieved using `pageResourceProvider.getResourceURL("<path in the custom page resources folder>")`

If you are not using Groovy you can directly access a resource by adding a link in `index.html`.

For example: `<link href="css/file.css" rel="stylesheet" />`

==== API access

If your page is viewed in a custom profile or in an application, you will have access facilities for xref:ROOT:rest-api-overview.adoc[the REST API].

you will be able to access any REST API using the following path: `../API/{API name}/{resource name}`

==== Theme access

If your page is viewed in an application, you will have access facilities for xref:runtime:applications.adoc[the application theme].

The `Theme.css` is directly accessible by adding the following link in `index.html`: `<link href="../theme/theme.css" rel="stylesheet" />`
