= Organization management in Bonita Studio
:page-aliases: ROOT:organization-management-in-bonita-bpm-studio.adoc
:description: Organization is the set of users, groups and roles. It is used indirectly to define privileges for tasks execution, applications, API, etc.

{description}

Within Bonita Studio, more than one organization can be defined. This is useful if you are developing a process that will be deployed in several organizations. It is also useful for testing, because you can create a reduced version of your organization that has the same structure but fewer users, saving time in managing your test environment.

== The ACME example organization

Bonita Studio includes a sample organization, called ACME. This organization contains a small number of users, who belong to different groups, with realistic roles.

You can use this example organization to explore how to manage an organization in Bonita Studio, for example by adding a user, or changing the role of a user.

You can also use this sample organization to test a process that you develop.

== Creating an organization

You must load an organization into Bonita Engine before running a process. There are two ways to do this:

* Create the organization in Bonita Studio, export it, and then import it into Bonita Adminstration Application.
* If you have a Subscription edition, use the xref:ROOT:ldap-synchronizer.adoc[LDAP synchronizer] to automatically load information from your LDAP directory into Bonita Engine.

To specify an organization manually, you create the organization, create the group hierarchy, specify roles, and then add users and their memberships.

. Start Bonita Studio.
. Click on the *_New_* button in the cool bar and select *_Organization_*
 ** A new organization will be created with a placeholder name such as Organization1.
 ** Change the placeholder name to the name of your organization, and add a description.
. Go to the *_Group_* tab to add groups to your organization:
 ** Click *_Add_* to add a group. You can specify the following:
  *** the group Name, which is used internally by the Bonita software (*NB:* Bonita doesn't support the '/' character in the group name field. It is used as path separator.)
  *** the Display name, which is the name displayed in Bonita Applications
  *** the Path, which shows the hierarchical relationship between groups
  *** a Description of the group
 ** Click *_Add_* to add the next group, and continue until you have added all the groups required. Note that each time you add a group, it is added as a subgroup of the group that is currently selected (by default this is the last group added). You can change the group hierarchy by specifying the Path.
 ** When you have added all the groups you need, click *_Next_*.
. Specify roles in your organization:
 ** Click *_Add_*, and add a role called _member_. This will be the default role for users within a group.
 ** Click *_Add_* and add the other roles you require. Typically, most organizations have a Manager role so the group manager can be easily identified, but the specific roles you require will depend on your processes. Remember that it is not necessary to copy all the role information from your business organization into your Bonita organization, but instead you should just create the roles that are useful in processes.
 ** When you have specified all the roles the processes/applications require, click *_Next_*.
. Add users to your organization.
 ** Click *_Add_*. A default username is added to the list of users.
 ** You can change the username, but the value must be in a format Bonita can use: only unaccented alphanumeric characters are permitted plus a period (.). +
One option is to use the personal part of the user's email address, that is, the part before the @ sign.
 ** Specify a password for the user. The password characters are not displayed, so keep note of the password you choose.
 ** Specify the manager of the user.
 ** In the *General* tab, specify the Title, First name, Last name, and Job title of the user.
 ** In the *Membership* tab, specify the groups that the user belongs to, and what role they have in each group.
 ** You can also specify *Personal contact* and *Professional contact* information for the user.
. Add all the users needed to test your processes and applications.
. When you have finished, click *_Finish_*.

== Exporting and importing an organization

You can export an organization definition from Bonita Studio. The exported file is in XML format, so can be modified. +

You can import an organization definition in the XML file that was exported from another Bonita Studio running the same version of Bonita, or that was constructed by some other method but has the same format. +

Open the organization you want to export from the project explorer and click on *_Export_* in the top bar of the organization.

To prepare your production system (unless you are using the LDAP synchronizer), you must create the organization that you need for all the processes that will be deployed, export it from Bonita Studio, and import it into Bonita Applications. After the organization is imported into Bonita Applications, you can xref:ROOT:admin-application-groups-list.adoc[manage groups], xref:admin-application-roles-list.adoc[roles], and xref:admin-application-users-list.adoc[users] in the organization.

== Modifying an organization

To modify an organization, double click on it in the project explorer +
To modify an item in an organization, select it in the item list and modify the information on the right-hand side of the list. +
To delete an item, select and it click *_Remove_*.

== Deploying an organization to Bonita Runtime

Deploying an organization means uploading the organization data to the Bonita Runtime temporarily so that you can test your process. +
The organization that you deploy overwrites one in the Bonita Runtime.

[WARNING]
====

Importing an organization overwrites the existing organization in Bonita Runtime, and this could have an impact on deployed processes. Take the time to check and test those processes in order to avoid regressions.
====

To deploy the organization data:

. Open the corresponding organization in the project explorer.
. Click the *_Deploy_*, and
. Specify the username of the user that will be
used to log in to the Bonita User Application when a process is started from
Bonita Studio. This user must be in the organization you have
selected.
. Click *Deploy*.

== Profile management

In order to log in to bonita UIs (Bonita User Application, Bonita Administration Application, your applications...), a user must have at least one profile (User, Administrator...etc).

*_In Community_*, only provided profiles are supported (User and Administrator). When deploying an organization from the Studio, each user is automatically mapped to all those profiles.

*_In Teamwork edition_*, 3 provided profiles (User, Process Manager and Administrator) can be edited in the Studio using an XML editor (Go to Organization > Profiles > Open). For development purposes, all users mapped to role _member_ (cf _ACME_ organization) will benefit from all profiles in the Bonita Applications to let you log in with any of those users and test your processes.
This will not be true for other environments.

*_In Efficiency, Performance and Enterprise editions_*, in addition to provided profiles it is possible to defined custom profiles in the Studio using the xref:ROOT:profileCreation.adoc[Profile Editor].

When creating or importing other organizations, you need to make sure that all users are mapped to at least one profile, through a group, a role, a membership, or as a user, to grant them access to Bonita Applications or your applications.
