= Profile Editor
:page-aliases: ROOT:profileCreation.adoc, ROOT:profile-creation.adoc
:description: Build a profile to customize the user's environment, define page listing and who can access it.

{description}

== Definition

=== Fonctional

Profiles work as permissions to give access to xref:applications.adoc[Living Applications]

A profile is made of a name, a description, and a mapping with the organization entities.
When used to access a Living Application, the application menu is defined in the xref:applicationCreation.adoc[application descriptor] itself.

All applications can use the default profiles *Administrator* and *User*.

=== Technical

Technically, a *profile* is an XML file. +
Profiles are packaged in *files of profiles*. +
A *file of profiles* is an XML file containing one or more profiles.

[source,xml]
----
<!-- file of profiles -->
<profiles>
	<profile>
		<!--  First Profile -->
	</profile>
	<profile>
		<!--  Second Profile -->
	</profile>
</profiles>
----

However, profiles in a given file of profiles are totally *independent*.

Default profiles (Administrator and User) belong to the file `default_profiles.xml`.
This file can only contain default profiles. It cannot be renamed or deleted.
Neither can be the default profiles within: only the mapping between default profiles and entities of the organization can be edited.

Only Enterprise, Performance and Efficiency editions can create new file of profiles, in order to create custom profiles.

The purpose of grouping profiles in one file is to manage together profiles related to a same business application. +
For example, if you want to create a leave management application for four kinds of users (Employees, Managers, Human Resources officers, and Administrators), then you will have to create four applications and four profiles, and to bind each profile to the related application. As for the four applications, the four profiles should be managed together, and so grouped in the same file of profiles.

Files of profiles are also handy to be used in different environments: you can create different files, with the same profile names, but each profile is mapped to different entities of the organization depending on the target environment.
Therefore, you could have a "profiles_dev.xml", a "profiles_UAT.xml", and a "profiles_prod.xml" files of profiles.

== Create and edit a profile

[NOTE]
====

All Bonita subscription editions come with an .xml editor for this feature. Only Enterprise, Performance and Efficiency editions also come with a graphical UI.
====

From Bonita Studio, use the *new* button in the Studio coolbar or click on *Organization* \-> *Profile* \-> *New...*
It will create an empty file of profiles with a default name and open an editor. You can *rename* this file from the graphical UI, the project explorer or the menu *Open*.

The profile graphical UI provided is bound to the xml source, so you can use it to build your profile without writing xml. +
You can switch from the graphical UI to the xml source at any moment, using the tabs _Editor_ and _Source_ at the bottom of the editor. +
A toolbar is embedded to the editor, use it to:

* *Add* a profile to profiles file: you can add a new profile or duplicate an existing one from your current project
* *Save* profiles file *As* another profiles file (useful to duplicate the whole file)
* *Deploy* profiles (i.e all the profiles in this file) +
⚠  In _production_ environment, you still need to import REST API Extensions manually *before* importing profiles file.
* *Rename* profiles file
* *Export* profiles file (download the .xml)
* *Delete* profiles file from your current workspace
* *Manage* the Organization: add users / groups / roles to the organization in order to map them to this profile
* *Restore* the default file of profiles to its initial state (_only available for the file_ `default_profile.xml`)

Using the graphical editor, you can set all the parameters of your profile.

The *profile name* has to be unique in a given file of profiles, else it will lead to conflicts when you will try to deploy the file of profiles. +
You can duplicate a profile name in different files, but remember that you can only have one instance of a given profile in production.

In the mapping section you can map Users / Groups / Roles / Memberships to your profile. You have to map your profile with elements of an active organization. +
⚠  Nodes in the group tree are *independent* ⚠  It means that mapping `/acme` to your profile won't map `/acme/hr` to it. Each node has to be mapped individually to be taken into account. However, you can easily add a whole part of your organization, using the _add subtree_ button:  select a node in the tree, and then click on _add subtree_.

The Applications section provides quick access to the applications mapped to this profile. +
For adding an application to a profile, open the application and assign the required profile by using xref:applicationCreation.adoc[application descriptor editor].

== Enable a profile

To enable a profile, it must be installed into the Bonita Administrator Application. +
For development purposes, the Studio can *deploy* profiles into the Bonita Administrator Application for you (_only for Performance and Efficiency editions_). +
On a production environment, it is done via the menu:Organization[Profiles] tab of the Bonita Administrator Application.
