= Special users
:page-aliases: ROOT:special-users.adoc
:description: This page explains the three other ways to log into Bonita than with a regular profile: Technical Administrator (formerly named Tenant Admin), Platform Administrator, and Guest user.

{description}

== Platform administrator.

The platform is the part of the system that is common to all processes and running services. The platform administrator can manage {openApiUrl}/{openApiLatestVersion}/#tag/Platform[through the API] the platform level resources (including starting/stopping pausing/resuming all services of the platform). He can also access the license information (for Enterprise editions). +
Its username and password are defined in a configuration file and need to be changed for any other usage of a Bonita Tomcat bundle than local development (see
xref:runtime:tomcat-bundle.adoc#tomcat-bundle-installation[Bonita Tomcat bundle installation procedure] for more information on how to proceed.
Its default credentials are:

* username: `platformAdmin`
* password: `platform`

[#technical-user]
== Technical user

The Bonita platform has a technical administrator (formerly known as the *tenant technical user*) with a specific username and password. The technical administrator can manage the maintenance state for the tenant, install a Business Data Model, install the resources and the organization. +
Their username and password are defined in a configuration file (or through environment variables of system properties) and need to be changed for any other usage of a Bonita Tomcat bundle than local development (see
xref:identity:technical-admin-credentials.adoc[Technical admin credentials page] for more information on how to proceed.
Its default credentials are:

* username: `install`
* password: `install`

== Guest user

With enterprise editions, it is possible to allow public access to some living applications (without the need to sign in to Bonita).
When accessing a public application without any active session on Bonita platform the user will be automatically logged in with a guest user account. +
To know more about this feature, go to the xref:ROOT:guest-user.adoc[Guest user access documentation].
