= Bonita Engine Queriable logger
:page-aliases: ROOT:queriable-logging.adoc
:description: Queriable logger provides information about important events that happened in the Bonita Platform.

{description}

[NOTE]
====
For Subscription editions only.
====

== Purpose

The queriable logger service provides information about important events in the Bonita Platform that are not directly related to execution of a process. The log includes information about administration operations such as deployment of a new process definition, commands, reporting, actor mapping, and organization and user management.

The Bonita Engine stores information in the queriable log. The information in the log is accessible using the https://javadoc.bonitasoft.com/api/{javadocVersion}/index.html[LogAPI].

The information available from the queriable log is primarily for the platform and process administrator. It is not intended to be used as a notification system: avoid pooling on the queriable log. If you need to be notified of specific events, use the configurable event service.

== Usage

Here is an example of how to search for log message about a specific activity:

[source,groovy]
----
final APIClient apiClient = new APIClient()
apiClient.login(username, password)
final SearchOptionsBuilder builder = new SearchOptionsBuilder(0, 100)
builder.filter(LogSearchDescriptor.ACTION_SCOPE, aTaskId)
builder.searchTerm("Adding a new user")
builder.sort(LogSearchDescriptor.ACTION_TYPE, Order.ASC)
final LogAPI logAPI = apiClient.getLogAPI()
final SearchResult<Log> searchedLogs = logAPI.searchLogs(builder.done())
for (Log log : searchedLogs.getResult()) {
     // Print the detailed user creation message:
    System.out.println(log.getMessage())
}
----

== Implementation details

The queriable logger service stores log message in the Bonita Engine back-end database using the Hibernate library. The https://github.com/bonitasoft/bonita-engine/blob/{bonitaTagOrBranch}/services/bonita-log/src/main/java/org/bonitasoft/engine/services/QueriableLoggerService.java[interface] and the https://github.com/bonitasoft/bonita-engine/blob/{bonitaTagOrBranch}/services/bonita-log/src/main/java/org/bonitasoft/engine/services/impl[implementation] of the service are available from the source code repository on https://github.com/bonitasoft/[GitHub].


== Disabling the Queriable logger

Each queriable log type can be turned off individually with its associated property. The properties must be listed into the `/setup/platform_conf/current/tenant_engine/bonita-tenant-sp-custom.properties` file.

=== Find the list of properties

* You can deactivate the logging on all the events listed xref:integration:event-handlers.adoc#_event_list[here].
* Or, you can also find a set of properties for each product version. You'll find them in a java library: The `bonita-subscription.xml` file contains the list of properties, and it is packed into the `/server/webapps/bonita/WEB-INF/lib/bonita-server-sp-[BonitaVersion].jar` file.

=== Disable the Queriable Logs

. Use the xref:runtime:bonita-platform-setup.adoc[Platform configuration setup tool] to pull the configuration on the disk: `./setup.sh pull`
. Edit the `/setup/platform_conf/current/tenant_engine/bonita-tenant-sp-custom.properties` file.
. Add one line per property for each type of queriable log you want to disable, and set it to false, e.g.:
`bonita.tenant.queriable.log.ACTOR_CREATED.INTERNAL=false`
`bonita.tenant.queriable.log.APPLICATION_PAGE_DELETED.INTERNAL=false`
. Use the xref:runtime:bonita-platform-setup.adoc[Platform configuration setup tool] to push the configuration in the database: `./setup.sh push`
. xref:runtime:tomcat-bundle.adoc#start[Restart] the application server

.List of all queriable log levels that can be disabled:
[%collapsible]
====
* ACTOR_CREATED
* ACTOR_DELETED
* ACTOR_UPDATED
* APPLICATION_CREATED
* APPLICATION_DELETED
* APPLICATION_UPDATED
* APPLICATION_PAGE_CREATED
* APPLICATION_PAGE_DELETED
* APPLICATION_PAGE_UPDATED
* APPLICATION_MENU_CREATED
* APPLICATION_MENU_DELETED
* APPLICATION_MENU_UPDATED
* BREAKPOINT_CREATED
* BREAKPOINT_DELETED
* CATEGORY_CREATED
* CATEGORY_DELETED
* CATEGORY_UPDATED
* COMMAND_CREATED
* COMMAND_DELETED
* COMMAND_UPDATED
* COMMENT_CREATED
* COMMENT_DELETED
* USERTASK_CONTRACT_DATA_CREATED
* PROCESS_CONTRACT_DATA_CREATED
* CONNECTOR_INSTANCE_CREATED
* CONNECTOR_INSTANCE_UPDATED
* CONNECTOR_INSTANCE_DELETED
* DATA_SOURCE_CREATED
* DATA_INSTANCE_CREATED
* DATA_INSTANCE_DELETED
* DATA_INSTANCE_UPDATED
* DEPENDENCY_CREATED
* DEPENDENCY_DELETED
* DEPENDENCY_UPDATED
* DEPENDENCY_MAPPING_CREATED
* DEPENDENCY_MAPPING_DELETED
* DOCUMENT_CREATED
* DOCUMENT_DELETED
* DOCUMENTMAPPING_CREATED
* DOCUMENTMAPPING_DELETED
* DOCUMENTMAPPING_UPDATED
* EVENT_INSTANCE_TRIGGER_CREATED
* EVENT_INSTANCE_TRIGGER_DELETED
* EVENT_INSTANCE_TRIGGER_UPDATED
* FLOW_INSTANCE_CREATED
* FLOW_INSTANCE_DELETED
* FLOW_INSTANCE_UPDATED
* GATEWAY_INSTANCE_CREATED
* GATEWAY_INSTANCE_UPDATED
* IDENTITY_GROUP_CREATED
* IDENTITY_GROUP_DELETED
* IDENTITY_GROUP_UPDATED
* IDENTITY_ROLE_CREATED
* IDENTITY_ROLE_DELETED
* IDENTITY_ROLE_UPDATED
* IDENTITY_USER_CREATED
* IDENTITY_USER_DELETED
* IDENTITY_USER_UPDATED
* IDENTITY_USER_CONTACT_INFO_CREATED
* IDENTITY_USER_CONTACT_INFO_UPDATED
* IDENTITY_USER_MEMBERSHIP_CREATED
* IDENTITY_USER_MEMBERSHIP_DELETED
* IDENTITY_USER_MEMBERSHIP_UPDATED
* IDENTITY_CUSTOM_USER_INFO_DEFINITION_CREATED
* IDENTITY_CUSTOM_USER_INFO_DEFINITION_DELETED
* IDENTITY_CUSTOM_USER_INFO_DEFINITION_UPDATED
* IDENTITY_CUSTOM_USER_INFO_VALUE_CREATED
* IDENTITY_CUSTOM_USER_INFO_VALUE_DELETED
* IDENTITY_CUSTOM_USER_INFO_VALUE_UPDATED
* JOB_CREATED
* JOB_PARAMETER_CREATED
* MESSAGE_INSTANCE_CREATED
* MESSAGE_INSTANCE_UPDATED
* PAGE_CREATED
* PAGE_DELETED
* PAGE_UPDATED
* PENDING_ACTIVITY_MAPPING_CREATED
* PAGE_CREATED
* PAGE_DELETED
* PAGE_UPDATED
* PROCESS_DEFINITION_CREATED
* PROCESS_DEFINITION_DELETED
* PROCESS_DEFINITION_UPDATED
* PROCESS_INSTANCE_CREATED
* PROCESS_INSTANCE_DELETED
* PROCESS_INSTANCE_UPDATED
* PROFILE_CREATED
* PROFILE_DELETED
* PROFILE_UPDATED
* PROFILE_MEMBER_CREATED
* PROFILE_MEMBER_DELETED
* PROFILE_MEMBER_UPDATED
* REF_BUSINESS_DATA_INSTANCE_CREATED
* REF_BUSINESS_DATA_INSTANCE_UPDATED
* REF_BUSINESS_DATA_INSTANCE_DELETED
* SCHEDULER_SCHEDULED
* SUPERVISOR_CREATED
* SUPERVISOR_DELETED
* FORM_MAPPING_UPDATED
* FORM_MAPPING_DELETED
* FORM_MAPPING_CREATED
* BUSINESS_DATA_CREATED
* BUSINESS_DATA_UPDATED
* BUSINESS_DATA_DELETED
====
