= Connect applications to Git
:page-aliases: applications:connect-git.adoc
:description: This guide shows how to connect your Bonita UI Builder application to a remote Git repository.


{description}

* Difficulty: beginner
* Estimated time: 15 minutes
* Prerequisites: Basic knowledge of Git


[NOTE]
====
Version Control works with any Git hosting service that supports the SSH protocol and deploys keys. HTTPS Git connections are not currently supported in Bonita UI Builder.
====

[WARNING]
====
The connection will fail if the repository is not empty.
====

== Connect an application to Git

.Connect to GitHub
[%collapsible]
====
This guide shows how to connect your Bonita UI Builder application to an empty remote GitHub repository.

1. Open the Bonita UI Builder app you want to connect to Git and click the **Connect Git** button on the left of the bottom bar.

2. Select **GitHub** as the service provider.

3. Create a new Git repository or open an existing empty repository.

4. After setting up an empty repository, navigate to the repository's landing page, click on the Code button, and copy the **SSH** URL.

5. Paste the URL in the **Generate SSH Key** section on Bonita UI Builder.

6. Click the **Generate SSH Keys** button, and unique `ECDSA 256` and `RSA 4096` keys are displayed. Choose the appropriate key based on your specific security requirements and system constraints.

7. Copy one of the keys, then navigate to your **Repository settings**. Proceed to **Deploy keys**, click on **Add deploy keys**, paste the copied key, and provide a meaningful title for future reference.

8. Check the **Allow write access** option and then add the key.

9. In Bonita UI Builder, click the **Connect Git** button.

With these steps, you have successfully connected to Git.
====

.Connect to GitLab
[%collapsible]
====
This guide shows how to connect your Bonita UI Builder application to an empty remote GitLab repository.

1. Open the Bonita UI Builder app you want to connect to Git and click the **Connect Git** button on the left of the bottom bar.

2. Select **Gitlab** as the service provider.

3. Create a new Git repository or open an existing empty repository. See link:https://docs.gitlab.com/ee/user/project/index.html[How to create a new repository / project].

4. After setting up an empty repository, navigate to the repository's landing page, click on the Code button, and copy the **SSH** URL.

5. Paste the URL in the **Generate SSH Key** section on Bonita UI Builder.

6. Click the **Generate SSH Keys** button, and unique `ECDSA 256` and `RSA 4096` keys are displayed. Choose the appropriate key based on your specific security requirements and system constraints.

7. Copy one of the keys, then navigate to your **Repository settings**. Proceed to **Deploy keys**, click on **Add deploy keys**, paste the copied key, and provide a meaningful title for future reference.

8. Check the **Allow write access** option and then add the key.

9. In Bonita UI Builder, click the **Connect Git** button.

With these steps, you have successfully connected to Git.
====

.Connect to Bitbucket
[%collapsible]
====
This guide shows how to connect your Bonita UI Builder application to an empty remote Bitbucket repository.

1. Open the Bonita UI Builder app you want to connect to Git and click the **Connect Git** button on the left of the bottom bar.

2. Select **Bitbucket** as the service provider.

3. Create a new Git repository if you don't already have one. See link:https://support.atlassian.com/bitbucket-cloud/docs/create-a-git-repository/[How to create a new repository / project].

4. After setting up an empty repository, navigate to the repository's landing page, click on the **Clone** button, select **SSH** and copy the **SSH** URL.

5. Paste the SSH URL into the **Generate SSH Key** section in Bonita UI Builder, remove the `git clone` from the URL.

6. Click the **Generate SSH Keys** button, and unique `ECDSA 256` and `RSA 4096` keys are displayed. Choose the appropriate key based on your specific security requirements and system constraints.

7. Copy one of the keys, then navigate to your **Workspace settings**. Proceed to **SSH keys**, click on **Add an SSH key**, paste the copied key, and provide a meaningful title for future reference.

8. In Bonita UI Builder, click the **Connect Git** button.

With these steps, you have successfully connected to Git.
====

.Connect to Other Git Providers
[%collapsible]
====
This guide shows how to connect your Bonita UI Builder application to any Git provider, using an Azure repos as an example.

1. Open the Bonita UI Builder app you want to connect to Git and click the **Connect Git** button on the left of the bottom bar.

2. Select **Others** as the service provider.

3. Create a new Git repository or open an existing empty repository.

4. After setting up an empty repository, navigate to the repository's landing page, and copy the **SSH** URL.

5. Paste the URL in the **Generate SSH Key** section on Bonita UI Builder.

6. Click the **Generate SSH Keys** button, and unique `ECDSA 256` and `RSA 4096` keys are displayed. Select the `RSA 4096` key when connecting to Azure Repos.

7. Copy the key, then navigate to **User Settings** from the top right corner and open **SSH public keys**.

8. Click **+ New key**, add the key name and paste the generated `RSA 4096` key in the Public Key Data input box.

9. In Bonita UI Builder, click the **Connect Git** button.

With these steps, you have successfully connected to Git.
====

== See also

* xref:./git-settings[Git settings]