= Bonita Versions
:page-aliases: ROOT:product-versioning.adoc
:description: Discover how Bonita manages its product and the versions of the application elements and how it can impact your projects

{description}

== Platform Versions

After years of semantic versioning, and one release trying calendar versioning, Bonita now settles down in a mix type of versioning: YYYY.#-uX, since version 2021.2:

* YYYY is the year of the release
* # is the release number of the "main" release
* uX is for the _update_ number: 0 for the "main", and then each "maintenance" release gets an increment of 1.

For example:

* If the last main release is 2021.2, its binaries are labelled 2021.2-u0
* The 3rd maintenance version of this release is 2021.1-u3

Keep in mind that:

* Two main versions are released every year
* A new maintenance version is made available at least every month to our customers
* All maintenance versions are cross-compatible for the same main version. For example, transitioning from a *2021.2*-u1 to a *2021.1*-u3 will not require any Bonita database update procedure. However, transitioning from a *7.11*.5 to a *2021.2*-u2 will require a Bonita database update procedure.

[#technical-id]
== Technical Id

A technical Id also exists for Bonita components, and it follows the usual semantic versioning X.Y.Z:

* X is the major version number. It changes when non-backward compatible changes are implemented.
* Y is the minor version number. It changes when backward compatible features are added.
* Z is the maintenance version number. The maintenance versions contain fixes.

Here is a Bonita Platform version / Technical Id / UI Designer version correspondence table:

|===
| Release date | Bonita Platform version | Technical Id | UI Designer version

| 2023-11-07
| 2023.2-rc1
| 9.0.0.rc-01
| 1.17.12

| 2023-10-13
| 2023.2-b1
| 9.0.0.beta-01
| 1.17.8

|===

== Element version

In addition to the platform version, most elements have a model version. Bonita Studio and UI Designer use this model version to determine if the corresponding element is compatible. +
If the elements are incompatible, then either Bonita Studio migrates the elements (when the model version is lower than the Bonita Studio version), or you will have to update your studio to a compatible version. +

Example:

In the case below, my diagram model version is "7.12.1-001". I will not be able to open it with a 7.11 Studio but I will be able to open it without Bonita update with any 7.12 Studio. Finally, if I'm using a 7.13 Studio, my diagram will be migrated.


[source,xml]
----
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" ...>
  <process:MainProcess xmi:id="_dNo_EBrNEeughd1BclcISA" name="Administration" author="John Doe"
                        bonitaVersion="7.12.2" bonitaModelVersion="7.12.1-001" <!--1-->
                        configId="ACED000....">
    <elements xmi:type="process:Pool" xmi:id="_dNo_ERrNEeughd1BclcISA" name="DeleteVersion" version="0.0.1">
      <elements xmi:type="process:StartEvent" xmi:id="_dNo_ExrNEeughd1BclcISA" name="Start" outgoing="_dNo_KBrNEeughd1BclcISA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_dNo_FBrNEeughd1BclcISA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_dNo_FRrNEeughd1BclcISA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_dNo_FhrNEeughd1BclcISA" name="" content="" returnTypeFixed="true"/>
      </elements>
...
    </elements>
  </process:MainProcess>
</xmi:XMI>
----
<1> bonita version and model version declarations

The following elements have model versions:

* Diagrams
* Organization
* Business Data Model
* BDM Access control
* Applications
* Pages
* Forms
* Fragments
* Layouts
* Customer Widgets

These model versions should not change between maintenance versions of a given main version (e.g. between a 7.12.5 and a 7.12.3). This means that no update procedure is needed in production or the Studio when changing the maintenance version.

[NOTE]
====

Changing the main version does not imply that the model version of all elements will change: in some cases, updating to a new main version will not require to migrate the elements.
====

== Version checks in Bonita Studio and UI Designer

=== Studio

Bonita Studio will check the model version of every element of a given project when cloning or importing it. The element model version will also be checked when importing elements individually.

The model versions of all elements are also checked when deploying a project. Finally, the model version is checked when an element is opened.

To check the compatibility of your elements manually, you can use the "Validate" action in the project's context menu or via the File menu.

You will not be able to work with incompatible elements nor deploy them. However, it is possible to migrate older elements.

=== UI Designer

The UI Designer will check the model version of all elements when it is launched and when a given element is opened. You will not be able to work with incompatible elements. However, you will be able to migrate older elements.

[WARNING]
====

Element migration is not reversible. Once the studio or UI Designer has migrated an element, it is no longer compatible with the previous version of the Bonita component.
====
