= Update overview
:page-aliases: migration-overview.adoc
:description: Learn how to update Bonita Platform from an older version to a newer version.

Learn how to update a Bonita Platform from an older version to a newer version.

[NOTE]
====
.*Updating* means moving from one Bonita version to a newer one, to benefit from:
* new features (in Main versions)
* technology updates (in Main versions)
* bug fixes (in Maintenance versions)
 ====

== Updating your Bonita Runtime

Based on your current Bonita Runtime version and the targeted one, you will have to use at least one of the following tools.

WARNING: You cannot update your platform from a version earlier than 6.0.2.

|===
|*Tool* | *Documentation*| *Use cases*
| Bonita Migration Tool 1.x | xref:update-with-migration-tool.adoc[Migration Tool Documentation]
|From version *6.0.2* or later to any version up to *7.0.0*
| Bonita Migration Tool 2.x | xref:update-with-migration-tool.adoc[Migration Tool Documentation]
|From version *7.0.0* or later to any version up to *7.13.0*
| Bonita Update Tool 3.x | xref:update-with-update-tool.adoc[Update Tool Documentation]
|From version *7.10.0* or later to any version up to *the latest*
|===

=== Update happy path 

There are three Bonita tools that can be used for updating Bonita Runtime. 
In case you are wondering which one to choose depending on your Bonita version, here's an idea : 

|===
|*Source version* | *Target version*| *Update path*
| 6.x.y |7.x.y | *Use Bonita Migration Tool 1.x*
| 7.9.y or any Bonita version before 7.10 | 7.13.y | *Use Bonita Migration Tool 2.x*
| 7.10.1 | 7.10.5 
a| * You still have to go through the update process for maintenance 
* *Use Bonita Migration Tool 2.x*
| 7.10.y | latest Bonita 
a| * After Bonita 7.11, benefiting from all the advantages do not require an update
* *Use Bonita Update Tool 3.x*
|===
== Updating your Bonita Studio

To update to a newer version of Bonita Studio, install the new version using the xref:ROOT:bonita-bpm-studio-installation.adoc[Studio installer wizard] for your operating system.
If you want to keep the artifacts in your workspace, select the option to migrate your workspace.

WARNING: if you do not migrate your workspace, or if you use the OS-independent archive to install the new Bonita Studio,
your workspace is not automatically migrated. In this case, you must manually export each item from the older Bonita Studio and import it into the newer version.


== Migrating your process definitions

A process definition created using a previous Bonita 7.x can be run on this version after a platform migration. You might choose to update the process definition to take advantage of new features.
To update a process definition, export it from the older version of Bonita Studio as a `.bos` file, then import it into the
newer version and update it.
Note: you cannot import a process definition `.bos` file into a version of Bonita Studio that is older than the version
that was used to create it.

A process definition created using a version 6.x of Bonita, or using 6.x forms or case overview pages, needs to have its task and instantiation forms modified in a previous version of
Bonita (7.0.0 to 7.7.4) before migrating to this version. Bonita Studio 7.8 and above can't import these forms, which may result in data loss or process malfunctions. For more details see xref:update-with-migration-tool.adoc[[platform migration].
