= Updating Bonita Studio
:page-aliases: ROOT:update-studio.adoc
:description: How to update your existing Bonita Studio to a newer version.

{description}

== Updating to a new Main version

. Read the version xref:ROOT:release-notes.adoc[release notes] to understand the major changes and their possible impact on your projects
. Download the latest Bonita Studio version:
 * https://www.bonitasoft.com/downloads[Community edition]
 * https://customer.bonitasoft.com/[Subscription editions]
. Install Bonita Studio
. Launch it
. If you are using a GIT repository
 .. In your previous studio, make sure you have pushed all the latest changes to your project
 .. Clone your project in the latest Studio version, some artifact migrations will require actions/decisions from your part
 .. Repeat for each project that needs to be moved to the new version
. If you are not using a GIT repository
 .. In your previous studio, export your project as a BOS file
 .. Import the .BOS in the latest Bonita Studio version, some artifact migrations will require actions/decisions from your part
 .. Repeat for each project that needs to be moved to the new version


== Updating to a new Maintenance version (Enterprise only)
Maintenance versions are cross-compatible, meaning that it is not required that your Bonita Studio version matches the target Bonita Runtime version.

For example, your production runtime can be in 2021.1-0408 and your Studio in 2021.1-0218.

=== Project update

When cloning an existing project from an older version of the same base version, the target runtime version is not automatically updated. +
This behavior allows other project contributors to keep using an older Studio version without needing to install additional dependencies. +
It is perfectly fine to reference a different target runtime version than the one currently run by the Studio.+
However, you can update this version from the `Edit project information...` contextual menu or by using the pencil button in the project Overview. +
Before updating this version ensure that collaborators of the project have either:

* Installed the same Studio version

or

* Installed the required dependencies for this version:
** By installing and starting a Studio of this version at least once
** By downloading those dependencies from the https://customer.bonitasoft.com[Customer Service Center] (Maven repository) and copying them into their local Maven repository

Keeping the target runtime version up-to-date may be useful in some cases like including bug fixes or having a reliable dependency resolution in case of dependencies updates (CVE fixes).


== Updating your project to the project composition

Version 2021.2 introduces major changes to the way Bonita Studio manages projects. When importing or cloning your project in this version or any later version, it will be transformed into a Maven project. +
All your project dependencies (connectors, libraries, actor filters...) will then be managed with Maven.

=== BOS Import

In the BOS import wizard, an additional step has been added. Bonita Studio is going to scan your project dependencies and try to find them on the configured Maven repositories (by default Maven Central is configured).

If the dependencies are found then they will be used as remote dependencies (not copied in your project) otherwise they will be copied in the project and will be committed with your project sources.

In both cases, dependencies that are in the project but are not used will not be added in the migrated project unless you add them manually (by ticking the corresponding checkboxes).

You can also remove the other dependencies (at your own risk).

=== Project cloning

If your project is cloned through GIT, there is no extra step in the wizard. The migration is automatically applied to the checkouted branch. +
A `MIGRATION_NOTES.adoc` file is generated at the root of the project to detail the major changes occurring at migration. +
It is up to you to keep it in the project or not (later migrations will be appended to this file if it exists.)

The dependencies are also analyzed by the studio but the result of the analysis is directly applied to your project. +
The studio is going to scan your project dependencies and try to find them on the configured Maven repositories (by default Maven Central is configured).

If the dependencies are found, then they will be used as remote dependencies (not committed in your project), otherwise they will be added to the project local repository store and will be committed to your project.

=== Impact on Extension creation

[CAUTION]
====
From Bonita 2021.2 on, it will no longer be possible to create connectors, actor filters, and themes from Bonita Studio. You will have to use the corresponding xref:software-extensibility:software-extensibility.adoc[Maven archetypes].
====

If your project already has actor filters, connectors, or themes, you will still be able to edit them from Bonita Studio. However, we recommend migrating them to standalone dependencies.
