= Upgrading from Community to Enterprise
:page-aliases: ROOT:upgrade-from-community-to-a-subscription-edition.adoc
:description: Learn how to change Bonita edition: move from a Bonita Community to any Bonita Enterprise

{description}

*Upgrading* means moving from a Bonita Community edition environment to any Bonita Enterprise edition environment.

== To check before upgrading

A Bonita edition upgrade can only be performed between environments having the same Bonita version.

[NOTE]
====
* *POSSIBLE* - upgrade from a Bonita 2021.2 Community edition to Bonita 2021.2 Enterprise edition.
* *NOT POSSIBLE* - upgrade from Bonita 2021.2 Community to Bonita 2021.3 Enterprise. +
====

Updating to a newer version at the same time as upgrading to the Enterprise edition is *NOT* an option. +

== Upgrade process

An upgrade has to be performed independently on Bonita components.

Upgrading a Bonita Runtime allows you to keep its data (process definitions, cases, BDM...) while benefiting from the Enterprise edition features.

[NOTE]
====
The *upgrade procedure* is quite simple with an execution time of less than 30 minutes.

A *service downtime* will be required.
====

[WARNING]
====
A Bonita Runtime upgrade can only be performed on the same database vendor (E.g. PostgreSQL) and on the same Bonita version (E.g. Bonita 2023.2 (=_9.0_))
====


=== With Self-Contained Application

==== Build an Enterprise version of a Self-Contained App

===== Import/Clone your project in Bonita Studio Enterprise edition

To perform an upgrade from the Community edition of Bonita Studio and its resources (such as process diagrams, data models), follow these steps:

. xref:ROOT:bonita-bpm-studio-installation.adoc[Install a Bonita  Studio] Enterprise edition.
. If you are using GIT, clone your project, it will be upgraded during the clone operation
. If you are not using GIT :
.. Export your projects from the Bonita Studio Community edition to `.bos` archives. We recommend that you keep those archives as a backup.
.. Import your `.bos` archives into the Bonita Studio in Enterprise edition.

The upgrade is performed automatically and silently when importing resources into Bonita Studio Enterprise edition.

===== Build

xref:build-run:build-application.adoc[Build] a new version of your application from a command-line interface.

==== Upgrade a SCA Bonita Runtime

To upgrade a Bonita Runtime from a Community edition to an Enterprise edition, follow these steps:

. Retrieve an xref:ROOT:licenses.adoc[Enterprise license] file
. Install and configure the `platform-setup-sp` tool
.. (Optional) Download the `platform-setup-sp-<version>.zip` and extract using the following commands:
+
[source,shell]
----
mvn dependency:copy -Dartifact=com.bonitasoft.platform:platform-setup-sp:<version>:zip -DoutputDirectory=.
unzip platform-setup-sp-<version>.zip -d <platform-setup-install-folder>
----
Replace __<version>__ using the version matching your target xref:version-update:product-versioning.adoc[Bonita version]. +
Replace __<platform-setup-install-folder>__ with the folder where you want to install the tool.

.. Configure the `database.properties` file (you may retrieve the one used in community) to connect to the database.
. Run `<platform-setup-install-folder>/setup(.sh/.bat) pull` to fetch your current Community configuration from the database
. Copy your license file into the `<platform-setup-install-folder>/platform_conf/licenses` folder
. Stop your Community application version
. Run `<platform-setup-install-folder>/setup(.sh/.bat) push` to push your new license in the database and apply the enterprise upgrade
. Start your new Enterprise application version

[NOTE]
====
Downloading the `platform-setup-sp` tool is optional as it is already packaged in the bundle archive when building your SCA using the `bundle` mode. It is recommended when using a Docker image.
====

=== Upgrade a Bonita Runtime with a Tomcat bundle

To upgrade a Bonita Runtime from a Community edition to an Enterprise edition, follow these steps:

. Download and unzip the Bonita Enterprise bundle to `<bonita-enterprise-installation>` folder
. Copy your database.properties fom your Community installation `setup` folder to `<bonita-enterprise-installation>/setup` folder
. Run `<bonita-enterprise-installation>/setup/setup(.sh/.bat) pull` to fetch your current Community configuration.
. Retrieve an xref:ROOT:licenses.adoc[Enterprise license] file
. Copy your license file into `<bonita-enterprise-installation>/setup/platform_conf/licenses`
. Push your new license in the database: `<bonita-enterprise-installation>/setup/setup(.sh/.bat) push`
. Stop Bonita Community platform with `<bonita-community-installation>/stop-bonita(.sh/.bat)` script.
. Start the Enterprise Bonita Runtime using `<bonita-enterprise-installation>/start-bonita(.sh/.bat)` script

Once you have started Bonita Enterprise Runtime at least once, you can pull your Enterprise configuration (`<bonita-enterprise-installation>/setup/setup(.sh/.bat) pull`)
and change the Enterprise-specific configuration files to match your needs. See xref:runtime:bonita-platform-setup.adoc[Bonita Runtime setup tool] for details about
how to apply configuration changes.

==== Import Enterprise Admin App

Starting with Bonita 2021.2, Bonita Portal has been replaced with Bonita Applications.
In Enterprise edition, an additional application for administrators is available for manual import - Bonita Administrator Application.

Here are the steps to follow :

. Go to `<bonita-enterprise-installation>/server/webapps/bonita/WEB-INF/classes/org/bonitasoft/web/application/`.
. Unzip the file `bonita-admin-application-sp-x.y.z.zip`. You should have an xml and a png file.
. Connect to the bonita platform using the super administrator account.
. Go to applications, import the xml file.
. ⚠ (Optionally, click on more details of your newly imported application, and import the png file as logo)

=== Remove Community Admin App

If you chose to include the Admin App in your SCA or if you were using the Bundle, you will have two versions of the app installed: the community and enterprise versions. To avoid any confusion, you can remove the community version from the `Applications` menu of the Super Admin application.

=== Enterprise specific configuration

The upgrade is now finished, you can verify that you are now running an Enterprise edition in the Super Administrator application; the edition displayed in the "Platform maintenance" page should indicate Enterprise edition.

Once you have started Bonita Enterprise Runtime at least once, you can re-pull your Enterprise configuration (`<platform-setup-install-folder>/setup(.sh/.bat) pull`)
and change the Enterprise-specific configuration files to match your needs. See xref:runtime:bonita-platform-setup.adoc[Bonita Runtime setup tool] for details about
how to apply configuration changes.
