= Tasks in integration tests
:description: Manage tasks in integration tests using the Bonita test toolkit

Learn to execute tasks and to validate their states in integration tests using the Bonita test toolkit.

[NOTE]
====
Integrations tests are built upon the Bonita Test Toolkit, based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client]. +
The Bonita Test Toolkit is only available for Enterprise, Performance, Efficiency and Teamwork. editions. 
====

== Retrieve tasks

Any task (user task, service task...) defined on a process can be retrieved through the xref:process.adoc#_tasks[process instance]. +
Keep in mind that only tasks that *have been executed or are ready* can be retrieved, incoming tasks are not accessible.

A task is returned as an object `Task` or `UserTask` (which extends `Task`). + 
It offers the possiblity to retrieve sone meta information about the task, its state, and gives access to eventual xref:variable.adoc[variables] and xref:connector.adoc[connectors].

Besides that, a user task provides information about candidates, assignee, due date, and can be assigned and executed.

== Assign and execute user tasks

User tasks can be executed from using the corresponding process instances to advance processes: 

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void assign_and_execute_tasks(BonitaTestToolkit toolkit) {
        User walter = toolkit.getUser("walter.bates");
        ProcessDefinition processDef = toolkit.getProcessDefinition("myProcess");
        ProcessInstance processInstance = processDef.startProcessFor(walter);
        Task userTask = processInstance.getFirstPendingUserTask("aTask"); <1>
        Contract contract = createContract(); <2>

        // Check the candidates of a task
        Set<User> candidates = userTask.getCandidates(); <3>
        assertThat(candidates).extracting(User::getUserName).containsExactly(walter.getUserName());

        // Assign a task to a user
        userTask.assignTo(walter); <4>

        // Execute an assigned task, with or without a contract.
        userTask.execute(); <5>
        userTask.execute(contract);

        // Assign and execute a task, with or without a contract.
        userTask.execute(walter); <6>
        userTask.execute(walter, contract);

        // Use the provided predicates to ensure that a taks has been correctly executed before to continue.
        await().until(userTask, hasBeenExecutedBy(walter) <7>
                .and(taskArchived())
                .and(taskCompleted()));
    }
}
----
<1> Retrieve the pending task _aTask_ from the process instance.
<2> Create a contract from a dedicated method to execute the task (more details about contract creation xref:contract.adoc[here]).
<3> Retrieve the candidates of the task (i.e the users that can be assigned to the task), and ensure that walter is the only candidate.
<4> Assign the task to a user.
<5> Execute the task with or without a contract. The task must have been already assigned.
<6> Assign and execute the task with or without a contract. If the task is already assigned to an other user, it will be reassigned to the new user before to be executed.
<7> Wait until the task is completed before to continue. Mor details about task predicates in the dedicated section xref:_task_predicates[bellow].

== Task predicates

In order to make asynchronous assertions on processes (using for example http://www.awaitility.org/[Awaitility]), some convenient predicates come with the Bonita test tookit. It allows to ensure in a scenario that the system is in the expected state before to continue. +
For example, it is possible to use the predicate `taskCompleted()` on a user task to ensure that a task has been correctly executed before to continue. Awaitility (or any other asynchronous library) will check this predicate at a given frequency, and will throw an error if the timeout is reached (i.e the case has not been started in time).

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void atask_predicates(BonitaTestToolkit toolkit) {
        User walter = toolkit.getUser("walter.bates");
        User helen = toolkit.getUser("helen.kelly");
        ProcessDefinition processDef = toolkit.getProcessDefinition("myProcess");
        ProcessInstance processInstance = processDef.startProcessFor(walter);
        Task userTask = processInstance.getFirstPendingUserTask("aTask");


        await().until(userTask, isNotAssigned()); <1>
        await().until(userTask, hasCandidates(walter, helen)); <2>
        await().until(userTask, isAssignedTo(walter)); <3>
        await().until(userTask, taskReady()); <4>
        await().until(userTask, hasBeenExecutedBy(walter)); <5>
        await().until(userTask, taskCompleted()); <6>
        await().until(userTask, taskArchived()); <7>
        await().until(userTask, taskFailed()); <8>
    }
}
----
<1> Verify that the user task has no assignee.
<2> Verify that the user task has two candidates: walter and helen.
<3> Verify that the user task is assigned to walter.
<4> Verify that the user task is ready.
<5> Verify that the user taks has been executed by walter.
<6> Verify that the user task is completed.
<7> Verify that the user task is archived.
<8> Verify that the user task has failed. 