= Users in integration tests
:description: Manage users in integration tests using the Bonita test toolkit

To start processes or execute human tasks in integration tests, users from the deployed organization must be used. +
This page details how to retrieve users in integration tests using the Bonita Test Toolkit.

[NOTE]
====
Integrations tests are built upon the Bonita Test Toolkit, based on the open-source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client]. +
The Bonita Test Toolkit is only available for Enterprise, Performance, Efficiency, and Teamwork editions. 
====

== Retrieve a User

Users are mainly used to start processes and execute tasks. Any user in the organization can be retrieved using its username and the Bonita Test Toolkit: 

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user(BonitaTestToolkit toolkit) {  <1>
        User user = toolkit.getUser("walter.bates"); <2>
        ...
    }
}
----
<1> A `BonitaTestToolkit` is injected by the `BonitaTestExtension`
<2> The user Walter Bates is retrieved using its username (`walter.bates`).

[NOTE]
====
The user password is not required to retrieve the user, why? 

Because the Bonita Test Toolkit only authenticates with the technical user. It executes processes and tasks for a given user, but it is always the technical user that is logged in (it uses the _execute as_ feature).
====

== Find users by group

Retrieves a paginated list of users belonging to a group of the organization

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user_in_group(BonitaTestToolkit toolkit) {
        List<User> users = toolkit.findUsersInGroup("/acme/production/rd", 0, 10); <1>
        ...
    }
}
----
<1> Takes a `groupPath` parameter to identify a given group in the target runtime organization.

[WARNING]
====
Does not retrieves users belonging to sub groups.
====

== Find users by role

Retrieves a paginated list of users having a given role in the organization

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user_with_role(BonitaTestToolkit toolkit) {
        List<User> users = toolkit.findUsersWithRole("manager", 0, 10);
        ...
    }
}
----

== Find users by membership

Retrieves a paginated list of users having a given role in the organization

[source, Java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user_with_membership(BonitaTestToolkit toolkit) {
        List<User> users = toolkit.findUsersWithMembership("/acme/production/rd", "manager", 0, 10);
        ...
    }
}
----

== Configure the technical user

As explained above, the test toolkit only uses the technical user. The credentials of the technical user are retrieved through the system properties `bonita.tech.user` and `bonita.tech.password`. +
The default values are [_username_: `install`, _password_:  `install`].

Those properties can be set through Maven properties when running the tests: 

`mvn clean verify -Dbonita.tech.user=<username> -Dbonita.tech.password=<password>`

