= Access to Bonita Artifact Repository (Subscription editions only)
:page-aliases: ROOT:bonita-repository-access.adoc
:description: Set up access to Bonita Artifact Repository to download development dependencies.

{description}

[#bonita-artifact-repository]
== What is Bonita Artifact Repository?

Bonita Artifact Repository is a solution to get Maven artifacts produced by Bonitasoft, which can be consumed as dependencies in downstream projects.

[WARNING]
====
For now on, only xref:test-toolkit:ROOT:process-testing-overview.adoc[Bonita Test Toolkit] is available on Bonita Artifact Repository.
====

[#credentials]
== Ask for credentials to your account manager

Once your subscription is registered, your account manager will automatically receive an email with valid credentials.
These credentials will last as long as your subscription, but you will not need to change them if you extend that subscription.

Credentials are unique per subscription and include:

* A login (the email used for the subscription)
* A token

[#maven]
== Maven

Starting from Bonita 2021.2, Bonita Studio uses https://maven.apache.org/[Maven] internally to resolve required dependencies.

[NOTE]
====
In the below example, we use Maven as the project build tool for extension projects. But it is also possible to use Gradle if it is the tool of your choice.
====

An Internet connection is required.

=== Maven settings overview

Once you were granted with Bonita Artifact Repository credentials, you have to tell https://maven.apache.org/configure.html[configure] `Maven` to use Bonita Maven repository.

This is done in a file named https://maven.apache.org/settings.html[settings.xml] which is present by convention in the following default place: `$HOME/.m2/settings.xml`

[source, xml]
.Sample sections of settings.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository/>
  <interactiveMode/>
  <offline/>
  <pluginGroups/>
  <servers/>
  <mirrors/>
  <proxies/>
  <profiles/>
  <activeProfiles/>
</settings>
----

=== Bonita Maven repository declaration

In this `settings.xml` file you have to declare Bonita Maven repository to let Maven know that some dependencies can be found there.
In the following code snippet, you will find how to declare new https://maven.apache.org/settings.html#Repositories[repositories] to Maven.

[source, xml]
.Part of settings.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <!-- ...  -->
    <profiles>
        <profile>
            <id>bonitasoft</id>
            <repositories>
                <repository>
                    <id>bonitasoft-releases</id>
                    <name>Bonitasoft Releases</name>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <url>https://bonitasoft.jfrog.io/artifactory/maven</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>bonitasoft-releases</id>
                    <name>Bonitasoft Releases</name>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <url>https://bonitasoft.jfrog.io/artifactory/maven</url>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
    <!-- ...  -->
  <activeProfiles>
    <activeProfile>bonitasoft</activeProfile>
  </activeProfiles>

</settings>
----

[IMPORTANT]
====
Do not forget to mark `bonitasoft` profile as `active` in the `activeProfiles` section or the declared repositories will not be used for dependency resolution.
====


=== Authentication

Now that Maven is aware of Bonita Maven repository, we have to give it the credentials to be allowed to download artifacts. Here is the simple way to specify credentials to use with https://maven.apache.org/settings.html#Servers[repository servers] but we strongly advice users to use https://maven.apache.org/guides/mini/guide-encryption.html[password encryption] feature to enforce security.

[source, xml]
.Server authentication in settings.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <!-- ...  -->
    <servers>
        <server>
            <!-- This server ID must be the same as the one use for repository declaration ! -->
            <id>bonitasoft-releases</id>
            <username>MY_LOGIN</username>
            <password>MY_BONITA_REPOSITORY_TOKEN</password>
        </server>
    </servers>
    <!-- ...  -->
</settings>
----

=== Maven configuration in Bonita Studio

If you want to set up access to Bonita Artifact Repository using Bonita Studio, please refer to the dedicated page on how to xref:setup-dev-environment:configure-maven.adoc[configure Maven from Bonita Studio].
