= Run an Application
:description: This page describes how to run and update an Application.

{description}

== Prerequisites

Your application have been previously built for an environment (cf. xref:build-run:build-application.adoc[]) and packaged as a Docker image and/or a Tomcat bundle.

== How to run an Application
[#run]

Depending on the artifact produced by the build, follow the dedicated instructions on how to configure and run your Application:

* xref:runtime:bonita-docker-installation.adoc[Configure and run your Application as a Docker image]
* xref:runtime:tomcat-bundle.adoc[Configure and run your Application as a Tomcat bundle]

The Bonita Runtime automatically installs and deploys all the artifacts of your Application at startup. A recap of what
have been successfully installed is available in the logs of the Runtime. Also, if an error occurs during the process,
in addition to log the reason, the Tomcat server stops and modifications are partially reverted.

[NOTE]
.Partial rollback explanations:
BDM and Bonita Platform databases run on two independent instances. The BDM installation is made at the beginning of
the installation process, the others artifacts are installed afterward. If an error occurs during the BDM installation,
modifications are reverted and the installation process is aborted. However, if an error occurs during artifacts
installation, modifications on the BDM are not reverted, only modifications on artifacts are.

== How to update an Application

=== Increment project version

1. Open your project with Bonita Studio.
2. Edit project information (right-click on the root folder of the project explorer and click on `Edit project information...`).
3. Increment the version.

[NOTE]
The project version must respect the https://semver.org[Semantic Versioning (SemVer)] specification.

=== Build the project

Build the new version of your application for a given environment. Please refer to the dedicated documentation on xref:build-run:build-application.adoc[how to build a project].

=== Run the application

As mentioned above, follow the same instructions on <<run>>.

[NOTE]
Following SemVer specification, if the new version is lower or equals than the current version, the application will not be updated.

=== Update strategies

During the update of an application, the following artifacts are updated according to the following strategies:

[cols="1,2,2"]
|===
|Artifact| Update strategy | Comment

|Living application
|Delete the application and recreate it
|

|BDM
|Update the BDM, limited by what is supported (add column & add objects)
|

|Business data model access controls
|Uninstalls the previous version and installs the new version
|

|Layout
|Uninstalls the previous version and installs the new version
|

|Organization
|Merge the organization and deactivate elements only presents in the previous organization
|

|Page
|Uninstalls the previous version and installs the new version
|


|Process and Form
|Deactivate previous version and activate new version (keep open case opening with previous version until they are finished)
|If you want to keep the latest process version activated, you should duplicate the process from your project in Studio.

|Profile
|Stops importing if any profile already exists. Imports all if none already exists.
|

|REST API extension
|Uninstalls the previous version and installs the new version
|

|Theme
|Uninstalls the previous version and installs the new version
|
|===