= Update a new version of application
:description: Learn how the update of a new version of an application works.

{description}

== Update your project

If you need to update your project, to add some new feature or fixing issues, you should be From your Bonita Studio, you can update your project from the Bonita Studio.
You should update the project version field in from the project properties layout. Process and Living Application descriptor should be updated too if needed.

When this is done, you are ready to build you project and deploy the new version of your application.

== Behind the scene

When you deploy a new version of your application, Bonita will check if the new version is compatible with the previous one.
If it is the case, the new version will be deployed and the previous one will be deactivated.
If it is not the case, the new version will not be deployed and the previous one will still be active.

=== Policies

For each artifact, this following policies is use during the application update.
[cols="1,1"]
|===
|Artifact| Expected behavior

|Living application
|Delete the application and recreate it

|BDM
|Update the BDM, limited by what is supported (add column & add objects)

|Business data model access controls
|Uninstalls the previous version and installs the new version

|Layout
|Uninstalls the previous version and installs the new version

|Organization
|Merge the organization and deactivate elements only presents in the previous organization

|Page
|Uninstalls the previous version and installs the new version

|Process and Form
|Deactivate previous version and activate new version (keep open case opening with previous version until they are finished)

|Profile
|Stops importing if any profile already exists. Imports all if none already exists.

|REST API extension
|Uninstalls the previous version and installs the new version

|Theme
|Uninstalls the previous version and installs the new version
|===
