= Google Calendar connectors
:page-aliases: ROOT:google-calendar.adoc
:description: Bonita native Google Calendar connectors allow to connect Bonita processes to Google calendar to manage events.

{description}

== Overview

The Google Calendar (API v3) connectors enable client applications to view and update calendar events by using Google Data API feeds. For details of the API, see the Google https://developers.google.com/google-apps/calendar/[Developer's Guide].

Your business application, or set of processes, can create new Google calendar events, can edit, move, or delete existing events, and can query for events that match particular criteria. The connectors available are as follows:

* Get event
* Create event
* Update event
* Delete event
* Move event

This page describes how to create a Google Apps service account and get connection credentials, then how to configure the calendar client in your domain. You only need to get one set of credentials, and configure the client once, and then you can configure any number of Google calendar connectors. Use the connector wizard as usual to configure a Google Calendar connector. For each connector, you need to provide the parameters specific to the connector actions, and you need to specify the connection parameters.

== Google configuration

https://github.com/bonitasoft/bonita-connector-googlecalendar-V3[Please consult the documentation on the connector repository]

== Specify connector connection parameters

When you add a Google Calendar connector to a process diagram, you need to specify connection parameters in the wizard. The table below explains what to specify:

|===
| Parameter name | Required information

| Application name
| A unique name that identifies the calling application in the Google reporting and statistics

| Calendar ID
| The email address that identifies the calendar that the created event will belong to. Typically, this will be a process or business variable

| Service Account ID
| The email address of the Google client, which you noted earlier from the Credentials page

| Authentication method
| There are two ways to authenticate with a Json token (highly recommended) or with a P12 file

| Service Account P12 file
| The full path to the private key file, which you noted earlier

| Service Account Json token
| The full Json token value

| Service Account User
| The email address of the user who is creating the event. This user must have appropriate access rights to create or modify events in your domain
|===
