= Process testing 
:page-aliases: ROOT:process-testing-index.adoc
:description: Tips and how-tos for functional and performance testing of your automation projects.

{description} 

== Functional testing
Bonita Studio contains several features that you can use to verify your processes and their elements while the project is in development:

* Connectors testing: go to *Test connector* in the _Development_ menu.
* Expressions testing: use the *Evaluate* feature of the Expression editor.
* Process diagram validation: choose *Validate* from the _Diagram_ menu, or go to the _Details_ panel, _Validation status_ tab and click *Refresh*. The _Details_ panel contains a list of warnings and errors indicating things to correct in the diagram. Click on a row in the list to highlight the relevant item in the diagram.
* Process local run: Select the process pool and click on the *Run* icon of the studio coolbar. The processes are deployed in the embedded Tomcat, and made available in Bonita provided applications. +

If you have already created your own xref:ROOT:actors-index.adoc[actors] for your lanes and human tasks, you need to map them to entities of your test organization before you run your processes. To do so: 

. Create your test organization (see below)
. Select the process pool
. Click on the *Configure* icon of the Studio coolbar and configure the _Actor mapping_

== Integration Testing

[NOTE]
====

For Enterprise, Performance, Efficiency and Teamwork editions only.
====

To write automated integration test scenarios for your automation project you can use the Bonita Test Toolkit. It provides powerful methods to execute all the steps of a process and check the corresponding outputs (statuses, business data, tasks used)

It can be used in any IDE and can easily be integrated into a Continuous Integration.

More information in the dedicated documentation: Bonita Test Toolkit.


== Unit Testing

== Performance testing
In addition to functional testing during development, we recommend that you monitor the system load. This will help evaluate the performance, so you can make your processes efficient.

When you have finished developing your process, we also recommend that you perform a load test with the expected number of simultaneous users of the project, and a realistic rate of use of the processes. This will help you evaluate the size of the platform (CPU, RAM, etc.) you will need when the project goes into production.

[.card-section]
== Learn more

[.card.card-index]
--
xref:ROOT:configure-a-test-organization.adoc[[.card-title]#Configure a test organization# [.card-body.card-content-overflow]#pass:q[Create only the main entities of the target organization]#]
--

[.card.card-index]
--
xref:ROOT:configuring-a-process.adoc[[.card-title]#Configure a process# [.card-body.card-content-overflow]#pass:q[Prepare each process to be deployed in each target environment]#]
--

[.card.card-index]
--
xref:ROOT:run-a-process-from-bonita-bpm-studio-for-testing.adoc[[.card-title]#Run a process from Bonita Studio# [.card-body.card-content-overflow]#pass:q[Simulate the final process execution]#]
--

[.card.card-index]
--
xref:ROOT:log-files.adoc[[.card-title]#Studio log files# [.card-body.card-content-overflow]#pass:q[Log files content for easy monitoring and troubleshooting]#]
--
