= Create process integration tests
:description: This pages describes how to write process integration tests using the Bonita Test Toolkit.

{description}

[NOTE]
====
The Bonita Test Toolkit is opnly available for Enterprise, Performance, Efficiency and teamwork editions only. 

However, it based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client] to make HTTP calls on the Bonita platform. Any user can make its own test toolkit using this client. 
====

Some developer skills are required to follow this documentation page and, generally, to write process integration tests.

== Motivations

In the world of development, writing tests is not an option. It is the best way to ensure that a product fulfill its requirements, and that existing existing features won't be broken by future developments. 

This apply to Bonita processes. For each process, an integration test should be written, to validate that the process executes correctly depending on the inputs, that after each task the platform is in the expected state and so on.

The Bonita Test Toolkit offers the possibility to write such tests. It performs HTTP calls on the targeted Bonita platform to start and execute cases, and make assertions at any time on the state of the platform, the content of the data... +
It is written is Java, and should be used with a Java test framework like JUnit. 

== Quick start

This quick start tutorial assumes that a Bonita platform is running at `localhost:8080/bonita`. On this platform, a small BDM and basic process using this BDM is installed. +
No matter where is your platform running and what kind of process is installed on it, you should be able to follow this quick start tutoriel and adapt it to your use case.

Create a new Maven project with the following pom.xml: 

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.company.test</groupId>
    <artifactId>bonita-process-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Bonita process test</name>
    <description>Maven project to test Bonita processes</description>
  
    <properties>
        <!-- maven -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>
        <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
        <maven-dependency-plugin.version>3.2.0</maven-dependency-plugin.version>
        <maven-project-info-plugin.version>3.1.2</maven-project-info-plugin.version>
    
        <!-- Bonita -->
        <bonita-test-toolkit.version>0.0.1-SNAPSHOT</bonita-test-toolkit.version>
    
        <!-- Test -->
        <junit.version>5.8.1</junit.version>
        <assertj-core.version>3.21.0</assertj-core.version>
    </properties>
    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency> <1>
            <groupId>com.bonitasoft</groupId>
            <artifactId>bonita-test-toolkit</artifactId>
            <version>${bonita-test-toolkit.version}</version>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
----
<1> The Bonita Test Toolkit dependency

In `src-test/java/com/company/test`, create a class `ProcessIT.java` with the following content: 

[source, java]
----
package com.company.test;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import com.bonitasoft.test.toolkit.BonitaTestToolkit;
import com.bonitasoft.test.toolkit.assertion.BonitaAssertions;
import com.bonitasoft.test.toolkit.contract.ComplexInputBuilder;
import com.bonitasoft.test.toolkit.contract.ContractBuilder;
import com.bonitasoft.test.toolkit.junit.extension.BonitaTestExtension;
import com.bonitasoft.test.toolkit.junit.extension.BonitaTestExtension.Configuration;
import com.bonitasoft.test.toolkit.model.BusinessData;
import com.bonitasoft.test.toolkit.model.Task;

public class ProcessIT {

    private static final String USER_NAME = "walter.bates";
    private static final String BUSINESS_OBJECT_TYPE = "com.company.model.Dinosaur";
    private static final String PROCESS_NAME = "create-dinosaur";
    private static final String CREATE_TASK = "CreateDinosaur";
    private static final String HUNT_TASK = "goToHunt";

    @RegisterExtension
    static BonitaTestExtension bonitaExtension = new BonitaTestExtension(Configuration.builder()
            .targetRuntimeURL(() -> "http://localhost:8080/bonita")
            .deleteProcessInstances()
            .clearBDM()
            .build()); <1>

    @Test
    public void test_my_process(BonitaTestToolkit toolkit) throws Exception { <2>
        var user = toolkit.getUser(USER_NAME); <3>
        var processDef = toolkit.getProcessDefinition(PROCESS_NAME); <4>
        var businessObject = toolkit.getBusinessOject(BUSINESS_OBJECT_TYPE); <5>

        assertThat(businessObject.findAll(0, 10)).isEmpty();

        var processInstance = processDef.startProcessFor(user); <6>
        BonitaAssertions.assertThat(processInstance).isStarted();
        BonitaAssertions.assertThat(processInstance).containsPendingTasks(CREATE_TASK); <7>

        var complexInputBuilder = ComplexInputBuilder.complexInput()
                .textInput("name", "Tyrannosaurus")
                .textInput("color", "Brown")
                .booleanInput("hungry", true);
        var task1Contract = ContractBuilder.newContract().complexInput("dinosaurInput", complexInputBuilder).build(); <8>
        var task1 = processInstance.getFirstPendingTask(CREATE_TASK); <9>
        BonitaAssertions.assertThat(task1).hasCandidates(user);
        BonitaAssertions.assertThat(task1).isReady();

        task1.execute(user, task1Contract);

        // Tasks assertions
        BonitaAssertions.assertThat(task1).isArchived();
        BonitaAssertions.assertThat(processInstance).isArchived();
        assertThat(processInstance.searchActivities()).map(Task::getName).containsExactlyInAnyOrder(CREATE_TASK, HUNT_TASK);
        assertThat(processInstance.getFirstActivity(HUNT_TASK).isArchived()).isTrue();

        // Data assertions
        List<BusinessData> businessData = businessObject.query("findByName", List.of("name=Tyrannosaurus"), 0, 10);
        assertThat(businessData).hasSize(1);
        assertThat(businessData.get(0).getStringField("name")).isEqualTo("Tyrannosaurus");
        assertThat(businessData.get(0).getStringField("color")).isEqualTo("Brown");
        assertThat(businessData.get(0).getBooleanField("hungry")).isEqualTo(true);
    }

}
----
<1> `BonitaTestExtension` is a JUnit5 extension. It's a convenient way to setup a Bonita tets class. This extension allows to inject a `BonitaTestToolkit` correctly instantiated in test methods.
<2> The `BonitaTestToolkit`, injected by the `BonitaTestExtension`, is the main entry point to interact with the targeted Bonita platform.
<3> The toolkit offers the possibility to retrieve an existing user on the targeted Bonta platform. Users are used to execute processes during the test scenario.
<4> A process definition represents a deployed process on the targeted Bonita platform. It is used to start cases of a given process.
<5> Using the toolkit, you can create a `BusinessObject`. It has to match an existing BusinessObject defined in the installed Business Data Model, and is used to retrieve instances of this business object.
<6> The process under test is started using its process definition.
<7> The class `BonitaAssertions` offers the possibility to make assertions on Bonita concepts. It makes synchronous http calls on the targeted Bonita platform to perform the assertions.
<8> Contracts can be built using a `ContractBuilder` and a `ComplexInputBuilder` if required. It creates a key-value model representing the contract required to execute the task.
<9> Pending user tasks can be retrieved from the `ProcessInstance`. Different actions and assertions can be performed on user tasks.