= Download and launch Bonita UI Builder
:page-aliases: applications:download-and-launch.adoc
:description: Describes how to download and launch Bonita UI Builder.

[NOTE]
====
For Subscription editions only.
====

== Prerequisites
* Docker installed
* 2024.3 Bonita (or any later version) started on the local machine

To use Bonita UI Builder, a Bonita runtime running on your local machine is required (it may be a Bonita Studio or a standalone Bonita runtime).

[[create-docker-environment]]
== Create the docker environment

- Create a `docker-compose.yml` file with the content below:


.Click to see the docker compose file
[%collapsible]
====
[source,docker,subs="+macros,+attributes"]
----
include::example$ui-builder/development/docker-compose.yml[]
----
====

INFO: You can override and configure all xref:ui-builder-docker-installation.adoc#environment-variables[environment variables] in the `docker-compose.yml` file.

- Create a `nginx` configuration file `nginx.conf` with the content below:

.Click to see the nginx configuration file
[%collapsible]
====
[source, nginxconfiguration]
----
include::example$ui-builder/development/nginx.conf[]
----
====


To use the provided docker and nginx files above without modification, make sure that the Bonita runtime is accessible at `http://localhost:8080`.

[TIP]
You can change the Bonita runtime port by updating the `docker-compose.yml` file and the `nginx.conf` file. Default port is `8080`.

== Download and launch the docker image

Bonita UI Builder docker image is located in the xref:software-extensibility:bonita-repository-access.adoc[Bonita Artifact Repository].
Once you got the credentials, you have to authenticate with the `docker login` command:
[source, shell, subs="+attributes"]
----
docker login {bonitasoft-registry}
----

Run the following command to launch Bonita UI Builder:
[source, shell]
----
docker compose up -d
----

Then, you can access Bonita UI Builder at `http://localhost`.


[NOTE]
====
The first time, the initialisation can take a while, a waiting message appears. Reload the page if the page is blank.
====

[TIP]
====
If encountering issues with Windows and WSL, check our xref:faq.adoc#WSLissue[FAQ] .
====

== Authenticate with the UI Builder

Log in on Bonita UI Builder with the authentication page of Bonita runtime using the credentials of one of the users of the Bonita runtime database.

You can now build your user interface with the Bonita UI Builder!




