= Download and launch Bonita UI Builder
:page-aliases: applications:download-and-launch.adoc
:description: Describes how to download and launch Bonita UI Builder.

[NOTE]
====
For Subscription editions only.
====

== Prerequisites
* Docker installed
* 2024.3 Bonita (or any later version) started on the local machine

To use Bonita UI Builder, a Bonita runtime running on your local machine is required (it may be a Bonita Studio or a standalone Bonita runtime).

[[create-docker-environment]]
== Create the Docker environment

The Docker environment is composed of two containers:

1. Bonita UI Builder: the core service that runs a low-code application platform based on Appsmith.
2. Bonita UI Proxy: a reverse proxy to establish communications between Bonita UI Builder and a Bonita Runtime.

First, create a `docker-compose.yml` file with the content below:

[source,docker,subs="+macros,+attributes"]
----
include::example$ui-builder/development/docker-compose.yml[]
----

[NOTE]
====
A volume is mounted to the local folder `./stacks` to store persistent data. In case the container crashes, your work will not be lost.
Fill free to update the folder to another location on your local machine.
====

[NOTE]
====
You can override and configure all xref:ui-builder-docker-installation.adoc#environment-variables[environment variables] in the `docker-compose.yml` file.
====

== Download and launch the Docker image

Bonita UI Builder Docker image is located in the xref:software-extensibility:bonita-repository-access.adoc[Bonita Artifact Repository].
Once you got the credentials, you have to authenticate with the `docker login` command:
[source,console,subs="+attributes"]
----
docker login {bonitasoft-registry}
----

Run the following command to launch Bonita UI Builder:
[source,console]
----
docker compose up -d
----

Then, you can access Bonita UI Builder at `http://localhost`.


[NOTE]
====
The first time, the initialisation can take a while, a waiting message appears. Reload the page if the page is blank.
====

[WARNING]
====
By default, the database volumes are not persisted. Make sure you export your applications as .json files before running the command:
[source,console]
----
docker compose down
----
If you do not want to lose your data, you can use instead these commands to stop and restart Bonita UI Builder:
[source,console]
----
docker compose stop
docker compose restart
----
====

[TIP]
====
If encountering issues with Windows and WSL, check our xref:faq.adoc#WSLissue[FAQ] .
====

== Authenticate with the UI Builder

Log in on Bonita UI Builder with the authentication page of Bonita runtime using the credentials of one of the users of the Bonita runtime database.

You can now build your user interface with the Bonita UI Builder!




