= Download and launch Bonita UI Builder
:page-aliases: applications:download-and-launch.adoc
:description: Describes how to download and launch Bonita UI Builder.

[NOTE]
====
For Subscription editions only.
====

== Prerequisites
* Docker installed
* 2024.3 Bonita (or any later version) started on the local machine

To use Bonita UI Builder, a Bonita runtime running on your local machine is required (it may be a Bonita Studio or a standalone Bonita runtime).

[[create-docker-environment]]
== Create the docker environment

- Create a `docker-compose.yml` file with the content below:


.Click to see the docker compose file
[%collapsible]
====
[source,docker,subs="+macros,+attributes"]
----
include::example$ui-builder/development/docker-compose.yml[]
----
====

INFO: You can override and configure all xref:ui-builder-docker-installation.adoc#environment-variables[environment variables] in the `docker-compose.yml` file.

== Configure the bonita-ui-proxy image

The *bonita-ui-proxy* image is based on the official Nginx Docker image and a nginx.conf is included in the image.

The image contains environment variables used for the configuration:

- `NGINX_ACCESS_LOG_ALL` - By default, 2xx and 3xx requests are not logged. Set to `1` to log all requests (default: `0`).
- `NGINX_LISTEN_ADDRESS` - The address `host:[port]` on which Nginx is listen on for incoming requests (default: `80`). More information on the https://nginx.org/en/docs/http/ngx_http_core_module.html#listen[Nginx documentation].
- `BONITA_HOST` - Host of the Bonita runtime to which UIB will request (default: `host.docker.internal`).
- `BONITA_PORT` - Port of the Bonita runtime to which UIB will request (default: `8080`).
- `UIB_HOST` - Host of the UI Builder instance (default: `host.docker.internal`).
- `UIB_PORT` - Port of the UI Builder instance (default: `8090`).


To use the provided bonita-ui-proxy docker image without modification, make sure that the Bonita runtime is accessible at `http://localhost:8080`.

== Download and launch the docker image

Bonita UI Builder docker image is located in the xref:software-extensibility:bonita-repository-access.adoc[Bonita Artifact Repository].
Once you got the credentials, you have to authenticate with the `docker login` command:
[source, shell, subs="+attributes"]
----
docker login {bonitasoft-registry}
----

Run the following command to launch Bonita UI Builder:
[source, shell]
----
docker compose up -d
----

Then, you can access Bonita UI Builder at `http://localhost`.


[NOTE]
====
The first time, the initialisation can take a while, a waiting message appears. Reload the page if the page is blank.
====

[WARNING]
====
By default, the database volumes are not persisted. Make sure you export your applications as .json files before running the command.
[source, shell, subs="+attributes"]
----
docker compose down
----
If you do not want to loose your data, you can use instead these commands to stop and restart Bonita UI Builder:
[source, shell, subs="+attributes"]
----
docker compose stop
docker compose restart
----
====

[TIP]
====
If encountering issues with Windows and WSL, check our xref:faq.adoc#WSLissue[FAQ] .
====

== Authenticate with the UI Builder

Log in on Bonita UI Builder with the authentication page of Bonita runtime using the credentials of one of the users of the Bonita runtime database.

You can now build your user interface with the Bonita UI Builder!




