= Translate your application in different languages
:page-aliases: applications:how-to-translate-your-application-in different-languages.adoc
:description: Learn how to make your application available in multi-languages.

{description}

* Difficulty: beginner
* Prerequisites: have an application on Bonita UI Builder

Suppose, you're developing an application and would like to make it possible to be available in several language by just selecting a language option.
However, there is currently no built-in feature in UIB to make an application multi-languages, you can achieve doing it manually by following steps mentioned below.


== Example

=== 1 Create app UI
* Drag and drop a `Select` widget onto your interface, name it as `SelectLanguge`, and set the `Source Data` property as follows;

[source, JS]
----
[
  {
    "key": "English",
    "value": "en"
  },
  {
    "key": "Francaise",
    "value": "fr"
  },
  {
    "key": "Spanish",
    "value": "es"
  }
]
----

* Now, drag and drop a `Text` widget and add a sentence to its `Text` property.
For example, `This is a sample application to demonstrate the posibility of making it available in multi-languages.`


=== 2 Create JS objects
* Navigate to the `JS` section and create a new JS object and name it `localization`.
* Inside `localization` file, create JS objects for all the languages to map with the values that we set for the `SelectLanguage` widget. Add the words/sentences together with it's translation as key:value pair for all the languages shown in the code snippet below;

[source, JS]
----
export default {
	translations: {
		en: {
			"This is a sample application to demonstrate the posibility of making it available in multi-languages.": "This is a sample application to demonstrate the posibility of making it available in multi-languages."
		},
		fr: {
			"This is a sample application to demonstrate the posibility of making it available in multi-languages.": "Il s'agit d'un exemple d'application visant à démontrer la possibilité de le rendre disponible en plusieurs langues."
		},
		es: {
			"This is a sample application to demonstrate the posibility of making it available in multi-languages.": "Esta es una aplicación de muestra para demostrar la posibilidad de hacerlo disponible en varios idiomas."
		}
	}
}
----


[NOTE]
====
All the language key must match the value of the `SelectLanguage` source data as we set previously like en, fr, and es, etc.
====


=== 3 Create another JS objects
* To keep our code base clean, create another JS object and name it `i18n`.
* Copy and paste the JS code blocks as shown below;

[source, JS]
----
export default {
	languageKeys: {},
	onLanguageChange() {
		this.languageKeys = localization.translations[SelectLanguage.selectedOptionValue];
	},
	setLangugeKey() {
		this.languageKeys = localization.translations["en"];
		return this.languageKeys;
	}
}
----

[WARNING]
====
Make sure you have enabled `Run on page load` setting for `setLangaugeKey` function.
====


=== 4 Bind JS objects to the widgets
* Come back to the UI section and select `SelectLanguage` widget.
* Give it a `Label` as `{{i18n.languageKeys["Select language"]}}`
* In the Events property, set `{{i18n.onLanguageChange();}}` to call the function when language changes
* Now, select the text widget, and set the `Text` propert as `{{i18n.languageKeys["This is a sample application to demonstrate the posibility of making it available in multi-languages."]}}`


[NOTE]
====
Since the objective of this example is to implement a workaround, it doesn't deal with the cookies.
You can search on the internet and implement it as per your requirements.
====