= Production packaging
:page-aliases: applications:production-packaging.adoc
:description: Procedure to build the UI production binary

NOTE: Before starting, ensure you have **Docker** installed on your system.

[[build-docker-image]]
== Build a docker image

Add this Dockerfile in your project to the root of your project:

[[dockerfile]]
[source,docker,subs="+macros,+attributes"]
----
include::example$ui-builder/Dockerfile[]
----

WARNING: If you are using the 1.0.0-beta.1 version of the UI builder, be sure to read the comment in the Dockerfile.

Unless specific needs, you do not need to edit variables in this dockerfile.

Save the Dockerfile next to the `workspace` folder which contains all your xref:package-and-deploy-your-application.adoc#store-application[exported JSON applications]:

[source,shell]
----
..
Dockerfile
workspace/
  myApp.json
  myOtherApps.json
----


NOTE: You can change the default `workspace` folder and use any folder, but in this case, edit the dockerfile's `WORKSPACE` build argument with the new folder path.

=== Default build command

With this command, the image will be built with the default values defined in the Dockerfile.

WARNING: If you use this command, be sure to have the `workspace` folder next to the Dockerfile.

[source,bash]
----
  docker build -t <image-name> .
----

=== Advanced build

You can override some default values by using the following build arguments:

[cols="1,1,1"]
|===
|Args | Description | Default value

|BASE |The base image to use | {bonita-ui-builder-image}
|VERSION |The version of image to use | {bonita-ui-builder-version}
|WORKSPACE  | The folder containing the apps descriptor | ./workspace/
|===

[source,bash,subs="+attributes"]
----
  docker build --build-arg "BASE={bonita-ui-builder-image}" \
               --build-arg "VERSION={bonita-ui-builder-version}" \
               --build-arg "WORKSPACE=./workspace/" \
               -t <image-name>:<version> .
----

[[run-production-binary]]
== Run the production binary

To run the production docker image, you can use the following command:

[source,bash]
----
  docker run --name <container-name> -p 8080:80 \
            -e BONITA_API_URL=<bonita-runtime-url>/bonita/API \
            <image-name>:<image-version> \
----

You can override and configure all xref:ui-builder-docker-installation.adoc#environment-variables[environment variables].

NOTE: If you want to test your applications before going into production, instead of using `docker run`, you can use a `docker-compose.yml` file in the likes of what was done in the xref:download-and-launch.adoc#create-docker-environment[first steps] (i.e. with a `nginx` reverse proxy and the docker image xref:production-packaging.adoc#build-docker-image[built previously]).
