= Bonita UI Builder docker configuration guide
:page-aliases: applications:ui-builder-docker-installation.adoc
:description: Provide the configuration guide for the Bonita UI Builder Docker images.

This guide provides instructions on how to configure the `bonita-ui-builder` and `bonita-ui-proxy` Docker images.

[[environment-variables]]
== Docker container Environment variables

=== Configure the `bonita-ui-builder` image

The following environment variable is mandatory:

- `BONITA_API_URL`: The URL for the Bonita API.

The following environment variables are optional:

- `BONITA_HEALTHCHECK_USER`: Defines the username to request the Bonita healthcheck API (default: `monitoring`).
- `BONITA_HEALTHCHECK_PASSWORD`: Defines the password to request the Bonita healthcheck API (default: `mon1tor1ng_adm1n`).
- `BONITA_DEV_MODE`: Enables user to development mode when set to `true` (default: `true`).
- `LOGGING_LEVEL_ROOT`: Sets the logging level for the root logger (default: `debug`).
- `LOGGING_LEVEL_COM_APPSMITH`: Sets the logging level for Appsmith components (default: `debug`).
- `LOGGING_LEVEL_COM_BONITASOFT`: Sets the logging level for BonitaSoft components (default: `debug`).
- `LOGGING_LEVEL_COM_EXTERNAL_PLUGINS`: Sets the logging level for external plugins (default: `debug`).

=== Configure the `bonita-ui-proxy` image

The *bonita-ui-proxy* image is based on the official Nginx Docker image. It includes a custom `nginx.conf` file built to establish communications between Bonita UI Builder and a Bonita Runtime.

The following environment variables are available to customize the configuration:

- `NGINX_ACCESS_LOG_ALL`: By default, 2xx and 3xx requests are not logged. Set to `1` to log all requests (default: `0`).
- `NGINX_LISTEN_ADDRESS`: The address `host:[port]` on which Nginx is listen on for incoming requests (default: `80`). More information on the https://nginx.org/en/docs/http/ngx_http_core_module.html#listen[Nginx documentation].
- `BONITA_HOST`: Host of the Bonita runtime to which UI Builder will request (default: `host.docker.internal`).
- `BONITA_PORT`: Port of the Bonita runtime to which UI Builder will request (default: `8080`).
- `UIB_HOST`: Host of the UI Builder instance (default: `host.docker.internal`).
- `UIB_PORT`: Port of the UI Builder instance (default: `8090`).

To use the provided `bonita-ui-proxy` Docker image without modification, ensure the Bonita runtime is accessible at `http://localhost:8080`.

If you want to see our custom Nginx configuration used in this image, run this command:

[source,console,subs="+attributes"]
----
docker run --rm {bonita-ui-proxy-image} \
    cat /etc/nginx/templates/nginx.conf.template
----

[.troubleshooting-title]
== Troubleshooting

[.troubleshooting-section]
--
[.symptom]
I cannot access to the Bonita UI Builder.

[.cause]#Cause#
The Bonita UI Builder is not correctly configured.

[.solution]#Solution#
Check the environment variables and make sure they are correctly set. The `BONITA_API_URL` should target a valid Bonita Runtime.
--