# Example on how to use Postgres 15 with a Subscription edition of Bonita
services:
  bonita-db:
    image: bonitasoft/bonita-postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: my-secret-pw
    restart: always
    # Uncomment those lines to mount a volume with your dumps
    #volumes:
    #  - ~/my/test/dumps:/opt/bonita/dump

  # In case you have built an Application, use instead as example:
  # my-application:
  #  image: my-application-[my built environment]:[my aplication's semantic version]
  bonita:
    # this uses the latest maintenance version, but you can also pin a specific maintenance version such as {bonitaVersion}-u0
    image: bonitasoft.jfrog.io/docker/bonita-subscription:pass:a[{bonitaVersion}]
    # Update the hostname with the one used when generating the license
    hostname: localhost
    volumes:
      # Replace ~/bonita-lic with the folder containing the license
      - ~/bonita-lic:/opt/bonita_lic/
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=postgres
      - DB_HOST=bonita-db
      - DB_PORT=5432
      - DB_NAME=bonita
      - DB_USER=bonita
      - DB_PASS=bpm
      - BIZ_DB_NAME=business_data
      - BIZ_DB_USER=business_data
      - BIZ_DB_PASS=bpm
    restart: on-failure:2
    depends_on:
      bonita-db:
        # It uses the HEALTHCHECK of the database Docker image
        condition: service_healthy
