= Deploy Bonita Runtime with Docker
:page-aliases: ROOT:bonita-docker-installation.adoc
:description: How to install and use the Bonita Runtime Docker distribution.
:tabs-sync-option:

{description}

== Prerequisites

* A working Docker environment.
* Access to xref:software-extensibility:bonita-repository-access.adoc[Bonita Artifact Repository] (for *Subscription editions only*).


== Versioning

Multiple tags exist:

* `latest`: Points to the latest version of the platform
* `pass:a[{bonitaVersion}]`: Points to the latest maintenance version of the pass:a[{bonitaVersion}] version
* `pass:a[{bonitaVersion}]-uX`: Tag of a maintenance version of pass:a[{bonitaVersion}] (e.g. `pass:a[{bonitaVersion}]-u0`, `pass:a[{bonitaVersion}]-u1`...)

[WARNING]
====
`latest` and `pass:a[{bonitaVersion}]` are tags that change each time a new version of the platform is released.
It is safer to use the more complete version tag `pass:a[{bonitaVersion}]-uX` when scripting deployments to ensure
the binaries do not change.
====


== Installation procedure

=== Retrieve a license (Subscription editions only)

Subscription editions require a valid license to start the Bonita Runtime.

First generate a request key into a container with a specific hostname (-h):

[source,shell,subs="+macros,+attributes"]
----
docker run --rm -h <hostname> -it {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}] /bin/bash ./generateRequestKey.sh
----

Answer the questions related to the license you want. This will print out the request key and exit automatically from the running container.

Then complete the form on the https://customer.bonitasoft.com/license/request[Customer Service Center] to request a license (use the request key previously generated). Follow the requested steps to download the license file (`.lic` extension).

Copy the license file into a folder that will be mounted as a volume of the docker container. In this example, we will use `~/bonita-lic/`.

Alternatively, you can create a named persistent volume in docker to keep license files. See https://docs.docker.com/storage/volumes/[docker documentation on volumes].

=== Start the container

[tabs]
====
Community edition::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -d -p 8080:8080 bonita:pass:a[{bonitaVersion}]
----
--

Subscription editions::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ -d -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}]
----

Creates a Docker container with the hostname `-h` defined previously and the volume `-v` containing your license file.

NOTE: This fresh start only adds the initial license to the Bonita Runtime. To renew a license on an existing installation, see <<section-update-configuration,Update configuration and license section>>
--
====

This command starts a container running the Tomcat Bundle with Bonita Runtime. As the command does not specify any environment variables, this is likely a launch of a Bundle on your host using startup.+{sh|bat}+ (with security hardening on REST and HTTP APIs, cf. <<start-bonita-custom-credentials, Security concerns>>). It means that Bonita uses an H2 database here.

When the container is up and ready, you can access Bonita at the address http://localhost:8080/bonita and log in using the xref:identity:special-users.adoc#technical-user[technical user].

==== Start the container interactively

You may also run the Bonita container with an interactive shell session in order to control start and stop of the Tomcat bundle. Although the main usage of the Docker image is to automatically start the Bonita runtime, manually start and stop Tomcat may be useful for development or troubleshooting purposes.

Run the container as follows in order to get an interactive `bash` shell session:

[tabs]
====
Community edition::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -it -p 8080:8080 bonita:pass:a[{bonitaVersion}] bash
----
--

Subscription editions::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ -it -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}] bash
----
--
====

Then run `/opt/files/startup.sh` inside the container to start Tomcat. In order to stop Tomcat inside the container, press `Ctrl-C`. +
Repeat this sequence to manually start and stop Tomcat in the container.


=== Custom Permissions

If your project contains REST API Extensions with custom permissions, you can create a volume and map this volume to a local folder with the `custom-permissions-mapping.properties` file to use in Bonita Docker image:

[source,shell]
----
docker run --name bonita [...] -v ~/local-folder-path/:/opt/bonita/setup/platform_conf/initial/tenant_template_portal/ [...]
----

=== Connect Bonita to a database

By default, the Bonita container works out of the box with an H2 database, but *it is not recommended outside a development environment*.

Your database can be either a Docker container or an installed service.

==== Database as a Docker container

We provide preconfigured database images to work with Bonita which are available on https://hub.docker.com/u/bonitasoft[Bonita DockerHub], such as:

* https://hub.docker.com/r/bonitasoft/bonita-postgres[Postgres]
* https://hub.docker.com/r/bonitasoft/bonita-mysql[MySQL]
* https://hub.docker.com/r/bonitasoft/bonita-sqlserver[SQL Server]

Those images are built from the GitHub repository https://github.com/Bonitasoft-Community/bonita-database-docker[bonita-database-docker], and can be further adapted or customized to suit your needs.

The configuration of a database to work with Bonita is detailed in the xref:database-configuration.adoc[Database configuration page].

===== Quick start

Preconfigured database images can be run as followed:

[tabs]
====
Postgres::
+
--
[source,shell]
----
docker run -d --name bonita-postgres -p 5432:5432 bonitasoft/bonita-postgres:15.4
----
--

MySQL::
+
--
[source,shell]
----
docker run -d --name bonita-mysql -p 3306:3306 bonitasoft/bonita-mysql:8.0.33
----
--

SQL Server::
+
--
[source,shell]
----
docker run -d --name bonita-sqlserver -p 1433:1433 bonitasoft/bonita-sqlserver:2022-CU13
----
--
====

===== Using Docker Compose

Below are more complete examples on how to run Bonita with a preconfigured database image using https://docs.docker.com/compose/[Docker Compose].

[tabs]
====
Community edition::
+
[tabs]
=====
Postgres::
+
--
[source,yaml,subs="+macros,+attributes"]
----
include::example$docker/community/postgres/docker-compose.yml[]
----
--
=====

Subscription editions::
+
[tabs]
=====
Postgres::
+
--
[source,yaml,subs="+macros,+attributes"]
----
include::example$docker/subscription/postgres/docker-compose.yml[]
----
--

MySQL::
+
--
[source,yaml,subs="+macros,+attributes"]
----
include::example$docker/subscription/mysql/docker-compose.yml[]
----
--

SQL Server::
+
--
[source,yaml,subs="+macros,+attributes"]
----
include::example$docker/subscription/sqlserver/docker-compose.yml[]
----
--
=====
====

To execute it, first create a file `docker-compose.yml` with a content above, then run the command:

[source,shell]
----
docker compose up -d
----

Run the command below to view and follow log output from containers:

[source,shell]
----
docker compose logs -f
----

To shut it down and clear your environment:

[source,shell]
----
docker compose down -v --remove-orphans
----

====== Cluster mode

Below is an example on how to simulate the run of Bonita in a cluster mode.

We use Postgres as database and https://hub.docker.com/_/traefik[Traefik] as an HTTP reverse proxy and load balancer.

After execution, Bonita is available at `http://bonita.localhost` (the address can be changed with the label `traefik.http.routers.bonita.rule`).

[source,yaml,subs="+macros,+attributes"]
----
include::example$docker/cluster/docker-compose.yml[]
----

[NOTE]
--
When starting a cluster from scratch, you need first to start *only one instance* of the `bonita` service, because the first node initializes the database schema and populates it.

When the first instance has done starting, you can then run the command below to scale up the service.

[source,shell]
----
docker compose up -d --scale bonita=<num> --no-recreate
----
_Where `<num>` is the number of `bonita` instances wanted (e.g. `--scale bonita=2`)._
--

==== Database as an installed service

If the database is not a Docker container but an installed service, you can load the configuration with environment variables, for instance:

[tabs]
====
Community edition::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita \
    -e DB_VENDOR=postgres \
    -e DB_HOST=172.17.0.2 \
    -e DB_PORT=5432 \
    -e DB_NAME=custombonitadb \
    -e DB_USER=custombonitauser \
    -e DB_PASS=custombonitapass \
    -e BIZ_DB_NAME=custombusinessdb \
    -e BIZ_DB_USER=custombusinessuser \
    -e BIZ_DB_PASS=custombusinesspass \
    -d -p 8080:8080 bonita:pass:a[{bonitaVersion}]
----
--

Subscription editions::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ \
    -e DB_VENDOR=postgres \
    -e DB_HOST=172.17.0.2 \
    -e DB_PORT=5432 \
    -e DB_NAME=custombonitadb \
    -e DB_USER=custombonitauser \
    -e DB_PASS=custombonitapass \
    -e BIZ_DB_NAME=custombusinessdb \
    -e BIZ_DB_USER=custombusinessuser \
    -e BIZ_DB_PASS=custombusinesspass \
    -d -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}]
----
--
====

[#start-bonita-custom-credentials]
=== Start Bonita with custom security credentials

Security credentials can be customized using environment variables:

[tabs]
====
Community edition::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita \
    -e BONITA_RUNTIME_ADMIN_USERNAME=tech_user \
    -e BONITA_RUNTIME_ADMIN_PASSWORD=secret \
    -e PLATFORM_LOGIN=pfadmin \
    -e PLATFORM_PASSWORD=pfsecret \
    -e MONITORING_USERNAME=monitorAdmin \
    -e MONITORING_PASSWORD=monitor_Secr3t-P455w0rD \
    -d -p 8080:8080 bonita:pass:a[{bonitaVersion}]
----
--

Subscription editions::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ \
    -e BONITA_RUNTIME_ADMIN_USERNAME=tech_user \
    -e BONITA_RUNTIME_ADMIN_PASSWORD=secret \
    -e PLATFORM_LOGIN=pfadmin \
    -e PLATFORM_PASSWORD=pfsecret \
    -e MONITORING_USERNAME=monitorAdmin \
    -e MONITORING_PASSWORD=monitor_Secr3t-P455w0rD \
    -d -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}]
----
--
====

The Bonita Runtime is now available using technical login `tech_user / secret`.


== Secure your remote access

[tabs]
====
Community edition::

This docker image ensures to activate by default static authorization checks (Subscription editions only) on xref:identity:rest-api-authorization.adoc[REST API]. To be coherent it also deactivates the HTTP API.
But for specific needs, like exposing directly the Runtime APIs through HTTP (not to be mixed up with the REST API), you can override this behavior by setting `HTTP_API` to true:
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita \
    -e HTTP_API=true \
    -e HTTP_API_PASSWORD=S0me-h11p-s3cr3t \
    -d -p 8080:8080 bonita:pass:a[{bonitaVersion}]
----
--

Subscription editions::

This docker image ensures to activate by both static and dynamic authorization checks on xref:identity:rest-api-authorization.adoc[REST API]. To be coherent it also deactivates the HTTP API.
But for specific needs, like exposing directly the Runtime APIs through HTTP (not to be mixed up with the REST API), you can override this behavior by setting `HTTP_API` to true:
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ \
    -e HTTP_API=true \
    -e HTTP_API_PASSWORD=S0me-h11p-s3cr3t \
    -d -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}]
----
--
====

[#adding-ca-certificates]
== Adding internal CA certificates to the truststore

Add your certificates to `/certificates` inside the container (e.g. by using a volume) and set the environment variable `USE_SYSTEM_CA_CERTS` on the container to any value. With Docker CLI this might look like this:

[tabs]
====
Community edition::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita \
    -v $(pwd)/certs:/certificates/ \
    -e USE_SYSTEM_CA_CERTS=1 \
    -d -p 8080:8080 bonita:pass:a[{bonitaVersion}]
----
--

Subscription editions::
+
--
[source,shell,subs="+macros,+attributes"]
----
docker run --name bonita -h <hostname> -v ~/bonita-lic/:/opt/bonita_lic/ \
    -v $(pwd)/certs:/certificates/ \
    -e USE_SYSTEM_CA_CERTS=1 \
    -d -p 8080:8080 {bonitasoft-docker-repository}/bonita-subscription:pass:a[{bonitaVersion}]
----
--
====

The certificates would get added to the system CA store, which would in turn be converted to Java's truststore.

[#environment-variables]
== Environment variables

When starting the Bonita container, you can adjust the configuration of the Bonita instance by passing one or more environment variables on the Docker run command line or the Docker Compose.

=== PLATFORM_PASSWORD

This environment variable is recommended for you to use the Bonita image. It sets the platform administrator password for Bonita. If it is not specified, the default password `platform` will be used.

=== PLATFORM_LOGIN

This optional environment variable is used in conjunction with PLATFORM_PASSWORD to define the username for the platform administrator. If it is not specified, the default username `platformAdmin` will be used.

=== BONITA_RUNTIME_ADMIN_USERNAME

This optional environment variable is used in conjunction with BONITA_RUNTIME_ADMIN_USERNAME to define the username for the technical user. If it is not specified, the default username `install` will be used.

=== BONITA_RUNTIME_ADMIN_PASSWORD

This environment variable is recommended for you to use the Bonita image. It sets the technical user password for Bonita. If it is not specified, the default password `install` will be used.

[#monitoring-username]
=== MONITORING_USERNAME

This optional environment variable is used in conjunction with `MONITORING_PASSWORD` to define the access to endpoints protected with https://en.wikipedia.org/wiki/Basic_access_authentication[BASIC Auth access]: the xref:runtime-monitoring.adoc#prometheus-publisher[Monitoring endpoint], the xref:runtime-monitoring.adoc#jmx-publisher[JMX publisher], and the xref:healthcheck-mechanism.adoc#api-health-endpoints[API health endpoints]. If it is not specified, the default monitoring username `monitoring` will be used.

[#monitoring-password]
=== MONITORING_PASSWORD

This optional environment variable is used in conjunction with `MONITORING_USERNAME` to define the access to endpoints protected with https://en.wikipedia.org/wiki/Basic_access_authentication[BASIC Auth access]: the xref:runtime-monitoring.adoc#prometheus-publisher[Monitoring endpoint], the xref:runtime-monitoring.adoc#jmx-publisher[JMX publisher], and the xref:healthcheck-mechanism.adoc#api-health-endpoints[API health endpoints]., the default monitoring password `mon1tor1ng_adm1n` will be used.

=== REST_API_DYN_AUTH_CHECKS

Removed & does not work anymore, now you can use <<dynamic-check-enable,BONITA_RUNTIME_AUTHORIZATION_DYNAMICCHECK_ENABLED>> instead.

[#dynamic-check-enable]
=== BONITA_RUNTIME_AUTHORIZATION_DYNAMICCHECK_ENABLED (Subscription editions only)

This optional environment variable is used to enable/disable dynamic authorization checking on Bonita REST API. The default value is *true*, which will activate dynamic authorization checking.

=== HTTP_API
This optional environment variable is used to enable/disable the Bonita HTTP API. The default value is false, which will deactivate the HTTP API.
From Bonita 2022.1, HTTP API is protected with https://en.wikipedia.org/wiki/Basic_access_authentication[Basic access authentication]. See the following 2 parameters to configure Basic access authentication.

=== HTTP_API_USERNAME
This optional environment variable is used to configure the HTTP API Basic access authentication username. The default value is *http-api*.

=== HTTP_API_PASSWORD
This optional environment variable is used to configure the HTTP API Basic access authentication password. There is no default value, and providing a value is mandatory if `HTTP_API=true`.

=== JMX_REMOTE_ACCESS
This optional environment variable is used to enable/disable the access to the https://docs.oracle.com/en/java/javase/11/management/using-jconsole.html[JMX console] from a remote machine. +
Default value is *false*. +
The host to connect to is the name / IP address of the bonita server, the port to connect to is 9000. +
The credentials to connect are the environment variables <<monitoring-username, MONITORING_USERNAME>>, <<monitoring-password, MONITORING_PASSWORD>>.

=== REMOTE_IP_VALVE_ENABLED
This optional environment variable allows to activate/deactivate xref:runtime:reverse-proxy-configuration.adoc[reverse proxy redirection]. Default value is *false*.

=== ACCESSLOGS_STDOUT_ENABLED
This optional environment variable allows to activate/deactivate writing Tomcat access logs to standard output. Default value is *false*.

=== ACCESSLOGS_FILES_ENABLED
This optional environment variable allows to activate/deactivate writing Tomcat access logs to a specific file. When activated, will write those logs to `/opt/bonita/logs/` *inside* the docker container.
In practice, it is only useful when mounting a volume to the aforementioned directory. Default value is *false*.

=== ACCESSLOGS_PATH
If `ACCESSLOGS_FILES_ENABLED=true`, this optional environment variable overrides the default path to of the access log file.
Default value is */opt/bonita/logs*.

=== ACCESSLOGS_PATH_APPEND_HOSTNAME
If `ACCESSLOGS_FILES_ENABLED=true`, this optional environment variable allows to append a subdirectory with the *hostname* to the full path of the directory to put access log files into.
Default value is *false*.

=== ACCESSLOGS_MAX_DAYS
If `ACCESSLOGS_FILES_ENABLED=true`, this optional environment variable allows to automatically delete access log files after a certain number of days. Default value is *30*.

=== HEAPDUMP_PATH
This optional environment variable overrides the default path of the heap dump file.
Default value is */opt/bonita/logs*.

=== HTTP_MAX_THREADS
This optional environment variable allows to specify the maximum Http thread number Tomcat will use to serve HTTP/1.1 requests. Directly modifies the *maxThreads* parameter in the *server.xml* file of the Tomcat inside the docker container.
More information on the usefulness of this parameter can be found https://tomcat.apache.org/tomcat-9.0-doc/config/http.html[here]. Default value is *20*.

=== JAVA_OPTS
This optional environment variable is used to customize JAVA_OPTS. The default value is -Xms1024m -Xmx1024m.
The syntax to use is `-e JAVA_OPTS="-Xms2048m -Xmx2048m"`

=== DB_VENDOR
This environment variable is automatically set to postgres or mysql if the Bonita container is linked to a PostgreSQL or MySQL database using --link. The default value is h2. It can be overridden if you don't use the --link capability.

=== DB_HOST, DB_PORT
These variables are optional, used in conjunction to configure the bonita image to reach the database instance. There are automatically set if --link is used to run the container.

=== BONITA_DS_CONNECTION_POOL_INITIAL_SIZE, BDM_DS_CONNECTION_POOL_INITIAL_SIZE
Change the default value for the Bonita and/or the BDM datasource `initialSize`. This is the initial number of connections when the connection pool starts.

=== BONITA_DS_CONNECTION_POOL_MAX_TOTAL, BDM_DS_CONNECTION_POOL_MAX_TOTAL
Change the default value for the Bonita and/or the BDM datasource `maxTotal`. This is the maximum number of active connections that can be allocated from this pool at the same time.

=== BONITA_DS_CONNECTION_POOL_MIN_IDLE, BDM_DS_CONNECTION_POOL_MIN_IDLE
Change the default value for the Bonita and/or the BDM datasource `minIdle`. This is the minimum number of active connections that always established after pool created and connection has reached this size.

=== BONITA_DS_CONNECTION_POOL_MAX_IDLE, BDM_DS_CONNECTION_POOL_MAX_IDLE
Change the default value for the Bonita and/or the BDM datasource `maxIdle`. This is the maximum number of connections that should be kept in the pool at all times.

=== DB_NAME, DB_USER, DB_PASS

These variables are used in conjunction to create a new user, set that user's password, and create the bonita database.

`DB_NAME` default value is bonitadb.

`DB_USER` default value is bonitauser.

`DB_PASS` default value is bonitapass.

=== BIZ_DB_NAME, BIZ_DB_USER, BIZ_DB_PASS

These variables are used in conjunction to create a new user, set that user's password and create the bonita business database.

`BIZ_DB_NAME` default value is businessdb.

`BIZ_DB_USER` default value is businessuser.

`BIZ_DB_PASS` default value is businesspass.

=== BONITA_SERVER_LOGGING_FILE, BONITA_SETUP_LOGGING_FILE

WARNING: DEPRECATED See <<logger_configuration,how to configure logger>>

Since Bonita 7.9 BONITA_SERVER_LOGGING_FILE and BONITA_SETUP_LOGGING_FILE can be used to update logging configuration.

`BONITA_SERVER_LOGGING_FILE` default value is `/opt/bonita/conf/logs/log4j2-appenders.xml,/opt/bonita/conf/logs/log4j2-loggers.xml`

`BONITA_SETUP_LOGGING_FILE` default value is `/opt/bonita/setup/logback.xml`

=== BONITA_RUNTIME_STARTUP_UPDATE_ONLY

When set to true, the application exit right after the initialization/update phase. Exit with the `0` exit code when no errors occurred during the startup phase, `1` otherwise.

=== CLUSTER_MODE

This environment variable activates the xref:overview-of-bonita-bpm-in-a-cluster.adoc[Cluster mode] on Bonita, allowing to start several nodes that will join the cluster.


[#logger_configuration]
== Logger configuration

To ease the logger configuration, you can mount a volume on folder `/opt/bonita/conf/logs` containing the configuration files:

[source,shell]
----
docker run -v ~/my-config/log4j/:/opt/bonita/conf/logs/ ...
----

The volume must contain the 2 files
https://raw.githubusercontent.com/bonitasoft/bonita-distrib/{bonitaTechnicalVersion}/tomcat-resources/tomcat-distrib-for-bonita/src/main/resources/tomcat/server/conf/log4j2-loggers.xml[log4j2-loggers.xml]
and
https://raw.githubusercontent.com/bonitasoft/bonita-distrib/{bonitaTechnicalVersion}/docker/files/log4j2/log4j2-appenders.xml[log4j2-appenders.xml]

[NOTE]
====
Log4j2 automatically reloads configuration files when there is a change. However, if the file is invalid, the initial version
of that file is used instead, and is not reloaded unless one of the other watched file is changed.
====

If no user is specified to create the container (`--user`), the filesystem access rights are downgraded to allow only the `bonita` user (inside the Docker container), meaning that a standard user cannot access the log4j2 configuration folder on the host machine (`~/my-config/log4j/` in this example) anymore. Make sure to access it as a "sudoer" to hot-modify the logger configuration, or specify a dedicated user when creating the container:

[source,shell]
----
docker run --user <my-dedicated-bonita-user> -v ~/my-config/log4j/:/opt/bonita/conf/logs/ ...
----

== Migrating from an earlier version of Bonita

The migration scripts affect only the database, not the Bonita instance.
The procedure to migrate a Bonita container is therefore as follows:

* Stop and destroy the running Bonita container.
* Play the migration script on your Bonita database see xref:version-update:update-with-migration-tool.adoc[migrate the platform from an earlier version of Bonita].
* Get the new Bonita docker image, as explained above.
* Update the license, see <<section-update-configuration,Update configuration and license section>>
* Start a new Bonita container.

[#section-update-configuration]
== Update configuration and license

Once renewed from Bonita Customer Portal, the license file and the configuration files are updated using the Setup Tool.

Setup tool can be used outside the Docker container directly by downloading the Tomcat bundle and running it from there.

[NOTE]
====
The Setup Tool requires access to the database. Because of that, if the database is running inside a Docker container, the dedicated port must be exposed to the host.
====

See the xref:runtime:bonita-platform-setup.adoc#update_platform_conf[Setup Tool page] for more information.


== Troubleshoot and debug problems inside a Docker container

Bonita pass:a[{bonitaVersion}] Docker image comes with a set of tools embedded, https://github.com/apangin/jattach[jattach], that allows to interact with the Tomcat JVM inside a Bonita container via Dynamic Attach mechanism.

Example of useful commands it supports, that you can run from outside the container, include:

* `docker exec <CONTAINER_NAME> jattach 1 jcmd VM.flags` to see all JVM flags passed to Bonita Tomcat JVM:

[source,shell,subs="+macros"]
----
Connected to remote JVM
JVM response code = 0
-XX:CICompilerCount=4 -XX:ConcGCThreads=2 -XX:G1ConcRefinementThreads=8 -XX:G1HeapRegionSize=1048576 -XX:GCDrainStackTargetSize=64 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/bonita/server/logs
----

* `docker exec <CONTAINER_NAME> jattach 1 properties` to see all System properties that Java will use:

[source,shell,subs="+macros"]
----
Connected to remote JVM
JVM response code = 0
#Fri Sep 10 14:03:16 GMT 2021
com.arjuna.ats.arjuna.common.propertiesFile=/opt/bonita/server/conf/jbossts-properties.xml
sysprop.bonita.bdm.db.vendor=h2
awt.toolkit=sun.awt.X11.XToolkit
java.specification.version=17
sun.cpu.isalist=
sun.jnu.encoding=ANSI_X3.4-1968
java.class.path=/opt/bonita/server/lib/ext/bonita-tomcat-juli-pass:a[{bonitaTechnicalVersion}].jar\:/opt/bonita/server/bin/bootstrap.jar\:/opt/bonita/server/bin/tomcat-juli.jar
sysprop.bonita.db.vendor=h2
java.vm.vendor=Ubuntu
----

Read the https://github.com/apangin/jattach[official jattach documentation] for a complete list of supported commands.
