== Cache configuration and policy
:page-aliases: ROOT:cache-configuration-and-policy.adoc
:description: Learn how to configure Living Application cache.

{description}

Details about this cache configuration impact for the end user, and tutorial on modification of this configuration.

=== Cache policy over view

The default cache policy configured on your bonita bundle will allow your browser to store recently used information so that
it can be quickly accessed at a later time, thereby improving performance.
When you browse through different forms or custom pages that use the same images, CSS, or JavaScript, your browser will not have to re-download the files.
Instead, the browser can simply load them from the cache, which is stored on your local hard drive.

This cache policy will have impacts on the Living applications display time and theme update.

Note that in every cases, custom pages and forms take advantage of the cache mechanism in an Application.

==== Development configuration

By default cache is disabled for the web server embedded by Bonita studio, as it is more comfortable to realise development without cache.
But you can decide to activate cache, to be closer to the production display time. To do this,
see xref:ROOT:bonita-bpm-studio-installation.adoc#enable_cache[Cache configuration] documentation.

[#applications]

== Living application and custom pages

As the pages generated by the UI Designer take advantage of a xref:live-update.adoc#cache-busting[cache busting] mechanism, we can set the
cache duration to 6 months.
To fit your needs, you can change this duration into your server configuration, by following those steps:

. Go in `workspace\tomcat\server\webapps\bonita\WEB-INF`
. Open `web.xml` file.
. Search `CustomPageCacheFilter` filter-name.
. Change value for *duration* param to value what you want and *save file*.
. This update will be up when last cache expiration down or when end user empty cache browser.

NOTE: Html resources will be not caching.
