= Put Runtime in maintenance mode
:page-aliases: ROOT:pause-and-resume-bpm-services.adoc
:description: Learn how to execute maintenance tasks on your tenants by pausing and resuming BPM services of a Bonita Runtime.

{description}

For certain maintenance tasks that require a change to database tables or to information used by several processes (for example to update the Business Data Model), it is necessary to pause services of Bonita Runtime temporarily while it is updated. This is done by pausing the tenant. +

When a tenant is paused, this has the following consequences:

* Only the technical user can log into Bonita, and only into the Bonita Super Administrator application.
* Users who are currently logged in, including _regular_ Administrators, are automatically logged out.
* Users who are filling in forms when the service is paused will lose any information that has not been submitted.
* All processes are automatically paused.

Those are the reasons why such maintenance procedures must be planned at a time of low usage and must be communicated carefully to the users. +

The following sections explain how to pause and resume services in a tenant using the Bonita Super Administrator application. +
You can also use the https://javadoc.bonitasoft.com/api/{javadocVersion}/index.html[Engine API] or the xref:rest-api-overview.adoc[Web REST API].

== Pause a tenant

. Log into Bonita Super Administrator application
. Go to *BPM services*
. Click the *_Pause_* button
. In the popup, click *_Pause_* to confirm that the tenant is to be paused
. The tenant is immediately paused.

== Resume a tenant

. Log into Bonita Super Administrator application
. Go to *BPM services*
. Click the *_Resume_* button
. In the popup, click *_Resume_* to confirm that tenant services are to be resumed.
. The tenant resumes activity.

After the services are resumed, it is important to inform users that they can now log into all applications.
