= Profiles overview in Bonita User Interfaces
:page-aliases: ROOT:profiles-portal-overview.adoc, ROOT:profiles-applications-overview.adoc
:description: This page explains what a profile is in the Bonita Administrator Application.

{description}

== Definition

A profile is an indirection to some entities of the organization: users, groups, roles, and/or memberships.
Profiles work as permissions to give access to:

* xref:applications.adoc[Living Applications]
* Defined objects and attributes of the BDM (through xref:ROOT:access-control-api.adoc[BDM Access Control])
* xref:identity:rest-api-authorization.adoc[REST API extension permissions]

One organization entity can be mapped to several profiles. In Bonita Applications, a logged-in user can switch between his/her profiles in the navigation bar.

In development, the creation and edition of profiles is done through the xref:identity:profile-creation.adoc[profile editor] in Bonita Studio. +
In non-production and production, an Administrator can use the _Organization_>__Profiles__ menu of Bonita Administrator Application.

[NOTE]
====

Changing the mapping of a profile on a non-production or production Runtime may lead to inconsistencies when updating the project or deploying it on another server. +
It should only be done to recover from an error temporarily. We strongly encourage you to report all changes in the sources profiles files of the project.
====

== Default profiles

=== User

By default, it gives access to the Bonita User Application.

=== Administrator

By default, it gives access to Bonita Administrator Application, which includes:

* xref:ROOT:admin-application-process-list.adoc[Process Management]
* xref:ROOT:organization-in-bonita-applications-overview.adoc[Organization Management]
* xref:ROOT:bdm-management-in-bonita-applications.adoc[Business Data Model Management]
* xref:applications.adoc[Applications Management]
* xref:ROOT:licenses.adoc[License Information] (Enterprise, Performance, Efficiency, and Teamwork editions only)
 This profile is also mapped to the xref:ROOT:admin-application-overview.adoc[Bonita Administrator Application], bringing about the same value but with more customization options.

[NOTE]
====

In Bonita ACME organization, all users have the role *Member*, and the role *Member* is mapped to all default profiles. +
This simplifies process testing (log in as any user to see Bonita User and Administrator Application).
====
