= Purge tool change log
:page-aliases: ROOT:purge-tool-changelog.adoc
:description: This is the changelog of the purge tool.

This is the changelog of the purge tool.

The purge tool is used to remove data from bonita archive tables. It is useful for big production environments.

== 2.0.0 - August ?, 2024

Breaking changes:

- Java 17+ is now required to run the tool.
- Properties in the `application.properties` file have been renamed. Please update your configuration file accordingly.

New features:

- Improve the CLI user experience.
- Add a new `list` command to list the archived process instances that can be deleted.
- Add a new `delete` command to delete archived process instances with more options for better flexibility.
- The `delete` command now supports 2 deletion modes: `batch-delete` and `copy-truncate`.
- Delete operation is now executed in batch for a better control of the deletion process.
- Add a new option to the `delete` command to set the batch size.
- Add a new option to the `delete` command to set a timeout interval between each batch.
- Add a new option to the `delete` command to use a period (e.g.: 1d, 2w, 3m, 4y) instead of an exact date timestamp to filter instances.
- Process definition id is now optional in the `delete` command.
- Add a new `delete-file-input` command to delete archived file input values.

Fixes:

- The CLI can be run from `bin/` or root folder.
- Fix the date format display

Others:

- deps: update Springboot version to `3.3.2`
- deps: update MySQL connector to `8.4.0`
- deps: update PostgreSQL driver to `42.7.3`
- deps: update Oracle driver to `21.14.0.0`
- deps: update MS SQL Server driver to `9.4.1.jre11`
- deps: update Exposed JDBC to `0.52.0`


== 1.0.9 - June 11, 2024

Fixes:

- robustness: prevent the tool from being launched from bin folder.
  Tool must be run from **root folder** by launching `bin/bonita-purge-tool`. If not, the tool will exit with a specific error message.


== 1.0.8 - June 5, 2024

Now the tool **MUST** be run from the **root folder** by calling:

[source,shell]
--
bin/bonita-purge-tool[.sh/.bat]
--
It cannot be run from the **bin/** folder anymore.

Fixes:

- fix(config): config file not taken into account

Others:

- deps: update PostgreSQL driver
- build: update build and GH Actions
- build: update push to GDrive action

== 1.0.7 - Dec 11, 2023
- deps: update Springboot version
- deps: update MySQL connector
- build: use standard GH runners to build & release
- deps: update snakeyaml

== 1.0.6 - Oct 10, 2023
- Use the latest version of Springboot 2.7.x

== 1.0.5 - Sep 16, 2022
- Use Springboot 2.6.x
- Update JDBC drivers to latests
- Fix github actions workflow (internal)

== 1.0.4 - Mar 23, 2022

fixes :

- Fix: add methods to drop index if created at tool startup, this way allowing to re-run a previously stopped run without being blocked

Others :

- Run tests with MS SQL Server version *2019*
- Doc: remove mentions of "Portal". Use "Bonita Applications" instead.

== 1.0.3 - Feb 25, 2021

fixes :

- Fix: usage print when no parameter is passed.

== 1.0.2 - Jul 21, 2020

fixes :

- fix(arch_contract_data_backup): fix deletion of arch_contract_data_backup (#35) @educhastenier

== 1.0.1 - Jul 3, 2020

fixes :

- DataInstance and ContractData are not orphan, but deleted anyway

== 1.0.0 - Mar 20, 2020

This is the first production-ready version of Bonita Purge Tool.
Tested on:

    PostgreSQL
    MySQL
    Oracle database
    MS SQL Server
