# Use for running a bonita-ui-builder during development.
services:
  bonita-ui-builder:
    image: ${IMAGE_NAME:-pass:a[{bonita-ui-builder-image}]:latest}
    container_name: bonita-ui-builder
    environment:
      BONITA_API_URL: http://host.docker.internal:${BONITA_RUNTIME_PORT:-8080}/bonita/API
    ports:
      - "8090:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  reverse-proxy:
    image: ${IMAGE_NAME:-pass:a[{bonita-ui-proxy-image}]:latest}
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
