# Use for running a bonita-ui-builder during development.
services:
  bonita-ui-builder:
    image: pass:a[{bonita-ui-builder-image}]:pass:a[{bonita-ui-builder-version}]
    container_name: bonita-ui-builder
    environment:
      BONITA_API_URL: http://host.docker.internal:8080/bonita/API
    ports:
      - "8090:80"
    # Mount a volume to store persistent data
    volumes:
      - ./stacks:/appsmith-stacks
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # A reverse proxy used to communicate between Bonita UI Builder and a Bonita Runtime
  bonita-ui-proxy:
    image: pass:a[{bonita-ui-proxy-image}]:latest
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
