# Use for running a bonita-ui-builder during development.
services:
  bonita-ui-builder:
    image: pass:a[{bonita-ui-builder-image}]:pass:a[{bonita-ui-builder-version}]
    container_name: bonita-ui-builder
    environment:
      BONITA_API_URL: http://bonita-ui-proxy/bonita/API
    # Mount a volume to store persistent data
    volumes:
      - ./stacks:/appsmith-stacks
      - ./web_applications:/opt/appsmith/workspace/app/export

  # A reverse proxy used to communicate between Bonita UI Builder and a Bonita Runtime
  bonita-ui-proxy:
    image: pass:a[{bonita-ui-proxy-image}]:pass:a[{bonita-ui-builder-version}]
    ports:
      - 443:443
      - 80:80
    environment:
      UIB_HOST: bonita-ui-builder
      UIB_PORT: 80
      # Target existing Bonita installation running on docker host
      BONITA_HOST: host.docker.internal
      BONITA_PORT: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
