# Compress images on demand (workflow_dispatch), and at 8pm every Monday (schedule).
# Open a Pull Request if any images can be compressed.
name: Weekly Compress Images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 8 * * 1'
jobs:
  compress-images:
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_compress-images-nightly.yml@master
    secrets: inherit
