name: Contribution check

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_dispatch:


jobs:
  pr-title:
    runs-on: ubuntu-20.04
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  pr-content-check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check PR content
      uses: bonitasoft/actions/packages/pr-diff-checker@1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        diffDoesNotContain: '["https://documentation.bonitasoft.com/", "Bonita BPM"]'
        extensionsToCheck: '[".adoc"]'
    - name: Check content writing
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

