name: Contribution check

on:
  pull_request:
    # 'edited': check the PR title on changes
    types: [opened, edited, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write # post comments if the PR title doesn't match the "Conventional Commits" rules
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  pr-content-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check forbidden content
        uses: bonitasoft/actions/packages/pr-diff-checker@1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          diffDoesNotContain: '["https://documentation.bonitasoft.com/", "Bonita BPM"]'
          extensionsToCheck: '[".adoc"]'
      - uses: actions/checkout@v3
      - id: files
        name: Detect changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Check content writing
        uses: errata-ai/vale-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{ steps.files.outputs.added_modified }}

