name: Contribution check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commit-message-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check PR title and body
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-body-regex: '(.*\n*)+(.*)'
  pr-content-check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check PR content
      uses: bonitasoft/actions/packages/pr-diff-checker@1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        diffDoesNotContain: '["https://documentation.bonitasoft.com/", "Bonita BPM"]'
        extensionsToCheck: '[".adoc"]'
    - uses: actions/checkout@v2
    - name: Check content writing
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
