name: Build PR preview

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/pr-build-preview.yml'

jobs:
  build:
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_surge-build-preview.yml@master
    secrets: inherit
    with:
      component-name: bonita
      fail-on-warning: true
