name: Publish PR preview

on:
  pull_request:
    # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/publish-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write # surge-preview write PR comments
    steps:
      - name: Build and publish pr preview
        uses: bonitasoft/bonita-documentation-site/.github/actions/build-and-publish-pr-preview/@fix/update_pattern_for_comments_preview
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          component-name: bonita
