name: Publish PR preview

on:
  pull_request:
    # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/publish-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write # surge-preview write PR comments
    steps:
      - name: Build and publish pr preview
        # use the branch of https://github.com/bonitasoft/bonita-documentation-site/pull/513 to test its implementation
        uses: bonitasoft/bonita-documentation-site/.github/actions/build-and-publish-pr-preview/@chore/validate_doc_content_branch
        with:
          # use the branch of the doc-site PR under test
          doc-site-branch: chore/validate_doc_content_branch
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          component-name: bonita
