# Compress images on demand (workflow_dispatch), and at 8pm every Monday (schedule).
# Open a Pull Request if any images can be compressed.
name: Weekly Compress Images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 8 * * 1'
jobs:
  compress-images:
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_nightly_compress_image.yml@feat/create_reusable_nightly_compress_image
    secrets:
      github-token: ${{ secrets.BONITA_CI_PAT }}